### ISSUE TITLE
[Discipline Priest][Borrowed Time]

### ISSUE THREAD

**Issue by enbx** [Stormforge-gg/Bugtracker-Wotlk-Beta#10]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Borrowed Time grants 25% spell haste after casting Power Word: Shield; this buff empowers the next casted spell.
**Current behaviour**:
Buff from discipline talent "Borrowed Time" is not removed when used with the spell "Penance"
**Expected behaviour**: 
Buff should be removed after Penance cast is over / interrupted.
**Revision**:

**Comment by enbx** [comment]
+ Borrowed Time also interacts weirdly with Holy Nova, it reduces GCD time without being consumed. I'm not sure but i believe the spell haste from Borrowed Time should only apply to spell cast time, not to GCD

**Comment by Godmatik** [comment]
Apparently intended and not a bug.

https://www.mmo-champion.com/threads/642862-Borrowed-Time-Penance-Bug

**Comment by enbx** [comment]
Thanks, very interesting. I think i've never seen it implemented like this on any pserver. I'll see if i can find an old video in which this interaction is observable.

**Comment by enbx** [comment]
https://youtu.be/sjV8ZgNDWYU?t=61
Indeed the buff is not removed by Penance, hard to tell wether it's buffing Penance but I guess this gives the forum post enough credibility to make it confirmed.

Problem mentioned in the first comment remains.

**Comment by Godmatik** [comment]
It does buff the speed of penance, yes

**Comment by Wolffenstein** [comment]
Working as intended.
