### ISSUE TITLE
[DUNGEON][NPC] Oculus player's drake

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#100]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Player's drake does not disappear after dismounting and mobs aggro on him. No parachute if player is falling after dismounting.

**Current behaviour**: Player's drake does not disappear after dismounting and mobs aggro on him. No parachute if player is falling after dismounting.

**Expected behaviour**: After player gets off drake it should disappear. There should "Parachute" buff once player is on a drake.

www.wowhead.com/npc=27692/emerald-drake
https://www.wowhead.com/npc=27755/amber-drake
https://www.wowhead.com/npc=27756/ruby-drake
https://www.wowhead.com/spell=96038/parachute

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
