### ISSUE TITLE
[DUNGEON][NPC] Utgarde Keep NPCs

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#102]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Some NPCs not using some of their abilities. Could be because I was testing alone. Ingvar (last boss) missing some quotes.

**Current behaviour**:

1) Dragonflayer Ironhelm missing Ringing Slap ability (interrupt). https://www.wowhead.com/npc=23961/dragonflayer-ironhelm#abilities;mode:heroic
2) Dragonflayer Heartsplitter missing Piercing Jab ability. https://www.wowhead.com/npc=24071/dragonflayer-heartsplitter#abilities;mode:heroic
3) Ingvar missing "I return! A second chance to carve your skull!" and "No! I can do... better! I can..." quotes. https://www.wowhead.com/npc=23954/ingvar-the-plunderer

**Expected behaviour**: Mobs should use all of their abilities and Ingvar should have all his quotes.

**Revision**: 1040

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/162596540-bceb9680-1afe-40ba-b52c-f82714f7d019.png)
They do cast Ringing Slap, but only when a player in range is actually casting a spell

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
