### ISSUE TITLE
[DUNGEON][NPC][OBJECT] Utgarde Pinnacle

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#103]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Found few issues in UP.

**Current behaviour**:

1) Svala Sorrowgrave's position is glitching out during the fight. When player is kiting her she is flickering in the air as she's chasing.
https://www.wowhead.com/npc=26668/svala-sorrowgrave

2) You can pull trash and last boss through the gate that is in the first room by sending any pet (it will pass through the gate like a ghost) but boss will reset if you try to get him walk through the gate.

3) Ferocious Rhino missing grevious wound ability. Could be cauase of testing alone. https://www.wowhead.com/npc=26686/ferocious-rhino#abilities;mode:heroic

**Expected behaviour**: Svala should have normal movement/flight. That gate object shouldn't let pets and other NPCs walk through it until opened. Ferocious Rhino should use all of his abilities.

**Revision**: 1040

**Comment by Wolffenstein** [comment]
Grievous Wound is not cast on the tank.

**Comment by Wolffenstein** [comment]
> You can pull trash and last boss through the gate that is in the first room by sending any pet (it will pass through the gate like a ghost) but boss will reset if you try to get him walk through the gate.

Personally I can't do it with the Felhunter, but as you said, even if you manage to do it then the boss will reset. Pathfinding on private servers does not support temporary objects such as gates and doors so it's difficult to provide a permanent solution to this. It's a core issue in general, not tied to UP.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.

**Comment by Nuy** [comment]
> > You can pull trash and last boss through the gate that is in the first room by sending any pet (it will pass through the gate like a ghost) but boss will reset if you try to get him walk through the gate.
> 
> Personally I can't do it with the Felhunter, but as you said, even if you manage to do it then the boss will reset. Pathfinding on private servers does not support temporary objects such as gates and doors so it's difficult to provide a permanent solution to this. It's a core issue in general, not tied to UP.

So similar issue can be in WG? I remember in WG you can't send pets through keep walls until it's destroyed so if it's fixed in stock I'd look for solution there.
