### ISSUE TITLE
[Talent] [Hunter] Lock and Load

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#104]
**Description**: 
The Survival Talent _Lock and Load_ is not being procced by _Explosive Trap_ and _Black Arrow_.
https://wotlk-twinhead.twinstar.cz/?spell=56453

**Current behaviour**:
The Survival Talent _Lock and Load_ is not being procced by the periodic Damage of _Explosive Trap_ and _Black Arrow_ (see videos).
In the videos I have used 3 full duration of both Spells on the Target Dummie without a single _Lock and Load_ procc.
Black Arrow: https://streamable.com/hcfu4b
Explosive Trap: https://streamable.com/08d4vp

**Expected behaviour**: 
You have a **[33%/66%/100%]** chance when you trap a target with Freezing Trap, Freezing Arrow or Frost Trap and a **[2%/4%/6%]** chance when you deal periodic damage with your Immolation Trap, Explosive Trap or Black Arrow to cause your next 2 Arcane Shot or Explosive Shot spells to trigger no cooldown, cost no mana and consume no ammo. This effect has a 22 sec cooldown.

**Revision**: 
https://wotlk-twinhead.twinstar.cz/?spell=56453
https://db.rising-gods.de/?spell=56344

**Comment by Dionizodoros** [comment]
Tested on 500 ticks of explosive trap, 100 of black arrow and 40 of immolation. It certainly doesnt work at all.

Frost and freezing traps do trigger it though.

**Comment by Wolffenstein** [comment]
Fixed in rev 1087.
