### ISSUE TITLE
[Dungeon][NPC] Drakkari Frenzy

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#106]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Incorrect pathing of [mob](https://www.wowhead.com/npc=29834/drakkari-frenzy) in Gundrak

**Current behaviour**: Moving out of the water in a glitchy fashion, skipping up and down in the water.

**Expected behaviour**: According to [comments](https://www.wowhead.com/npc=29834/drakkari-frenzy#comments) on wowhead, they should jump out of the water with a splash.

**Revision**: 
--
![e057b4f82e0f40116a701a63def1fd32](https://user-images.githubusercontent.com/17366512/162589944-2335db4a-1697-490a-a9dc-f4987e48e019.png)
![443845ccf79cbbd21242014623ebaa58](https://user-images.githubusercontent.com/17366512/162589999-ce334d8b-3006-436d-a7a0-b082317a8032.png)

**Comment by klankin** [comment]
the fish do jump out of the water and splash back in most of the time. some are just getting stuck, floating above the water, others are getting stuck on land

**Comment by Wolffenstein** [comment]
Fixed in rev 1087.
