### ISSUE TITLE
[Dungeon][NPC] Drakkari Colossus

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#107]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The [boss](https://www.wowhead.com/npc=29307/drakkari-colossus) in Gundrak does not drop any loot.

**Current behaviour**: The boss doesn't drop any loot, also gives 250 rep for killing the mojo elemental and the colossus (unsure if intended).

**Expected behaviour**: Should drop loot!

**Revision**:

**Comment by Lmdezorn** [comment]
Technically, it is the Drakkari Elemental (npc=29573) who should drop the loot in this encounter. But yeah, no loot in sight atm.

**Comment by Wolffenstein** [comment]
Fixed in rev 1087.
