### ISSUE TITLE
[NPC] Loken's Lightning Nova

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Wotlk-Beta#108]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Loken is the last boss of the Halls of Lightning.
During the encounter he uses the spell Lightning Nova (ID 59835)

**Current behaviour**:
The spell cast can be interrupted.

**Expected behaviour**: 
The cast shouldn't be interruptible.

**Revision**: 
1040

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.

**Comment by kamithin** [comment]
Still interruptable in 1046. I think ID posted above is wrong. 
![image](https://user-images.githubusercontent.com/96308873/163106475-30d28e17-e2ae-4243-92ae-3809cbac0094.png)
ID = 52960

**Comment by LautaroJMolina** [comment]
I took it from wowhead, so it might be wrong
https://www.wowhead.com/spell=59835/lightning-nova

**Comment by kamithin** [comment]
It's fixed now, it was something else. I guess Wolf forgot to close it.
