### ISSUE TITLE
[Dungeon][NPC] Drakkari Fire Weaver

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#109]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: A [mob](https://www.wowhead.com/npc=29822/drakkari-fire-weaver) in Gundrak has a broken spell interaction.

**Current behaviour**: The flame shock is not consumed by the lava burst.

**Expected behaviour**: The lava burst should consume the flame shock to deal double damage. [Source](https://wowpedia.fandom.com/wiki/Drakkari_Fire_Weaver)

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
