### ISSUE TITLE
[Discipline Priest] [Aegis]

### ISSUE THREAD

**Issue by enbx** [Stormforge-gg/Bugtracker-Wotlk-Beta#11]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Discipline talent "Divine Aegis" grants the target a shield after scoring a critical heal.
**Current behaviour**:
"Divine Aegis" does not grant a shield from critical hits by 'Holy Nova' 
**Expected behaviour**: 
"Divine Aegis" should provide a shield from critical hits by 'Holy Nova'
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
