### ISSUE TITLE
[Quest] Mission: Plague This! [Zone} Howling FJord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#110]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Each of the plague tanks can be hit by bombs multiple times, and each hit will count towards quest completion.

**Current behaviour**: A single Plague Tank can be hit multiple times in a short time interval (2,3,4,5) and it will count towards quest completion.
**Expected behaviour**:  A single Plague tanks should only count once in a short time interval. The Plague tank that was hit should also catch fire. https://www.wowhead.com/quest=11332/mission-plague-this#videos

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
