### ISSUE TITLE
[Web] Mount doesnt work

### ISSUE THREAD

**Issue by Killing4pree** [Stormforge-gg/Bugtracker-Wotlk-Beta#111]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The "Swift Spellfire Carpet" Mount should make the character stand over a floating carpet and be able to move on it when used upon.
**Current behaviour**:
When you summon the "Swift Spellfire Carpet" mount, the carpet does present itself but without the character mounted on top of it which means the character is unable to use the mount which then creates another issue that is when you dismount the carpet does not vanish instead it stays on the same spot as when it was summoned meaning there no control over it and it stacks on everytime we try to summon this specific mount.
**Expected behaviour**: 
When trying to summon this mount the character is suppose on be on top of it and be able to ride the floating carpet with no issue and be able to dismount with the carpet vanishing away as it should like every other mount on dismount command.
**Revision**:

**Comment by kgms20** [comment]
Confirmed !

![WoWScrnShot_041022_012036](https://user-images.githubusercontent.com/103254348/162595149-7e7f100a-c701-4efc-b05a-b5e7f292e928.jpg)

**Comment by Wolffenstein** [comment]
It's a mount that got scrapped in wotlk beta. It's only available on the PTR because I added various mounts that exist in the database en mass.
