### ISSUE TITLE
[Quest] Steel Gate Patrol [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#113]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  This quest has at least 2 bugs. Gargoyle aren't fighting back when engaged, they exit combat and reset their hp as soon as they are attacked.  If you move towards target when machine gun ability is being channeled, flying machine gets stuck.

**Current behaviour**:   Gargoyles are exiting combat as soon as they are engaged and flying machine is getting stuck.

**Expected behaviour**:   https://www.wowhead.com/quest=11391/steel-gate-patrol#videos

**Revision**:

**Comment by Cold-Martijn** [comment]
Fixed the getting stuck in next batch, I need halp from someone else to fix the not fighting back.
