### ISSUE TITLE
Druid Berserk

### ISSUE THREAD

**Issue by Dawidoww96** [Stormforge-gg/Bugtracker-Wotlk-Beta#114]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Druid Berserk

**Current behaviour**:When Berserk is activated Mangle doesn't hit extra targets

**Expected behaviour**: When Berserk is active , Mangle should hit 2 extra targets

**Revision**:

**Comment by haephaistoss** [comment]
only bear mangle should hit 2 extra targets.

**Comment by haephaistoss** [comment]
![image](https://user-images.githubusercontent.com/67190649/162596417-6f3086fa-65e3-48c0-867a-491f7dd411a3.png)


And it works just fine in my testing done 5 seconds ago
