### ISSUE TITLE
Tier 7 tokens

### ISSUE THREAD

**Issue by Dawidoww96** [Stormforge-gg/Bugtracker-Wotlk-Beta#115]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:When two tier tokens drop , they are always of the same class requirements

**Expected behaviour**: Tier tokens should be able to be of different types when they drop from one boss kill

**Revision**:

**Comment by Wolffenstein** [comment]
It's random.
