### ISSUE TITLE
Shade of Akama

### ISSUE THREAD

**Issue by Dawidoww96** [Stormforge-gg/Bugtracker-Wotlk-Beta#116]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:When you engage Shade of Akama in Black temple , you can't target the npc 

**Expected behaviour**: When you kill the channelers you should be able to target Shade of Akama and kill him
**Revision**:

**Comment by Godmatik** [comment]
Did Akama physically walk to the shade and start engaging him?

**Comment by Wolffenstein** [comment]
TBC dungeons have not been ported yet. Please dont test them.
