### ISSUE TITLE
[NPC] Dragonblight

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#118]
Descriptif: https://www.wowhead.com/npc=26426/arctic-ram
![image](https://user-images.githubusercontent.com/62518101/162594585-005a3bb7-153c-4e45-8fa4-4a6e1a0d699c.png)

Current behaviour: 
npc=26426 wrong location or is that normal ? https://youtu.be/RG9TMn1FJzc?t=109

-

Descriptif: https://www.wowhead.com/npc=26333/corrupted-lothalor-ancient

![image](https://user-images.githubusercontent.com/62518101/162594773-32820e3e-d22f-4492-bdd9-e4d05e493794.png)

Current behaviour: 
npc=26333 unusual movement

Descriptif: 
ttps://www.wowhead.com/npc=27342/bloodpaw-warrior
https://www.wowhead.com/npc=27343/bloodpaw-shaman
![image](https://user-images.githubusercontent.com/62518101/162595089-0bfa53f6-bbc4-4228-9b4b-fd6123471131.png)

Current behaviour: 
npc=27342 unusual movement/ they touch each other constantly
npc=27343 unusual movement/ they touch each other constantly

-
Descriptif: https://www.wowhead.com/npc=27333/onslaught-mason#screenshots
![image](https://user-images.githubusercontent.com/62518101/162595201-f2e949e3-9118-4196-a087-2ff6f9d169e6.png)

Current behaviour: 
npc=27333 unusual movement/they have no mass/they are not in a correct position

![aaaaaa](https://user-images.githubusercontent.com/62518101/162595329-f91db814-a4fc-42d2-beb8-30902ca39a38.png)

-
Descriptif: 
https://www.wowhead.com/npc=27330/onslaught-infantry

Current behaviour: 
npc=27330 unusual movement

-
Descriptif: 
https://www.wowhead.com/npc=26291/crystalline-ice-giant#abilities

Current behaviour: 
npc=26291 unusual movement/stone throw bugger

**Comment by therealCrysis** [comment]
Works fine in rev 1165
