### ISSUE TITLE
[Divine Favor][Paladin] Not getting 2 crit by casting an instant spell after the casted one.

### ISSUE THREAD

**Issue by Hazas** [Stormforge-gg/Bugtracker-Wotlk-Beta#12]
**Description**: 
Using a spell that enhance the use of another spell should give you the enhancement for the next cast + the next instant spell if the instant is cast instantly after the casted spell. The only proof I could find about this is an [old video](https://www.youtube.com/watch?v=vrmSiHHVpIY) from the end of TBC, but I recall it working that way on wotlk as well.

**Current behaviour**:
I'll use an exemple so it's easier to understand but it's the same for some other spells that works that way in the game: as a Holy Paladin, using Divine Favor, then casting Holy Light guarantees that holy light to crit 100%, but casting Holy Shock Right after it doesnt guarantee a crit.
**Expected behaviour**: 
If casting Holy Shock right at the end of Holy Light/Flash of Light, it should guarantee that both spells crit.

**Revision**: 
I'm not sure what is the "issue" not making this happens as this was kind of a glitch back in the days, perhaps it has to do with game latency or spell queueing.

**Comment by haephaistoss** [comment]
feels similar to fingers of frost to me

**Comment by Hazas** [comment]
OK so I have done more testing with Frost mage, it seems it's the same issue with FIngers of Frost as you said. proccing Fingers of Frost, casting 1 Ice lance, then casting Frostbolt>Ice Lance result in the last Ice lance to not benefit from the FoF proc.

**Comment by Hazas** [comment]
I don't know about priest so maybe this wasn't happening for them anyway but using inner focus - Greater Heal>Holy Nova result ine Holy Nova to not benefit from Inner Focus

**Comment by Wolffenstein** [comment]
That's due to spell batching which won't be implemented.
