### ISSUE TITLE
[Spell][Class] Druids' bash doesn't interrupt NPCs that are immune to stuns

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Wotlk-Beta#120]
**Description**: The Bash ability (spell=8983 at 80, rank 3) of the Druid class doesn't interrupt NPCs that are immune to stuns

**Current behaviour**: The Bash ability (spell=8983 at 80, rank 3) of the Druid class doesn't interrupt NPCs that are immune to stuns, fo instance dungeon and raid bosses. For the moment, I only have tested with some dungeons bosses (Moorabi in Gundrak, Novos in DTK), but I don't expect the behavior to change with other bosses (I will take the time to test it with all the other bosses when I'll have time).

**Expected behaviour**: Since the patchnote 3.0.3., "the interrupt from this ability will now work on targets who are immune to the stun." (https://wowpedia.fandom.com/wiki/Bash_(druid_ability)). So bosses with kickable spells like Moorabi in Gundrak, or Vezax in Ulduar, should be interrupted when one bear uses successfully (no miss, no parry, no dodge) his bash during the spell cast.

**Steps to reproduce the issue**: Pull a boss known to be interruptable on certain casts, such as Moorabi in Gundrak, wait for him to cast, use Bash and see that it never interrupts the cast.

**Revision**:

**Comment by Lmdezorn** [comment]
I haven't tested with previous ranks of the Bash ability (spell=6798 for the rank 2, spell=5211 for the rank 1), but given the tooltip "Stuns the target for X sec and interrupts non-player spellcasting for 3sec.", I expect these ranks to behave in the same way.

**Comment by haephaistoss** [comment]
Hammer of Justice and Arcane Torrent have the same effect, test those too plz

**Comment by Emtec** [comment]
Fixed in 1097
