### ISSUE TITLE
[Quest][Item] Surrender... Not!

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#121]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Buff from [quest](https://www.wowhead.com/quest=11566/surrender-not) item does not display properly

**Current behaviour**: The buff from [King Mrgl-Mrgl's Spare Suit](https://www.wowhead.com/item=34620/king-mrgl-mrgls-spare-suit) displays as a stacking buff

**Expected behaviour**: Should only display as a single buff

**Revision**: 1041

![9e1a040a3219fcea6f6c084102a9a993](https://user-images.githubusercontent.com/17366512/162608846-608b3a80-8822-4d94-a487-bdb91f4f63d9.png)
![d53d45523f753158780d06ba743d6aea](https://user-images.githubusercontent.com/17366512/162608847-57fd958a-75f4-41a2-8d85-3158be3dcfd4.png)

**Comment by Evolvee** [comment]
fixed in next rev
