### ISSUE TITLE
[Quest] [Light's Point] Massacre at Light's Point

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Wotlk-Beta#123]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Scarlet Fleet Defender evade while bing in the Scarlet Cannon (tested middle and left cannon). Evading happens primarily after Scarlet Fleet Defender are close to the boat or on the ramp, but occasionally also further away.

**Current behaviour**:
Scarlet Fleet Defender evading while attacking cannon.

![Evade - Scarlet Fleet Defender](https://user-images.githubusercontent.com/103358327/162610933-a4246efb-b5e6-445a-b0c5-e36b85f4e01d.png)

**Expected behaviour**: 
Scarlet Fleet Defender not evading.

**Revision**:

**Comment by therealCrysis** [comment]
Issue known from several cores. These cannons are indeed tricky sometimes.

**Comment by Wolffenstein** [comment]
Fixed in rev 1194.
