### ISSUE TITLE
[NPC] Brogokk

### ISSUE THREAD

**Issue by rhav3** [Stormforge-gg/Bugtracker-Wotlk-Beta#124]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [https://tbc.wowhead.com/npc=17380/broggok](url) in "The Blood Furnace" isn't attackable if you start combat before he fully enteres the room and can't be killed.

**Current behaviour**: Can't be attacked if triggered too early but attacks player.

**Expected behaviour**: Should be attackable as soon as gates open.

**Revision**:

**Comment by Wolffenstein** [comment]
TBC dungeons have not been ported yet.
