### ISSUE TITLE
[Quest] Discipline

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#125]
**Description**: In Storm Peaks for the quest Discipline, the Disciplining Rod can be used on any Vyrkul, should only be exhausted. 

**Current behaviour**: Disciplining Rod can be used on any Vyrkul

**Expected behaviour**: Disciplining Rod should show 'Invalid Target' when used on Captive Vyrkul (https://www.youtube.com/watch?v=dUBTN-0j_co)

**Revision**: 1041

**Comment by Evolvee** [comment]
fixed in next rev
