### ISSUE TITLE
[NPC] Followers/Summons stacking on each other

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#126]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Some followers of quests and summons are stacking on top of each other

**Current behaviour**: Army of the dead and baby murlocs from a [quest](https://www.wowhead.com/quest=11560/oh-noes-the-tadpoles) are two examples I have seen of NPC followers stacking on top of each other. There are most likely more examples but these are the two I have personally seen

**Expected behaviour**: They should be spread out while idle or following the player

**Revision**: 1041
![796f228218610496ac7a4fbd75dcb87a](https://user-images.githubusercontent.com/17366512/162614379-9c56adba-e8c2-4f1c-8df1-c1bdf44e0735.png)
![88fb4c4df2d4beade559c3bbe4e88e39](https://user-images.githubusercontent.com/17366512/162614399-e62fdbf4-6cd7-4961-9829-fa2a2018347d.png)

**Comment by Nuy** [comment]
https://wow.zamimg.com/uploads/screenshots/normal/215202-army-of-the-dead.jpg

They should position themselves like that.

**Comment by Wolffenstein** [comment]
Fixed in rev 1043.
