### ISSUE TITLE
[DUNGEON][RDF] Gundrak

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#127]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Dungeon finder teleports players to wrong entrance. They should start the dungeon at northern (serpent boss) entrance.

**Current behaviour**: Dungeon finder teleports players to wrong entrance.

**Expected behaviour**: They should start the dungeon at northern (serpent boss) entrance. https://www.youtube.com/watch?v=YneYODCJOC4

**Revision**: 1041

**Comment by Wolffenstein** [comment]
Fixed in rev 1046.
