### ISSUE TITLE
[ZONE][NPC] Venture Bay lighthouse area

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#128]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: This area is broken. Both Alliance and Horde NPCs spawn at the same time and lightouse area isn't a capture point.

**Current behaviour**: Can't capture lighthouse and both Horde and Alliance NPCs spawn at the same time.

**Expected behaviour**: Venture Bay lighthouse area is supposed to be a capture point like the ones found in Hellfire or EPL. If Horde captured the area Alliance NPCs shouldn't spawn.

https://www.wowhead.com/npc=27758/westfall-brigade-defender
https://www.wowhead.com/npc=27759/commander-howser
https://www.wowhead.com/npc=27748/conquest-hold-defender
https://www.wowhead.com/npc=27708/general-gorlok
https://www.youtube.com/watch?v=hKM38kSJwyo

**Revision**: 1041

**Comment by Wolffenstein** [comment]
Fixed in rev 1062.
