### ISSUE TITLE
[Priest][Inner Focus]

### ISSUE THREAD

**Issue by enbx** [Stormforge-gg/Bugtracker-Wotlk-Beta#13]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Inner Focus(14751) reduces mana cost and increases crit chance of the next casted spell.
**Current behaviour**:
Inner Focus is not removed when you cast 'Holy Nova', it still makes it cost no mana (and increases crit chance) though. It is only removed when you deal damage with Holy Nova, healing yourself with it will not consume Inner Focus.
**Expected behaviour**: 
Inner Focus should buff 'Holy Nova' and be removed afterwards.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
