### ISSUE TITLE
[Spell][DK] Raise Ally

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#130]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Raise Ally preventing people from being rezzed

**Current behaviour**: After leaving ghoul form during Raise Ally, the targeted played is unable to be resurrected by other players (the rez is cast but no pop up to accept/decline appears)

**Expected behaviour**: The player should be able to be rezzed after leaving ghoul form

**Revision**: 1041

**Comment by Emtec** [comment]
Fixed in 1128
