### ISSUE TITLE
[NPC] Summons/Pets Movement Issue

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#131]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Jumping causes pet to move forward

**Current behaviour**: Upon jumping, the summoned ghoul will move forward until the player moves or jumps again, quickly returning to the players side again

**Expected behaviour**: The ghoul shouldn't move when jumping

**Revision**: 1041
![3f40fbf3ddcd1bd94c22ada02e5e0f6e](https://user-images.githubusercontent.com/17366512/162619912-7d7465b2-e4ad-471d-82aa-c377dcc05035.png)
![d66bb5da3c8845c3974e40a559cf6369](https://user-images.githubusercontent.com/17366512/162619914-3e12753d-9352-44eb-9634-1d8503c7b93f.png)

**Comment by klankin** [comment]
tested with other summons and pets, interacts the same way

**Comment by Wolffenstein** [comment]
Fixed in rev 1043.
