### ISSUE TITLE
Flight path Gundrak -> Camp Tunka'lo

### ISSUE THREAD

**Issue by 666franz666** [Stormforge-gg/Bugtracker-Wotlk-Beta#135]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Flight path [Zone]Gundrak -> [Zone]Camp Tunka'lo looks bugged
**Current behaviour**:
sliding along the ground and through trees at [Zone]Zim'Torga, flying backwards and straight upwards at the mountains before [Zone]Camp Tunka'lo
**Expected behaviour**: 
a smooth flying path
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1070.
