### ISSUE TITLE
[Spell][Mage]  barrage arrows

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#136]
https://ru.wowhead.com/spell=5143/%D1%87%D0%B0%D1%80%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D0%BA%D0%B8%D0%B5-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D1%8B

https://wowroad.info/?spell=54490

![Безымянный1](https://user-images.githubusercontent.com/40593874/162631041-ff18380f-cb82-4f3d-ac8b-fcbd475d175a.png)
![Безымянный](https://user-images.githubusercontent.com/40593874/162631044-907f3411-5721-4bba-a4eb-3f6256368d3d.png)

**Description**: 

**Current behaviour**:  The talent works, there is a proc, but the time reduction does not occur and the arrows do not fly out 1 time in 0.5 seconds, only the mana cost decreases to 0

**Expected behaviour**:  the amount of required mana should decrease to 0, as well as the casting time to 2.5 seconds and casts should be every 0.5 seconds

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1042.
