### ISSUE TITLE
Alpha Wall in Brill

### ISSUE THREAD

**Issue by 666franz666** [Stormforge-gg/Bugtracker-Wotlk-Beta#137]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Alpha Wall in [Zone]Brill at the Stable so you can´t get to [NPC]Zachariah Post, to buy undead mounts
**Current behaviour**:
there is some kind of alpha wall in front of the Stable in [Zone]Brill so you can´t get inside
**Expected behaviour**: 
you should get in there ^^
**Revision**: 
![World of warcraft 3 3 5a  Screenshot 2022 04 10 - 19 26 06 69](https://user-images.githubusercontent.com/57036752/162631738-e5e61528-2f9c-4800-b1f8-443bbf033837.png)

**Comment by Nuy** [comment]
Something is breaking with your character model when you use these GM buffs and then remove them. It's like game world sees your character as still huge and you block on things. Maybe it's that?

**Comment by Wolffenstein** [comment]
It's related to scale auras, not Brill
