### ISSUE TITLE
[Quest][Storm Peaks] The Last of Her Kind / zone - Hibernal Cavern

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#138]
**Description**: Lok'lira's Bargain (Bruunhildar Challenger disguise) is not active in Hibernal Cavern, player appears as character model, not Bruunhildar Challenger model. 

**Current behaviour**: Lok'lira's Bargain is not active in Hibernal Cavern (used for The Last of Her Kind)

**Expected behaviour**: Lok'lira's Bargain should be active in the cave (https://www.wowhead.com/quest=12983/the-last-of-her-kind#screenshots:id=124060)

**Revision**: 1041

**Comment by Wolffenstein** [comment]
Fixed in rev 1043.
