### ISSUE TITLE
[NPC] [Event] [Dungeon] Utgarde Pinnacle, Trophy Hall event half working

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Wotlk-Beta#14]
**Description**: Event in Trophy Hall for second boss: (https://www.wowhead.com/npc=26687/gortok-palehoof) seems odd, starting with the "Energy Ball" spawning a few seconds late

**Current behaviour**: After 1 or 2 spawns of adds it goes straight to boss

**Expected behaviour**:  Just be able to fight all "statues" of creatures istead of 1 or 2 and then the boss like in this video from 2009: https://www.youtube.com/watch?v=-v3GTKOjqaM

**Revision**:

**Comment by Wolffenstein** [comment]
It only spawns 2 on Normal which I assume is the difficulty you tested.

**Comment by blommenboy** [comment]
Tested on HC and its spawns all 4
