### ISSUE TITLE
[Storm Peaks - Pit of the Fang] [NPC] Hyldsmeet Warbear

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#141]
**Description**: Hyldsmeet Warbear are doing small patrol in Pit of the Fang, not engaging each other. If you pull multiple of them, they fight each other instead of you. 

**Current behaviour**: Hyldsmeet Warbear doing small aimless patrol, not fighting each other, focus on each other instead of you when pulled. 

**Expected behaviour**: Hyldsmeet Warbear should be fighting each other in the pit, probably should fight you when pulled.

**Revision**: 1041

**Comment by Wolffenstein** [comment]
Should be fixed.
