### ISSUE TITLE
[Zone] PvP Arena Timer Broken

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#142]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Time until arena gate opening is too long, timer addons are thrown off

**Current behaviour**: Took 60 seconds from when the countdown said 30 seconds remaining to start, something is not right

**Expected behaviour**: The gate should open on time

**Revision**: 1041

**Comment by Wolffenstein** [comment]
Fixed in rev 1043.
