### ISSUE TITLE
Hunter ability "Feed Pet" missing

### ISSUE THREAD

**Issue by Impranta** [Stormforge-gg/Bugtracker-Wotlk-Beta#143]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Spell "Feed pet" is not present?
**Current behaviour**:
/
**Expected behaviour**: 
/
**Revision**:

**Comment by Godmatik** [comment]
It requires the hunter taming quest chain to be completed, possibly the instant lvl 80s don't have it on them by default

**Comment by Wolffenstein** [comment]
Fixed in rev 1043. Will require remaking the character.
