### ISSUE TITLE
[NPC][Zul'Drak] Heb' Drakkar Striker - Movement

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#144]
**Description**: 
When starting to attack **Heb' Drakkar Striker**, it does not dismmount propperly and swims on the ground.

**Current behaviour**:
 When engaging in combat with **Drakkar Striker**, the NPC does not dismount propperly from its Bat and it swims on the ground (see video).

https://streamable.com/mnsx19

**Expected behaviour**: 
The NPC should propperly dismount and walk on the ground after engaging combat.

**Revision**: 
https://www.wowhead.com/npc=28465/hebdrakkar-striker

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/324

duplicate, closing this one because the other has youtube link, survives longer than streamable :)
