### ISSUE TITLE
[NPC] Chillmere Coast NPCs [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#145]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Some of the Chillmere Coast NPCs are missing their abilities.

**Current behaviour**: Servitor Shades, Mur'ghoul Flesheaters and Chillmere Tidehunters miss all of their abilities.

**Expected behaviour**:   Servitor Shades - https://www.wowhead.com/npc=24485/servitor-shade#abilities
                                         Mur'ghoul Flesheaters  - https://www.wowhead.com/npc=23644/murghoul-flesheater#abilities
                                         Chillmere Tidehunters  - https://www.wowhead.com/npc=24460/chillmere-tidehunter#abilities

**Revision**:

**Comment by Amun12** [comment]
According to wotlk DB (http://wotlk.cavernoftime.com) Mur'ghoul Flesheater has only Rend, compared to wowhead where it has both Rend and Consume Flesh.

**Comment by Cold-Martijn** [comment]
> According to wotlk DB (http://wotlk.cavernoftime.com) Mur'ghoul Flesheater has only Rend, compared to wowhead where it has both Rend and Consume Flesh.

That WotLK database you linked is from another private server. WoWhead is more accurate (and also not always fully correct).
The person who will fix this (probably me when I have time ^^) will probably use sniffs, videos, or other sources aswell to verify how often it should be cast, and if they cast any other spells.

**Comment by Cold-Martijn** [comment]
23645 - note to self for later
