### ISSUE TITLE
[Quest]Reconnaissance Flight [Zone]Sholazar Basin

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#146]
**Description**: 
Once the flight reaches [the Avalanche](https://wowpedia.fandom.com/wiki/The_Avalanche), the plane will be attacked by the undead bats that patrol the skies around it. You will be forced to take the plane back to the [Lakeside Landing](https://wowpedia.fandom.com/wiki/Lakeside_Landing) at [River's Heart](https://wowpedia.fandom.com/wiki/River%27s_Heart_(subzone)) before the engine completely goes.
https://wowpedia.fandom.com/wiki/Reconnaissance_Flight
**Current behaviour**:
After the is being hit by the undead bats when you should gain control of the plane, it keeps getting higher into the sky, no control over landing what so ever. Flying over the area of landing does nothing.
https://streamable.com/uprwbk
**Expected behaviour**: 
Expected behaviour is that you can normally fly and control the plane on a downward trajectory towards the [Lakeside Landing](https://wowpedia.fandom.com/wiki/Lakeside_Landing)
https://www.youtube.com/watch?v=bKDuH7VhXj4
**Revision**:

**Comment by Wolffenstein** [comment]
Can you try pressing space? I believe the client has some issues with handling vehicles sometimes, not sure if I can even fix that

**Comment by kgms20** [comment]
Rechecked, yea space worked, thanks.
