### ISSUE TITLE
[NPC] Primordial Drake [Zone] Sholazar Basin

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#148]
**Description**: 
Unusual movement 
https://wowpedia.fandom.com/wiki/Primordial_Drake
They can be found both flying in the air and walking on the ground.
**Current behaviour**:
No flying animations.
Currently the flying drakes showcase ground movement animations. Like they are walking a invisible surface mid air. 
When you attack one of the flying ones, the animation of the "landing" looks like the drake is going down the stairs. 
https://streamable.com/oz1s7s
https://streamable.com/72kwpm
https://streamable.com/a27trp
**Expected behaviour**: 
They can be found both flying in the air and walking on the ground. Flying ones should have normal flying animations like other flying drakes, same as landing animation.
https://www.youtube.com/watch?v=WntQaCDqZnY - 1:26
**Revision**:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/723
(just leaving this here so the alpha issue is linked)

**Comment by kgms20** [comment]
Re-uploaded to Youtube
https://www.youtube.com/watch?v=49zR_unuvWo

**Comment by Cold-Martijn** [comment]
fixed.
