### ISSUE TITLE
([Glyph][Class] Glyph of Life Tap)

### ISSUE THREAD

**Issue by Hawkingtail** [Stormforge-gg/Bugtracker-Wotlk-Beta#15]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Life tap doesn't trigger glyph of lifetap("When you use Life tap or Dark Pact, you gain 20% of your Spirit as spell power for 40 sec.")

**Current behaviour**: All ranks of life tap do not proc the spell power buff 

**Expected behaviour**: when you life tap with the glyph you should get a 20% spirit to spell power conversion for 40 seconds.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
