### ISSUE TITLE
[Quest][Grizzly Hills] ... Or Maybe We Don't

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#151]
**Description**: 
The **delpleted War Golem** stops following the Player after it has collected 2 charge Levels. 

https://www.wowhead.com/quest=12138/or-maybe-we-dont

**Current behaviour**:
The **delpleted War Golem** that is spawned by using  **Golem Control Unit** stops following the Player after it has collected 2 charge Levels. After killing **Lightning Sentry** NPC the Golem walks to them and charges 1 level. After he has done it the second time, he stops coming back to the player and stays in the position after he has sucessfully charged up the scond time (see video below). Also you can see, that on the second charge, there is no animation happening compred to the first charge in the video.
Has to be resummoned to work again.

https://streamable.com/nq80hy

**Expected behaviour**: 
The **delpleted War Golem** is supposed so walk back to the player after he has sucessfully charged up on the corpse of the dead **Lightning Sentry** NPC (see video below).

https://www.youtube.com/watch?v=vez8QL_dnTY

**Revision**: 
https://www.wowhead.com/quest=12138/or-maybe-we-dont

**Comment by Evolvee** [comment]
fixed in next rev
