### ISSUE TITLE
[NPC] Sholazar Basin

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#152]
**Description**: 
https://www.wowhead.com/npc=28212/bythius-the-flesh-shaper
https://www.wowhead.com/npc=28207/cerberon
https://www.wowhead.com/npc=28211/glonn

![qsdqdq](https://user-images.githubusercontent.com/62518101/162744763-25cab2b8-b79a-47f1-9b63-ae9886d6b58d.png)

**Current behaviour**: unusual movement 

**Expected behaviour**: 
https://youtu.be/a_lKae7sbSU?t=9
![image](https://user-images.githubusercontent.com/62518101/162762041-5b131295-e41b-4074-a2e2-6af391dd42ff.png)

**Revision**: 

*******************

**Description**: https://www.wowhead.com/npc=28081/frenzyheart-scavenger
![sdqqz](https://user-images.githubusercontent.com/62518101/162763319-735434d6-ecea-4a86-a206-65e0e1c9475c.png)

**Current behaviour**: unusual movement 

*********
**Description**: 
https://www.wowhead.com/npc=28078/frenzyheart-ravager
https://www.wowhead.com/npc=28079/frenzyheart-hunter

**Current behaviour**: unusual movement

**Comment by therealCrysis** [comment]
Works just fine in rev 1165
