### ISSUE TITLE
[NPC] Sky Terror [Zone] Zul'Drak

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#155]
**Description**: 
Npc not responding to aggro or combat.
https://www.wowhead.com/npc=28246/sky-terror
**Current behaviour**:
No aggro radius at all.
When attacked, remains still in that spot and therefore not even using any attacks or abilities.
https://streamable.com/pnblxd
**Expected behaviour**: 
Sky Terrors should have aggro radius, should be entering combat and attacking / using ability (Screech)
Sky Terrors are [gargoyles](https://wowpedia.fandom.com/wiki/Gargoyle) attacking [The Argent Stand](https://wowpedia.fandom.com/wiki/The_Argent_Stand) in [Zul'Drak](https://wowpedia.fandom.com/wiki/Zul%27Drak).
https://wowpedia.fandom.com/wiki/Sky_Terror
**Revision**:

**Comment by kgms20** [comment]
Re-uploaded on Youtube.
https://www.youtube.com/watch?v=VMgaNZIG1C0

**Comment by Cold-Martijn** [comment]
fixed, including grabbing Argent Crusader and Argent Shieldman in the air, dropping them to death, unless they have a parachute, that would make them survive.
