### ISSUE TITLE
[Quest][Grizzly Hills]  Take Their Rear!

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#158]
**Description**: 
The Questitem (**Grizzly Flank**) that Drops from Grizzly Bears, has a low drop rate.

https://www.wowhead.com/quest=12216/take-their-rear

**Current behaviour**:
The Droprate of _Grizzly Flank_ is farely low compared to the amount of items you have to get. Also in an video, the droprates look higher compared to here. Droprate is around 1 Grizzly Flank per 8-9 NPCs and you need 8 Grizzly Flanks in total.

https://www.wowhead.com/quest=12216/take-their-rear#videos:id=86601

https://www.youtube.com/watch?v=1_eli9b1ckI

**Expected behaviour**: 
Droprate of the Questitem should be increased.

**Revision**:

**Comment by Godmatik** [comment]
Looks like 25% drop rate per wowhead

**Comment by Wathsup** [comment]
ye, its definetly below that rn on the server.

**Comment by Cold-Martijn** [comment]
fixed in next batch
