### ISSUE TITLE
[Quest] The Ancient Armor of the Kvaldir [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#159]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The plane ( Harry's Bomber), that's supposed to take you to the quest destination flies at an extremely slow pace. 
"Dead" Forsaken Deckhands on top of the ship (where the quest item is located) are killable. I assume that's a bug as well.
 
**Current behaviour**:  Right now it takes over 10 minutes the reach the destination.

**Expected behaviour**:  It should be way faster (2nd video) https://www.wowhead.com/quest=11567/the-ancient-armor-of-the-kvaldir#videos

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.
