### ISSUE TITLE
[Rogue] Rupture 

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#16]
**Description**: 
Rogue Assassination skill Rupture

**Current behaviour**:
Damage over time Bleed does not crit.

**Expected behaviour**: 
Rupture should produce critical strikes like other Physical skills as of Patch 3.3.3, "[Rupture] The damage-over-time component of this ability can now produce critical strikes."

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
