### ISSUE TITLE
[NPC] Graymist Hunter

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#160]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: An area in Grizzly Hills is missing a number of mob spawns (a quest in conquest hold has you kill them)

**Current behaviour**: The purple flower patch north of conquest hold and the area west of conquest hold is missing [Graymist Hunter](https://www.wowhead.com/npc=26592/graymist-hunter) and possibly [Tallhorn Stag](https://www.wowhead.com/npc=26363/tallhorn-stag) Spawns

**Expected behaviour**: There should be multiple worg spawns in this purple area, just like the other purple ones north/northeast of it and also worg spawns in the area directly west of conquest hold

**Revision**: 1045

[this](https://youtu.be/LBmWoccRsIU?t=47) is the only retail video i could find with a glimpse of the purple area and [here](https://www.youtube.com/watch?v=cpNg_PZo69U) is a video for the area to the west
![ec0e7366f499c4115b8632f1a126e475](https://user-images.githubusercontent.com/17366512/162817435-a46dfd41-4415-4c67-bf2f-a9254ece2adc.png)

**Comment by therealCrysis** [comment]
It works fine in rev 1165
