### ISSUE TITLE
[Quest] The Dead Rise! [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#161]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Firstly, the quest is missing RP elements. Gathering each of the four clues should trigger a story , told by the ancestor associated with the specific clue.
                           Secondly, the ancestors Fengir the Disgraced, Rodin the Reckless, Isuldof Iceheart and Windan of the Kvaldir are killable, while they shouldn't be.

**Current behaviour**: The ancestors are killable and they are missing RP element.

**Expected behaviour**:  They shouldn't be killable. Each time you gather a clue, it should be followed by story:
                                     Fengir the Disgraced says: From sundered ground the sacrament was stolen. The Shield of Aesirites is lost. Unrest will be eternal.  
                                     Rodin the Reckless says: The Staff of Storm's Fury pilfered. A curse upon this land! The storms will never cease!
                                     Isuldof Iceheart says: The Frozen Heart of Isuldof will consume this land until it is returned. Woe unto those that hold the heart as the curse of frozen blood besets them...
                                     Windan of the Kvaldir says: The anguish of ten-thousand years awaits any foolish enough to don the Ancient Armor of the Kvaldir. Beware the mist and fog, mortals; for with them comes your end.

https://www.wowhead.com/quest=11504/the-dead-rise

**Revision**:

**Comment by Cold-Martijn** [comment]
fixed with next batch
