### ISSUE TITLE
[NPC] Multiple NPCs across Howling Fjord are missing their abilities

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#162]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**: The following NPCs are missing their abilities : Proto-Whelp, Fanggore Worg, Darkclaw Bat, Sepulchral Overseer, Bjomolf, Varg, Thornvine Creeper, Iron Rune Stonecaller, Binder Murdis, Thorvald, "Scoodles" and Mutinous Sea Dog.

**Expected behaviour**:  Proto-Whelp https://www.wowhead.com/npc=23688/proto-whelp#abilities
                                         Fanggore Worg  https://www.wowhead.com/npc=24026/fanggore-worg#abilities
                                         Darkclaw Bat https://www.wowhead.com/npc=23959/darkclaw-bat#abilities
                                         Sepulchral Overseer https://www.wowhead.com/npc=23993/sepulchral-overseer#abilities
                                         Bjomolf https://www.wowhead.com/npc=24516/bjomolf#abilities
                                         Varg https://www.wowhead.com/npc=24517/varg#abilities
                                         Thornvine Creeper https://www.wowhead.com/npc=23874/thornvine-creeper#abilities
                                         Iron Rune Stonecaller https://www.wowhead.com/npc=24030/iron-rune-stonecaller#abilities
                                         Binder Murdis https://www.wowhead.com/npc=24334/binder-murdis#abilities
                                         Thorvald https://www.wowhead.com/npc=27926/thorvald#abilities
                                         "Scoodles" https://www.wowhead.com/npc=24899/scoodles#abilities
                                          Mutinous Sea Dog https://www.wowhead.com/npc=25026/mutinous-sea-dog#abilities

**Revision**:

**Comment by Amun12** [comment]
Just adding that there are conflicting info about Thorvald and "Scoodles", as according to one of wotlk DBs each of them has an additional ability compared to the one present on Wowhead : Thorvald http://wotlk.cavernoftime.com/npc=27926 and "Scoodles" http://wotlk.cavernoftime.com/npc=24899

**Comment by EtheriousNW** [comment]
Fixed in rev 1055
