### ISSUE TITLE
[Quest][Grizzly Hills] The Thane of Voldrune

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#164]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Multiple issues with this [quest](https://www.wowhead.com/quest=12255/the-thane-of-voldrune)

**Current behaviour**: The protodrakes do not despawn when dismounted and interacting with the chained protodrake to obtain the vehicle seems to randomly cause my client to seize up and crash.

**Expected behaviour**: The drakes should despawn and the chained flamebringer should not crash your client when trying to mount it

**Revision**: 1045
(spawned so many because i was trying to figure out what exactly was causing the crash. I was able to mount it fine without crashing three times in a row and then the fourth try crashed me again. crashed a total of 4 times before giving up)
![59cfb97f2f86445cc3b563234c774b6c](https://user-images.githubusercontent.com/17366512/162825570-edb03fa1-5512-4ef7-877a-5df1b5f6a860.jpg)

**Comment by Peglaa** [comment]
Very fun quest.
![image](https://user-images.githubusercontent.com/15163719/162829402-c78dbc02-809c-4716-af1f-182d962a2ab9.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1064.
