### ISSUE TITLE
[Hell Hath a Fury] [High Priestress Tua-Tua] [Zul'Drak]

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#166]
**Description**: 
Quetz'lun's Spirit at the Altar of Quetz'lun wants you to use Quetz'lun's Hexxing Stick upon High Priest Mu'funu, High Priestess Tua-Tua, and High Priest Hawinni. Once you have done this, slay them.
https://wotlk.evowow.com/?quest=12674
**Current behaviour**:
https://wotlk.evowow.com/?item=39158 
Quest item working only on Mu'funu and Hawinni. 
Tua-Tua NPC is on 1 hp and has a casting animation, says " Invalid target " when I use the quest item on her.
https://streamable.com/xx8vlk
**Expected behaviour**: 
Should work on High Priestress Tua-Tua aswell.
Use: [Channels the hexxing hatred of Quetz'lun's Spirit at High Priest Mu'funu, High Priestess Tua-Tua, or High Priest Hawinni.](https://wotlk.evowow.com/?spell=52251) (5 seconds cooldown)
https://www.youtube.com/watch?v=NUQFBbzbdT0
**Revision**:

**Comment by EtheriousNW** [comment]
Fixed in rev 1055 rewrote to add some missing stuff, might be good to retest.
