### ISSUE TITLE
[Quest][Grizzly Hills] The Conquest Pit

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#169]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The chain quest for the conquest pit in the conquest hold in grizzly hills is not scripted

**Current behaviour**: The quest is accepted and the mob instantly spawns, no voicelines/yells and timer

**Expected behaviour**: The goblin should shout some lines and there should be a delay until the fight starts

**Revision**: 1045

(links to video of quest)
[quest=12427](https://www.youtube.com/watch?v=VC2o4XZCxLA)
[quest=12428](https://www.youtube.com/watch?v=dzB-4vuna2s)
[quest=12429](https://www.youtube.com/watch?v=86Zc9zoaS2g)
[quest=12430](https://www.youtube.com/watch?v=r9wytIqIgig)
[quest=12431](https://www.youtube.com/watch?v=kuKyNR7x7kQ)

**Comment by EtheriousNW** [comment]
Fixed in rev 1055 please retest :)
