### ISSUE TITLE
[Quest][Icecrown] The Will of the Naaru, no portal to Shattrath offered by [NPC] Rhydian

### ISSUE THREAD

**Issue by St-Nuke** [Stormforge-gg/Bugtracker-Wotlk-Beta#170]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Quest][Icecrown] The Will of the Naaru, part of the Bridenbrad chain, after speaking with Fordring, Rhydian the Kirin Tor npc is supposed to walk forward and offer you a port to Shattrath. He never moves, and has no conversation option (this last may be intended). 

**Current behaviour**: Rhydian does not move or make a portal. 

**Expected behaviour**: See top 2 comments from https://www.wowhead.com/quest=13081/the-will-of-the-naaru:
By splunge on 2008/09/29 (Patch 3.0.1)		
If you wait about 10 seconds, Rhydian will wander over and open up a portal to Shattrath for you right next to you.
 Ilidar on 2008/11/29 (Patch 3.0.3)
 And after speaking with A'dal, he will teleport you back to Dalaran.

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
