### ISSUE TITLE
[Talent][Druid] Omen of Clarity - procs after crafting

### ISSUE THREAD

**Issue by byakku** [Stormforge-gg/Bugtracker-Wotlk-Beta#172]
**Description**: 
Druids have [Omen of Clarity](https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity) talent that _"causes all of your spells and auto-attacks to give a chance to grant you a Clearcasting buff, which reduces the [mana](https://wowwiki-archive.fandom.com/wiki/Mana), [rage](https://wowwiki-archive.fandom.com/wiki/Rage), or [energy](https://wowwiki-archive.fandom.com/wiki/Energy) cost of your next damage or healing spell or offensive ability to zero."_

**Current behaviour**:
Clearcasting can proc after crafting. Tested with Leatherworking.

**Expected behaviour**: 
Clearcasting shouldn't proc after crafting is done.

**Revision**: 
1044

**Comment by haephaistoss** [comment]
Why exactly? Crafting is spell casting. It should proc of ALL slellcasting, and you'd be surprised to find out how many stuff is done though spells in wow.

**Comment by haephaistoss** [comment]
I don't wanna be rude, but dude at least take the time to do some Google search before reporting something.

https://www.wowhead.com/spell=16864/omen-of-clarity#comments

**Comment by haephaistoss** [comment]
![Screenshot_20220413_014030_com brave browser](https://user-images.githubusercontent.com/67190649/163066653-a786be8f-3f77-483d-87eb-abcc967dc4b5.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 1046.
