### ISSUE TITLE
[Talent][Druid] Omen of Clarity procs when changing zones, in flight 

### ISSUE THREAD

**Issue by St-Nuke** [Stormforge-gg/Bugtracker-Wotlk-Beta#173]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Talent][Druid] Omen of Clarity can be triggered by traveling to a different zone (mounted), or in flight. 

**Current behaviour**: I noticed taking a flight path from Icecrown to Wyrmrest that I got an Omen proc when I hit the Dalaran flight hub, later I was flying mounted in Icecrown, and when I changed internal zones, I got an Omen proc in flight form. 

**Expected behaviour**: Omen procs from spells and abilities only--probably needs research. 

**Revision**:

**Comment by haephaistoss** [comment]
Actually omen of clarity is notorious for procing off of every single shit that happens to the druid, should look around on way back machine and elitist jerks if you wanna dive deep

**Comment by Wolffenstein** [comment]
Fixed in rev 1046.
