### ISSUE TITLE
[Sholazar Basin][Quest item] Multiple call/dismiss quest items 

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#174]
**Description**: 
Quest item dismiss function is missing
https://www.wowdb.com/items/38512-zepiks-hunting-horn
https://www.wowhead.com/item=38623/jaloots-favorite-crystal
https://www.wowhead.com/item=38624/moodles-stress-ball
**Current behaviour**:
With these 3 quest items, you can only summon the NPC, while dismiss option does not work at all. 
https://www.youtube.com/watch?v=2JJJ2QHZlRE
**Expected behaviour**: 
You should be able to summon the NPC on first use and dismiss on the second use. Also that principle should work on every quest item that has that same call or dismiss mechanic.
[Calls or dismisses Zepik.](https://wotlk.evowow.com/?spell=51189)
[Calls or dismisses Jaloot should he be managing to pay attention at the time.](https://wotlk.evowow.com/?spell=51191)
[Calls or dismisses Moodle.](https://wotlk.evowow.com/?spell=51192)
**Revision**

**Comment by BAndysc** [comment]
Fixed in rev 1051
