### ISSUE TITLE
[Quest][Icecrown] Crusader Bridenbrad's tabard not rewarded

### ISSUE THREAD

**Issue by St-Nuke** [Stormforge-gg/Bugtracker-Wotlk-Beta#175]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Quest reward from https://www.wowhead.com/quest=13083/light-within-the-darkness does not also include the tabard. [NPC] Tirion Fordring completes the quest chain. See attached for pic of inventory and character. 
![WoWScrnShot_041122_214600](https://user-images.githubusercontent.com/103507260/162983656-c6e475b8-be5a-4b14-a829-b143beafba5f.jpg)
**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Wolffenstein** [comment]
You're not supposed to receive any tabards for this quest.
