### ISSUE TITLE
[Quest] Steamtank Surprise (12326); [Spell] Ice Prison (49333);

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Wotlk-Beta#176]
**Description**: 
Ice Prison doesn't affect Mindless Wight (27287)

**Current behaviour**:
Ice Prison doesn't affect Mindless Wight (27287)

**Expected behaviour**: 
Ice Prison does affect Mindless Wight (27287)

**Revision**: 
1044

**Comment by EtheriousNW** [comment]
Fixed in rev 1055
