### ISSUE TITLE
[NPC] Foreman Thaldrin [Icecrown]

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#179]
**Description**: 
https://wowwiki-archive.fandom.com/wiki/Foreman_Thaldrin
http://wotlk.cavernoftime.com/npc=31399

**Current behaviour**:
NPC missing following abilities: 
http://wotlk.cavernoftime.com/spell=59992
http://wotlk.cavernoftime.com/spell=21401
http://wotlk.cavernoftime.com/spell=16509
http://wotlk.cavernoftime.com/spell=15580

![Foreman Thaldrin](https://user-images.githubusercontent.com/103254348/162993519-0fcd1ba7-dcc1-4533-b7ed-1652f4233de2.jpg)

**Revision**:

**Comment by EtheriousNW** [comment]
Fixed in rev 1055

**Comment by kgms20** [comment]
Issue still present re tested 2x since launch
