### ISSUE TITLE
[Quest] Bloody Breakout

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#18]
**Description**: When Koltira Deathweaver exits the keep for Bloody Breakout, he mounts up and after taking a hit dismounts but continues to run at mounted speed. 

**Current behaviour**: Koltira Deathweaver dismounts but continues to run at mounted speed.

**Expected behaviour**: Koltira Deathweaver should stay on his mount. 

**Revision**: 1036

**Comment by Cold-Martijn** [comment]
Might be knockback that caused this? Does not usually happen (tested 3 times, could not reproduce).

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
