### ISSUE TITLE
[NPC] Runic Battle Golem

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#180]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Runic Battle Golems](https://www.wowhead.com/npc=26284/runic-battle-golem) should be fighting with Earthen Warriors in Thor Modan in Grizzly Hills

**Current behaviour**: The runic battle golems are not fighting with the earthen warriors, the earthen warriors are attacking them though

**Expected behaviour**: the battle golems should be attacking back

**Revision**: 1045
![a4bb48dbc07abb2ce7122b53954489e1](https://user-images.githubusercontent.com/17366512/163007437-d6a6a7bf-8b73-4c2f-a729-98089e5b22fd.png)

**Comment by EtheriousNW** [comment]
Fixed in rev 1055
