### ISSUE TITLE
[Icecrown] Changing zones procs Dying Curse and Lightweave Embroidery

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#182]
**Description**: 
https://wotlkdb.com/?spell=55642
https://wotlkdb.com/?item=40255
In zones Sindragosa's Fall, Aldur'thar: The Desolation Gate, Scourgeholme, Icecrown(The Argent Vanguard), Savage Ledge, almost every part of Icecrown.
**Current behaviour**:
While changing the above mentioned zones, trinket Dying Curse and tailoring back enchant Lightweave Embroidery proc on their own every time.
https://www.youtube.com/watch?v=gTkRPeyjSOs
**Expected behaviour**: 
Changing zones should not trigger any trinket or enchant procs.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1046.

**Comment by kgms20** [comment]
All issues still existing, also happening in Storm Peaks.

**Comment by kgms20** [comment]
Update, happening all across Northrend.
