### ISSUE TITLE
[NPC] Moa'ki Bottom Thresher [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#184]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Every single Moa'ki Bottom Thresher I have encountered so far seems to be stuck, immovable, evades if engaged from range  and unless fought in melee, exits combat (resets) shortly after.

**Current behaviour**: Right now, they can be only killed by standing in their melee.

**Expected behaviour**:  They should be mobile.

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
