### ISSUE TITLE
[No Rest For The Wicked] Alumeth's Remains

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#186]
**Description**: 
https://wotlkdb.com/?quest=13346
Combine his [[heart]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Heart), [[skull]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Skull), [[scepter]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Scepter) and [[robes]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Robes) from around their chamber and use his [[remains]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Remains) on the crystal there.
[Awakens Alumeth the Ascended.](https://wotlkdb.com/?spell=60831)
**Current behaviour**:
Once you turn in the completed quest, the quest item remains in your bags.
https://www.youtube.com/watch?v=_17yRD8m4GQ
https://www.youtube.com/watch?v=XQuYL8bfbGo
**Expected behaviour**: 
Once you finish channeling the quest item, it should dissapear from your bags as Alumeth the Ascended spawns.
https://www.youtube.com/watch?v=J1Ke_aJC7Xk - 5:13
https://www.youtube.com/watch?v=WbpvWIx9IV0 - 2:10
**Revision**:

**Comment by drezzy958** [comment]
You can right click on the video to resume a specific sequence

**Comment by kgms20** [comment]
**UPDATE**
Day 2 after finishing the quest, I still have Alumeth's Remains in my inventory which I can use at any moment, spamming it infinite times. 
So I went and got the same quest, now daily, where it states :
Combine his [[heart]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Heart), [[skull]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Skull), [[scepter]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Scepter) and [[robes]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Robes) from around their chamber and use his [[remains]](https://wowwiki-archive.fandom.com/wiki/Alumeth%27s_Remains) on the crystal there.
Same thing happened, then I turned in the quest, and all the items required to create Alumeth's Remains dissapeared, while Alumeth's Remains still remained in bags.
https://www.youtube.com/watch?v=XQuYL8bfbGo

What is the point of collecting those 4 items, when you have that one item all along? Does not make sense.
Like i linked in **Expected behaviour** , it should instantly dissapear upon using.

**Comment by Evolvee** [comment]
fixed in next rev
