### ISSUE TITLE
[Quest] The Ironwall Rampart [NPC] Grimkor the Wicked

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#189]
**Description**: 
https://wowpedia.fandom.com/wiki/Grimkor_the_Wicked
https://wowpedia.fandom.com/wiki/Grimkor%27s_Hound
**Current behaviour**:
NPC Grimkor The Wicked missing quote : "You think you can wrest this rampart from my control?
I think not. When I've finished beating the arrogance out of you, I'll impale your corpse on the spikes as an example to any other 'heroes'!" 
NPC Grimkor's Hound is a level 1 elite also missing abilities.
NPC Grimkor The Wicked has only meele attack and missing ability Shadow Bolt and Summon Skeletons.

**Expected behaviour**: 
Once summoned NPC should have a quote and both of his abilities, starting from attacking with Shadow Bolt.
https://www.youtube.com/watch?v=fL-XW_GoxPw - 1:12
https://www.youtube.com/watch?v=s2BB85bPw4c - 1:00

![WoWScrnShot_041222_210206](https://user-images.githubusercontent.com/103254348/163039356-fd152845-6657-4b90-a724-c4f3413fdea3.jpg)

![WoWScrnShot_041222_214444](https://user-images.githubusercontent.com/103254348/163041499-df5b85bb-3f1a-4c93-b4ee-6392e7301e92.jpg)

**Revision**:

**Comment by EtheriousNW** [comment]
Fixed in rev 1055 feel free to retest
