### ISSUE TITLE
[zone][quest] Ruby sanctum zone / Ruby sanctum quest - exists on 3.0 patch

### ISSUE THREAD

**Issue by duzyizly** [Stormforge-gg/Bugtracker-Wotlk-Beta#19]
**Description**: 
Right now you are able to enter Ruby sanctum (not sure if for testing purpose), you are also able to pick/complete ruby sanctum quest line which should not exist "yet".
This should be not possible till very endgame of wotlk.

https://www.wowhead.com/quest=26012/trouble-at-wyrmrest

![image](https://user-images.githubusercontent.com/43931626/162402920-78b734af-ff55-4ec9-a177-082a5a0d097f.png)

**Revision**: 
1036

**Comment by BAndysc** [comment]
Fixed in 1054
