### ISSUE TITLE
[NPC] Claw [Zone] The Underbog

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#190]
[Zone] [NPC] 

**Description**:  https://wowclassic.judgehype.com/database/en/npc/17827/griffe/
![azazazazaz](https://user-images.githubusercontent.com/62518101/163042337-c81206d0-ad7c-4def-b46b-79a543e5a108.png)

**Current behaviour**:
Claw NPC 17827 = the pet does not attack

**Expected behaviour**: 
https://youtu.be/fVF2rGQwGhE?t=7

**Comment by EtheriousNW** [comment]
No need to report TBC dungeons, they will be ported from Karazhan
