### ISSUE TITLE
[Quest] Chasing Icestorm: Thel'zan's Phylactery (12467)

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#191]
**Description**: 
NPC leaves and comes back but Icestorm never comes.

**Current behaviour**:
After talking to Wyrmbait (27843) he flies into the distance and returns but Icestorm is never spawned.
Wyrmbait is then unable to be talked to, even after dropping quest.

**Expected behaviour**: 
Talking to Wyrmbait will spawn Icestorm

**Revision**: 
1044

**Comment by Wolffenstein** [comment]
Fixed in rev 1046.
