### ISSUE TITLE
[NPC The Steamvault

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#192]
**Description**: https://tbc.wowhead.com/npc=17799/dreghood-slave
![image](https://user-images.githubusercontent.com/62518101/163044360-ac9fd294-90c3-46e4-8ff4-7e7616ea180d.png)

**Current behaviour**:
he does not mine

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/62518101/163044341-7aa0dd8d-4ffb-4394-9da3-045334426838.png)

-------

**Description**:  
https://tbc.wowhead.com/npc=17721/coilfang-engineer
https://www.wowhead.com/npc=17802/coilfang-warrior
![image](https://user-images.githubusercontent.com/62518101/163045639-974bf956-ae5d-46f1-b2aa-b78f2c8db0a4.png)

**Current behaviour**:
npc=17721 he does not mine
npc=17802 no patrol in front of the npc 17721

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/62518101/163045815-9c468f3d-fc30-474a-bab6-fad9d68628ce.png)
https://youtu.be/ZlTPD5_8aF8?t=162

------

**Description**: 
https://www.wowhead.com/npc=17802/coilfang-warrior
https://tbc.wowhead.com/npc=17801/coilfang-sir
![image](https://user-images.githubusercontent.com/62518101/163046704-50179686-d20c-492c-b6a2-cf4141449f63.png)

**Current behaviour**: bad position

------
**Description**: 
https://tbc.wowhead.com/npc=17917/coilfang-water-elemental
https://tbc.wowhead.com/npc=17797/hydromancer-thespia
                         
![image](https://user-images.githubusercontent.com/62518101/163047021-127dcc5c-a85f-4e96-ae98-772e96e6155a.png)

**Current behaviour**: when I attack the (npc=17797 Hydromancer Thespia) the ( npc=17917 coilfang water-elemental) does not attack me

**Expected behaviour**: 
https://youtu.be/ZlTPD5_8aF8?t=599

---------

**Description**:  
https://tbc.wowhead.com/npc=17800/coilfang-myrmidon
https://en.tbc.wowhead.com/npc=17803/oracle-de-glissecroc
![xxxxxxxxxxx](https://user-images.githubusercontent.com/62518101/163049769-ba4582c3-1c13-4fd4-96d1-b7ec10075bf9.png)

**Current behaviour**:  after killing (npc=17796 mekgineer-steam rigger) NPCs don't spawn in front of last boss door

**Expected behaviour**: 
https://youtu.be/ZlTPD5_8aF8?t=1145

**Comment by EtheriousNW** [comment]
The TBC dungeons will be ported from Karazhan so no need to report these
