### ISSUE TITLE
[Quest] Rivenwood Captives [Zone] Howling Fjord

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#196]
**Description**: 
https://www.wowhead.com/quest=11296/rivenwood-captives
https://www.wowhead.com/npc=24211/freed-winterhoof-longrunner

![qsdqdqd](https://user-images.githubusercontent.com/62518101/163077683-d47de3fc-c935-4835-98d5-38d0b0c03e4a.png)

**Current behaviour**: they attack once released

**Expected behaviour**: they must not attack

https://youtu.be/wRbuYl86x8w?t=76

**Comment by Evolvee** [comment]
fixed in next rev
