### ISSUE TITLE
[Quest] On Ruby Wings [Zone] Dragonblight 

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#197]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The quest doesn't work. Firstly, it's impossible to kill Thiassi the Lightning Bringer on top of the dragon, as it keeps evading and exiting combat. Secondly, even if you dismount and kill it, Antiok doesn't spawn, thus making this quest impossible to complete.

**Current behaviour**:  Thiassi the Lightning Bringer can't be killed while on top of the drake, and killing him without the drake doesn't spawn Antiok. 

**Expected behaviour**:  https://www.wowhead.com/quest=12498/on-ruby-wings#videos

**Revision**:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/232
