### ISSUE TITLE
[NPC][Drop] Forgotten Depths Slayer

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Wotlk-Beta#198]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Obtained 6 manuals: heavy frostweave bandage, while doing the initial quests in the Valley of Echoes (killed ~ 40 mobs).

**Current behaviour**:
Forgotten Depths Slayer (ID = 30333) have an increased chance to drop Manual: Heavy Frostweave Bandage (ID = 39152). 

**Expected behaviour**: 
According to https://wotlkdb.com/?item=39152 the manual has a 0.1 % drop chance from Forgotten Depths Slayer (ID = 30333).

**Revision**:

**Comment by Wolffenstein** [comment]
Not a bug.
