### ISSUE TITLE
[Quest]An Undead's Best Friend [Zone] Icecrown

### ISSUE THREAD

**Issue by Brabo2397** [Stormforge-gg/Bugtracker-Wotlk-Beta#199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
For the quests An Undead's Best Friend (https://www.wowhead.com/quest=13169/an-undeads-best-friend),
Honor is for the Weak (https://www.wowhead.com/quest=13170/honor-is-for-the-weak) and From Whence They Came (https://www.wowhead.com/quest=13171/from-whence-they-came), you click the Eye of Domination. This gives you control over a creature with a different action bar. It also gives you the buff Ethereal (https://www.wowhead.com/spell=58548/ethereal).
![WoWScrnShot_041322_095002](https://user-images.githubusercontent.com/103562720/163127012-e97bac29-7215-4119-85ff-8c68a7d38b2d.jpg)

**Current behaviour**:
Upon completing these quests, you keep the Ethereal effect.
**Expected behaviour**: 
Upon completing these quests, the effect is supposed to drop off.
https://youtu.be/M-1ckoVKFOU?t=386 This video shows the Ethereal effect dropping on a different (retail?) server.
**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
