### ISSUE TITLE
[Quest] Death Comes From On High

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#2]
**Description**: 
You retain the "The Eye of Acherus[51852]" Buff when leaving the quest area as the eye.

**Current behaviour**:
Leaving the quest area ports you back to archerus but does not remove "The Eye of Acherus" buff so you must click it off manually.

**Expected behaviour**: 
Leaving the quest area ports you back to archerus and removes "The Eye of Acherus" buff.

**Revision**: 
1034

**Comment by Wolffenstein** [comment]
Should be fixed now.
