### ISSUE TITLE
[Core] On next attack abilities not checked for resource before cast, skips autoattack

### ISSUE THREAD

**Issue by H4Xx0R-PC** [Stormforge-gg/Bugtracker-Wotlk-Beta#20]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Using an on next attack ability (Maul, Heroic Strike, Cleave, Rune Strike) and then losing the resource needed before the attack is executed causes the swing timer to be reset while failing the special attack

**Current behaviour**:
Currently, reproducing the steps:
1: Get to 15 rage
2: Queue heroic strike
3: Cast e.g. Rend, causing the player to go below 15 rage
4: Swing timer ready

Will cause the ability to fail, causing the swing timer to reset. Neither a heroic strike nor an auto attack will be performed.

**Expected behaviour**: 
Reproducing the steps above should instead cancel the Heroic Strike and cast an auto attack instead.

**Revision**: 
1036

**Source**:
https://truewow.org/forum/viewtopic.php?f=49&t=13005&p=177188&hilit=next+attack#p177188

I can provide a bunch of other sources, just CBA searching right now.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
