### ISSUE TITLE
[Quest] Assault By Air [Zone] Icecrown

### ISSUE THREAD

**Issue by Brabo2397** [Stormforge-gg/Bugtracker-Wotlk-Beta#200]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
For the quest Assault By Air (https://www.wowhead.com/quest=13309/assault-by-air), you shoot at Ymirheim Spear Guns (https://www.wowhead.com/npc=31280/ymirheim-spear-gun) to blind them so that they don't attack your airplane.
**Current behaviour**:
The Ymirheim Spear Guns are not attacking the airplane.

**Expected behaviour**: 
The Ymirheim Spear Guns are supposed to attack the airplane.
https://youtu.be/qLQD8YtVDnc This video shows how the quest should work.
**Revision**:

**Comment by FX-SF** [comment]
Still does not work as of revision 1309: Cannons will not attack Skybreaker Suppressor Bug trivializes difficulty of quest (i start quest, afk 5 minutes, come back, quest is complete)
Heres an additional [2009 video guide](https://www.youtube.com/watch?v=QocqIwmiMpk&ab_channel=DugiGuides) in depth guide

**Comment by Cold-Martijn** [comment]
please check again after next update of the PTR, should be fixed.
