### ISSUE TITLE
[Raid][NPC] Grand Widow Faerlina

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#201]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently missing a web gate at the exit during the fight. Also on 25m the [worshippers](https://www.wowhead.com/npc=16506/naxxramas-worshipper) should not be giving Faerlina [Widow's Embrace](https://www.wowhead.com/spell=28732/widows-embrace) on death (this mechanic is reserved for 10m only). Widow's Embrace should come from a mind control onto the worshipper on 25m

**Current behaviour**: There is no gate that closes behind the raid, allowing full resets. Worshippers debuffing Faerlina on death on 25m difficulty.

**Expected behaviour**: There should be a web that closes the exit after engaging the boss. Worshippers should need to be MC'd on 25m.

**Revision**: 1046

[source](https://youtu.be/1HVZEGNeoOg?t=37)

![fb17b1aa444a43b689383a91e25ab5c4](https://user-images.githubusercontent.com/17366512/163146954-d062ab58-1a5e-4500-99c6-9f2ac9b9b22a.jpg)
![1b4a913662d0ce0d3347988ef5eee048](https://user-images.githubusercontent.com/17366512/163150003-0cc4723b-7e01-41bc-9843-af3f5cb51763.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1047.
