### ISSUE TITLE
[Raid][NPC] Plague Beast

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#203]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Abilities of [Plague Beast](https://www.wowhead.com/npc=16034/plague-beast) in naxx (tested on 25) not functioning properly

**Current behaviour**: Mutated Spores is not an aura(?) or it is not functioning as an active spell. Plague Splash is applying two debuffs with two separate values. One being 1900-2100 damage every 3 seconds, the other being 950-1050 damage every 3 seconds.

**Expected behaviour**: Mutated Spores should be an aura(?) or at least be used and not miss. Plague splash should only apply a single debuff.

**Revision**: 1046

![2b6b0468f79f4baae813b0120f35b330](https://user-images.githubusercontent.com/17366512/163157002-af1d9147-cb6d-4a43-aa0e-cdae95ffac6e.png)
![932f71d302d15f8fb18cf8a5b5c66607](https://user-images.githubusercontent.com/17366512/163157009-0262c0a5-b9ef-4b3f-81ef-6220a83b83c1.png)
![09597a7fc17da0df6fef1d017866c572](https://user-images.githubusercontent.com/17366512/163157012-21333ae1-1b4f-4cd5-9a31-42c2e48135e7.png)

**Comment by Wolffenstein** [comment]
Mutated Spores is a permanent aura they have on themselves, which periodically deals AoE damage (which can miss). That part is working correctly.

Plague Splash fixed in revision 1047.
