### ISSUE TITLE
[Raid][NPC] Eye Stalk

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#204]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Potentially buggy behavior from the [Eye Stalks](https://www.wowhead.com/npc=16236/eye-stalk) in the plague quarter gauntlet.

**Current behaviour**: The eye stalks, once aggro'd, do not reset when leaving the room (or moving into Loatheb's room), causing the player to be stuck in combat and are causing a weird interaction with the aggro indicator on the player frame. The ones that aren't aggro'd continue to pop up and down like normal.

**Expected behaviour**: Unsure of the blizzlike behavior (maybe this is blizzlike) but it doesn't seem right to me the way they are acting now. If anyone has further information, please comment.

**Revision**: 1046

https://user-images.githubusercontent.com/17366512/163163869-4d1659eb-1528-4311-9c94-54670b226a98.mp4

![c6d53db0533a1677436051f36ae29071](https://user-images.githubusercontent.com/17366512/163163905-3a163add-d68a-4dda-93f0-e055c254755c.png)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/163242883-783fc99d-a11b-4005-8b09-c35c6dda184d.png)
It's blizzlike, you get stuck in combat with them until you kill them on retail as well.
