### ISSUE TITLE
[Raid][NPC] Unholy Sword(s)

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#206]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Unholy Swords](https://www.wowhead.com/npc=16216/unholy-swords) is currently missing a sword in naxxramas

**Current behaviour**: Model only has one sword

**Expected behaviour**: Model should wield two swords

**Revision**: 1046

![3ba00ce46e2af9c47c188fc501108145](https://user-images.githubusercontent.com/17366512/163224940-e525571c-4006-4490-98ab-32eee6f30332.png)
![99569-unholy-swords](https://user-images.githubusercontent.com/17366512/163225145-dbef16ed-fdfe-49cd-a654-72222b6914bc.jpg)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/163244479-4bc69c8d-8b18-442f-8a6e-efa987ac39fe.png)
That's weird, it's single sword on retail and in my sniffs

**Comment by Wolffenstein** [comment]
Fixed in rev 1047.
