### ISSUE TITLE
[Raid][NPC] The Four Horsemen

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#208]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Two of the four horsemen do not use their listed AoE abilities. This was tested in naxx25, with a partner to make sure it was not a solo issue. (unless it requires more than two people to meet the requirements for them to cast the abilities) 

**Current behaviour**: [Lady Blaumeux](https://www.wowhead.com/npc=16065/lady-blaumeux) is not using her [Void Zone](https://www.wowhead.com/spell=28863/void-zone) ability. [Sir Zeliek](https://www.wowhead.com/npc=16063/sir-zeliek) is not using his [Holy Wrath](https://www.wowhead.com/spell=28883/holy-wrath) ability.

**Expected behaviour**: These two horsemen should be using their listed abilities.

**Revision**: 1046

**Comment by Wolffenstein** [comment]
Are you sure there was someone nearby? Holy Wrath only has 45yd range

**Comment by Wolffenstein** [comment]
Never mind, i see what's wrong

**Comment by Wolffenstein** [comment]
Fixed in rev 1047.
