### ISSUE TITLE
[Zone]  Gnomeregan

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#209]
**Description**: https://www.wowhead.com/npc=7079/viscous-fallout
![image](https://user-images.githubusercontent.com/62518101/163231361-1756d154-25a2-4a35-a645-e2e525baf5f0.png)

**Current behaviour**: the size is too small of the NPC 7079

**Expected behaviour**:  
https://youtu.be/Rn92PSPu8GA?t=6

---------

**Description**: https://www.wowhead.com/npc=7849/mobile-alert-system
![image](https://user-images.githubusercontent.com/62518101/163231951-508952b6-9c84-4ea2-a9f6-464d1feca3c6.png)

**Current behaviour**: no warning sound

**Expected behaviour**:  https://www.wowhead.com/sound=5805/a-mobile-alert-bot-intrdralert0

**Comment by Cold-Martijn** [comment]
Fixed the warning sound, and I don't see issues with Viscous Fallout, it has a bigger size than the elementals in the same room.
