### ISSUE TITLE
[Raid][Object] Naxxramas Portal

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#210]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The Naxxramas portal in Maexxna's room is not flush with the wall

**Current behaviour**: Not properly aligned with the wall

**Expected behaviour**: Should be aligned with the wall

**Revision**: 1046

![a702284a5973462e057c66613f703622](https://user-images.githubusercontent.com/17366512/163234135-691db32a-b0de-4b82-b5cd-bc6be7953a1b.png)

blizzlike:
![8ad3c67e428d38af94a9a6c2169cb2d4](https://user-images.githubusercontent.com/17366512/163234204-92e75810-c361-4d00-9167-bb92bb9fa03d.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1047.
