### ISSUE TITLE
[Raid][NPC] Kel'Thuzad

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#211]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Kel'Thuzad](https://www.wowhead.com/npc=15990/kelthuzad) did not cast [Frost Blast](url) once (tested solo in 25m)

**Current behaviour**: KT did not cast frost blast once during the fight. This was tested solo so there could be a minimum amount of people needed to trigger the ability but the wiki does state it can be cast on the main tank (his current target) in 25m.

**Expected behaviour**: KT should cast his frost blast 

**Revision**: 1046

![3100deb71595effd3e8658c161fd3fef](https://user-images.githubusercontent.com/17366512/163241461-77fa01d2-f5b1-40ad-b79a-0c0c11af5c56.png)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/163246897-de9918ea-7610-4b1c-844c-a0ecbbb6271f.png)
Works fine for me in 25m.
