### ISSUE TITLE
[Quest] Worm Wrangler [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#214]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The quest is broken. Dropping the box anywhere in Ice Heart Cavern and right clicking on it counts towards prorgression. You don't need to place to place it on top of Ice Heart Jormungar spawn at all in order to get the quest done.

**Current behaviour**: Dropping the box anywhere inside the cave and right clicking on it counts towards progression. Dropping it on top of the Spawn, doesn't despawn it.

**Expected behaviour**:  The box should be dropped on top of Ice Heart Jormungar Spawn, which causes the Jormungar to despawn, and only then right clicking the box should count towards quest progression.
https://www.wowhead.com/quest=12078/worm-wrangler#videos

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
