### ISSUE TITLE
[Spell][Paladin] Seal of Corruption

### ISSUE THREAD

**Issue by flatronek** [Stormforge-gg/Bugtracker-Wotlk-Beta#215]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Seal of Corruption](https://wotlk.evowow.com/?spell=53736) is causing damage with the `Once stacked to 5 times, each of the Paladins attacks also deals 33% weapon damage as additional Holy damage.` portion even with just 1 stack present on the target. The damage seems to scale with number of stacks for some reason.

![Seal of Vengeance bug](https://user-images.githubusercontent.com/12128129/163260032-9caaedea-e5fd-4909-8a1c-b7930d0e9b18.png)

**Current behaviour**:
Seal of Corruption deals on-hit damage when at least 1 stack of Blood Corruption debuff is present on the target.

**Expected behaviour**: 
Seal of Corruption deals on-hit damage only when Blood Corruption is stacked to 5 times.

**Revision**: 
1047

**Comment by Wolffenstein** [comment]
That is actually correct and mimics retail behaviour even if it's against what it says.
