### ISSUE TITLE
[Talent][Warrior] Blood Frenzy

### ISSUE THREAD

**Issue by flatronek** [Stormforge-gg/Bugtracker-Wotlk-Beta#216]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Blood Frenzy](https://wotlk.evowow.com/?spell=29859) dissipates from the target when [Deep Wounds](https://wotlk.evowow.com/?spell=12867) ends even though [Rend](https://wotlk.evowow.com/?spell=47465) is still present on the target. 

Both `Rend` and `Deep Wounds` properly apply `Blood Frenzy`. According to the tooltip: `In addition your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%.` [Blood Frenzy](https://wotlk.evowow.com/?spell=29859) should be up while either `Rend` or `Deep Wounds` are present. 

![blood-frenzy-1](https://user-images.githubusercontent.com/12128129/163261268-36b62994-6a5d-4746-bdb5-1a008b5e2538.png)
![blood-frenzy-2](https://user-images.githubusercontent.com/12128129/163261277-8057675e-aaa3-4af9-9d30-54faff1e08e4.png)

**Current behaviour**:
`Blood Frenzy` drops when `Deep Wounds` ends even if `Rend` is still on the target.

**Expected behaviour**: 
`Blood Frenzy` does not drop when `Deep Wounds` ends while `Rend` is on the target.

**Revision**: 
1047

**Comment by flatronek** [comment]
Not sure if it helps or if you even want such help, but here's my report of the same bug to another core with a fix: https://github.com/azerothcore/azerothcore-wotlk/issues/8505

**Comment by Wolffenstein** [comment]
Fixed in rev 1060.
