### ISSUE TITLE
[NPC] Crystalline Ice Giant [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#217]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  In every video of "Really Big Worm" I have watched so far, Crystalline Ice Giant inside Ice Heart Cavern next to Rattlebore were dead, which would make sense considering it's the lair of their archenemy.

**Current behaviour**: They are alive and well. <a href="https://ibb.co/5FRynR6"><img src="https://i.ibb.co/dg5qL5r/Ice-Heart-Cavern.png" alt="Ice-Heart-Cavern" border="0"></a>

**Expected behaviour**:  They should be dead according to the wowhead videos. https://www.wowhead.com/quest=12080/really-big-worm#videos

**Revision**:

**Comment by EtheriousNW** [comment]
Fixed in rev 1055
