### ISSUE TITLE
[NPC][Quest] Xink's Shredder [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#218]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  There are two bugs I have discovered associated with [Harp on This!](https://www.wowhead.com/quest=12052/harp-on-this) and [Lumber Hack](https://www.wowhead.com/quest=12050/lumber-hack) and concerning Xink's Shredder. 

**Current behaviour**: 
First: 4th ability or [Emergency Repair Kit](https://www.wowhead.com/spell=47966/emergency-repair-kit) doesn't seem to be working. Attempting to cast it displays the  message that Xink's Shredder is immune to it.

Second (possibly a bug): After completing the quests, you can keep summoning Xink's Shredder (althought unmountable this time)  and stack them up for a while before they start despawning. ( I can't find a source if this is a bug or it's intended)
<a href="https://ibb.co/SJ8HT6q"><img src="https://i.ibb.co/TrSJXwz/Shredder.png" alt="Shredder" border="0"></a>

**Expected behaviour**:  https://www.wowhead.com/npc=27061/xinks-shredder#abilities

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
