### ISSUE TITLE
[NPC} Dragonblight NPCs missing abilities

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#220]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Certain Dragonblight NPCs missing some or all of their abilities. 

**Current behaviour**:  

Blighted Elk, Blacksmith Goodman,Rotting Storm Giant and Rattlebore miss all of their abilities.
                                      
High General Abbendis and Onslaught Commander Iustus and Rothin the Decaying each miss one of their abilties.

**Expected behaviour**:  

Blighted Elk https://www.wowhead.com/npc=26616/blighted-elk#abilities ([Plague Blight](https://www.wowhead.com/spell=43506/plague-blight))
                                       
 Blacksmith Goodman https://www.wowhead.com/npc=27234/blacksmith-goodman#abilities ( [Crush Armor](https://www.wowhead.com/spell=33661/crush-armor) and [Skull Crack](https://www.wowhead.com/spell=15621/skull-crack))
                                       
 Rotting Storm GIant https://www.wowhead.com/npc=27270/rotting-storm-giant#abilities / http://wotlk.cavernoftime.com/npc=27270( Conflicting spell names (between wowhead and wotlk db) [Forged Thunder](https://www.wowhead.com/spell=50405/forged-thunder) or [Lightning Bolt](http://wotlk.cavernoftime.com/spell=49238))

Rattlebore https://www.wowhead.com/npc=26360/rattlebore#abilities ([Corroded Mind](https://www.wowhead.com/spell=51203/corroded-mind), [Corrosive Spit](https://www.wowhead.com/spell=47447/corrosive-spit) and [Powerful Bite](https://www.wowhead.com/spell=48287/powerful-bite) According to http://wotlk.cavernoftime.com/npc=26360 ( [Mortal Strike](http://wotlk.cavernoftime.com/spell=13737) as well)

High General Abbendis and Onslaught Commander Iustus should have [Unrelenting Onslaught](https://www.wowhead.com/spell=50713/unrelenting-onslaught)  (conflicting with http://wotlk.cavernoftime.com, however there is a comment on wowhead written during  3..3.3 patch that confirms that they should have [Unrelenting Onslaught](https://www.wowhead.com/spell=50713/unrelenting-onslaught)

Rothin the Decaying should have [Shadow Bolt](https://www.wowhead.com/spell=9613/shadow-bolt) ( I have engaged him a couple of times, 1-2 minutes long each time and he didn't cast a single Shadow Bolt)

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
