### ISSUE TITLE
[NPC] Captain Welsington [Icecrown]

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#221]
**Description**: 
Captain Welsington missing 2 abilities.
**Current behaviour**:
NPC missing abilities Mortal Strike and Intercept.
Tested 2 times 3min + combat time.
![WoWScrnShot_041422_001941](https://user-images.githubusercontent.com/103254348/163279627-28ec3aa8-f260-4e31-b8c5-697ee9ba5583.jpg)
**Expected behaviour**: 
https://wowpedia.fandom.com/wiki/Captain_Welsington
https://wotlk-twinhead.twinstar.cz/?npc=29489#abilities

**Comment by Evolvee** [comment]
fixed in next rev
