### ISSUE TITLE
[Zone] UBRS Blocked

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#227]
**Description**: https://www.wowhead.com/npc=10429/warchief-rend-blackhand
![image](https://user-images.githubusercontent.com/62518101/163465239-20c3012b-4a8a-43bb-9989-087519f9c959.png)
![image](https://user-images.githubusercontent.com/62518101/163465718-c013b814-a5d0-4fcb-9586-d93181bc320d.png)

**Current behaviour**: 
no Warchief Rend Blackhand + block the door does not open (a lot of private server encounter the same problem)

**Expected behaviour**: 
https://youtu.be/EF-q43XlNeI?t=4

**Comment by Godmatik** [comment]
the dungeon was fully revamped and well scripted on Netherwing, hopefully Wolf can just port it all over

**Comment by therealCrysis** [comment]
^this. Closing.
