### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender [Zone] Dragonblight

### ISSUE THREAD

**Issue by Ojren** [Stormforge-gg/Bugtracker-Wotlk-Beta#229]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: In quest you need to bring rescued villagers back to NPC using summoned gryphon. 
[](https://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender)
**Current behaviour**:
After dropping one villager gryphon rapidly disappears and needs to be resummoned each time you rescue new villager.
**Expected behaviour**: 
Gryphon should dissapear only after finishing quest or not being used for some time.

**Revision**:

**Comment by Amun12** [comment]
Yeah, happened to me as well. Forgot to report it.

**Comment by Evolvee** [comment]
fixed in next rev
