### ISSUE TITLE
Flying in Dalaran

### ISSUE THREAD

**Issue by Dionizodoros** [Stormforge-gg/Bugtracker-Wotlk-Beta#230]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Flying in Dalaran

**Current behaviour**: You can use your flying mount at the enterance to krasus landing

https://imgur.com/a/gq0C2hj

**Expected behaviour**: You shouldnt be able to use flying mount in Dalaran

**Revision**:

**Comment by Cold-Martijn** [comment]
I believe this spot at Krasus landing is indeed not a bug.

**Comment by Dionizodoros** [comment]
Alright, then youre probably right. I have no idea how it supposed to work but ive been told that wrong report is better than no report.

**Comment by Cold-Martijn** [comment]
> Alright, then youre probably right. I have no idea how it supposed to work but ive been told that wrong report is better than no report.

that is certainly true :) if you think something is bugged, give it a go!
