### ISSUE TITLE
[NPC] Multiple NPC's missing a combat sequence between them [Storm Peaks] Snowdrift Plains

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#231]
**Description**: 
In Snowdrift Plains multiple NPC's are standing near each other where there should be a combat loop sequence between them which is related to the following quests that involve those NPC's.
https://wowwiki-archive.fandom.com/wiki/Quest:Rare_Earth
https://wowwiki-archive.fandom.com/wiki/Quest:Fighting_Back
https://wowwiki-archive.fandom.com/wiki/Quest:Relief_for_the_Fallen

**Current behaviour**:
While flying over the area you can see the following NPC's :
Stormforged Raider - https://wowwiki-archive.fandom.com/wiki/Stormforged_Raider
Stormforged Reaver - https://wowwiki-archive.fandom.com/wiki/Stormforged_Reaver
Dolomite Giant - https://wowwiki-archive.fandom.com/wiki/Dolomite_Giant
Earthen Defender - https://www.wowhead.com/npc=29477/earthen-defender
Fallen Earthen Defender - https://wowwiki-archive.fandom.com/wiki/Fallen_Earthen_Defender
Fallen Earthen Defender quotes: 
**Let us fight the Irons together!
Thank you! I thought I was doomed.
Let me fight by your side!
I was certain I was going to die out here.**
Description for the quest Fighting Back:
"The refuge's defenders have done their best to blunt the iron dwarves' attacks, but we keep losing ground inch by inch. My men are hardy, but not tireless. Without reinforcements, it's only a matter of time until we will be overrun."
Also, Nidavelir Mole Machine - https://db.rising-gods.de/?object=191549&locale=0  missing summoning animation, it stands still where it should drill up from the ground and summon new units.
Clear indication that there should be combat.
In the video I included the expected behaviour.
https://www.youtube.com/watch?v=5Px65Nhikv4

**Expected behaviour**: 
You can see in the videos bellow the combat as well.
https://www.youtube.com/watch?v=p4ImhH4dOQI
https://www.youtube.com/watch?v=4js9Pur765U
**Revision**:

**Comment by therealCrysis** [comment]
Works properly in rev 1179
