### ISSUE TITLE
[Quest] On Ruby Wings [Zone] Dragonblight

### ISSUE THREAD

**Issue by Ojren** [Stormforge-gg/Bugtracker-Wotlk-Beta#232]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Fly dragon mount and destroy 30 waste scavengers and get Scythe of Antiok. 
[Quest](https://www.wowhead.com/quest=12498/on-ruby-wings)
Major bug since this quest is part of the main quest chain for this zone
**Current behaviour**:
1. Dragon mount is not summonable in The Wicked Coil area(it should be considering description of the 
[quest item](https://www.wowhead.com/item=38302/ruby-beacon-of-the-dragon-queen) )
2. One of the NPC [Grand Necrolord Antiok](https://www.wowhead.com/npc=28006/grand-necrolord-antiok#comments) is missing(when Thiassi the Lightning Bringer is respawned after death, Grand Necrolord Antiok is correctly riding him, then, after shouting his monologue, he dissapears).
3. Currently Thiassi is evading and resseting if you are not fighting him in melee on ground.

**Expected behaviour**: 

2. Missing NPC [Grand Necrolord Antiok](https://www.wowhead.com/npc=28006/grand-necrolord-antiok#comments) should be riding other NPC [Thiassi the Lightning Bringer](https://www.wowhead.com/npc=28018/thiassi-the-lightning-bringer) and engaging after Thiassi is killed. After Antiok is killed quest item should appear on ground.
3. Thiassi should be fighting dragon mount using his  [skill](https://www.wowhead.com/spell=50456/thiassis-stormbolt#used-by-npc)

**Revision**:

**Comment by Amun12** [comment]
I have already reported it.  You should use the search box to check if an issue has already been reported to avoid piling up redundant posts on the bugtracker.

**Comment by Ojren** [comment]
Well. Got little bit confused with search system(didnt find your report with it at first).Though your report is very sparse and lacking in correct details.

**Comment by Amun12** [comment]
Well I wouldn't say lacking any important details (which wouldn't be obvious to devs), more like concise. I did miss the The Wicked Coil part which you could have added in the comment section. We shouldn't be making bugtracker more messy than it should be , in order to make it easier for the devs.

**Comment by Cold-Martijn** [comment]
https://www.wowhead.com/quest=12498/on-ruby-wings#videos

**Comment by Dirtsleeper** [comment]
[NPC] Wyrmrest Vanquisher (27996) Shows nameplate as Unknown when mounted

**Comment by Wolffenstein** [comment]
Fixed in rev 1076.
