### ISSUE TITLE
[seduction][warlock] 

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#234]
**Description**: 

**Current behaviour**: in a warlock, in a succubus, seduction has a diminishing for application, but not for duration, i.e. 3 times undermine seduction is applied for 20 seconds, 4 times immunity

**Expected behaviour**:  should have 3 temptations with decreasing duration and 4x immunity

**Revision**:

**Comment by Emtec** [comment]
Fixed in 1106
