### ISSUE TITLE
[Dungeon][Zone] Ahn'kahet Heroic; [NPC] Prince Taldaram (29308)

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#238]
**Current behaviour**:
After killing Prince Taldaram, I could NOT travel through the tunnel to the next area of the dungeon
![image](https://user-images.githubusercontent.com/24845497/163633897-ee0beb9d-8bba-415a-b0e0-b46bb7e31ccb.png)

**Expected behaviour**: 
After killing Prince Taldaram, I could travel through the tunnel to the next area of the dungeon

**Revision**: 
1048

**Comment by Nuy** [comment]
That happens after you remove that buff which increases your character's size. You just have to relog and it's fine.
