### ISSUE TITLE
[Dungeon] AK; [NPC] Jedoga Shadowseeker (29310)

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#239]
**Current behaviour**:
[Spell] Gift of the Herald (56219) is applied instantly when the volunteer is "sacrificed". This results in the buff lasting about 4 seconds shorter than it should.

**Expected behaviour**: 
[Spell] Gift of the Herald (56219) is applied when Jedoga becomes active after the "sacrifice".

You can see in the video below that the buff has almost the full duration when the user finally targets her.
https://youtu.be/P8Ng_-nkX8M?t=48

**Revision**: 
1048

**Comment by Nuy** [comment]
It's 3/4 of duration so not sure what you mean by "almost the full duration". Also, you can clearly see her being red and bigger as she's descending so she is buffed already in the air.

**Comment by Dirtsleeper** [comment]
You can see in this image, the buff has 7/8 of the duration remaining and the player didn't target her immediately.
![image](https://user-images.githubusercontent.com/24845497/164020042-c9a8bbe3-df37-464f-a78c-4afa20155308.png)
If you target her immediate in the current version, the most duration it'll ever have is 3/4

**Comment by Wolffenstein** [comment]
Fixed in rev 1059.
