### ISSUE TITLE
[Dungeon] UP; Aggro on last pack in first exterior hallway

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#243]
**Current behaviour**:
Pack doesn't aggro when getting close
![image](https://user-images.githubusercontent.com/24845497/163657152-40747e6d-b1e8-4657-9ae4-18a93b00ef96.png)

**Expected behaviour**: 
Pack aggros

**Revision**: 
1048

**Comment by Lmdezorn** [comment]
I don't succeed in reproducing the issue you're reporting. 

What GM buffs did you have on your char at that time? I don't really know what might have caused this, but maybe coming too fast (several ofthe GM buffs increase the movement speed) compared to "normal" speeds triggers that bug? I tried with Berserk (spell=72525), Rage (spell=66776) and Saronite Barrier (spell=63364) on me, always pulled aggro while getting closer to the pack.
