### ISSUE TITLE
[Trinket] Illustration of The Dragon Soul

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#25]
**Description**:  Trinket isnt applying stacks properlly and it reacts to every single spell.

**Current behaviour**:  At this moment, trinket adds buff stacks with every single spell including mounting up. Also it should add 1 buff charge/stack per 1 spell cast, atm its adding 2 buff stacks per 1 spell cast on some spells and on some spells the usual 1 buff stack.
Human Warlock
Spells tested: Kirin Tor ring (Teleport caster to Dalaran), Fel Armor, Summon Felhunter (any pet), Detect Invisibility, Demonic Circle, Create Healthstone, Soulstone, Firestone, Spellstone, Summon (mount), Unending Breath, Eye of Kilrogg .. etc, almost every spell. 
Life Tap and Health Funnel spells each add 2 buff stacks per one cast.
Ritual of Summoning, Souls , Soulshatter dont trigger any buff stacks tho.
**Expected behaviour**: 
[Each time you cast a damaging or healing spell you gain 20 spell power for the next 10sec, stacking up to 10 times.](https://wotlk-twinhead.twinstar.cz/?spell=60485) 
It should only work on damaging or healing spells as mentioned. For example in a warlock case any damaging spell + Health Funnel would add one buff stack/charge. 
**Revision**:

**Comment by kgms20** [comment]
**UPDATE**
The trinket procs 2 buff stacks on collecting Primordial Hatchlings in Sholazar Basin. Quest: Securing the Bait

**Comment by kgms20** [comment]
Trinket procs while crafting (Tailoring), crafting also procs Lightweave Embroidery 
https://wotlk.evowow.com/?spell=55642

**Comment by Amun12** [comment]
Blink and collecting Snowfall Glade Pups causes procs as well.

**Comment by kgms20** [comment]
Activates Illustration trinket proc, Dying Curse, Lightweave Embroidery upon using Fate Rune of Baneful Intent (https://wotlkdb.com/?item=43090) , eating Fist feast.

**Comment by Emtec** [comment]
Fixed in 1111
