### ISSUE TITLE
[Icecrown] [Quest] Basic Chemistry

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Wotlk-Beta#250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quest "Basic chemistry" (ID = 13279) requires you to neutralise a plague cauldron with spinal fluid (ID = 44010), which was obtained through the prequest. 

**Current behaviour**:
No adds are spawning, despite several attempts (usage of the quest item). Thus the plague cauldron cannot be neutralised.
![Plague cauldron](https://user-images.githubusercontent.com/103358327/163703704-13d02207-3b54-4bd3-a759-ce6ba616f0c7.png)

**Expected behaviour**: 
Adds should be spawning every time the quest item is used next to a plague cauldron until the plague cauldron is neutralised.
See https://www.wowhead.com/quest=13279/basic-chemistry#comments

**Revision**:

**Comment by Evolvee** [comment]
my fix for this was uploaded at 20.4. so i guess it wasnt live on the PTR when u made this issue
