### ISSUE TITLE
[Feature] Calendar, offline invited players dont see events

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Wotlk-Beta#252]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I created an event and invited everyone in the guild.
![image](https://user-images.githubusercontent.com/7255825/163818676-b8e81b62-4413-4ddd-9dcc-92f34e1e1936.png)

**Current behaviour**:
Offline players got the minimap icon glow, but then nothing on the actual calendar.

Minimap icon:
![image](https://user-images.githubusercontent.com/7255825/163819067-dc9e5242-1f16-414e-a98f-2e7a63bbcf86.png)

Calendar view:
![image](https://user-images.githubusercontent.com/7255825/163819090-a7fb8909-1323-44de-bb1d-3dd4c6d44aa9.png)

**Expected behaviour**: 
Offline invited players should see the event when they log in and be able to respond.

**Revision**: 1048

Sidenote, minor:
Creator's responded date is wrong.
![image](https://user-images.githubusercontent.com/7255825/163819249-33a1c0b9-0e17-4a1e-99f3-4bdc202cf881.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.
