### ISSUE TITLE
[Dungeon] UK; [Fight] Sarvald and Dalronn

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#253]
**Current behaviour**:
When one of the bosses are killed, they DON'T receive the "ghostly" visual effect.

**Expected behaviour**: 
When one of the bosses are killed, they DO receive the "ghostly" visual effect.

**Revision**: 
1048

**Comment by Wolffenstein** [comment]
Fixed in rev 1059.
