### ISSUE TITLE
[Npc] Putridus the Ancient

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Wotlk-Beta#255]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Rare elite mob in Icecrown (ID = 32487).

**Current behaviour**:
Was tagged by "someone" else despite no other players being around. Did not yield any loot for me.

**Expected behaviour**: 
Not being tagged by someone else if not engage in combat/no other players are around. 

**Revision**:

**Comment by FX-SF** [comment]
Was able to target mob, kill mob, and received expected loot. Did _not_ test with other player to visually see any tag issues
![WoWScrnShot_050622_150551](https://user-images.githubusercontent.com/105084838/167223059-8c57e389-1b72-4d76-a077-b39ae92b3288.jpg)
![WoWScrnShot_050622_150726](https://user-images.githubusercontent.com/105084838/167223070-7d152e65-df12-4696-b978-626074c1f54a.jpg)
![WoWScrnShot_050622_150734](https://user-images.githubusercontent.com/105084838/167223077-b251a5ca-e075-4da3-8a1b-5fcdeedb9ea0.jpg)
.

**Comment by FX-SF** [comment]
Did a second test with another person:
1) Did 6% damage to mob and then ran far for normal leash reset. Another player outside of group was able to kill after leash reset. 
2) Unsuccessful at reproducing issue.

**Comment by FX-SF** [comment]
Went there again 5 days later, still no issue

**Comment by therealCrysis** [comment]
Works fine for me as well in rev 1179. Closing for now.
