### ISSUE TITLE
[Dungeon] GD; [Boss] Colassal/Elemental; Elemental Size

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#257]
**Current behaviour**:
When the Elemental (29573) Spawns, he shrinks then grows instead of just growing.

**Expected behaviour**: 
When the Elemental (29573) Spawns, grows from small to large

**Revision**: 
1048

**Comment by Wolffenstein** [comment]
Fixed in rev 1087.
