### ISSUE TITLE
[Dungeon] DTK; [Boss] The Prophet Tharon'ja; [Spell] Rain of Fire

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#261]
**Current behaviour**:
After Rain of Fire cast, the boss begins channeling instead of placing the AoE.

**Expected behaviour**: 
After Rain of Fire cast, the ground is affected for 6 seconds.

**Revision**: 
1048

**Comment by kamithin** [comment]
Blizzlike bug

**Comment by Wolffenstein** [comment]
Blizzlike bug indeed
