### ISSUE TITLE
[Dungeon] DTK; [Boss] The Prophet Tharon'ja; [Spell] Decay Flesh

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#262]
**Description**: 
The boss never casts Decay Flesh

**Revision**: 
1048

**Comment by kamithin** [comment]
![image](https://user-images.githubusercontent.com/96308873/163927730-8642670d-622c-4e0f-a4e5-7ebaf7b9e52d.png)
He never casts decay flesh while on full hp. 
![image](https://user-images.githubusercontent.com/96308873/163927952-320894fd-98fe-483f-aca8-f6bf423b09db.png)
