### ISSUE TITLE
[Dungeon] VH; Defense Mechanism does 0 damage

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#263]
**Description**: 
Activating the defense mechanism does 0 damage to [NPC] Portal Guardian (30892)
Defense mechanism only brings [NPC] Portal Keeper (30295) to ~70% health.
After failing an attempt, the defense mechanisms don't reset with the dungeon.

**Revision**: 
1048

**Comment by Nuy** [comment]
Portal Keeper/Guardian can't take damage from that and it does only 13000 damage in normal mode.

https://wowwiki-archive.fandom.com/wiki/Violet_Hold_(original)
https://wowwiki-archive.fandom.com/wiki/Defense_Control_Crystal

**Comment by Dirtsleeper** [comment]
I was in heroic and Keepers do take damage currently
