### ISSUE TITLE
[Dungeon] VH; [Boss] Xevozz (29266); Doesn't Cast [Spell] Arcane Bolt

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#264]
**Description**: 
This is listed in Dungeon Journal but can't find any other evidence of it.

**Revision**: 
1048

**Comment by kamithin** [comment]
He casts Arcane Barrage Volley not Bolt
![image](https://user-images.githubusercontent.com/96308873/163927186-50545c4e-abf4-403f-bba1-8f88457036c5.png)

**Comment by Dirtsleeper** [comment]
Here are the listed spells on WoWHead
![image](https://user-images.githubusercontent.com/24845497/164021057-9487b191-8b7e-4fdc-9048-20abb0dff0f0.png)

**Comment by Dirtsleeper** [comment]
In the videos I could find, I couldn't see anything that explicitly stated it was there. I can't imagine blizz changing the boss after the fact though. Maybe the journal is wrong.

**Comment by Wolffenstein** [comment]
IIRC they messed up the journal. He never casts any Arcane Bolts.
