### ISSUE TITLE
[SPELL][TALENT][MAGE][PALADIN] Spellsteal can steal Divine Sacrifice

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#267]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Mage can Spellsteal Divine Sacrifice buff which is physical what's not correct. If the target getting spellstolen has other magical buffs on top of Divine Sacrifice Spellsteal can roll Divine Sacrifice for next stolen buff. 

**Current behaviour**: Spellsteal can roll Divine Sacrifice for next stolen buff. 

**Expected behaviour**: Divine Sacrifice is physical buff so mage shouldn't be able to steal it.

https://wotlk.evowow.com/?spell=30449
https://wotlk.evowow.com/?spell=64205

**Revision**: 1048

**Comment by Wolffenstein** [comment]
Fixed in rev 1059.
