### ISSUE TITLE
[Quest] The Sum is Greater than the Parts (ID = 13043)

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Wotlk-Beta#268]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Part of a long quest chain in Icecrown that leads into [Battle at Valhalas](https://www.wowhead.com/?quest=13213)

**Current behaviour**:
I can go into Nergeld (ID = 30403) but ability 1 (Punch; ID = 56746) does no damage to close by minions and or Dr. Terrible. Similar ability 4 (Chained Grip; ID = 60540) does pull minions/Dr. Terrible behind Nergeld instead of directly in front of him.

**Expected behaviour**: 
Punch should do damage to close by enemies. Chained Grip should place pulled enemy in front of Nergeld.

**Revision**:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1256
Alpha bugtracker link, for easier closing both issues :) Both reports also describe punch, but both also describe different additional issues.

**Comment by Wolffenstein** [comment]
Fixed in rev 1074.
