### ISSUE TITLE
[NPC][Profession] Linzi Blackbolt

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Wotlk-Beta#269]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Linzi Blackbolt is an alchemy trainer in Dalaran, she teaches various archemy recipes, including transmutations.

**Current behaviour**:
Linzi currently teaches recipes for transmuting raw epic gems.

**Expected behaviour**: 
Epic gems (outside of fishing and dragon eyes) are not available in the game until 3.2 content.
She shouldn't teach those until 3.2 content release.

**Revision**: 
1060

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.
