### ISSUE TITLE
[NPC] Magistrix Lambriesse

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Wotlk-Beta#270]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Magistrix Lambriesse is the emblem of heroism vendor in dalaran horde quarter, she sells different gear for emblems as her title implies.
As a note, the aliance equivalent npc might have the same problem.
EDIT: I can't write

**Current behaviour**:
She sells a multitude of gear, including raw epic gems.

**Expected behaviour**: 
These gems should not be available until 3.2 content is introduced.

**Revision**: 
1060

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.
