### ISSUE TITLE
[Talent] Borrowed Time (52800) does not trigger

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Wotlk-Beta#271]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Borrowed time 5/5 does not always trigger.
**Current behaviour**:
While casting a long spell like Greater Heal spam PW:S, shield will go off but you won't get the Borrowed Time buff
![image](https://user-images.githubusercontent.com/7255825/164774388-a850461e-6388-4630-a1a9-dbcae40aa876.png)

**Expected behaviour**: 
You should always get Burrowed Time after casting PW:S
![image](https://user-images.githubusercontent.com/7255825/164774434-bf9e57da-37d6-4b70-a719-51361e33aa4a.png)

**Revision**: 
1060

**Comment by Wolffenstein** [comment]
Fixed in rev 1071.
