### ISSUE TITLE
[Quest] Cold Hearted

### ISSUE THREAD

**Issue by cillo1** [Stormforge-gg/Bugtracker-Wotlk-Beta#272]
**Description**: 
During the quest  [Cold Hearted](https://www.wowhead.com/quest=12856/cold-hearted) whilst riding one of the Captured Proto-Drakes; after resolving an issue mentioned in #132 by pressing space bar, you move quite a lot faster than what is shown in a video of the quest from 2008. 

**Current behaviour**: 
[Moving way too fast on Captured Proto-Drake ](https://www.youtube.com/watch?v=bCI9_jnmzlg)

**Expected behaviour**: 
[Correct movement speed of the Captured Proto-Drake](https://youtu.be/M_484Zsfmec?t=27)

**Revision**: 
1060

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.
