### ISSUE TITLE
[Spell] Feed Pet (ID = 1536)

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Wotlk-Beta#273]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Feed pet (ID = 1536) is used to increase the happiness of a hunter's pet.

**Current behaviour**:
Feed pet doesn't let you pick a food items that you want to feed to your pet instead feeds him "air" - you can see the buff appearing on my pet. However, happiness of the pet never increases.

![Unbenannt](https://user-images.githubusercontent.com/103358327/164888308-d311d071-af16-4394-8064-4d59393a36ae.png)

**Expected behaviour**: 
Feed pet lets you choose which item you want to feed to your pet and increases your pets happiness after numerous feasts.

**Revision**:

**Comment by Wolffenstein** [comment]
PTR only bug, will be fixed after next update (but will require creating a new hunter)
