### ISSUE TITLE
[Spell][Warrior] Victory Rush

### ISSUE THREAD

**Issue by DraxerTABC** [Stormforge-gg/Bugtracker-Wotlk-Beta#274]
**Description**: Victory Rush not refreshing itself when you get killing blow with it.

**Current behaviour**: Not refreshing when you get killing blow on enemy that gives honor/xp with Victory Rush.

**Expected behaviour**: Should refresh when you get killing blow on enemy that gives honor/xp.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.
