### ISSUE TITLE
[Dungeon][NPC] Risen Drakkari Death Knight (26830)

### ISSUE THREAD

**Issue by filipboev** [Stormforge-gg/Bugtracker-Wotlk-Beta#275]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[ Risen Drakkari Death Knight](https://www.wowhead.com/npc=26830/risen-drakkari-death-knight) doesn't seem to be using the [Fear](https://www.wowhead.com/spell=51240/fear) ability.

**Current behaviour**:
The only spells I noticed being cast are Deafening Roar & Icy Touch. Testing period was approx. 10 minutes idle combat.
I tested alone, and it might be a spell only used in a party setting and not on the member with the highest threat, still unsure on that.

![image](https://user-images.githubusercontent.com/1146940/164992337-2736356f-d19c-4754-be20-87adeb30f952.png)

**Expected behaviour**: 
NPC should periodically cast fear on party members

Example: https://youtu.be/TcbF0wpGePw?t=565

**Revision**: 
1060

**Comment by Wolffenstein** [comment]
They cast Fear on non-tank entities, so if you test it alone they won't use it.
