### ISSUE TITLE
[NPC] Tier and gear vendors with wrong items

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Wotlk-Beta#276]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I made one issue instead of many small ones, don't know if it was preferable.
Basically, a list of gear vendors around Dalaran that offer items introduced after 3.0.

NPCs:
Rafael Langrom
Valerie Langrom

Matilda Brightlink
Bragund Brightlink

Rueban Lauren
Paldesse

Horace Hunderland
Griselda Hunderland
Dubin Clay

**Current behaviour**:
Leather:
Rafael Langrom sells leather tier 9 and tier 10.
Valerie Langrom sells tier 7, tier 8, and various pieces of leather armor for emblems.

Mail:
Matilda Brightlink is the mail equivalent of Rafael Langrom.
Bragund Brightlink is the mail equivalent of Valerie Langrom.

Cloth:
Rueban Lauren same as Rafael but for cloth.
Paldesse same as Valerie but cloth.

Plate: (this one is a little different)
Horace Hunderland tier 9 and 10 plate vendor.
Dubin Clay tier 8 plate vendor.
Griselda Hunderland tier 7 and various plate items vendor.

**Expected behaviour**: 
Leather:
Rafael Langrom shouldn't exist until patch 3.2, and he should only sell tier 9 at that point, tier 10 when 3.3 releases.
Valerie Langrom should not sell tier 8 or 226, emblems of conquest items until 3.1.

Mail:
Matilda Brightlink same as Rafael Langrom.
Bragund Brightlink same as Valerie Langrom.

Cloth:
Rueban Lauren same as Rafael.
Paldesse same as Valerie.

Plate:
Horace Hunderland is the same case as Rafael.
Griselda Hunderland should not sell emblems of conquest plate gear until 3.1.
Dubin Clay should not be present until 3.1.

**Revision**: 
1076

**Comment by Wolffenstein** [comment]
Fixed in rev 1078.
