### ISSUE TITLE
[Quest] Fate, Up Against Your Will [Zone] Stormwind wotlk questline

### ISSUE THREAD

**Issue by Ojren** [Stormforge-gg/Bugtracker-Wotlk-Beta#278]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Fate, Up Against Your Will](https://www.wowhead.com/quest=13369/fate-up-against-your-will) quest can be taken but is not working at all. No event. No NPC.

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by EtheriousNW** [comment]
Any video of this quest?

**Comment by Vishiswaz** [comment]
https://youtu.be/y-psRBcr6eg

Linked on discord, will link it here as well for posterity

**Comment by therealCrysis** [comment]
Entire Battle for Undercity should not be available on 3.0 content anyway. Closing for now.
