### ISSUE TITLE
[TALENT] Arcane Potency instantly gets eaten with next arcane missle

### ISSUE THREAD

**Issue by Dekirayne** [Stormforge-gg/Bugtracker-Wotlk-Beta#281]
**Description**: 

![image](https://user-images.githubusercontent.com/12075744/165538994-cc11c048-9139-47a9-9d15-6a2113437d02.png)

**Current behaviour**:

If Arcane Missles procs clearcasting it will instantly eat the Arcane Potency on the next arcane missle that hits the target.

**Expected behaviour**: 

Arcane Potency should not get popped on the next missle in line, it should be stored for the next spell that hits the target, it is a huge dps loss for arcane mages if it stays like that

**Revision**:

**Comment by therealCrysis** [comment]
Confirmed bug in rev 1179.

**Comment by Wolffenstein** [comment]
Fixed in rev 1212.
