### ISSUE TITLE
[SPELL] Focus Magic doesn't work on healing spell crits

### ISSUE THREAD

**Issue by Dekirayne** [Stormforge-gg/Bugtracker-Wotlk-Beta#282]
**Description**: 
![image](https://user-images.githubusercontent.com/12075744/165540047-8c379034-af55-4a65-8c30-ce55c55847f6.png)

**Current behaviour**:
Focus Magic gives the 3% crit to the target, but healing spells that crit will not give mage the 3% crit buff back, only works on dmg spells
**Expected behaviour**: 
It should work on both healing and damage spells
**Revision**:

**Comment by Bigmedve** [comment]
When a tooltip says 'hit' it doesn't apply to heals, as they don't 'hit'. When you critically hit with a spell it should be damage, so then it's working according to the tooltip.

**Comment by Emtec** [comment]
Fixed in 1102
