### ISSUE TITLE
[patch] mail from argent tournament

### ISSUE THREAD

**Issue by Cold-Martijn** [Stormforge-gg/Bugtracker-Wotlk-Beta#283]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/90683398/165960580-9e64e384-e92c-4b68-9d5b-c656f395a1cb.png)

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by therealCrysis** [comment]
What is wrong tho?

**Comment by Vishiswaz** [comment]
This should only be active from 3.2 onwards @therealCrysis

**Comment by Cold-Martijn** [comment]
> What is wrong tho?

Should be in on the moment we will implement argent tournament stuff. Idk if that will be 3.2 or 3.1 for this server.

**Comment by Cold-Martijn** [comment]
also, WTB CONENT PATCH label

**Comment by Vishiswaz** [comment]
> > What is wrong tho?
> 
> Should be in on the moment we will implement argent tournament stuff. Idk if that will be 3.2 or 3.1 for this server.

Some argent stuff was implemented on blizzard servers in 3.1 as hype for preparing to take on the lich king. Then that was stepped up with even more stuff in 3.2, which wound up being its own (admittedly disappointing) raid tier.

**Comment by therealCrysis** [comment]
Okay, this letter should arrive on 3.1 patch obviously. Confirmed bug.

**Comment by Wolffenstein** [comment]
Fixed in rev 1216.
