### ISSUE TITLE
[Object] Battered Chest in Starting zones containing only few coppers.

### ISSUE THREAD

**Issue by DraxerTABC** [Stormforge-gg/Bugtracker-Wotlk-Beta#284]
**Description**: Looting Battered Chests in starting zones contains only few coppers.

**Current behaviour**: Battered Chests contains only few coppers

**Expected behaviour**: Battered Chests are supposed to contain sometimes green items, potions, food/water and some greys.

**Revision**:

**Comment by therealCrysis** [comment]
Confirmed in rev 1179.

It's worth to check Battered Chests' loot tables not only in starting location. Just flew over Redridge and loot was kind of poor. Surprisingly, almost every chest cointained Gold Ore, food, and white item.

**Comment by Nuy** [comment]
All chests seem to have incorrect loot and probably respawn. In some chests I've opened in Tanaris there was only some money and [Broken Blade of Heroes](https://tbc.wowhead.com/item=9719/broken-blade-of-heroes) what isn't even supposed to be inside such chest I believe.

**Comment by KurtySuit** [comment]
Opened a [chest](https://classic.wowhead.com/object=106318/battered-chest) in Echo Isles (Durotar), only had copper aswell, but despawned even if i didn't loot it

**Comment by Cold-Martijn** [comment]
Previously fixed by Wolf.
