### ISSUE TITLE
[Druid] Flight Form Momentum

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#286]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I went through this on Crystalsong with Tauri, Druids are supposed to maintain their forward momentum when they disable flight form in air while moving. Currently, they do not. This was also a bug on Atlantiss TBC, but I didn't know it was supposed to be this way for TBC as well until after I stopped playing there.

Here's evidence of it happening in ORIGINAL TBC (2007), devs can check Classic TBC now if they'd like as well. But this was definitely how things worked by WotLK for sure. https://www.youtube.com/watch?v=v7QXb6I9OtY&feature=youtu.be&t=51

Here is the Tauri ticket where they initially argued with me that this was client side (it isn't): https://bug.tauriwow.com/index.php?do=details&task_id=23188&project=3

Here is the Tauri ticket where they finally made the change: https://bug.tauriwow.com/index.php?do=details&task_id=25212

That last link also includes extra evidence, if it's needed.

I would really recommend getting this changed before launch. Flight form momentum makes a huge difference to the experience of farming as a druid, and it's specific to Druids until either Cata or MoP.

**Comment by Cold-Martijn** [comment]
I can confirm the behaviour should be druid flight forms having momentum and regular mounts should not.

**Comment by Wolffenstein** [comment]
Fixed in rev 1165.

**Comment by Vishiswaz** [comment]
Confirmed working
