### ISSUE TITLE
[NPC][UBRS][Event] Solakar Flamewreath (ID 10264)

### ISSUE THREAD

**Issue by egovir32** [Stormforge-gg/Bugtracker-Wotlk-Beta#29]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://classic.wowhead.com/object=175245/father-flame
https://classic.wowhead.com/item=13371/father-flame
https://classic.wowhead.com/npc=10264/solakar-flamewreath

https://github.com/TrinityCore/TrinityCore/issues/19370
https://github.com/azerothcore/azerothcore-wotlk/issues/611

**Current behaviour**: Looting the object 175245 does not trigger the event.

**Expected behaviour**: When you loot on the object 175245, an event is supposed to be triggered, spawning several waves of dragonkins with Solakar Flamewreath as the final wave.

**Revision**:

**Comment by therealCrysis** [comment]
Dungeon was revamped and works fully on Atlantiss. Needs to be ported.
