### ISSUE TITLE
[SPELL][SHAMAN][PET] Spirit Wolves aren't affected by Heroism/Bloodlust

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#290]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Spirit Wolves aren't affected by Heroism/Bloodlust.

**Current behaviour**: Spirit Wolves aren't affected by Heroism/Bloodlust,.

https://wotlk.evowow.com/?spell=2825
https://wotlk.evowow.com/?spell=32182
https://wotlk.evowow.com/?npc=29264

**Expected behaviour**: Spirit Wolves should be regarded as normal pets and get affected by Heroism/BL. Proof - https://www.youtube.com/watch?t=219&v=hXSswHbQ_xI&feature=youtu.be.

**Revision**: 1094

**Comment by Emtec** [comment]
Fixed in 1108
