### ISSUE TITLE
[NPC][SPELL][WARLOCK] Doomguard (1)

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Wotlk-Beta#291]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Doomguard should dismiss your current pet after succesfully enslaving it (see video)
https://www.youtube.com/watch?v=3tYPzOyUPm4&ab_channel=abysswalker21 
**Current behaviour**:
Currently the pets overlap visually, i can have both a primary pet and a doomguard stacked on top of each other
**Expected behaviour**: 
Doomguard should dismiss your current pet after you use enslave demon
**Revision**:

**Comment by MildlyDampTowelette** [comment]
https://imgur.com/a/kSiZ1US
Voidwalker and Doomguard

**Comment by Emtec** [comment]
Fixed in 1109
