### ISSUE TITLE
[NPC][SPELL][WARLOCK] Doomguard (2)

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Wotlk-Beta#292]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
A Doomguard summoned through CoD disappears too early. 
**Current behaviour**:
Doomguard disappears after 15 seconds. This happens both after using enslave demon and just leaving him be.
**Expected behaviour**: 
https://wowpedia.fandom.com/wiki/Doomguard_(warlock_minion) indicates that a Doomguard summoned through ritual of doom lasts for 15 minutes.
The video below shows the doomguard being summoned through CoD. It's not clear how long this one lasts (>15seconds in any case), but it's a reasonable assumption that it would also last 15 minutes. I can't say for certain though.
https://www.youtube.com/watch?v=3tYPzOyUPm4&ab_channel=abysswalker21

**Revision**:

**Comment by MildlyDampTowelette** [comment]
Comment on duration on  wowhead https://www.wowhead.com/npc=11859/doomguard#comments :
'As of Patch 3.1 the doomguard and the infernal are very much worth it.

They are a fine boost to DPS, they also do not attack raid members anymore, they simply despawn after the timer runs out.

the doomguard stays for 15 mins while the infernal stays for 1 min. '

**Comment by Emtec** [comment]
Fixed in 1112
