### ISSUE TITLE
Halls of Lightning Hall of the Watchers

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#294]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

In 3 separate Halls of Lightning runs, the mobs in Halls of the Watchers consistently did not activate when they were supposed to. First run, two activated. Second run, three activated. Third run, none activated when I went through (video below), then three activated (after I stopped recording) when my friend joined me. The only ones that activate at all are the 3 together at the end of the hall to the left.

https://youtu.be/BGVfI985Jjg

**Comment by Wolffenstein** [comment]
Its random

**Comment by Emtec** [comment]
Fixed in 1114
