### ISSUE TITLE
Tukemuth

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This mob spawns in the client from mega far away. Even when other large mobs don't. Like, Galleon and Sha on Mistblade far away.
![WoWScrnShot_050422_225045](https://user-images.githubusercontent.com/78314117/166857225-62bfc218-c0e5-4e1b-b76c-2ba99b3bd71a.jpg)
![WoWScrnShot_050422_225053](https://user-images.githubusercontent.com/78314117/166857227-2ae9b5f3-97fb-410f-8894-fb57b0ff9701.jpg)

**Comment by Wolffenstein** [comment]
not a bug
