### ISSUE TITLE
Ahn'Kahet The Old Kingdom: Hall of the Conquered Kings

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#296]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Movement of other players in the hall after the 2nd boss of Old Kingdom looks really buggy. Visual bug only, but still, not exactly looking great.

https://youtu.be/SR4KvKVfhnM

**Comment by Cold-Martijn** [comment]
could this be due to the PTR buffs? They have an enlarge on them.

**Comment by Wolffenstein** [comment]
Unrelated to the dungeon

**Comment by Vishiswaz** [comment]
Yeah we removed the buffs at 0:18 in the video and did it again.
