### ISSUE TITLE
[NPC][SPELL][WARLOCK] Inferno (infernal)

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Wotlk-Beta#299]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Infernals are summoned through inferno (spell) and follow the player for 1 minute until they disappear.
**Current behaviour**:
Infernals move at about half the speed of normal players, it's easy to outrun them. 
**Expected behaviour**: 
Infernals seem to run at 100% player speed in the footage i have found. I have included some clips from tbc and vanilla. I can't find any patch notes that indicate that their movement speed was altered prior or after wotlk prepatch.

https://www.youtube.com/watch?v=kqAH2O1jmHU&ab_channel=ryanrendon
https://www.youtube.com/watch?v=LDU6ElhMKnY&ab_channel=BennyHeflinger
https://www.youtube.com/watch?v=7cuyUfokGg8&ab_channel=SuliferCroft

**Revision**:

**Comment by Emtec** [comment]
Fixed in 1120
