### ISSUE TITLE
[Quest] Death Comes From On High - move speed bug

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#3]
**Description**: In DK starting zone the quest Death Comes From On High gives the player massive movement speed if you cancel Eye of Acherus via ui. 

**Current behaviour**: Character moves very fast after cancelling Eye of Acherus from Death Comes From On High quest (fixes with relog)

**Expected behaviour**: Character shouldn't go fast

**Revision**: 1034

**Comment by Wolffenstein** [comment]
Should be fixed now.
