### ISSUE TITLE
(Not sure if bug) Naxx Visual Effect

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#301]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The area where the orb is in Naxx to teleport you to Sapph/KT seems to have the visual effect of the floor duplicated a few feet above it.

Maybe I'm just uneducated on this but I don't believe I've seen that on other private servers. Is this a bug or blizzlike?
![WoWScrnShot_050522_222319](https://user-images.githubusercontent.com/78314117/167056541-ae59af8e-2eda-45e6-8433-0aff9e953f6f.jpg)

**Comment by Wolffenstein** [comment]
not a bug
