### ISSUE TITLE
Krystallus (Halls of Stone)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#302]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This may not be a bug, but it feels off.

When Krystallus kicks everyone back, on other servers I've played on (yes, I understand this could be wrong), they immediately start to get slowed. Here, it takes a second or two before the slow starts at all. This makes the boss pretty trivial.

Again, if this isn't a bug and was researched and is intended to be this way, sure thing no problemo. But otherwise it should be fixed.

**Comment by Wolffenstein** [comment]
Not a bug
