### ISSUE TITLE
Mage Hunter Ascendant (Nexus)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#303]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Looks like we got a floater, boys

![WoWScrnShot_050522_233144](https://user-images.githubusercontent.com/78314117/167062551-ebb0ffb8-a6ba-464d-9ff4-e293c64258a5.jpg)
![WoWScrnShot_050522_233146](https://user-images.githubusercontent.com/78314117/167062581-427392ad-f9ad-4ba8-8bd2-02266e4251ae.jpg)

Well, standing in the air anyways.

It appears they're supposed to be floating, sure, but not standing in the air while casting, no?

Edit: The other ones that float in this room do the same thing.

Edit 2: This ascendant also doesn't come when you LoS her
![WoWScrnShot_050522_233457](https://user-images.githubusercontent.com/78314117/167062816-c82ff0a9-9cda-4b2c-9018-e506176f94f3.jpg)

**Comment by Wolffenstein** [comment]
They use Levitate

**Comment by Wolffenstein** [comment]
They chase me when i go out of LoS so dunno, I'll force a primary ability type in rev 1123 just to be sure.
