### ISSUE TITLE
Nexus: Crystalline Frayer

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#304]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
2 issues.

1. The regeneration aura they give when they die should NOT stack. I found video evidence from a video during Cataclysm, hopefully this will do. https://youtu.be/VGwH7P1U-sI?t=583

Around the linked timecode, the 2nd player kills at least two near them and only one buff appears.

2. When these "emerge from their seed pod", currently they are set to immediately reset back to their original positions and ignore players even if they're right on top of them. Additionally, they do not keep the players in combat while they are in their Seed Pods.

I'm not sure what the correct behavior is exactly but I know this isn't it. I believe the whole point of this gauntlet is that the frayers will keep the players in combat (in exchange for a regeneration buff when you're standing near them), and will keep coming for you until the boss is defeated. At the very least they should re-aggro if you're right on top of them when they emerge from their pods.

This might need to be tested on retail. But this is almost definitely an instance where other pservers have this better. Though this isn't the first time I've seen this aura stack, some other servers have this bug as well.

**Comment by Wolffenstein** [comment]
"Additionally, they do not keep the players in combat while they are in their Seed Pods." they're not supposed to keep you in combat, that would be retarded

**Comment by Vishiswaz** [comment]
You sure? I thought that was the trade off basically for the aura they give. You get stuck in combat and can't drink but you get passive mana regen. But yeah I could be completely off base.

**Comment by Wolffenstein** [comment]
There is no trade-off its just private server incompetence to not script the mob properly for 15 years

**Comment by Vishiswaz** [comment]
Fair enough

**Comment by Wolffenstein** [comment]
Fixed in rev 1123.
