### ISSUE TITLE
[PET][WARLOCK] Hard exit (Alt F4) demon swap

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Wotlk-Beta#308]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Every time you log in, you should see your current demon in the character selection screen, which will be summoned instantly once logged in.
**Current behaviour**:
If you force exit the game (alt f4)with any demon, and immediately log in again , you end up with a different pet in some occasions. I'm currently not sure what triggers this, but it has atleast a 50% chance to occur and I have tested this with various demons.
**Expected behaviour**: 
After hard exiting the game, you should keep the demon you summoned last. 
**Revision**:

**Comment by MildlyDampTowelette** [comment]
After testing some more, the demon usually defaults to void walker after the hard exit, though I have seen the occasional succubus.

**Comment by therealCrysis** [comment]
Works correctly in rev 1184
