### ISSUE TITLE
[NPC] Drak'Tharon Keep: Novos The Summoner

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#313]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
During this fight, the mobs on the stairs should not aggro to you until you attack them first, not regular aggro rules. Otherwise just putting one person up there and having them do nothing prevents them from getting downstairs, which would trivialize the achievement.

Edit: It's possible that some of the mobs follow regular aggro rules and others don't. This may need to be tested on retail.

**Comment by Wolffenstein** [comment]
Not a bug, tested on retail
