### ISSUE TITLE
[NPC] Drak'Tharon Keep: Risen Drakkari Bat Rider

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#314]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Currently missing a dismount animation when he dismounts on aggro.

https://youtu.be/NjaK-4hLh44

**Comment by Vishiswaz** [comment]
The Risen Drakkari Handler also is missing this.

**Comment by Wolffenstein** [comment]
What dismount animation?

**Comment by Vishiswaz** [comment]
The cloud of dust you see when you dismount. At least with visual effects up all the way.

**Comment by Wolffenstein** [comment]
That only affects players and maybe some NPCs. Closing unless you find it for this specific NPC on a video.

**Comment by Vishiswaz** [comment]
https://youtu.be/k8aI9zfenR4

@Wolffenstein

**Comment by Vishiswaz** [comment]
I also found one without it https://youtu.be/8oO4WIPx7OY

But that could be from spell detail being turned down on their client. I can't tell.
