### ISSUE TITLE
[NPC] Drak'Tharon Keep: Scourge Brutes and Drakkari Guardians

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#316]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you Vanish after pulling these, you get stuck in combat, and the mobs do not properly reset. https://youtu.be/mGmJjvkq1CM

**Comment by Wolffenstein** [comment]
Fixed in rev 1136.
