### ISSUE TITLE
[NPC] Drak'Tharon Keep: Tharon'ja

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#317]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The main mechanic (him turning the group into skeletons) can be avoided with LOS.

https://youtu.be/e7sAs7GxvKk

Dunno if blizzlike, probably shouldn't be this way regardless.

**Comment by Wolffenstein** [comment]
Fixed in rev 1136.
