### ISSUE TITLE
[Global] Missing Text in Picked Lock Item Trade

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#318]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you have someone pick a lock for you through an item trade window, there's supposed to be green text saying "Pick Lock" once the lock pick has been confirmed as part of the trade. Currently, you can't see any confirmation that the rogue (or blacksmith?) is going to pick the lock for you if you trade.

https://youtu.be/CHmBWmvDGXY

https://www.engadget.com/2007-05-26-a-rogues-lock-box-request.html

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/167468437-5ec05578-2c0c-4cd8-821f-6723f6bbcc62.png)
? it works fine

**Comment by Vishiswaz** [comment]
I'll try to recreate later. But I showed it in my video
