### ISSUE TITLE
[NPC][UBRS][Event] Blackrock Stadium Event

### ISSUE THREAD

**Issue by egovir32** [Stormforge-gg/Bugtracker-Wotlk-Beta#32]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Blackrock Stadium Event takes place in the [Upper Blackrock Spire] as a mandatory event to progress further into the instance.

https://wowpedia.fandom.com/wiki/Blackrock_Stadium
https://classic.wowhead.com/npc=10429/
https://classic.wowhead.com/npc=10339/
https://classic.wowhead.com/npc=10162/
https://www.youtube.com/watch?v=W4DFETlnRqg
https://github.com/dalaranwow/dalaran-wow/issues/90

**Current behaviour**: Entering the arena does not properly trigger the event. No waves of dragonkins/orcs are spawned, however [Lord Victor Nefarius] does taunt the player as intended.
After several minutes [Gyth] will spawn, moving into the center of arena. Bringing him to 50% of MAXHP does not trigger [Rend Blackhand] spawn, so after killing [Gyth], player cannot leave the arena, and the northern gates are permanently closed, trapping the player inside.

**Expected behaviour**: Once a player moves to the center of the stadium, [Lord Victor Nefarius][10162] and [Rend Blackhand][10429] will appear on the eastern balcony while many cheering orcs will appear on the western balcony. [10162] will taunt the players and start sending waves of creatures from the northern gate. You will have a few waves of 1 elite/multiple non-elites, then a few waves of 2 elites/multiple non-elites, and finally a few waves of 3 elites/multiple non-elites.
If the players defeat all the waves, [10162] will get furious and send [10429] and his personal dragon [Gyth][10339] to defeat the players.
Once [10429] is defeated, [10162] will withdraw back to [Blackwing Lair] and the southern gate will reopen so the players can leave the arena.

**Revision**:

**Comment by Godmatik** [comment]
Dungeon was revamped and works fully on Atlantiss, likely he just needs to bring it over to this core

**Comment by therealCrysis** [comment]
Like matik said. Closing it.
