### ISSUE TITLE
[NPC] Gundrak: Slad'ran

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#320]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You can currently avoid the Poison Nova by line-of-sighting it. You should not be able to.

Throughout wotlk, players kept finding new things they could use to los and blizz kept fixing it. I would copy blizzard's intent on this one, rather than changing patch by patch which things can block los and which can't.

**Comment by Wolffenstein** [comment]
Proof?

**Comment by Vishiswaz** [comment]
Of this server's status or blizzlike?

**Comment by Wolffenstein** [comment]
That it should not be LoSable

**Comment by Vishiswaz** [comment]
https://www.wowhead.com/npc=29304/sladran#comments
![image](https://user-images.githubusercontent.com/78314117/167272763-37368231-7f85-4d79-b71f-c089cbfb7b12.png)

https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/47528647
![image](https://user-images.githubusercontent.com/78314117/167272842-7107a74a-dc96-451d-aa9d-785c86f204f0.png)

Might just be better to check retail if possible. But it also seems like it was shadow hotfixed potentially at some point or maybe multiple times.

**Comment by Vishiswaz** [comment]
https://www.wowhead.com/spell=55081/poison-nova#comments
![image](https://user-images.githubusercontent.com/78314117/167272882-38cc572b-914d-489e-9c47-2dd3d618a405.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1136.
