### ISSUE TITLE
[Zone][Nexus][Drop] - Lack of loot table for many mobs

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#323]
**Current behaviour**:1) Some mobs do not appear to have a loot table: (Azure Scale-binders, Crazed Mana-Wraithes, Crystalined Keepers are the three main culprits that NEVER drop loot it seems). There are also some mobs that drop items sometimes, and others times not. The whole instance feels weird with many obvious candidates for drop loot not dropping loot

**Expected behaviour**: Loot table for Azure Scale-Binders, Crazed Mana-Wraithes, and Crystalined Keepers

**Revision**: 
1125

**Comment by FX-SF** [comment]
Azure Scale-Binder loot table 
1) https://wotlkdb.com/?npc=26735#drops
2) https://www.wowhead.com/npc=26735/azure-scale-binder
3) https://wotlk.evowow.com/?npc=26735#drops

Crystallined Keeper loot table
1) https://wotlkdb.com/?npc=26782#drops
2) https://www.wowhead.com/npc=26782/crystalline-keeper#drops;mode:normal
3) https://wotlk.evowow.com/?npc=26782#drops

I cannot find a loot table for Crazed Mana-Wraith and I feel confident there is none.

@therealCrysis

**Comment by therealCrysis** [comment]
Crystallined Keepers got loot.
Azure-Scale Binder do not.

Rev 1184

**Comment by Wolffenstein** [comment]
Fixed in rev 1242.
