### ISSUE TITLE
Zul'Drak: Heb'Drakkar Striker

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#324]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mobs swim through the air after dismount. https://youtu.be/ZI0fBzG4paY

And they're missing a dismount animation.

**Comment by Cold-Martijn** [comment]
Alpha bugtracker report for easier closing: https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/581

**Comment by Cold-Martijn** [comment]
Fixed.... I think :) if you have any video of how this NPC should behave in general, please post.
