### ISSUE TITLE
[NPC] Emissary of Hate: No RP script, improper patrol, does not cast spells correctly

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#327]
**Description**: Emissary of Hate is a Mob that spawns from killing about 6 burning legion demons on the Isle of Quel'danas for the quest: The Battle Must Go On. He is not well scripted.

**Current behaviour**: Emissary of Hate spawns after killing about 6 burning legion demons on the Isle of Quel'danas. He patrols his spawn point only like any other moving mob fixed to a single location. He casts Mortar, which summons Mortar. This spell appears to do nothing. During the fight, something named Flame Wave summons Flame Wave II. Emissary of Hate never actually casts Flame Wave (i.e., a spell cast that can be interrupted with rogue kick). This spell also seems to do nothing. You are able to spike his corpse with the banner and complete the quest as normal.

**Expected behaviour**: Emissary of Hate spawns after killing about 6 burning legion demons on the Isle of Quel'danas. He patrols FROM his spawn point up and down the Dawning Square on a straight path. He vocalizes the following quotes:
   a) You fear death? Far worse awaits you, should you fail! Slay the mortals!
  b) Kil'jaeden's patience wears thin! Destroy the naruu's lackeys once and for all!
  c) Return to your posts! The battle is not yet over!
After some time within the fight, Emissary of Hate casts Flame Wall, which spawns a line of fire in front of the caster which deals fire damage to enemies in its path. It appears that he casts this spell, Mortar, as well: https://wotlk.evowow.com/?spell=25003.
**Revision**: 1125
![WoWScrnShot_050622_225507](https://user-images.githubusercontent.com/105084838/167241139-dbbb4246-8460-4f4e-8b90-058255b40bea.jpg)

**Comment by Evolvee** [comment]
fixed in next rev
