### ISSUE TITLE
[Zone] Warsong Hold - Docile Guards towards Enemy Faction

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#33]
Description:
Warsong Hold NPCs do not attack Alliance Character. (Level 70 Gnome DK)
(Guards, and other NPCs)
Seems like a faction check error.

Current behaviour:
Guards don't attack

Expected behaviour:
Guards do attack

**Revision**: 
1036

**Comment by Cold-Martijn** [comment]
Can confirm the issue. Not sure, but could be that it is indeed in the faction. Faction = 1980

**Comment by Cold-Martijn** [comment]
Same issue with Orgrimmar Grunt id 3296 as an alliance player.

**Comment by Peglaa** [comment]
Core issue apparently. It appears to be the case in all of Northrend.

**Comment by Wolffenstein** [comment]
Fixed in rev 1040.
