### ISSUE TITLE
[Spell] Mining: Failed Attempt

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#331]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Currently, at low mining levels, you can get the error "Failed Attempt".

This is a leftover from pre-WotLK. There should be no more Failed Attempts.

This likely happens for Herbing as well. Did Skinning have it? Idk

https://youtu.be/6A6ymfnMZMo

**Comment by Wolffenstein** [comment]
Fixed in rev 1137.
