### ISSUE TITLE
[Global] Chests

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#333]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When looting a chest, there's no chat message saying how much you looted. This appears to be just a visual bug, as the money in my bag did go up.

https://youtu.be/gcBF3m6blEc

On a side note, all the chests I'm finding in Elwynn only contain a small amount of copper. There's literally nothing else in them. No green BoEs. No crafting or gathering materials. No food or water.

**Comment by Wolffenstein** [comment]
Fixed in rev 1144.
