### ISSUE TITLE
[NPC][Drop] Gold Pickup Schedule

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#336]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This item appears to be missing from the loot tables of Elwynn Forest gnolls. It should be roughly a 3% drop rate (and at or near 100% for the gnoll rare spawn). Of course, I don't have access to the database, so I could just be super unlucky, but I killed, looted, and respawned what feels like hundreds of Riverpaw Outrunners with zero of the Gold Pickup Schedules [(and linen cloth, see my other ticket)](https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/335) dropping.

**Comment by Vishiswaz** [comment]
Someone told me they got it to drop yesterday. So maybe it's not bugged. Good to double-check though.

**Comment by FX-SF** [comment]
35 Gnoll Kills: None of them dropped the Gold Pickup Schedule. There was no cloth drops. Hogger did not drop. 
36th kill was Rare elite: Gruff Swiftbite. He dropped the quest item

**Comment by therealCrysis** [comment]
Confirmed in rev 1184

**Comment by Cold-Martijn** [comment]
Upped the chance a bit, was indeed quite low.
