### ISSUE TITLE
[Npc] King Mrgl-Mrgl (25197) Voice is Human

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#34]
**Description**: 
Voice when speaking to NPC is human, not Murloc

**Current behaviour**:
NPC Voice

**Expected behaviour**: 
Murloc Voice

**Revision**: 
1036

**Comment by Cold-Martijn** [comment]
This is not a bug :) The voice is Night-Elf, because there is a Night Elf in that suit.
