### ISSUE TITLE
[NPC] Anub'arak - No Intro RP Quote

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#340]
1) **Anub'arak** should provide a **voice quote** upon entering his room. The quote is as follows:

 "I was king of this empire once, long ago. In life I stood as champion. In death I returned as conqueror. Now I protect the kingdom once more. Ironic, yes?"

**Comment by Wolffenstein** [comment]
Source?

**Comment by FX-SF** [comment]
Two unreliable sources :/ Warmane and wiki.
I did spend 5 minutes seeking 10+ year old video. I found 2, but neither provided evidence to support or disprove the quote.

**Comment by Wolffenstein** [comment]
It's not in my sniffs, didnt occur in any of my retail visits there and not in any video. Closing.
