### ISSUE TITLE
Azjol-Nerub: Hadronox

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#341]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Full disclaimer here: I'm not sure what's blizzlike, but if this is blizzlike, you might want to consider changing it anyways.

It appears as if it doesn't matter if your group kills the trash mobs really fast, the "Hadronox moves up the tunnel" script doesn't happen until a timer happens. Overall, this makes the fight take like 5 minutes no matter how fast you kill the adds.

Is this blizzlike? Maybe. Idk. But if it is, you should consider changing it anyways.

I even tried killing the mobs that were heading down to Hadronox to see if that sped things up. It did not have any effect on the amount of time for each "Moving up the tunnel" script to run.

**Comment by Wolffenstein** [comment]
Blizzlike

**Comment by Vishiswaz** [comment]
It might be blizzlike, I'll trust you on that.

But you guys might want to consider having mercy on your players. They are not going to be happy waiting 5 minutes every time.
