### ISSUE TITLE
[NPC] Utgarde Pinnacle: Skadi

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#343]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When he casts his frost breath, it currently all appears at once.

Instead, the frost breath on the ground should appear progressively as he flies down the hallway.

**Comment by Vishiswaz** [comment]
It also appears as if the frost breath does not spawn at all down the whole hallway if none of the players are close by at the time. https://youtu.be/VXcph25Ps4Y

**Comment by NatsumeLily** [comment]
1. You should also be able to disarm him (even during whirlwind).

2. You should also be able to taunt during the whirlwind.

3. There should be a harpooner in every even numbered wave.

**Comment by Wolffenstein** [comment]
> It also appears as if the frost breath does not spawn at all down the whole hallway if none of the players are close by at the time.

not a bug
