### ISSUE TITLE
[Druid][Spell] Omen of Clarity  AND [Zone] Utgarde Pinnacle

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#344]
Druid Bear is proccing Omen of Clarity when in the Eagle's Eye location in Utgarde Pinnacle

We originally believed it to be paladin aura triggering omen of clarity, but then noticed it was location based. Later determined it to be at the Eagle's Eye location in Utgarde Pinnacle. 

Omen of clarity triggered at both ends of Eagle's Eye and down the entire length of this area.

**Revision**: 1125

https://user-images.githubusercontent.com/105084838/167273300-d46b5cbe-0b8a-4c39-844a-6fde1622548b.mp4

**Comment by Wolffenstein** [comment]
Fixed in rev 1136.
