### ISSUE TITLE
Utgarde Pinnacle: King Ymiron

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#346]
**Description**: 
You can currently interrupt his spell "Bane".

**Expected behaviour**:
You shouldn't be able to interrupt it. Only purge or spellsteal.

**Comment by FX-SF** [comment]
Was Heroic Mode

**Comment by Wolffenstein** [comment]
Fixed in rev 1136.

**Comment by Soufly** [comment]
Nope,this aint fixed ... 0 banes so far today.
