### ISSUE TITLE
[NPC] Oculus: Emerald Drake

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#348]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Emerald Drake can use its heal on other players that are not mounted on dragons.

https://youtu.be/uETLQ4I2dTY

Pretty sure they're not supposed to be able to?

**Comment by Wolffenstein** [comment]
Fixed in rev 1136.
