### ISSUE TITLE
[Global] Duel Run Away Announcement

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#350]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There's currently no message saying "X has fled from Y in a duel", or at least, it appears for the player fleeing and not the player staying at the duel flag.

https://youtu.be/ztRkMxjOyaQ

**Comment by Emtec** [comment]
Fixed in 1135
