### ISSUE TITLE
[Trinket] Illustration of The Dragon Soul #2

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#353]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/25 was the old Report. While the trinket is working better than it did, it is still bugged.

**Current behaviour**: Direct damage spells are not giving any stacks, DoTs are only giving stacks on ticks, HoTs are only giving stacks on tick, Aoes aren't giving any stacks (Seems to be mostly damage aoes), Bleed ticks are giving stacks. 

**Expected behaviour**: 
Direct damage spells should give 1 stack and direct damage spells with additional DoT components should in addition give 1 stack per DoT tick. 
DoTs should give 1 stack on application and 1 stack for every tick.
HoTs should give 1 stack on application and 1 stack for every tick.
Aoes should give 1 stack for every target hit.
Bleeds should not give any stacks.
Channeled spells should give 1 stack for every tick/hit.
Some random spells should also give 1 stack but it's case by case basis.

_Here's a list of things I noted but the above still apply if I missed any._
**Druid -**
Direct damage spells should give their stacks.
DoTs should be giving 1 stack on application.
HoTs Should be giving 1 stack on application.
Hurricane should give 1 stack for every hit.
Bleeds are giving 1 stack for ticks (not correct).
Starfall should give a stack for every hit. 

**Mage -**
Direct damage spells should give their stacks.
Arcane Explosion should give 1 stack for every hit.
Arcane missile should give 1 stack for every channeled hit/tick.
Slow fall should give 1 stack.
Flamestrike should give 1 stack for every hit of the initial hit.
Blizzard should give a stack for every hit. 
Cone of Cold should give 1 stack for every hit. 
Frost Nova should give 1 stack for every hit.
Blast Wave should give 1 stack for every hit.
Dragon's Breath should give 1 stack for every hit.

**Priest -**
Direct Damage spells should give give their stacks.
Levitate should give 1 stack.
Power Word: Shield should give 1 stack.
Holy Nova should give 1 stack for every damage hit too.
Devouring Plague should give stacks according to the above rules (Currently gives none).
Shadow Word: Death should give 1 stack for dealing damage, but damage on self shouldn't give stacks.

**Warlock -**
Life Tap should give 1 stack.
Seed of Corruption should give 1 stack for every hit.
Hellfire should give should give 1 stack for every hit, but damage on self shouldn't give stacks.
Rain of Fire should give 1 stack for every hit.
Shadowflame should give 1 stack for every hit.
Fel Armor should not give any stacks.

**Shaman -**
Healing Stream Totem should give give 1 stack for every heal.

**Revision**: 1125

**Comment by Emtec** [comment]
Fixed in 1134

**Comment by NatsumeLily** [comment]
Seems to be bugged still. Some spells are giving 2 stacks now. Healing Stream Totem should give stacks. 
Buffs are giving stacks when they shouldn't (spells like mark of the wild, blessing of kings, mage armour buffs).
Dispells are giving stacks when they shouldn't.
