### ISSUE TITLE
Corpse Despawn

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#354]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Some NPC corpses despawn instantly after looting, some don't.

Which one is intended, so I can report the ones that are wrong? https://youtu.be/CB6Ma1zanf0

**Comment by FX-SF** [comment]
There appears to be at least 2 specific types of mobs that do this behavior, while all others around Westfall do not:
1) Young Fleshripper
2) Rusty Harvest Golem

**Comment by Cold-Martijn** [comment]
This is a feature.
