### ISSUE TITLE
[Quest][Storm Peaks] When All Else Fails

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Wotlk-Beta#356]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quests puts you on a rocket to fly to the next questing hub.
**Current behaviour**:
You can control the rocket and can't dismount when you get to the destination.
No dismount or dismiss buttons
![image](https://user-images.githubusercontent.com/7255825/167284934-1962320d-ee98-4773-8ffb-3e3d082c44bd.png)

**Expected behaviour**: 
I think the rocket should fly by itself like in the video.
https://www.youtube.com/watch?v=EmW_72zioB8&ab_channel=GitGudGuides
**Revision**:

**Comment by FX-SF** [comment]
Could not dismiss it as pet
Could not dismount as if "WotLK vehicle concept" (aka riding red, green, and yellow dragons in oculus)
Could not interact with npcs
Could not turn in quest
Was able to abandon quest, but could not dismount.
Was able to log out and log in unmounted

This is an 20s example of being unable to turn in the quest, or dismount
https://user-images.githubusercontent.com/105084838/167313082-c6a78d46-4ca2-4373-8951-a6081e2fa692.mp4

This is a 20s example of being "stuck" and unable to interact with npc's or dismount UPON abandoning the quest:
https://user-images.githubusercontent.com/105084838/167313182-f7bf921d-45a2-45f5-a4fa-311cd87191ab.mp4

**Comment by EtheriousNW** [comment]
Fixed
