### ISSUE TITLE
[Storm Peaks] Snowdrift Plains

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Wotlk-Beta#357]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In the Snowdrift Plains there are two 'factions' of npcs.
**Current behaviour**:
They don't fight eachother.
![image](https://user-images.githubusercontent.com/7255825/167293996-273fa78f-ce44-4e40-b73f-b97c2f184b4b.png)

**Expected behaviour**: 
They should fight
https://www.youtube.com/watch?v=vO6lNzU0NIU&ab_channel=WorldOfWarcraftGuidesAndGameplay
**Revision**:

**Comment by FX-SF** [comment]
The Earthen Defender will NOT engage the Stormforged Raider, and vise versa.
The Earthen Defender will NOT engage the Stormforged Reaver, and vise versa.
The Dolomite Giant    will NOT engage the Stormforged Raider (even brought together), unable to tell if vise versa.
The Dolomite Giant    WILL       engage the Stormforged Reaver, seemingly the one who initiates combat every time.

https://user-images.githubusercontent.com/105084838/167315702-4734c954-a191-4973-ab96-d28fd0e6c31d.mp4

**Comment by EtheriousNW** [comment]
They fight eachother now, but spawns could use some work.
