### ISSUE TITLE
[Quest][Storm Peaks] The Iron Colossus

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Wotlk-Beta#358]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
The iron colossus mob resets when the worm submerges to dodge the slam
**Expected behaviour**: 
He shouldnt evade/reset when you submerge

Cant confirm the video is from original wotlk
also his damage feels a bit high
https://www.youtube.com/watch?v=wVm0zGJcW4M&ab_channel=peycha
**Revision**:

**Comment by FX-SF** [comment]
#776

**Comment by Cold-Martijn** [comment]
rev 1381
