### ISSUE TITLE
[Spell][Shaman] Sentry totem

### ISSUE THREAD

**Issue by Minnona** [Stormforge-gg/Bugtracker-Wotlk-Beta#362]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Sentry totem is bugged. Sometimes, upon calling it and dismissing with Totemic Recall, the shaman freezes in place and won't move until relogged. Additionally, Sentry Totem right clicking doesn't change shaman's PoV to it and vice versa. The buff is getting removed instead.

**Current behaviour**: ^

**Expected behaviour**: Upon casting the totem, shaman's PoV should change to it. The shaman should be able to jump and do some other stuff (jumping, buffing, healing self and others and etc) without being able to move. Right clicking the buff should rotate PoV between totem and shaman.

**Revision**: 1125

**Comment by Nuy** [comment]
Confirmed.

**Comment by Vishiswaz** [comment]
I also managed to crash the server by using a GM command to summon them elsewhere in an attempt to break the freeze.

**Comment by Emtec** [comment]
Fixed in rev 1133
