### ISSUE TITLE
[Trinket] Fury of the Five Flights

### ISSUE THREAD

**Issue by ScottieDOESknow** [Stormforge-gg/Bugtracker-Wotlk-Beta#367]
**Description**: 
Currently this trinket can build stacks without doing damage.
*(only tested with Divine Storm)*

**Current behaviour**: 
Trinket can build stacks without doing melee/ranged damage.

[Video of trinket issue](https://www.youtube.com/watch?v=0sG1BfonwIU)

**Expected behaviour**: 
Trinket should only build stacks via melee/ranged damage.

**Revision**: 
1125

**Comment by Nuy** [comment]
Currently most of proccing trinkets seem to be bugged and proc from anything even if they should proc only from damage/healing.

**Comment by ScottieDOESknow** [comment]
> Currently most of procing trinkets seem to be bugged and proc from anything even if they should proc only from damage/healing.

The only other proc trinket listed with ticket on this github is Illustration of the Dragon Soul.

**Comment by ScottieDOESknow** [comment]
> Currently most of procing trinkets seem to be bugged and proc from anything even if they should proc only from damage/healing.

The only other proc trinkets listed with ticket on this github is Illustration of the Dragon Soul and Dying Curse.

**Comment by Nuy** [comment]
> > Currently most of procing trinkets seem to be bugged and proc from anything even if they should proc only from damage/healing.
> 
> The only other proc trinkets listed with ticket on this github is Illustration of the Dragon Soul and Dying Curse.

I saw some emblem trinket proc from changing an area or mouting up but I don't remember which one was itt.

**Comment by ScottieDOESknow** [comment]
> I saw some emblem trinket proc from changing an area or mounting up but I don't remember which one was it.

Some of the *spell based* proc trinkets would proc off anything like zone change, mounting up, buff spells, crafting spells, etc BUT this trinket does not have that issue. It only has the issue described in original post.

**Comment by Wolffenstein** [comment]
Fixed in rev 1152.
