### ISSUE TITLE
[NPC] Vyragosa

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#37]
https://www.wowhead.com/npc=32630/vyragosa

**Description**: 

**Current behaviour**: NPC flies very slowly, too slowly and also does not aggro
![Безымянный1](https://user-images.githubusercontent.com/40593874/162480330-930b02ed-6e72-41ba-a257-14484e1eba20.png)
![Безымянный](https://user-images.githubusercontent.com/40593874/162480339-80a7bd84-be44-41a5-acf1-4a5c6d54ac33.png)

**Expected behaviour**:  must fly faster and aggro within a certain radius

**Revision**:

**Comment by EtheriousNW** [comment]
Fixed and live on beta
