### ISSUE TITLE
[Quest][The Storm Peaks] Sniffing Out the Perpetrator (lacks raid emote)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#370]
**Description**: 
During this quest, you are tasked with riding a Frosthound from an irrelevant starting spot to the entrance of Frosthowl Cavern. Upon reaching the entrance, you will dismount and must then slay Tracker Thulin.

**Current behaviour**:
Upon reaching the entrance of Frosthowl Cavern on your Frosthound, player is dismounted and receives partial credit. No raid emote occurs. 
https://user-images.githubusercontent.com/105084838/167342475-9c095dbd-20e1-4d6a-a82f-bdcfb232b136.mp4

**Expected behaviour**:
 In addition to receiving partial credit, there should be a raid emote: "The Frosthound  has located the thief's hiding place. Confront him!"
https://youtu.be/u_KLkp9fCLo?t=160

**Revision**: 
1125

Additional notes about the quest:
1) You can completely afk for the entire "vehicle" section and survive with 50% health (see video from current behavior). Was impossible to fail, but still fun and seems blizzlike.
2) At a specific spot during the "vehicle" section, the Frostwolf will do a sharp 180, head back for a second, do another sharp 180, and continue the path. It is jarring and consistent but not gamebreaking/abusable.

**Comment by Emtec** [comment]
Fixed in 1138
