### ISSUE TITLE
[Npc][Brann's Communicator] Tracker Thulin (Summon infinite Brann's to fight for you)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#371]
**Description**:
 Brann's Communicator is an item obtained from Tracker Thulin in The Storm Peaks. When used, it will summon Brann, a level 80 friendly elite that is essential to some quests in zone.

**Current behaviour**:
 1) If you use Brann's Communicator in a general manner, he will appear and offer you a quest. He will stand still.
2) However, if you bring combat near Brann, he will enter combat with the mob. 
3) After combat is finished, Brann will being to follow you, attacking mobs.
4) If you keep using Brann's Communicator, you can summon multiple Branns.
5) Brann SEEMS to only despawn only after 1-2 minutes have passed with no combat. If you keep entering combat, they do not despawn.

https://user-images.githubusercontent.com/105084838/167344911-fceb7b34-8883-48b9-b689-5a929076021f.mp4

**Expected behaviour**: 
NOT THAT!

**Revision**: 
1125

**Comment by Emtec** [comment]
Fixed in 1132
