### ISSUE TITLE
[NPC] Captive Proto-Drake (Consistent 30 degree ascending incline from intended direction)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#372]
**Description**: 
The Captive Proto-Drake is a friendly mob that you can mount and control during the quest "Cold Hearted".

**Current behaviour**: 
Upon mounting a Captive Proto-Drake and pressing spacebar to free some other slow speed issue, the Drake proceeds to ascend at a 30 degree angle above the direction you intend to go. (for example, if you were to aim directly down at a specific point, you will land on the ground a distance away from the point you were aiming for)

**Expected behaviour**: 
The Captive Proto-Drake should fly directly in a straight line just like any other controllable mount.

**Revision**: 
1125

Regular mount, notice it flew in the direction it was pointed
https://user-images.githubusercontent.com/105084838/167328777-2af748a1-577a-4759-87ee-0ba56cbb5402.mp4

Captive Proto-Drake mount, notice the change in angle from the direction it was pointed.
https://user-images.githubusercontent.com/105084838/167328799-171d2c90-5903-4895-ac22-7a7e2f186024.mp4

**Comment by Wolffenstein** [comment]
It's a vehicle not a mount

**Comment by FX-SF** [comment]
who cares if its a vehicle or a mount! Did you read the part where the protodrake doesnt fly straight at all?
