### ISSUE TITLE
[Spell] Oculus: Amber Drake - Damage increase

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#375]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Responding to @Wolffenstein (Report #349) about the 100% increased damage component stacking. 

**Current behaviour**: Currently it's stacking.

**Expected behaviour**: It shouldn't stack.

https://www.wowhead.com/spell=49592/temporal-rift#comments:id=467828:reply=74455

https://www.wowhead.com/npc=27656/ley-guardian-eregos#comments:id=468482
![image](https://user-images.githubusercontent.com/15247730/167483063-8c7c5f97-0b58-4a44-8a12-99f52d9652bc.png)

Then the reply to that post is someone correctly their old post, and confirming the damage component no longer stacks. 

https://youtu.be/pncdlQAFnwU?t=313 You see multiple cases where there are two channels or one channel, but the damage being done is roughly the same even if there are 2 active. And the damage differences there are because of the damage range the spell has.

Edit: I found some more but it's from patch 4.0.3.
https://www.wowhead.com/the-oculus#comments:id=1357375
![image](https://user-images.githubusercontent.com/15247730/167486234-a2be9624-135b-4c55-a093-7fdaee54c1e0.png)

**Comment by therealCrysis** [comment]
It has been fixed, according to Wolf.

**Comment by NatsumeLily** [comment]
@therealCrysis This was not fixed. Please reopen it
