### ISSUE TITLE
[Quest][The Storm Peaks] Norgannon's Shell (Roleplay Spell Missing)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#377]
**Description**:  During the quest Norgannon's Shell in The Storm Peaks, you summon a mob named Archivist Mechaton. He will perform some RP, and you then must slay Archivist Mechaton. 

**Current behaviour**:  During the RP event, Archivist Mechaton speaks 7 lines of dialog. He casts no spell during this RP event.
After the RP event, he will become targetable. He does not attack unless the player moves.

**Expected behaviour**: During the RP event, Archivist Mechaton should cast a spell between the 4th and 5th line of dialog: https://www.wowhead.com/spell=55224/archivists-scan.
After the RP event, he should attack the player on his own.

**Revision**: 
1125

video evidence of spell: https://youtu.be/VTsR1rTgkdU?t=27 
additional video evidence: https://www.youtube.com/watch?v=VTsR1rTgkdU&ab_channel=Flea420

**Comment by EtheriousNW** [comment]
Fixed
