### ISSUE TITLE
[Quest][The Storm Peaks] Norgannon's Shell (Multiple Bugs with quest item)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#378]
**Description**: During the quest Norgannon's Shell in The Storm Peaks, you are given a quest item named Charged Disk

**Current behaviour**:
1) This item has a 10s cd.
2) Each time it is used, a new version of Archivist Mechaton appear and begins RP.
3) If used rapidly, you can have multiple RP events occur at the same time:
https://user-images.githubusercontent.com/105084838/167496493-ae7e10ad-7578-4261-a0f4-549704492290.mp4
4) You can use this item very far away:
https://user-images.githubusercontent.com/105084838/167496763-2e462c4f-4ef6-4c54-9692-db825b86c97a.mp4
5) No matter where you are in WoW, if you use this item, the Archivist Mechaton RP event will occur in it's intended location (see point 4 above)

**Expected behaviour**: 
I do not know :/

**Revision**: 1125

**Comment by EtheriousNW** [comment]
Fixed
