### ISSUE TITLE
[NPC] Garrosh Hellscream

### ISSUE THREAD

**Issue by Abovexx** [Stormforge-gg/Bugtracker-Wotlk-Beta#38]
https://www.wowhead.com/npc=25237/garrosh-hellscream

**Description**: NPC missing in Borean tundra/Warsong Hold.

**Current behaviour**: NPC missing.

**Expected behaviour**:  Just below from where you received the quest. Hes standing in the middle of the circle.

**Revision**:

**Comment by Cold-Martijn** [comment]
Fixed, will be uploaded somewhere in upcoming time.
