### ISSUE TITLE
[NPC] Utgarde Pinnacle: Svala Sorrowgrave 

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#382]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You should be able to attack her while she's in the air, during ritual.
https://www.wowhead.com/npc=26668/svala-sorrowgrave#comments:id=634550
https://youtu.be/n3SAL8O9Uac?t=120

**Comment by FX-SF** [comment]
revision 1138

**Comment by Wolffenstein** [comment]
Fixed in rev 1143.
