### ISSUE TITLE
[NPC] Oculus: Mage-Lord Urom

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#384]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Time bomb does not work properly sometimes. https://youtu.be/K3FK0tSY3Xg 

(ignore the arcane explosion death in this, that's not the important part)

I think the "explosion" part of Time Bomb is hitting the target rather than nearby allies.

**Comment by FX-SF** [comment]
revision 1138
