### ISSUE TITLE
[Zone][Oculus] Druids on drakes

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#385]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Druids can currently mount on the drakes while in forms. I don't think they should be able to, it should force them out of form.

**Comment by FX-SF** [comment]
![image](https://user-images.githubusercontent.com/105084838/167525845-8135c665-30bd-41af-b54f-7184f92017e6.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1142.
