### ISSUE TITLE
[NPC] Gundrak: Crafty Snake

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#387]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is a single Crafty Snake critter that seems to spawn during the Slad'ran fight that doesn't de-spawn after a wipe.

**Comment by Wolffenstein** [comment]
He's not a part of the fight

**Comment by Vishiswaz** [comment]
I killed all the snakes in the room, start the fight, wipe or reset, and it's back.

No, it shouldn't be part of the fight. But it is for some reason.
