### ISSUE TITLE
[NPC] Portal Guardian

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#390]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Doesn't appear in front of the portal like he's supposed to while he's channeling, after spawning but not aggroing.
![WoWScrnShot_050922_225216](https://user-images.githubusercontent.com/78314117/167536830-13a082fe-46a2-41b1-af9f-ebc4a638d082.jpg)

**Comment by FX-SF** [comment]
revision 1138

**Comment by Wolffenstein** [comment]
Intended, they move randomly, not in front.
