### ISSUE TITLE
[Spell][Paladin] Hand of Reckoning

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#392]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The amount of damage Hand of Reckoning does is off by 1.

100 AP should have Hand of Reckoning do 50 damage. It does 51.
2000 AP should have Hand of Reckoning do 1000 damage. It does 1001.

**Comment by Wolffenstein** [comment]
"If the target is tauntable and not currently targeting you, causes ${1+0.5*$AP} Holy damage."
Not sure if it's a bug

**Comment by haephaistoss** [comment]
lots of spells use the same method, 1 dmg is sometimes added

**Comment by therealCrysis** [comment]
Closing.
