### ISSUE TITLE
[Global] Summon Stones

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#396]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
**Issue 1:** Summons using a stone have a cast time, then channel effect. It should be just the channeling effect as of 3.1. Since we're using spells from 3.3.5a, this should be updated probably? At the very least, code it to change in 3.1 onwards.

**Issue 2:** You can move around while doing this cast effect without interrupting the summon

**Issue 3:** You can move around while doing the channel effect without interrupting the summon

**Issue 4:** When someone helps the summon, their contribution is instantaneous. It should be a couple seconds of them channeling (with no channel bar) before it registers that a second person has contributed.

**Issue 5:** There is no visual for someone contributing. There should be an animation.

**Issue 6:** Once the contribution is made, there is a cast bar that appears on the screen for a couple seconds and THEN once it finishes the second player receives a summon. The summon should go through as soon as the contribution is finished being made by the second player (which is currently missing and instantaneous, as detailed in Issue 4)

**Issue 7:** The target of the summon should be decided the moment the summoner right clicks the stone, NOT whoever they are targeting at the end of their cast.

Regular summon stones have all 7 issues. Warlock summon stones have all issues except 2 and 3.

To be clear, here's what should happen for ALL summoning stones:
1. Player A targets the summoning target and right-clicks the stone.
2. Instantly, Player A starts channeling the summon, and whoever they are targeting is the target of this summon.
3. Player A can cancel the summon by moving, casting, jumping, hitting Escape, etc. All things that cancel normal channeled spells.
4. Player B right clicks the portal.
5. Without a cast time, they start a channeling animation with glowing hands, no cast bar visible.
6. If Player B moves before this is completed, their contribution to the summon is canceled and Player A's channeling continues as if nothing happened.
7. If Player B stays for a few seconds, the summon completes, both players instantly stop channeling and the target of the summon receives a summon prompt.

**Comment by FX-SF** [comment]
revision 1138

**Comment by Vishiswaz** [comment]
@Wolffenstein I saw you list summon stone updates on the WotLK tracker and pushed updates today to the PTR (currently in revision 1148)

Here's what's still bugged (I was only able to test regular summon stones):

Issues 1, 2, and 3 are still completely present.

Issue 4, 5, and 6 is resolved.

Issue 7 is only partially resolved (details below).

Here are some new issues:

Issue 8: As an addendum to 7 with the new revision, now if I select one player when I start my summon and have another player selected when the summon completes, no one receives a summon. Again, the target of the summon should be decided at the very beginning when the stone is right-clicked, and it does not matter who is targeting who after that moment.

To be clear, here is how it should work properly:
1. Player A selects summon target Player X.
2. Player A right clicks the stone. The summon target is now locked in as Player X.
3. Player A can now target whoever else they want. Themselves. Other party or raid members. People not in the group. NPCs. Or no one at all. It doesn't matter, Player X has already been designated as the summon target.
4. When the summon is completed by Player B contributing to the summon, Player X receives a summon.

This is functionally useful, so that when summoning a large raid somewhere, I as the summon initiator can select Player 1, right click the stone, then select Player 2 while I wait for someone to assist my first summon and waiting for it to go through. Then the moment it's done, I can right click the stone, then find the next person who needs a summon, etc. It makes things a lot speedier.

It's also useful for people who target other things while they're mid summon or accidentally un-target their summon target.

Issue 9: The summoning portal from right-clicking a summon stone should be on top of the player initiating the summon. I understand this may have gotten confused with my other ticket about Ritual of Summoning. Ritual of Summoning should create an offset portal _when casting the warlock spell that creates a summoning stone_. But when right-clicking a summoning stone, Warlock or normal, the "portal" that appears should not be offset. It should be on top of the player.
