### ISSUE TITLE
[Quest] Death's Challenge

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#4]
**Description**: DK starting zone Death's Challenge - talking to one Death Knight Initiate then challenging another challenges the wrong one. 

**Current behaviour**: I talk to Death Knight Initiate A, close chat window, talk to Death Knight Initiate B and challenge him, but the challenge is created with Death Knight Initiate A. 

**Expected behaviour**: Should challenge the Death Knight Initiate I am currently targeting/talking to. 

**Revision**: 1034

**Comment by Wolffenstein** [comment]
This is blizzlike, Blizzard uses a spell targetting nearest death knight, not a specific one.
