### ISSUE TITLE
[Global] Mob Reset

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#401]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If the devs know I'm wrong about this, please disregard. I'm not 100% sure what's blizzlike here, but I think this may be incorrect the way it is currently. Might need to be researched on Classic and/or Retail. I have no idea where I'd find a video for this, unfortunately.

https://youtu.be/bACaTsxpT0Q

2 players are engaged with mob A.

Player 1 has aggro, Player 2 does not.

Player 1 kites mob A outside of its leash. Player 1 leaves the combat table for mob A. This is definitely correct.

However, currently, mob A will reset entirely, also dropping Player 2 from combat.

This can be abused by a tank taunting mobs that someone is trying to kill/farm and kiting them away until they reset.

What I *think* should happen, and again I could be wrong, is that when Player 1 kites mob A away past their leash, Player 1 leaves combat and is removed from mob A's combat/threat/target list or whatever it's called. Player 2, however, remains in combat and the mob returns to them.

Again, if you tell me that it's not supposed to be that way and you're sure, I trust you're correct. Though it'd still be rife for abuse, blizzlike is blizzlike.

**Comment by Wolffenstein** [comment]
Blizzlike
