### ISSUE TITLE
[NPC][Naxxramas] Rotting Maggot, Diseased Maggot, & Eye Stalk

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#402]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Currently, the Diseased Maggots and Rotten Maggots appear to have a leash to them. They are regular raid mobs, no? I don't think they should have a leash to them.

The eye stalks, on the other hand, which are stationary, do not have a leash. They will continue to target you and keep you in combat as you exit the room and head towards Loatheb. I'm not sure if this is blizzlike or not. It's possible that these are the mobs that are supposed to have a leash, since they are stationary. But if they're not supposed to have a leash, then they're fine.

Might need retail testing.

Also, I noticed in a video from Classic that the Maggots were extremely slow moving. A lot slower than they are here. But that could just be a Vanilla Naxx thing, not WotLK.

**Comment by Wolffenstein** [comment]
Fixed in rev 1149.
