### ISSUE TITLE
[NPC][Naxxramas] Grobbulus

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#405]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Grobbulus encounter can be started from the first room of the plague quarter, before Patchwerk is killed.

Hhe will evade out, but if a player attacks Grobbulus in the first room, the raid group will get stuck in combat and the encounter technically starts, and Grobbulus will start dropping slime and doing his other mechanics a few seconds later.

https://youtu.be/zAWd6xpVIGQ

He should probably not be attackable before Patchwerk is killed. Maybe targetable but not attackable.

**Comment by Wolffenstein** [comment]
Fixed in rev 1149.
