### ISSUE TITLE
[NPC][Naxxramas] Crypt Guard

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#409]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When the tank pulls Anub'Rekhan, the Crypt Guards immediately go to other members of the group.

https://youtu.be/vx3O76JBGAk

I've seen servers where this was a global bug. Hopefully it's just this fight and can be fixed. If I find more instances of it, I'll link back to this in a new bug report.

Edit: I think this might be because this is how Crypt Guards that spawn _during_ the fight are supposed to ignore the tank upon spawning, but not the two that are there in the beginning on 25 man.

**Comment by Wolffenstein** [comment]
Fixed in rev 1149.
