### ISSUE TITLE
[Frostbolt][Mage]

### ISSUE THREAD

**Issue by Abovexx** [Stormforge-gg/Bugtracker-Wotlk-Beta#41]
**Description**:  Does not apply 60% slow effect.

**Current behaviour**: Does not apply 60% slow effect. Does apply 40% slow effect.

**Expected behaviour**:  "Slowing movement speed by 60%"

**Revision**:

**Comment by Gn0m** [comment]
https://wotlkdb.com/?talent#oZZV00h 
![image](https://user-images.githubusercontent.com/40593874/162495218-910f8c5f-f391-462a-b469-b07a331a30f9.png)
checked with another priest, the slowdown works correctly without talent and with talent, the only mistake is the display, the debuff itself is written incorrectly, i.e. 30-40-50 without talent and 40-50-60 with talent, but it should be 40 -50-60 without talent and 50-60-70 with talent

**Comment by haephaistoss** [comment]
client side, can't change it
