### ISSUE TITLE
[NPC][Naxxramas] Crypt Guard & Corpse Scarab

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#410]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These do not despawn when the fight ends. They should.

**Comment by Wolffenstein** [comment]
During anub fight? Everything despawns for me, cant reproduce.

**Comment by Vishiswaz** [comment]
I'll see if I can reproduce it later tonight
