### ISSUE TITLE
[NPC][Hellfire Peninsula] Doom Lord Kazzak

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#411]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
His mana drain ability, instead of draining 5% of maximum mana per tick, is draining 5% of your current available mana at the time the debuff is applied.

This makes it pretty trivial and possible to solo at 80 pretty easily. He drops a hefty amount of gold, so people on WotLK servers tend to farm him if they catch him while he's up.

**Comment by Wolffenstein** [comment]
Fixed in rev 1149.
