### ISSUE TITLE
[Zone][Howling Fjord] Wormskull Village

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#414]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It appears it's possible to be in the wrong phase when exiting Utgarde Keep, causing the Lich King outside to kill you.

Additionally, in the correct phase, that Lich King should not aggro or attack players. He is there for an RP event only, no?

Someone should test that whole quest line after this report is fixed.

**Comment by mythyrylfalcon** [comment]
I experienced the bug. Exited Utgarde Keep (Heroic) and exited the hall to fly to Utgarde Pinnacle. Appears to be "https://www.wowhead.com/npc=24248/the-lich-king" which seems to be a part of "https://wowpedia.fandom.com/wiki/The_Echo_of_Ymiron" quest.

**Comment by FX-SF** [comment]
revision 1148

**Comment by Cold-Martijn** [comment]
I made a fix to this version of the Lich King quite recently, but it is not uploaded yet. The fix miiiigght also fix this, but probably doesn't.
The quest and roleplay with the LK will work fine after that fix :)

**Comment by Cold-Martijn** [comment]
Can not reproduce this. Please try to catch this on video, and show me your questlog while doing so please.

**Comment by therealCrysis** [comment]
It seems fine in rev 1184
