### ISSUE TITLE
[NPC] [Gundrak] Drakkari Rhino - Charge

### ISSUE THREAD

**Issue by mythyrylfalcon** [Stormforge-gg/Bugtracker-Wotlk-Beta#418]
**Description**: Drakkari Rhino "https://www.wowhead.com/npc=29931/drakkari-rhino" should charge when initially engaged in combat.

**Current behaviour**: Walks into combat

**Expected behaviour**: Should immediately use charge "https://www.wowhead.com/spell=55530/charge" when engaged.

**Revision**:

**Comment by FX-SF** [comment]
Revision 1148

**Comment by therealCrysis** [comment]
Confirmed in rev 1184

**Comment by Cold-Martijn** [comment]
fixed in rev 1339
