### ISSUE TITLE
[Quest] Razormaw

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#422]
**Description**: 
The Quest Razormaw doesn't work
**Current behaviour**:
Once you used the item [Bundle of Dragon Bones](https://tbc.wowhead.com/item=24221/bundle-of-dragon-bones) Razormaw spawn but doesn't move
![image](https://user-images.githubusercontent.com/40879039/167968853-34056da7-861a-4c40-b3b1-24a9f4a87e3c.png)

**Expected behaviour**: 
He is supposed to spawn and come near the fire to be killed

**Comment by FX-SF** [comment]
revision 1148

**Comment by Cold-Martijn** [comment]
Fixed with next bunch of uploads.
