### ISSUE TITLE
[Zone] The Oculus - Falling into the "void" / off the map

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#425]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: Falling off in Oculus causes you to be teleported outside the instance portal, you are then killed. You then have to run to the portal as a ghost and resurrect outside the portal, and enter the portal to get back inside the instance. 

**Expected behaviour**:  Falling off in Oculus should be treated the same way as falling into the void or off Outlands. But in this case your corpse should be inside the instance. So you only need to enter the instance portal after running back as a ghost. 

**Revision**:

**Comment by FX-SF** [comment]
revision 1148

**Comment by therealCrysis** [comment]
Confirmed in rev 1184

**Comment by Wolffenstein** [comment]
Fixed in rev 1217.
