### ISSUE TITLE
[NPC] [Old Kingdom] Herald Volazj Insanity phase does not occur

### ISSUE THREAD

**Issue by mythyrylfalcon** [Stormforge-gg/Bugtracker-Wotlk-Beta#427]
**Description**: [Insanity](https://www.wowhead.com/spell=188541/insanity) – Herald Volazj drives all players insane, causing them to hallucinate Twisted Visages of each of their allies. Players are trapped alone in their insanity until they kill all of their Twisted Visages.

**Current behaviour**: Spell is cast, nothing happens.

**Expected behaviour**: See above

**Revision**:

**Comment by NatsumeLily** [comment]
Test it with another player first. Tested it with a friend and it seemed to be working fine from what we saw.

**Comment by FX-SF** [comment]
revision 1148
