### ISSUE TITLE
[NPC] Horde Siege Tank - No Combat AI Against Alliance

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#433]
**Description**: 
Horde Siege Tank is a mechanical mob located on the Coast of Echoes, directly west of Warsong Hold.

**Current behaviour**:
 Upon attacking as an Alliance player, the Siege Tank does not exhibit combat AI.
 Siege Tank will agro if another mob near it is agroed. 
Siege Tank will not agro on its own.

**Expected behaviour**: 
Upon attacking as an Alliance player, the Siege Tank does exhibit combat AI, potentially using vehicle combat abilities that horde can use. 

**Revision**: 1148

https://user-images.githubusercontent.com/105084838/168011865-f7940e37-2812-4063-b9b6-0f0efd33affc.mp4

2nd comment speaks on WotLK-era Siege Tank behavior.
![image](https://user-images.githubusercontent.com/105084838/168012061-c132ccf6-1a66-43d9-b76b-7d7658e5d23b.png)

**Comment by Cold-Martijn** [comment]
Oh god awfull, why link WoWhead comments from Wowfreakz server? :O

**Comment by FX-SF** [comment]
![image](https://user-images.githubusercontent.com/105084838/168024892-5e4466f8-0c52-497d-a370-55f49f8236f1.png)

**Comment by FX-SF** [comment]
I don't see the issue, unless your being comical which in that case lol:D

**Comment by Cold-Martijn** [comment]
I know they are actually from WoWhead, was more that it seems like a weird way to get to WoWhead comments in the first place :D there is no problem in it :)
