### ISSUE TITLE
[Spell] Vanish/Shadowmeld 

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#436]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Vanishing/Shadowmelding projectiles/spells mid-air doesn't work correctly. You avoid the damage and their effect but your Vanish/Shadowmeld gets interrupted and you're taken out of stealth. 

**Current behaviour**: Vanish/Shadowmeld gets interrupted by projectiles/spells that were mid-air at the time of its use.

**Expected behaviour**:  Your Vanish/Shadowmeld shouldn't get interrupted by projectiles/spells that are mid-air.

https://youtu.be/0wnC_3AkMfU?t=90 - You can see the Heroic Throw NOT interrupting Vanish despite it being used when Heroic Throw was already in flight. 
https://youtu.be/V0UvkL-mZq8?t=820 - Vanished Death Coil that was mid-flight and still in Vanish so rogue could use Cheap Shot. It worked pretty much the same in WotLK.

**Revision**: 1148

**Comment by Cold-Martijn** [comment]
im unsure if this should also work like that for shadowmeld? do you have any vids like for the vanish?

**Comment by Nuy** [comment]
> im unsure if this should also work like that for shadowmeld? do you have any vids like for the vanish?

We also tested Vanish and it was bugged the same way.

It's kind of common knowledge among WoW PvP community that Shadowmeld can let avoid abilities kind of like Vanish.

https://www.youtube.com/watch?v=BUMZ2JmvLlM
https://www.youtube.com/watch?v=I-V-zol2C2M - This is from Cata but it wasn't really changed there.

**Comment by haephaistoss** [comment]
Nelf hunter shmeld death coild midair warlock can /forfeit, as it is gg from there

**Comment by Wolffenstein** [comment]
Fixed in rev 1172.
