### ISSUE TITLE
[NPC] Manawraith low spawnrate and missing Arcane Residue

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#437]
**Description**: 
In Eversong Woods, i found only 4 [Manawraith](https://tbc.wowhead.com/npc=15648/manawraith) spawns near the quests that asking you to kill 5 of them and they don't cast [Arcane residu](https://tbc.wowhead.com/spell=29109/arcane-residue)e upon death

**Revision**: 
rev 1148

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
