### ISSUE TITLE
[Quest][NPC] The dwarven Spy/Prospector Anvilward missing RP

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#438]
**Description**: 
[The Dwarven Spy](https://www.wowhead.com/quest=8483/the-dwarven-spy) quest is missing RP interaction

**Current behaviour**:
[Prospector Anvilward](https://tbc.wowhead.com/npc=15420/prospector-anvilward) just stand where the RP is supposed to end
![image](https://user-images.githubusercontent.com/40879039/168133123-f88e233b-76af-44ab-96d6-410d11d15739.png)

**Expected behaviour**: 
He is supposed to wait the player near [Ley-Keeper Caidanis](https://tbc.wowhead.com/npc=15405/ley-keeper-caidanis), you talk to him, follow him then he aggro you and you can kill him

Video of the quest with timestamp
https://youtu.be/4q91T67iSJA?t=56

**Revision**: 
1148

EDIT : after killing him, he seems to respawn at the right place and state (friendly)

**Comment by FX-SF** [comment]
I tested this out yesterday. If you wait for a long time (5 minutes 10 minutes idk) They do perform RP.

**Comment by FX-SF** [comment]
I was there yesterday doing this quest. The last thing i did was activate the dwarf and then i just ran away. You might be seeing an unfinished quest attempt from over 24 hours ago xDD. 

This may mean that the dwarf (in friendly npc state) will not spawn until the dwarf (in hostile npc state) is dead.

Will grab more info

**Comment by FX-SF** [comment]
Beta server exhibits expected behavior. 

Exception: Once Prospector Anvilward performs RP walk and turns hostile, he will never despawn if not attacked, and the friendly version of him never spawns.

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
