### ISSUE TITLE
[Quest][Icecrown] Not a Bug - Dark Messenger Summon-able Without Dark Matter

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#440]
**Description**: There is an object named Summoning Stone in Icecrown. It is used in the quest Not a Bug. In the quest, you are tasked with obtaining 5x Dark Matter, a quest item. You are then asked to summon a Dark Messenger at the Summoning Stone using 5x Dark Matter.

**Current behaviour**: You can summon Dark Messenger without 5x Dark Matter,.

**Expected behaviour**: You cannot summon Dark Messenger without 5x Dark Matter.

**Revision**:  1148

https://user-images.githubusercontent.com/105084838/168168190-42429b07-fd16-4ee6-bd2a-e8370acf3d6b.mp4

**Comment by EtheriousNW** [comment]
Fixed and live on beta
