### ISSUE TITLE
[NPC] Hira Snowdawn 

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#442]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: She is part of the Kirin Tor faction and giving faction rep discounts. She is also selling the tome of cold weather flying.

**Expected behaviour**: She shouldn't be part of the Kirin Tor faction (giving rep discount) until next expansion. She also shouldn't be selling the tome until patch 3.2.
 

**Revision**: 1165

**Comment by NatsumeLily** [comment]
> Is it patch 3.2 for the tome or 3.3? I thought it was 3.3...

Tome was added 3.2.

**Comment by Vishiswaz** [comment]
> > Is it patch 3.2 for the tome or 3.3? I thought it was 3.3...
> 
> Tome was added 3.2.

Can you provide screenshots or anything just to be sure

**Comment by NatsumeLily** [comment]
https://wowpedia.fandom.com/wiki/Tome_of_Cold_Weather_Flight
![image](https://user-images.githubusercontent.com/15247730/168378737-ef981242-daa0-4168-ad9f-a1697fc7e2d7.png)

![image](https://user-images.githubusercontent.com/15247730/168378849-72708b16-9af5-4792-8be4-164c0cba452b.png)

**Comment by Evolvee** [comment]
fixed in next rev
