### ISSUE TITLE
[Spell] Wotlk Tailoring special clothes

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#443]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: Ebonweave, Spellweave, Moonshroud don't have any CD to craft. Don't have any locational requirement. Don't give the buffs associated with crafting them.

**Expected behaviour**:  They should have a 4 day CD, each of them being separate from each other. 

Crafting the cloths should have locational requirements. All of them being in Dragonblight.
Ebonweave @ 37,32 (Obsidian Dragonshrine)
Spellweave @ 55,65 (Azure Dragonshrine)
Moonshroud @ 64,73 (Emerald Dragonshrine)

Crafting the cloth should give buffs. The buffs last 30mins, can stack with each other, and do not persist through death.
[Ebonweave](https://www.wowhead.com/?item=41593) -> [Residue of Darkness](https://www.wowhead.com/?spell=59676)
[Spellweave](https://www.wowhead.com/?item=41595) -> [Nexus Residue](https://www.wowhead.com/?spell=59675)
[Moonshroud](https://www.wowhead.com/?item=41594) -> [Moonshroud Residue](https://www.wowhead.com/?spell=59674)

All of the above is removed in patch 3.3.3

**Revision**: 1165

**Comment by Amun12** [comment]
It's same with Titansteel bar. Prior to patch 3.3.3, it should have 20 hours Cooldown. Right now it has no CD.
