### ISSUE TITLE
[Zone][Wintergrasp] Double NPCs

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#446]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://youtu.be/sKVHdT5Ae94

It looks like there are duplicate entries of most NPCs in Wintergrasp.

One version has a faction (Valiance Expedition for Alliance), the other doesn't. I don't know which is blizzlike. Though I believe if they are supposed to be factionless they should still appear Friendly (in green)

After Horde won, I checked, and they also have the same issue with most NPCs in the fortress.

**Comment by Wolffenstein** [comment]
Fixed in rev 1170.
