### ISSUE TITLE
[Zone][Wintergrasp] View Distance

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#447]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
View Distance for Wintergrasp needs to be turned way up for multiple reasons.

1. It looks REALLY BAD to have buildings not appear until you're really close to them. Maybe if these could have an extra large view distance that is specific to destructible buildings (and workshops), that would solve that.
2. When aiming at targets far away, for example using the turrets at the fortress and towers, you need to be able to see very far away.
3. But you also don't want to only give people large viewing distance when in a turret, because then people will use turrets only to see extra far away. So really the view distance from inside WG needs to be expanded to whatever the absolute maximum distance any of the turrets can shoot at. Maybe a bit more so you can aim at people as they get close to your shooting range.

Here's some screenshots of how bad it looks with the draw distance for buildings so low.
![WoWScrnShot_051222_200401](https://user-images.githubusercontent.com/78314117/168186305-b14f69af-554c-47b3-a9d7-25b1e818bf8d.jpg)
![WoWScrnShot_051222_200456](https://user-images.githubusercontent.com/78314117/168186313-522770eb-49a9-4369-b199-9ab40d7cbcfe.jpg)
![WoWScrnShot_051222_200511](https://user-images.githubusercontent.com/78314117/168186343-78b0b41e-8c60-4d86-a078-5219f6f66eff.jpg)
![WoWScrnShot_051222_201729](https://user-images.githubusercontent.com/78314117/168187453-028bd4c0-bb14-4e1a-860a-cd283979aab7.jpg)

**Comment by FX-SF** [comment]
revision 1165

**Comment by Vishiswaz** [comment]
Also, now that cannons have been added, it looks even sillier
![WoWScrnShot_051422_013811](https://user-images.githubusercontent.com/78314117/168412345-6359483b-2f9a-4350-82d2-1fb488ecb251.jpg)

**Comment by Vishiswaz** [comment]
![WoWScrnShot_051822_235010](https://user-images.githubusercontent.com/78314117/169200503-57a12c80-b374-4d13-a1d6-e6805bec22ae.jpg)
please for the love of god fix this before release lol
