### ISSUE TITLE
[Quest][The Storm Peaks] Mobile Databank

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#449]
**Description**: Mobile Databank is a summoned NPC from an item Creteus's Mobile Databank. It follows you during the quest Fate of the Titans. Occasionally, Mobile Databank will perform RP.

**Current behaviour**: After Mobile Databank performs RP, It will stay fixed in a specific location and does not despawn. Exception: You use Creteus's Mobile Databank again.

**Expected behaviour**: After Mobile Databank performs RP, Mobile Databank will resume following you.

**Revision**: 1165

You can see the behavior at 1:22 of this video. 
0:50 shows some missing polish as well
https://youtu.be/uxFLWbMnM6s?t=50

**Comment by Wolffenstein** [comment]
Fixed in rev 1197.
