### ISSUE TITLE
[NPC] Sartharion

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#45]
https://www.wowhead.com/npc=28860/sartharion

**Description**: 
![image](https://user-images.githubusercontent.com/40593874/162496641-379ac7c7-6cf9-41a3-b0cb-5c795b744398.png)
![image](https://user-images.githubusercontent.com/40593874/162496933-8d45f4e4-3e97-4dff-9bd4-54110b19733e.png)

**Current behaviour**: Boss goes out of bounds

**Expected behaviour**: The boss must not leave the site, otherwise the meaning of his mechanics with waves is lost, on the 1st screenshot you can see how the waves go. That is, the players go out of the area and skip 1 boss mechanic, so it is necessary to make sure that when leaving the area, the boss is evaded.

**Revision**:

**Comment by Gn0m** [comment]
Firemen: Players who are off the platform are killed very quickly by the Firemen's spell. If you jump into the lava and get out quickly, the Flames usually don't happen.

**Comment by Wolffenstein** [comment]
Wrong

**Comment by Gn0m** [comment]
what does wrong mean, i.e. do you think that taking the boss out of the zone where the battle should take place with him is this correct behavior?

**Comment by H4Xx0R-PC** [comment]
https://www.wowhead.com/spell=57557/pyrobuffet will kill you when you leave the bosses platform.

Sure you can pull the boss off his platform, but you will just die then

**Comment by Gn0m** [comment]
Thanks for the clarification, I checked, apparently it was in the saronite shield and therefore it was not noticed, I tested it without a shield, the boss uses the indicated ability.

**Comment by H4Xx0R-PC** [comment]
> Thanks for the clarification, I checked, apparently it was in the saronite shield and therefore it was not noticed, I tested it without a shield, the boss uses the indicated ability.

I figured as much because I saw 10 stacks of the debuff on you from the first screenshot :)
