### ISSUE TITLE
[Item] The RP-GG

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#450]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
~~This item should prevent people from casting their mount spell. Currently, it allows you to have your 1.5 sec cast to open your mount, you then hear your mount sound, but the mount fails to appear.~~

~~I BELIEVE blizzlike would be that when you mount up, the RP-GG is dropped on the ground? But I'm not sure. Might need a retail check.~~

~~Also, I think these are currently missing from the workshops other than the ones in the fortress.~~

Okay, it was because I was using mounts that I shouldn't have, the X-53 Touring Rocket and Invincible. This should get fixed for these, just in case.

But now there's a new problem. I used my normal Charger paladin mount and the RP-GGs did not drop at all. So I can just run away with them on my mount. That's not supposed to happen.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Vishiswaz** [comment]
Well, I can't find evidence of it. So it must've been a bug I encountered on another server that I thought was blizzlike. Closing for now.
