### ISSUE TITLE
[Zone][Wintergrasp] Siege Engine

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#451]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Players inside Siege Engines are unable to switch to empty seats. It causes a disconnect. Then, my character couldn't log on until I used a gm command on a different character to end the battle manually.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Vishiswaz** [comment]
This was "fixed" though now entering the turrets causes all nearby players to disconnect.
