### ISSUE TITLE
[Zone][Wintergrasp] Eye of the Storm Portal + Meeting Stone

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#453]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These items are currently overlapping
![WoWScrnShot_051222_202317](https://user-images.githubusercontent.com/78314117/168187900-6ac62c73-ce7e-4890-b5d1-5c018a1c1b96.jpg)
.

**Comment by FX-SF** [comment]
revision 1165
