### ISSUE TITLE
[Zone][Wintergrasp] Ghosts/Graveyards

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#454]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

~~Issue 1: I died during the battle and I have a ghost gryphon. I'm unsure if there should be a ghost gryphon when the battle isn't happening, but definitely not during the battle.~~

~~Issue 2: When I released, I should automatically have been put in the queue for the auto-rezzes that happen every 30 seconds. I was not. (I died as an alliance member at Broken Temple while we were defending, got ported to the Broken Temple graveyard)~~

Issue 3: Graveyards are missing an NPC that looks like a ghost player casting a resurrection spell every 30 seconds, only appears during the battle. There's currently a normal Spirit Healer, and I don't believe those are supposed to be there at all, at least during the battle.

Issue 4: If I choose to walk back to my corpse during the battle (not a common thing but some people do it sometimes), I cannot see my corpse while I'm in ghost form.

~~Issue 5: There's no immunity buff at graveyards. When you are in a graveyard that your faction controls, you're supposed to get a buff that gives you full immunity to all enemy attacks, spells, controls, mana drains, etc.~~

~~Issue 6: Upon being resurrected by the Spirit Guides, you should get a temporary buff like in battlegrounds that allows you to cast spells (such as buffs) for no mana.~~

~~Issue 7: When waiting in the queue to be rezzed, you can hit the Cancel button. That's working fine. However, you should be able to re-enter the rez queue by talking to the spirit guide again. This is not working.~~

Issue 8: The Spirit Guides offer to teleport you to your current graveyard location. I don't think they should. They should be able to teleport you to graveyards your faction controls OTHER THAN the one you are at.

Edit: The Dwarven Spirit Guide WAS available at the graveyard in the alliance base. However, so was the Spirit Healer. It should not be both.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Vishiswaz** [comment]
Update:

FIXED: Issues 1, 2, 5, 6, and 7

NOT FIXED: Issues 3, 4 and 8

Update on Issue 3: There are more spirit guides now: Good. Spirit Healers should not be present during the battle, I believe, only when there is no ongoing battle. That is currently still bugged.

NEW ISSUE 9: Leaving a graveyard removes you from the resurrection queue, which is correct, but returning to the graveyard puts you back in. This should not be an automatic thing, only should happen when you talk to the spirit guide there.

Revision 1225

**Comment by NatsumeLily** [comment]
Broken temple graveyard was missing the spirit guide npc.

**Comment by Vishiswaz** [comment]
> Broken temple graveyard was missing the spirit guide npc for Horde.

And alliance, confirmed

**Comment by Wolffenstein** [comment]
Fixed in rev 1289.
