### ISSUE TITLE
[Zone][Wintergrasp] Leave Wintergrasp

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#455]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Issue 1: Currently, when you try to leave Wintergrasp by right-clicking the pvp icon on the minimap and selecting "Leave Wintergrasp", you get the message "you have exited the battle for wintergrasp" but you do not get teleported out.

You are supposed to be removed from the WG raid group(s) and be teleported out. I'm not sure to where, different servers have done it differently. I've seen some where it uses people's hearthstone regardless of if it's on cooldown. I've seen some where it teleports them to the same place you get sent to in icecrown if you don't accept the wg queue. Research will be needed to find out what's blizzlike.

Issue 2: The same thing should happen when you leave the WG raid group you're assigned to. You should be teleported out, but not sure what's blizzlike.

**Comment by FX-SF** [comment]
revision 1165
