### ISSUE TITLE
[Zone][Wintergrasp] Tenacity

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#456]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Tenacity doesn't currently increase the amount of damage that vehicles do to buildings.

I'm not sure if it should. My feeling is that it should, otherwise it's nearly impossible to win a battle as an attacker when you're massively outnumbered. But I don't know.

**Comment by Vishiswaz** [comment]
And while you're in there fixing Tenacity, make sure there's a level restriction of 70 to count towards it.

![image](https://user-images.githubusercontent.com/78314117/168207291-2a96a381-a823-4416-9554-3b9fa956edcb.png)

**Comment by FX-SF** [comment]
revision 1165

**Comment by NatsumeLily** [comment]
![image](https://user-images.githubusercontent.com/15247730/168399816-abd765d6-d04c-4c89-817a-189d9a902d3f.png)

**Comment by Cold-Martijn** [comment]
vehicle SIEGE damage should not be increased
