### ISSUE TITLE
Arcane Mage Missile Barrage

### ISSUE THREAD

**Issue by kadu93** [Stormforge-gg/Bugtracker-Wotlk-Beta#46]
[//]: # ([Arcane][Mage] Missile Barrage)

**Description**:  doesn't work with haste

**Comment by Amun12** [comment]
It's not that it doesn't work with haste, the issue is that Missle Barrage proc doesn't reduce casting time of Arcane Missiles, which is a major bug.

**Comment by Wolffenstein** [comment]
Fixed
