### ISSUE TITLE
[Zone][Wintergrasp] Incorrect Guards

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#462]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![WoWScrnShot_051222_211036](https://user-images.githubusercontent.com/78314117/168191812-6178ccb5-9d26-4efa-bb69-347a94eeb4ac.jpg)
![WoWScrnShot_051222_211039](https://user-images.githubusercontent.com/78314117/168191813-b1216a27-f80f-4be3-a6dd-3d49a2fc9985.jpg)

I'm not sure exactly what the issue is here but I know it's wrong. Either:

1. There should be 1 Alliance and 1 Horde guard

OR

2. There should only be Alliance Guards because they correspond with Sunken Ring

Honestly I'm not even sure these are in the right place. And I'm not sure if the guards change based on who controls which bases, or if they are static regardless of that.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Vishiswaz** [comment]
Closing and moving to #504
