### ISSUE TITLE
[Zone][Wintergrasp] Double Tower

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#463]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I don't think I need to explain this one.

https://youtu.be/D3Qyvg_qP4A

But also it appears that a tower at 50% does not show up as a damaged tower model. But it's hard to tell with the double tower issue.

**Comment by Cold-Martijn** [comment]
This wasn't because of GM buffs?

**Comment by Vishiswaz** [comment]
GM mode was off

**Comment by NatsumeLily** [comment]
Going to add that I was the one in the siege tank, I also saw more than one tower (not a GM). But unlike Vishi, I didn't see any hp bar going down.

**Comment by Wolffenstein** [comment]
Fixed in rev 1185.
