### ISSUE TITLE
[Zone][Wintergrasp] Honor Reward

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#464]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Honor rewards are completely and totally wrong. Plus you can get double honorable kills.

Battle Test 1: I started a battle (Horde defending), gave the horde player their First Lieutenant buff. I had the Recruit buff. I ended it, so Horde won. He (Horde, winning team) got 3000 honor (1x3000). I (Alliance, losing team) got 5750 (1x 1250 + 3x 1500). There's no way that's correct.

Battle Test 2: Started a battle (Horde defending). We both had the Recruit buff, no kills. Ended it, Horde won. He still got 3000 honor and I got 5750, same as in Test 1.

Battle Test 3: Started a battle (Horde defending). I (alliance) killed my friend (horde) and got 2 honorable kills for it. 2x124 honor points. Then I tried to loot his corpse and it [crashed the server](https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/465).

Battle Test 4: Started a battle (Horde defending). I (alliance) killed my friend (horde) repeatedly until I got First Lieutenant. I got the same amount of honor, and so did he. The amount of honor you get is supposed to change with your WG rank. It is not.

**Comment by FX-SF** [comment]
revision 1165
