### ISSUE TITLE
[Zone][Wintergrasp] Looting corpses crashes the server

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#465]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Right clicking a corpse of a person you killed in Wintergrasp during a battle should:

1. Force the player to release to the nearest graveyard their faction currently controls
2. Loot you some silver.

Instead, it:

1. Crashes the server
2. gg

**Comment by Wolffenstein** [comment]
Fixed in rev 1169

**Comment by Vishiswaz** [comment]
> Fixed in rev 1169

>69

Nice
