### ISSUE TITLE
[Zone][Wintergrasp] Capture Objective Bar doesn't disappear after a battle

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#466]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If you are at a capturable objective (one of the workshops outside the fortress) and the battle ends, the bar at the top of the screen does not disappear. It should.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Wolffenstein** [comment]
Fixed in rev 1186.
