### ISSUE TITLE
[Zone][Wintergrasp] Tug-Of-War Mechanics

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#467]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.engadget.com/2010-02-19-wintergrasps-hidden-balance-mechanics-revealed-minor-changes-c.html

Okay, I thought this wasn't fully implement, turns out it's just not fully implemented.

It appears that no matter how much I lose as an Alliance player, the final stage of the Tug-of-War mechanics never kicks in.

![image](https://user-images.githubusercontent.com/78314117/168399137-91c76f3c-8a7a-4866-97e9-535f6c3bc13d.png)

The tug-of-war mechanics is implemented for determining initial control of Broken Temple and Sunken Ring, but not for the ranking up system.

**Comment by Vishiswaz** [comment]
Never mind, it's implemented as far as I can tell.

**Comment by Vishiswaz** [comment]
Reopened and renamed this and provided details, as apparently it is indeed implemented but not fully.

**Comment by Wolffenstein** [comment]
It's working correctly already.
