### ISSUE TITLE
[Zone][Dalaran] Portal to Wintergrasp doesn't change based on control of WG

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#468]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Currently, Alliance always has a portal to Wintergrasp in their fortress. Horde never does.

That's, uh, not how that should work.

I know there should be a portal there for both sides when WG is contested. I don't know if the portal should be there at all when there is no battle.

**Comment by FX-SF** [comment]
revision 1165
