### ISSUE TITLE
[Zone][Wintergrasp] Teleport from Dalaran

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#469]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When talking to the Wintergrasp NPC Queue person in Dalaran on Horde side as Horde, they teleported me into the Alliance camp. This was during a game Alliance was attacking, Horde defending. NPCs killed instantly. Very sad.

On my alliance character, same battle, talked to the Alliance Wintergrasp queue NPC in dalaran, and it sent me to the Alliance camp correctly. And then I went back to Dalaran and took the portal to Wintergrasp and it sent me to the horde fortress. Oof.

**Comment by Wolffenstein** [comment]
Fixed in rev 1171.
