### ISSUE TITLE
[Zone][Wintergrasp] Siege Engine

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#471]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Switching positions on the vehicle is currently bugged, but also, when you're inside the body of the siege engine, you should be able to mouse over the Siege Turret of your vehicle and get the same icon as if you were outside of the vehicle, and also be able to right click to switch to it. Provided the seat is empty, of course.

**Comment by Wolffenstein** [comment]
Fixed in rev 1173.
