### ISSUE TITLE
[NPC][Zone] Dalaran Horde and Alliance Trespasser

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#472]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**:
Seems like the guards on either side of Dalarans faction living quarters that use the trespasser ability need LOS of you. So in stealth you can go right in, as long as you stay out of their cone of sight.  
https://www.youtube.com/watch?v=pNzz75dTIjM

Not sure if this is a bug, but it doesn't seem right. 

**Revision**: 1165

**Comment by Wolffenstein** [comment]
Fixed in rev 1176.
