### ISSUE TITLE
[Zone][Dalaran] Portal to Wintergrasp

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#474]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: At the moment Horde can use the portal to Wintergrasp in the Alliance area in Dalaran. In combination with #472, it gives Horde teleport to Wintergrasp all the time. 

**Expected behaviour**: The portal should be locked to the faction that controls Wintergrasp. 

**Revision**: 1165

**Comment by Vishiswaz** [comment]
Additionally, while you're putting restrictions on the portal, there should be a minimum of level 70 to enter the portal. It might already have this, but I'm just making a note for the dev to check.

https://www.bluetracker.gg/wow/topic/eu-en/8246768669-recent-in-game-fixes-3-6-09/

![image](https://user-images.githubusercontent.com/78314117/168207219-59b745a4-28ad-4edb-ab3b-5200706a197c.png)

**Comment by FX-SF** [comment]
revision 1165

**Comment by Wolffenstein** [comment]
Fixed in rev 1187.
