### ISSUE TITLE
[Zone][Wintergrasp] Raid Disbandment

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#475]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
2 people enter Wintergrasp and are the only players on that side. One person leaves by logging off. The raid group gets disbanded.

This should not happen. Wintergrasp is the only place in the game that I'm aware of where a one-person raid group can exist, especially during the battle.

I believe the way it's supposed to work is that the raid group in Wintergrasp during the battle has no minimum amount of players. And when the battle is over, you can leave the raid like a normal raid.

**Comment by Wolffenstein** [comment]
Fixed in rev 1171.
