### ISSUE TITLE
[Zone][Dalaran] Daily Dungeon Quests + Dungeon Finder Rewards

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#477]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Daily Dungeon and Daily Heroic quests in Dalaran are not active.

https://wowwiki-archive.fandom.com/wiki/Wrath_of_the_Lich_King_daily_quests#Dungeon_daily_quests

These should be a thing up until 3.3, where they are replaced by extra rewards for rdf heroic and the weekly raid quest.

Additionally, since there was no dungeon finder tool, there should not be any badge rewards from random heroics until 3.3. Of course, this is up to you guys, because "Blizzlike" would be to disable the dungeon finder entirely until 3.3, and I don't think you guys are doing that. So until then, the badge rewards should probably be removed, or it will just accelerate the speed at which people get to raid log mode, and it will also flood the market with more frozen orbs.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Wolffenstein** [comment]
It already is implemented the way I want it to be.
