### ISSUE TITLE
[NPC][Dalaran] Missing RP in city + Tiffany Cartier

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#478]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I noticed something while being a True WotLK Player and running around Dalaran aimlessly.

On other servers, Tiffany Cartier in the Jewelcrafting shop would greet my character when I walked in. And, come to think of it, most (all?) of the NPCs in Dalaran seem to be missing any sort of RP speaking. This should be looked into.

Edit: This IS working in the Inscription shop for that NPC. So it's not all NPCs missing it. But honestly, every Dalaran NPC should be checked for missing RP in /say.

Edit 2: Tailoring place has a greeting. Blacksmith does. First aid doesn't. Alchemy does. Enchanting does. Leatherworking does. Engineering doesn't. Mining doesn't. Herbalism does.

To be clear, I'm not sure if they're all supposed to have it. But I do know the jewelcrafter one is missing it. And there's also like no other /s or /y roleplay in Dalaran other than entering _some_ of the shops right now, which feels.... off

**Comment by Wolffenstein** [comment]
Fixed in rev 1175.
