### ISSUE TITLE
[Quest] The Shining Light | [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#48]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The ghouls downstairs that survive "Shining Light" buff provided by the quest will remain in combat, even after player leaves the area and goes upstairs, which also causes chain pulling all the mobs in the way. 

**Current behaviour**: The ghouls will keep following a player upstairs and won't reset until they die, kill a player or abilities such is Vanish/Invisibility etc. are used. 

**Expected behaviour**:  The ghouls should exit combat and reset as a player climbs upstairs. Ghouls should also be running away as you make contact while under "Shining Light" buff.  https://www.wowhead.com/quest=11288/the-shining-light

**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
