### ISSUE TITLE
[NPC][Dalaran] Arcanist Braedin

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Another missing RP event but this one actually has some function.

This guy is supposed to shout in Dalaran to alliance players to get them to come to Wintergrasp. I'm not sure when, if it's before the battle, during the battle, or both. But currently he does none. Most of the comments on wowhead are about this. https://www.wowhead.com/npc=32169/arcanist-braedin#comments

**Comment by FX-SF** [comment]
revision 1165
