### ISSUE TITLE
[NPC][Bloodtalon Shore ] Swiftclaw

### ISSUE THREAD

**Issue by anathrax** [Stormforge-gg/Bugtracker-Wotlk-Beta#481]
**Description**: 

In the starting area of the trolls quest "young an vicious" is bugged. It says to ride the raptor to his pen but all he does is that he runs in a circle and I have no control over him either with a mouse or keyboard

**Comment by Vishiswaz** [comment]
Is this in mop or WotLK

**Comment by Vishiswaz** [comment]
Yeah dude you posted this in the wrong place. This is the WotLK bug tracker.

**Comment by anathrax** [comment]
> Yeah dude you posted this in the wrong place. This is the WotLK bug tracker.

I see, mb
