### ISSUE TITLE
[NPC][Storm Peaks] Time-Lost Proto Drake

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#487]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Possibly related to the [Vyragosa](https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/326) ticket, since they should be sharing a respawn cycle and movement waypoints...

The Time-Lost Proto Drake is not implemented properly. I saw it a while ago and forgot to report it, so I have no footage or screenshots. But I know it's incorrect.

Vyragosa and TLPD are supposed to share a respawn, with only one of them being up at a time. I believe TLPD has a 1 in 8 chance of spawning whereas vyragosa has the remaining 7 of 8. There are many different possible spawn points, which are picked at random, and multiple different paths it can take. Hunting it is a whole thing that people have made tons of videos of on YouTube if you want to look up info on it, it's definitely out there.

**Comment by FX-SF** [comment]
Revision 1165

**Comment by Vishiswaz** [comment]
Appears to be fixed.
