### ISSUE TITLE
[NPC] Howling Fjord

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Wotlk-Beta#49]
Description :  
https://www.wowhead.com/npc=24871/risen-vrykul-ancestor
https://www.wowhead.com/npc=24872/blood-shade
https://www.wowhead.com/npc=27927/dragonflayer-guardian
https://www.wowhead.com/npc=23977/abandoned-pack-mule#screenshots
https://www.wowhead.com/npc=24540/necrotech
https://www.wowhead.com/npc=24485/servitor-shade
https://www.wowhead.com/npc=23643/unstable-murghoul
https://www.wowhead.com/npc=23656/dragonflayer-rune-seer
https://www.wowhead.com/npc=24676/crazed-northsea-slaver

Current behaviour:
npc=24871 The movements are not normal, too fast
npc=24872 unusual movement
npc=27927 unusual movement
npc=23977 unusual movement
npc=24540 unusual movement
npc=24485 unusual movement
npc=23643 unusual movement
npc=23656 unusual movement
npc=24676 unusual movement

Revision : readjust the speed of movements and unusual movement

**Comment by Cold-Martijn** [comment]
24871 - fixed
24872 - on my todo list
27927 - not a bug
23977  - not a bug
24540  - i'll double check this one, but I think not a bug
24485 - not a bug
23643  - i'll double check this one, but I think not a bug
23656 - there are quite many of these, any specific one? :)
24676 - I'll double check this one
