### ISSUE TITLE
[Zone][Wintergrasp] Wintergrasp Fortress Door

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#490]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The damage done to the Wintergrasp Fortress Door appears way up high above it instead of near or on the door itself.
![WoWScrnShot_051322_192400](https://user-images.githubusercontent.com/78314117/168400960-ae6f292c-8bb2-4163-a09b-64bb895ba72c.jpg)

**Comment by FX-SF** [comment]
Revision 1165

**Comment by Cold-Martijn** [comment]
client side

**Comment by Vishiswaz** [comment]
Are you sure this is client side? I've never seen this on any other server.
