### ISSUE TITLE
[Zone][Wintergrasp] Opposing faction vehicle map blimp

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#492]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: You can see the opposing factions vehicle map blimps, no matter how far away you are.

**Expected behaviour**: Not sure what the exact range you should be able to see them is, but the range until you can see the vehicle load in is probably the safest range. 

**Revision**: 1165

**Comment by Wolffenstein** [comment]
It has the gigantic AOI flag, which means it should be seen from very far away and I remember the same from playing on retail, so i need proof that it shouldnt
