### ISSUE TITLE
[Spell] Oculus: Amber Drake - Damage increase (Repost)

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#493]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Description:** Reposting this report since it was never fixed and was incorrectly closed. 

**Current behaviour:** Currently the damage bonus from Temporal Rift is stacking. Not only is it stacking (which isn't correct), it's multiplicative. Meaning one shock lance with 10 charges will do 1.2 million damage, effectively 3 shotting the boss with a full Amber drake team. 

**Expected behaviour:** It shouldn't stack.

https://www.wowhead.com/spell=49592/temporal-rift#comments:id=467828:reply=74455
![image](https://user-images.githubusercontent.com/15247730/168402114-cfdf9048-5ddd-43ca-af3d-96da384e6c52.png)

https://www.wowhead.com/npc=27656/ley-guardian-eregos#comments:id=468482
![image](https://user-images.githubusercontent.com/15247730/168402129-35375563-02a2-4fb8-b821-afd737eb52f8.png)

Then the reply to that post is someone correctly their old post, and confirming the damage component no longer stacks.

https://youtu.be/pncdlQAFnwU?t=313 You see multiple cases where there are two channels or one channel, but the damage being done is roughly the same even if there are 2 active. And the damage differences there are because of the damage range the spell has.

I found some more but it's from patch 4.0.3.
https://www.wowhead.com/the-oculus#comments:id=1357375
![image](https://user-images.githubusercontent.com/15247730/168402155-14697118-bfde-4c48-b253-8f93c34359cd.png)

**Revision**: 1165

**Comment by Wolffenstein** [comment]
Fixed in rev 1376.
