### ISSUE TITLE
[Spell][The Obsidian Sanctum] Twilight Torment

### ISSUE THREAD

**Issue by mythyrylfalcon** [Stormforge-gg/Bugtracker-Wotlk-Beta#495]
**Description**: Twilight Torment "https://www.wowhead.com/spell=57988/twilight-torment" Is not removed on death, departure from the instance or reset of the encounter

**Current behaviour**: Above

**Expected behaviour**: Spell should be applied when Shadron lands during the Sartharion encounter and be removed on death, departure or reset.

**Revision**: 1179

**Comment by mythyrylfalcon** [comment]
Apparently the casting mob "Acolyte of Shadron" is not resetting properly and continuing to cast from an alternate phase.

**Comment by Vishiswaz** [comment]
I'm not entirely sure right now but I do know this happened on Crystalsong initially too. Maybe the Tauri devs can assist?

**Comment by Vishiswaz** [comment]
Apparently I was even the one to report it back then. https://bug.tauriwow.com/index.php?do=details&task_id=24484

**Comment by Wolffenstein** [comment]
I meant the Acolyte not resetting properly
