### ISSUE TITLE
[NPC] Archavon the Stone Watcher

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#496]
**Description**: [Archavon the Stone Watcher](https://www.wowhead.com/npc=31125/archavon-the-stone-watcher#abilities;mode:n10) is a boss in VoA

**Current behaviour**:

1) [Rock Shards](https://www.wowhead.com/spell=58678/rock-shards) always targets tank.
2) [Archavon the Stone Watcher](https://www.wowhead.com/npc=31125/archavon-the-stone-watcher#abilities;mode:n10) drops a player which he has lunged for.

**Expected behaviour**: 

1) [Rock Shards](https://www.wowhead.com/spell=58678/rock-shards) should target a random player.
2) [Archavon the Stone Watcher](https://www.wowhead.com/npc=31125/archavon-the-stone-watcher#abilities;mode:n10) throws a player which he has lunged for.

**Revision**:  1179

Video Evidence:
1) You will have to slow this down and its very messy, but you can consistently see the throw mechanic:
 https://youtu.be/ev1QM-wOSEA?t=164
2) Rock Shard (spell mechanics also look different) 
 https://youtu.be/7F86rdQRiBs?t=40

**Comment by Wolffenstein** [comment]
1. It already targets random player
![image](https://user-images.githubusercontent.com/1576644/168449059-fc8d7c4d-84cd-43bf-8791-09a509eb4c82.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1184.
