### ISSUE TITLE
[NPC][The Obsidian Sanctum] Shadron, Tenebron, Vesperon solo fights

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#497]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The exit portal briefly appears during the Shadron solo fight each time he opens a portal. https://youtu.be/z4UhN0HuYCM

Minor bug, but I could see it briefly confusing people who are new.

Edit: This is also happening in the Tenebron solo fight, though I don't have footage.

Edit 2: Vesperon as well. 2 portals briefly appear, only 1 stays, other one immediately fades.

**Comment by Wolffenstein** [comment]
Blizzlike
