### ISSUE TITLE
[NPC][Naxxramas] Crypt Guard

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#498]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Reopen of https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/410

https://youtu.be/4SOL4QSipaY

Crypt Guards not despawning after Anub is down. I didn't have corpse scarabs in this run but I did a few days ago when I did it and they did not despawn either.

**Comment by Wolffenstein** [comment]
That's blizzlike and intended, I made it this way on purpose.
