### ISSUE TITLE
[Priest][Spell] Dispersion

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#5]
[Spell][Class] Dispersion

**Description**: Priest slows in ability Dispersion

**Current behaviour**: At the time of application after use, the effects are removed, but when new ones are applied, the priest slows down in a cloud, tested with an ice mage.

**Expected behaviour**: When using the ability, the slow must be removed and immunity to the slow should be given for the duration of the ability

**Revision**:

**Comment by Gn0m** [comment]
https://www.wowhead.com/spell=47585/dispersion

**Comment by Emtec** [comment]
Fixed in 1104
