### ISSUE TITLE
[DUNGEON][NPC] Dead mobs visual bug

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#50]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Some mobs in VH after dying slide on the ground towards the main door. https://www.wowhead.com/the-violet-hold

**Current behaviour**: Some mobs in VH after dying slide on the ground towards the main door.

**Expected behaviour**: Dead mobs should lie dead on the ground.

**Revision**: 1036

**Comment by Wolffenstein** [comment]
Cannot reproduce, please provide a video
