### ISSUE TITLE
[Zone][Dalaran] Missing Greetings in Shops (round 2)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#501]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Following up on previous ticket https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/478

Not all shops have their entry greetings working

Alchemy: Working
Enchanting: Working
**First Aid: Not working**
Jewelcrafting: Working
**Engineering: Not working** (but he does turn towards the player, very creepy)
Tailoring: Working
Leatherworking: Working
**Mining: Not working** (also turns towards the player)
Blacksmithing: Working
Herbalism: Working
Inscription: Working **BUT both Larana Drome and Jessica Sellers have a greeting and will activate from a single entrance. Is that supposed to happen?**

**Comment by Wolffenstein** [comment]
Fixed in rev 1191.
