### ISSUE TITLE
[Zone][Wintergrasp] Two Flags

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#502]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While it's very nice to see Horde and Alliance sharing, I don't think this is blizzlike.
![WoWScrnShot_051422_020806](https://user-images.githubusercontent.com/78314117/168413197-dd02767e-1aba-4530-bfa9-a34cdbca531a.jpg)
May be related to https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/463

**Comment by Wolffenstein** [comment]
Fixed in rev 1185.
