### ISSUE TITLE
[NPC][Hellfire Peninsula] Starving Helboar

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#505]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These mobs are supposed to have an increased aggro range as opposed to the standard most mobs have. As evidenced in many upset wowhead comments. https://tbc.wowhead.com/npc=16879/starving-helboar#comments

**Comment by Wolffenstein** [comment]
they already do
