### ISSUE TITLE
[DUNGEON][BOSS] Gal'darah

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#51]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Whirling Slash does way too much damage (not sure if it's intended tuning but 1 hit death seems way too excessive - it does 15-17k damage per hit on mail with 4.2k GS). Rhino form Puncture ability missing. Boss in rhino form after wipe if group wiped during rhino phase (visual).

**Current behaviour**: Too much damage from Whirling Slash. Rhino missing Puncture. Visual rhino form bug if group wiped during rhino phase.

**Expected behaviour**: Whirling Slash - "A whirlwind attack that does substantial melee AoE damage, and which leaves a debuff that ticks for ~3500 damage per 3 seconds. Movement speed slowed by 65%."; Rhino form should use Puncturel; After wipe boss should completely reset including his looks.

**Revision**: 1036

**Comment by Wolffenstein** [comment]
Fixed

**Comment by Nuy** [comment]
Puncture is human form ability actually it seems even though on Wowwiki it says it's rhino form. https://wowwiki-archive.fandom.com/wiki/Gal%27darah
