### ISSUE TITLE
[Core][Item] Satchel of Helpful Goods

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#513]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Tested rdf with a group of level 15s and 16s. Had 1 character leave group, didn't get a replacement. Had 2 more characters teleport out. Completed ragefire with the remaining 2. None of us received the satchel upon completion.

BUT: At level 17 the rewards screen for the Random Classic Dungeon shows a Satchel of Helpful Goods with the ID of 52003, which contains items with an ilvl of level 60. That's not correct. And it's very bad because they have a high ilvl with no level requirement.

EDIT: Queued again as level 17 with other characters in group being 17, 15, 15, and 22. This time, all 5 characters were inside the dungeon (Deadmines) when the boss died, and we all got the (wrong, level 60) Satchel.

**Comment by Wolffenstein** [comment]
Maybe because you deleveled yourself because otherwise its not possible
