### ISSUE TITLE
[Core] RDF Cooldown Clear on completion

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#518]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It seems that if a character is in the dungeon but not near the last boss when it dies, it's not fully removing the "On Cooldown" status that would allow the group to re-queue again.

So, each individual character shows the Random Classic Dungeon queue as possible for them, but the group leader cannot initiate because the characters far from the last boss appear as On Cooldown.
![ss](https://user-images.githubusercontent.com/78314117/168453027-e6302401-6cc5-4a5c-84a8-6a2bdf832bb4.jpg)

Edit: Maybe, even if it's not blizzlike, people who are afk when a dungeon ends should not have their cooldowns removed? Why should they be rewarded for the work everyone else did?

**Comment by Wolffenstein** [comment]
clientside bug
