### ISSUE TITLE
[Quest] Stunning Defeat at the Ring | [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#52]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The mobs which are part of the quest are not spawning correctly (excluding the first one) and they are missing dialogues.

**Current behaviour**:  Only the first one spawns next to the gates in the quest room, while the others spawn in the middle ( with exception of the 2nd which has a duplicate, one of which spawns in the middle and the other next to the gates (one of them disappears eventually)).

**Expected behaviour**:  They should spawn next to the gates in the quest room and run towards the middle. https://www.wowhead.com/quest=11300/stunning-defeat-at-the-ring

**Revision**:

**Comment by Cold-Martijn** [comment]
Related issues on Alpha bugtracker:
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/299
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1354

**Comment by Wolffenstein** [comment]
Fixed in rev 1213.
