### ISSUE TITLE
[Core] Running in Fear interrupted by casting

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#521]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When a mob runs away in fear, it should always keep doing so unless it:

1. Finishes running
2. Dies (obviously)
3. Receives a debuff that prevents flee like Judgment of Justice.

What should not happen: https://youtu.be/lm9YNIH4VQw

This may be specific to Defias Pillagers, which are also the subject of https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/520 and https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/511

**Comment by Cold-Martijn** [comment]
This might be a smoll remaining bad SAI, I will take a look at it if it is that.
If its a core issue i will remove assignment again.

**Comment by Vishiswaz** [comment]
I don't think it's specific to the Defias Pillagers anymore, I think it's all casters and ranged.

**Comment by Cold-Martijn** [comment]
Both in SAI and DBAI, all creatures that are using flee will continue using castermodule spells. This results in running away, do a fireball, and run away a bit more.

**Comment by Wolffenstein** [comment]
Fixed in rev 1192.
