### ISSUE TITLE
[NPC][Shadowfang keep] Archmage Arugal

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#530]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: 
1. The door to his area/room closes and doesn't open after he is killed. 
2. When he kills someone, nothing happens to his mana.

**Expected behaviour**: 
2. When he kills someone he should get 50% of his mana back. 

1. According to classic and Nostalrius (only two videos I could find) his room door should never close. I don't know if this was done to make the fight harder or something. But the door should at least open after he's killed, if you decide to keep the door closed during the fight. 

https://youtu.be/PZsdCVCAcmc?t=1394

https://youtu.be/jotsXq3DzVc?t=1904

**Revision**: 1184

**Comment by Vishiswaz** [comment]
Can you link the video from Classic

**Comment by Wolffenstein** [comment]
Fixed in rev 1216.
