### ISSUE TITLE
[NPC] [Wailing Caverns] Mutanus the Devourer not moving

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#531]
**Description**: 
[Mutanus the Devourer](https://classic.wowhead.com/npc=3654/mutanus-the-devourer) during the quest wasn't moving (and evading every attack) so i go to melee range, he started attacking but lose aggro once i got out of water and stayed on his spawn point (but no more evading)

**Current behaviour**:
Spawn, don't move and evade until you aggro him, can be deaggro and he stay in water

**Expected behaviour**: 
Spawn, move to the NPC to attack him

**Revision**: 
1184

**Comment by Cold-Martijn** [comment]
please recheck after revision 1195, i think this was on the changelog
