### ISSUE TITLE
[Spell] Nature's Grasp

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#534]
Was unable to learn spell "Nature's Grasp" from the trainer at level 10 as a Druid.

It says it requires Cat Form to learn it... but this is a balance spell, there should be no requirement beyond being the appropriate level + having already trained Entangling Roots

![Nature's Grasp](https://user-images.githubusercontent.com/37913400/168686668-5f76f528-525a-44ca-82b3-93845f1418b7.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1202.
