### ISSUE TITLE
Chen's Empty Keg

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#538]
Chen's Empty Keg item is missing from coords 56, 20 in the Barrens, it should be there for you to accept the quest, and has a respawn timer of about ~5 minutes or so per wowhead,
 
I have seen this in Classic as well.

https://classic.wowhead.com/item=4926/chens-empty-keg

**Comment by Tereneckla** [comment]
It has a spawn there, not all of them are up at the same time

**Comment by Godmatik** [comment]
I'm fairly certain multiple kegs can be up at once, will verify on classic.

**Comment by Tereneckla** [comment]
3 of the 9 can be up at the same time
