### ISSUE TITLE
[DUNGEON][NPC][BOSS] Trash near Drakkari Colossus

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#54]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Trash mobs near Drakkari Colossus (Living Mojo and Drakkari Golem) always aggro when boss is pulled (it's like they're linked) and that will always mean a wipe.

**Current behaviour**: Trash mobs near Drakkari Colossus are linked with the boss and pull together.

**Expected behaviour**: Trash mobs behind Drakkari Colossus shouldn't be linked with the boss.

https://www.wowhead.com/npc=29830/living-mojo
https://www.wowhead.com/npc=29832/drakkari-golem

**Revision**: 1036

**Comment by H4Xx0R-PC** [comment]
I can confirm the mobs are supposed to be linked, I tested this on retail.

2 Golems are linked and 1 living mojo.

**Comment by Wolffenstein** [comment]
This isn't a bug.
