### ISSUE TITLE
[QUEST] Verog the Dervish

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#541]
I went to the spot where Verog was, and he was already spawned for the quest.

He should only spawn after you kill nearby centaur, and one of them has a chance upon death (don't know the %) to do a 'yell' emote and summon him.

https://tbc.wowhead.com/quest=851/verog-the-dervish

**Comment by Cold-Martijn** [comment]
Issue was that he does not despawn once summoned :) He will now despawn when not in combat for 5 minutes.
