### ISSUE TITLE
[NPC] Gann Stonespire

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#546]
He was doing his patrol path just fine when I first approached - but when I stopped him to pick up his quest(s), he never resumed his patrol, just stood still entire time.

https://tbc.wowhead.com/npc=3341/gann-stonespire

**Comment by Cold-Martijn** [comment]
Did you stay in place next to him, or did you move away and found him in the exact same position?
On local, when staying next to him for 3 minutes, he will simply resume moving as he should :)

**Comment by baavgai123** [comment]
Seems like Gann Stonespire mentioned before is still standing in one place instead of patrolling his way in the Southern Barrens. I just met him like that without talking to him before.

**Comment by Cold-Martijn** [comment]
> 

He is on a 3 minute timer, however, NPC's do not update when there is no one nearby for performance reasons.
