### ISSUE TITLE
[QUEST] Hypercapacitor Gizmo

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#547]
You are able to attack the Enraged Panther before first opening the cage, should be inactive until you set him free.

![Gizmo](https://user-images.githubusercontent.com/37913400/168736682-9ac0f84f-b9f1-43aa-827a-a628ff50d5d2.png)

https://tbc.wowhead.com/quest=5151/hypercapacitor-gizmo

**Comment by Wolffenstein** [comment]
Fixed in rev 1201.
