### ISSUE TITLE
[NPCs] Salt Flat Scavenger

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#549]
Only 3 salt flat scavengers located @ 89, 67.

Should be 6-8 per wowhead comments.

The quest "Load Lightening" will be difficult with so few spawns.

https://tbc.wowhead.com/npc=4154/salt-flats-scavenger#comments

![Salt Flat Scavenger](https://user-images.githubusercontent.com/37913400/168739277-4f83e1f5-b344-4a47-ab1e-bc9097dced44.png)

**Comment by Cold-Martijn** [comment]
rev 1349
