### ISSUE TITLE
[Quest] The Echo of Ymiron | [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#55]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The quest is not fully scripted, Lich King is missing in the spirit world.

**Current behaviour**:  Lich King is missing.

**Expected behaviour**:  Lich King should be at the bottom of the stairs which lead to Utgarde Keep next to 2 Val'kyr Soulclaimers. Getting in range of him should trigger the event, in which LK pulls and freezes the player, followed by dialogue and finally kills the player.  https://www.wowhead.com/quest=11343/the-echo-of-ymiron
**Revision**:

**Comment by Cold-Martijn** [comment]
Works for me :)
