### ISSUE TITLE
[Quest][NPC] Saving Yenniku

### ISSUE THREAD

**Issue by WowPrivateServerEnjoyer** [Stormforge-gg/Bugtracker-Wotlk-Beta#550]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I'm not able to complete Saving Yenniku quest (https://classic.wowhead.com/quest=592/), because the given quest item, Soul Gem (https://classic.wowhead.com/item=3912/) is not usable on Yenniku (https://classic.wowhead.com/npc=2530); when I try to use the item targeting Yenniku, I get invalid target error. Another problem with Yenniku, that currently Yenniku is hostile, but not attackable, but according to this video, Yenniku should be attackable: https://youtu.be/MAN18yo0aPc?t=32

**Current behaviour**:
Yenniku is not attackable, and the soul gem quest item is not usable on him.

**Expected behaviour**: 
Yenniku should be attackable, and the soul gem quest item should be usable on him to turn Yenniku into a friendly NPC with a completable quest (https://classic.wowhead.com/quest=593/).

**Revision**: 1184

**Comment by EtheriousNW** [comment]
Fixed and live on beta
