### ISSUE TITLE
[NPC] Lesser Infernal

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#555]
Every lesser infernal I run into in Mannoroc Coven can not be targeted or interacted with, however they will still aggro onto you.

https://classic.wowhead.com/npc=4676/lesser-infernal

![Infernal](https://user-images.githubusercontent.com/37913400/168912759-11008fd5-26f9-4e84-927f-f470683eee30.png)

**Comment by Cold-Martijn** [comment]
Am I correct to assume they should just be regularly attackable like any other mob? Or should they become active after using something?
