### ISSUE TITLE
[Stranglethorn Vale][Drop] Half-Buried Bottle

### ISSUE THREAD

**Issue by WowPrivateServerEnjoyer** [Stormforge-gg/Bugtracker-Wotlk-Beta#558]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Half-Buried Bottle's (https://classic.wowhead.com/object=2560) drop table's items' drop chances seems incorrect. I opened 17 bottles, I gained the following items:

- 1 Carefully Folded Note (https://classic.wowhead.com/item=4098)
- 4 Crumpled Note (https://classic.wowhead.com/item=4100)
- 7 Ripped Note (https://classic.wowhead.com/item=4101)
- 5 Torn Note (https://classic.wowhead.com/item=4102)

This result differs from what can be expected according to wowhead, but it's also possible that I was really unlucky.

**Current behaviour**:
Half-Buried Bottle object's drop table's items' drop chances seems incorrect.

**Expected behaviour**: 
Carefully Folded Note's drop chance might need to be increased, and Crumpled, Ripped, Torn Note's drop chances might need to be decreased.

**Revision**: 1206

**Comment by Cold-Martijn** [comment]
I'll check the loot chances in the database and compare then with wowhead(comments)

**Comment by Cold-Martijn** [comment]
sliiiightly adjusted, but you had bad luck pretty much.
