### ISSUE TITLE
[Talent][Druid] Living Seed

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#559]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: Living Seed is blooming (proccing) and healing the target on any damage.

**Expected behaviour**:  It should only proc on melee attacks. Things like ranged spells and aoes shouldn't proc the heal. 

**Revision**: 1206

**Comment by Wolffenstein** [comment]
"The Living Seed will bloom when the target is next attacked. "
Source that it should be melee only? It has proc flags for spells too
