### ISSUE TITLE
[NPC][spell] Gluth - Decimate / Zombie Chow behavior

### ISSUE THREAD

**Issue by duzyizly** [Stormforge-gg/Bugtracker-Wotlk-Beta#56]
**Description**: 
Decimate spell of Gluth https://www.wowhead.com/npc=15932/gluth is actually killing everyone instead of reducing to 5%. Also summoned Zombie Chows https://www.wowhead.com/npc=16360/zombie-chow are not moving to Gluth while he is casting Decimate (but kinda hard to say because they just died like us instantly).

Tested twice on 10 man normal.

![image](https://user-images.githubusercontent.com/43931626/162535380-d9d92447-c947-4eef-b27e-775c1ffd4962.png)

**Expected behaviour**: 
Due to sources zombies should move to boss once he cast decimate, players and zombies should drop to 5% hp.
https://youtu.be/a8MnGxElPWg?t=71

**Revision**: 
1036

**Comment by haephaistoss** [comment]
are you sure, you didn't accidently put a berserk buff on gluth?

**Comment by duzyizly** [comment]
We had only saronite and uber heal.

**Comment by duzyizly** [comment]
3rd testing, same results, this time ardent defender blocked it.
As you can see there's no berserk / enrage etc. on the boss.
![image](https://user-images.githubusercontent.com/43931626/162538622-7db3b0b0-cf6a-40fa-8a40-fab0b2258daf.png)

**Comment by Wolffenstein** [comment]
Should be fixed now.
