### ISSUE TITLE
[NPC][Scarlet Monastery Libary] Houndmaster Loksey

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#560]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**:
1. He's missing the spell Battle Shout or isn't using it.
2. He doesn't use Blood Lust on his hounds. 

**Expected behaviour**: He should do both.

**Revision**: 1206

**Comment by Wolffenstein** [comment]
Fixed in rev 1279.
