### ISSUE TITLE
[Zone][Wintergrasp] Honor Reward

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#568]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I hadn't ranked up at all and was on the losing attacking faction and got 5750 honor total. There's no way that's correct. Reopening https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/464
![WoWScrnShot_051822_224124](https://user-images.githubusercontent.com/78314117/169192959-2d2b8350-da53-4b65-b1fe-1e8fe9857b53.jpg)

**Comment by Cold-Martijn** [comment]
not a bug
