### ISSUE TITLE
[Zone][Wintergrasp] Cinder Clouds

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#572]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Cinder Clouds in Wintergrasp that you can use the Zapthrottle Mote Extractor on are missing. There should be two or three in The Cauldron of Flames.

While you're in there fixing that, can you also please make sure that the respawn on all of the Engineering clouds are dynamic and not too fast? Otherwise the price of eternals will absolutely plummet and also the value of farming in Wintergrasp for most eternals will be massively reduced.

Edit: Also, at the Obsidian Dragonshrine, there are currently 2 nodes, I believe a 3rd is supposed to be present near where the snow meets the dark ground at the entrance. 
![WoWScrnShot_051822_231313](https://user-images.githubusercontent.com/78314117/169196545-75125640-00b8-4bd4-8e04-9a863bab4a26.jpg)

**Comment by Tarkamacska** [comment]
https://www.wowhead.com/npc=32522/cinder-cloud#comments
MAPS: 
https://www.wowhead.com/maps?data=3711:424223463242474273
https://www.wowhead.com/maps?data=65:383318

https://wowpedia.fandom.com/wiki/Cinder_Cloud

and usually in other wotlk servers, you can find Cinder Cloud on theese positions :
https://wotlk-twinhead.twinstar.cz/?npc=32522
