### ISSUE TITLE
[Spell] Transmute: Titanium CD

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#575]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: Currently has no CD.

**Expected behaviour**: Cooldown should be 1 day. 

Related to https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/443

**Revision**: 1206

**Comment by Amun12** [comment]
It shouldn't be 1 day, it should be 20 hours : https://wowwiki-archive.fandom.com/wiki/Titansteel_Bar .

**Comment by Wolffenstein** [comment]
Fixed in rev 1216.

**Comment by Godmatik** [comment]
> It shouldn't be 1 day, it should be 20 hours : https://wowwiki-archive.fandom.com/wiki/Titansteel_Bar .

@Amun12 You're thinking of titansteel transmute cooldown

Titanium transmute is indeed 1 day

**Comment by NatsumeLily** [comment]
> It shouldn't be 1 day, it should be 20 hours : https://wowwiki-archive.fandom.com/wiki/Titansteel_Bar .

1 day is 20 hours in wow. At least for crafting CDs
