### ISSUE TITLE
[Sunder Armor][Warrior] Sunder Armor - Glyph of Sunder Armor Causes Multiple Stacks of Sunder

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#576]
**Description**: 

Glyph of Sunder Armor causes two stacks of sunder armor to be applied to both targets instead of just a single stack applied to both targets.  Does not apply two stacks 100% of the time but most of the time.

**Current behaviour**:
See linked video.
https://streamable.com/g9b1za

**Expected behaviour**: 
Should only apply a single stack of sunder armor unless using devastate with glyph of devastate.

**Revision**: 
1206

**Comment by Ceago** [comment]
Addendum:  Only an issue for sunder armor, devastate functions correctly.

**Comment by Ceago** [comment]
Addendum:  Devastate functions correctly.  Only an issue with Sunder Armor.

**Comment by Wolffenstein** [comment]
Fixed in rev 1216.
