### ISSUE TITLE
Deserter Debuff from RDF

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Once a random dungeon finder group gets down to 3 players, the remaining 3 are supposed to be able to leave without getting Deserter. Currently, at least the first one is getting Deserter, didn't test the rest.

So in a group of 5 (Players A, B, C, D, and E), here's what should happen
A leaves - Deserter, group has 4 left
B leaves - Deserter, group has 3 left
C leaves - No deserter, group has 2 left
D leaves - No deserter, group has 1 left
E leaves - No deserter, group is disbanded

And to be clear, in the case of a group (Players A, B, C, D, and E) refilling after 2 people leaving (with new players F and G) but then disbands anyways:

A leaves - Deserter, group has 4 left
B leaves - Deserter, group has 3 left
F and G join - group has 5 people
C leaves - Deserter, group has 4 left
D leaves - Deserter, group has 3 left
F leaves - No deserter, group has 2 left
G leaves - No deserter, group has 1 left
E leaves - No deserter, group is disbanded

So what determines Deserter is how many players you're leaving behind. If you leave behind 4 or 3 group members, you get deserter.

All of this assuming the final boss of the dungeon isn't killed, of course.

**Comment by Wolffenstein** [comment]
Last two dont get deserter, not 3
