### ISSUE TITLE
Permanent "Pulsing Shockwave Aura" debuff in Halls of Lightning

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Wotlk-Beta#58]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I have a permanent pulsing shockwave aura debuff from halls of lightning, we pulled the first boss to the portal and I was knocked out by the boss or a mob through the portal and now I have this debuff permanently. I also cannot teleport back to the dungeon after being knocked out, it is saying you can't do that right now.
**Current behaviour**:
Debuff stuck on my character after being knocked out of instance.
**Expected behaviour**: 
Debuff to be removed after being knocked out of instance and the ability to teleport back into the dungeon.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in revision 1039.
