### ISSUE TITLE
[Quest][Zone] City of Light - Shattrath Intro Quest Non Functional - Not Completable

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#587]
**Description**: 
Upon speaking to Khadgar a arcane voidwalker should spawn to walk you around Shattrath.  Currently Khadgar performs his animation but does not actually summon this entity.  

**Current behaviour**:
https://streamable.com/czsccb

**Expected behaviour**: 
Should summon the blueberry and waste your time in a more respectful manner. 

**Revision**: 
1217

**Comment by Wolffenstein** [comment]
You were mounted.
