### ISSUE TITLE
[Core] "Need Before Greed" loot system - Dungeon Finder loot system

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#588]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: Dungeon finder is using Group loot. Need before greed loot system rules are not correct. 

**Expected behaviour**: Dungeon finder should be using need before greed loot system. 

In 3.3.0 the system was given new rules. 
![image](https://user-images.githubusercontent.com/15247730/169418975-f077c0a7-740b-44ab-b91e-b8b096bf4f59.png)

Need Before Greed rules should be (these are for deciding if you can need or not need) : 
1. The class must be able to equip the item.
2. Pure melee will be unable to roll on spell power items.
3. Classes are limited to their dominant armor type.
4. Players will be able to roll on items with a required level higher than player's current level.

**The above rules should not apply to vanilla dungeons. They should only apply to dungeons in TBC and Wotlk RDF.**
**In vanilla dungeons you should be able to need on anything.**

Confirmed restriction for Wotlk heroics would be not being able to need on Frozen orbs.

There were some more restrictions added to the wiki page in Cata but don't know if they apply in wotlk. 
![image](https://user-images.githubusercontent.com/15247730/169421237-6aa0aa5a-9255-47a5-9881-75f4f3d61287.png)

**Revision**: 1206

**Comment by NatsumeLily** [comment]
Proof the rules shouldn't apply to vanilla RDF. 

https://www.youtube.com/watch?v=772TnxwofaM - Druid can roll need on the shield.
https://www.youtube.com/watch?v=rQv5BAa3v5E - Warrior can roll need on spellpower cloth and leather.

https://www.wowhead.com/forums/topic/levelling-a-paladin-as-healer-ok-to-need-on-cloth-leather-156692
![image](https://user-images.githubusercontent.com/15247730/169421670-c8c248f3-a184-4f63-81af-b9452d5c27c3.png)

**Comment by Vishiswaz** [comment]
Might be smart to not go blizzlike and apply armor restrictions by type to vanilla dungeons. It's infinitely frustrating as a clothie to try to get gear while doing dungeons when every paladin and warrior is taking all your shit.

**Comment by Emtec** [comment]
Fixed 1220
