### ISSUE TITLE
[Quest][Hellfire Peninsula] The Demoniac Scryer - Multiple Small Issues

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#589]
**Description**: [The Demoniac Scryer](https://tbc.wowhead.com/quest=10838/the-demoniac-scryer) is a quest that requires you to defend [Demoniac Scryer](https://tbc.wowhead.com/npc=22258/demoniac-scryer) against some imps and [Fel Wardens](https://tbc.wowhead.com/npc=22273/fel-warden#abilities) for a period of time.

**Current behaviour**:
 1) Fel Wardens do not use any spells.
 2) Mobs spawn directly on top of Demoniac Scryer
 3) Demoniac Scryer regenerates to full hp upon end of combat.
 4) Sometimes the geometry of the event is incorrect (see pic 1 and 2)
 5) At the end of the event, the RP effects are horizontal rather than vertical (See video 2)

**Expected behaviour**: 
 1) Fel Wardens casts [Fireball](https://tbc.wowhead.com/spell=14034/fireball), and possibly [Frost Nova](https://tbc.wowhead.com/spell=11831/frost-nova)
 2) Mobs spawn about 5-7 yards away from the Demoniac Scryer.
 3) Demoniac Scryer retains healthpool upon end of combat.
 4) The geometry of the event should make the shape of an cross (See video 1)
 5) At the end of the event, the RP effects are vertical rather than horizontal (see video 1)

**Revision**: 1217

[Video 1: Shows Correct Geometry and Correct](https://youtu.be/d4TdDpdrbrQ?t=310)
[Video 2: Shows Incorrect Horizontal RP Effects](https://user-images.githubusercontent.com/105084838/169423834-2d87d8d2-801e-4fd4-b96a-d7e668903c20.mp4)

Pic 1
![image](https://user-images.githubusercontent.com/105084838/169423374-63b7fab5-9f65-4a88-8149-0f9964075872.png)

Pic 2
![image](https://user-images.githubusercontent.com/105084838/169423660-6ef343a8-87cf-4147-837e-b316d7620dfa.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1222.
