### ISSUE TITLE
[Quest][NPC] Breaking Down Netherock - Does not break down into shards

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#590]
**Description**: 
Netherock is an elite NPC in Netherstorm.  During combat he should break down into small shards. 

**Current behaviour**:
Netherock remains the same size with the same damage throughout the combat.

**Expected behaviour**: 
Should break down into smaller shards per https://www.youtube.com/watch?v=Je6tv_8ZJm0

**Server Revision**:

1217

**Comment by EtheriousNW** [comment]
Fixed and live on beta
