### ISSUE TITLE
[Quest][Hellfire Peninsula] From the Abyss - Multiple Issues (completable)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#594]
**Description**: During the quest [From the Abyss](https://tbc.wowhead.com/quest=10295/from-the-abyss), you are tasked with defeating [Void Baron Galaxis](https://tbc.wowhead.com/npc=16939/void-baron-galaxis) near Void Stones in Hellfire Peninsula. You summon him with [Warp Rift Generator](https://tbc.wowhead.com/item=29226/warp-rift-generator). Galaxis has two summon-able [Void Servants](https://tbc.wowhead.com/npc=19599/void-servant) using spell [Baron's Summons](https://tbc.wowhead.com/spell=34236/barons-summons).

**Current behaviour**: 
1) When you use quest item, a cast-bar appears titled: _Summon a Warp Rift in Void Ridge_
2) You can use quest item repeatedly, and the mobs never de-spawn. (See issue #591)
3) Upon using quest item, Galaxis and two servants appear immediately.
4) Galaxis never casts [Baron's Summons](https://tbc.wowhead.com/spell=34236/barons-summons). Instead the two servants immediately spawn alongside Galaxis.
5) Galaxis never sacrifices his servants.

**Expected behaviour**: 
1) When you use quest item, it should be an instant cast, not a cast-bar.
2) After using quest item, summoned mobs should de-spawn after some time if no combat is initiated.
3) Upon using quest item, Galaxis will appear about 20-30 yards into the abyss, "float/swim" over to the Void Stones, and await combat. 
4) Upon entering combat, Galaxis will cast [Baron's Summons](https://tbc.wowhead.com/spell=34236/barons-summons), which summons the two Void Servants. Alternatively, you can open with a stun and Galaxis will not summon the two Void Servants.
5) During the fight, Galaxis can sacrifice one of his servants to obtain a massive heal, possibly using the spell [Absord Life](https://tbc.wowhead.com/spell=34239/absorb-life)

**Revision**: 1217

**Comment by Emtec** [comment]
Fixed in 1219
