### ISSUE TITLE
[Spell] Saw Blade - Mobs Spam Ability Instead of Closing Range Gap

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#595]
**Description**: There are 3 mobs that use [Saw Blade](https://tbc.wowhead.com/spell=32735/saw-blade). Two of them are [Razorsaw](https://tbc.wowhead.com/npc=20798/razorsaw) and [Mo'arg Forgefiend](https://tbc.wowhead.com/npc=16946/moarg-forgefiend)

**Current behaviour**:
1) Razorsaw will spam Saw Blade if there is a ranged gap between player and Razorsaw, never moving.
2) Mo'arg Forgefiend exhibits similar behavior as Razorsaw, except he does close range gap somewhat.

**Expected behaviour**: 
1) Razorsaw should occasionally cast Saw Blade if conditions are correct. He should not spam Saw Blade and attempt to close the ranged gap.
2) Mo'arg Forgefiend should exhibit similar behavior as Razorsaw, with more emphasis on less spam and more gap-closing.

**Revision**: 1217

**Comment by Emtec** [comment]
Fixed in 1219
