### ISSUE TITLE
[NPC][Spell][Hellfire Peninsula] Forge Camp Legionaire - No Spells

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#596]
**Description**: [Forge Camp Legionaire](https://tbc.wowhead.com/npc=16954/forge-camp-legionnaire#abilities) is a felguard north of Thrallmar.

**Current behaviour**: The felguard casts no spells.

**Expected behaviour**: The felguard casts [Cleave](https://tbc.wowhead.com/spell=15496/cleave) and [Mortal Strike](https://tbc.wowhead.com/spell=32736/mortal-strike).

**Revision**:  1217

**Comment by Emtec** [comment]
Fixed in 1219
