### ISSUE TITLE
[NPC][Spell][Hellfire Peninsula] Warbringer Arix'Amal - No Flame Wave 

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#597]
**Description**: Part of the quest [Doorway to the Abyss](https://tbc.wowhead.com/quest=10392/doorway-to-the-abyss) requires you to fight [Warbringer Arix'Amal](https://tbc.wowhead.com/npc=19298/warbringer-arixamal#comments).

**Current behaviour**: Warbringer does not cast Flame Wave.

**Expected behaviour**: Warbringer does cast Flame Wave.

**Revision**: 1217

**Comment by Emtec** [comment]
Fixed in 1219
