### ISSUE TITLE
[NPC][Spell][Hellfire Peninsula] Blistering Rot - Low Debuff Time

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#598]
**Description**: [Blistering Rot](https://tbcdb.com/?spell=32722) is a spell casted by the mob [Blistering Rot](https://tbcdb.com/?npc=16901#abilities) (Confusing :D)

**Current behaviour**: The spell applies a debuff that lasts 30 seconds.

**Expected behaviour**: The spell should apply a debuff that lasts 60 seconds, rather than 30.

**Revision**: 1217

![image](https://user-images.githubusercontent.com/105084838/169498388-2e35746b-580b-4ccd-884d-b0db8f0d344b.png)
![image](https://user-images.githubusercontent.com/105084838/169498555-5d48a680-f46b-4077-8725-2b1c05963841.png)
![image](https://user-images.githubusercontent.com/105084838/169498686-2d484ead-b4b9-40d5-8598-432aa1fb55db.png)
![image](https://user-images.githubusercontent.com/105084838/169499064-5b20cbeb-3606-4771-8530-61bec8418f19.png)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/169898300-252dca28-0c75-472f-a16a-768cdee1f6a7.png)
idk works fine for me
