### ISSUE TITLE
[NPC][Hellfire Peninsula] Fulgore - Missing Spells/Abilities

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#599]
**Description**: [Fulgorge ](https://wotlk.evowow.com/?npc=18678)is a sandworm-like rare elite located in Hellfire Peninsula. It casts [Bore](https://wotlk.evowow.com/?spell=32738), a spell which is not to be confused with [Tunnel Bore](https://wotlk.evowow.com/?spell=34038). It casts [Poison](https://wotlk.evowow.com/?spell=31747), a spell which is not to be confused with [Poison Spit](https://wotlk.evowow.com/?spell=32330)

**Current behaviour**:
1) Fulgorge does not cast [Poison Spit](https://wotlk.evowow.com/?spell=32330). 
2) If you move away from Fulgorge after initiating combat, Fulgorge will exhibit no AI yet remain in combat.

**Expected behaviour**: 
1) Fulgorge casts [Poison Spit](https://wotlk.evowow.com/?spell=32330), a poison debuff that can stack over time. 
2) Fulgorge should also utilize a spell, possibly named [Tunnel Bore](https://wotlk.evowow.com/?spell=34038), which allows the worm to traverse the combat area without technically "moving"

**Revision**: 1217

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
