### ISSUE TITLE
[NPC] Kilix the Unraveler passive behavior (ambush event)

### ISSUE THREAD

**Issue by duzyizly** [Stormforge-gg/Bugtracker-Wotlk-Beta#6]
**Description**:
NPC Kilix the Unraveler is not fighting back against Anub'ar slayer and Anub'ar ambusher, same as his battleguards.
After he kills Underlord he stays passive.
https://www.wowhead.com/npc=26653/kilix-the-unraveler
https://www.wowhead.com/npc=26662/azjol-anak-battleguard
Also he stays in combat after mobs are dead (killed by player for example) - killing those mobs puts you in combat bug aswell.

There are also missing quotes from Kilix:
https://wowwiki-archive.fandom.com/wiki/Kilix_the_Unraveler

![image](https://user-images.githubusercontent.com/43931626/162323584-939cf578-374b-4fef-b133-e39ce3c88b73.png)
![image](https://user-images.githubusercontent.com/43931626/162323659-c7d3c876-c054-4b10-83aa-f170093762ea.png)

**Revision**: 
1034

**Comment by Dirtsleeper** [comment]
You can also still interact with him while he is in combat to turn in/accept quests

**Comment by Emtec** [comment]
Fixed in 1121
