### ISSUE TITLE
[Quest][Hellfire Peninsula] Marking the Path - No Mob Agro Upon Lighting Beacon

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#601]
**Description**: During the quest [Marking the Path](https://tbc.wowhead.com/quest=9391/marking-the-path#comments) {QuestID: 9391}, you are tasked with lighting three beacons with [Lit Torch](https://tbc.wowhead.com/item=23480/lit-torch) {ItemID: 23480}

**Current behaviour**: No mob agros upon lighting a beacon.

**Expected behaviour**: Upon lighting a beacon, mobs within a large distance (possibly 30-50 yards) will immediately move towards the beacon. Mobs will enter combat upon agro range and will immediately divert away from the beacon and towards the player.

**Revision**: 1217

[Video 1: Casual player PoV. Good video](https://www.youtube.com/watch?v=f9373BWgt9k&ab_channel=GameGuidesChannel)

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
