### ISSUE TITLE
[NPC][Hellfire Peninsula] Bonestripper Vulture

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#602]
@Cold-Martijn: Bonestripper Vulture {NPC ID: 16973} is exhibiting the exact same behavior as Bonestripper Buzzard in closed ticket #593 

 **Description**: Bonestripper Vulture {NPC ID: 16973} is a mob that will move to the location of a recently killed corpse, using the emote: _Bonestipper Vulture smells a fresh corpse nearby._

**Current behaviour:** If a Bonestripper Vulture is in combat, and a mob dies in close range of the vulture, the vulture will move to the location of the dead mob and then "root" itself in that location. It does not move, but will stay in combat.

**Expected behaviour**: Uncertain, possibly the bird will either move to the corpse for a brief moment, or ignore the body completely.

**Revision:** 1217

**Comment by Cold-Martijn** [comment]
cheers :)
