### ISSUE TITLE
[NPC] Shattered Hand Berserker - No Charge

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#603]
**Description**: [Shattered Hand Berserker](https://tbc.wowhead.com/npc=16878/shattered-hand-berserker#comments;mode:normal) {NPC ID: 16878} are famous for using [Charge ](https://tbc.wowhead.com/spell=35570/charge) {Spell ID: 35570} to disrupt the summoning stone at Hellfire Citadel.

**Current behaviour**: Berserkers do not cast Charge.

**Expected behaviour**: Berserkers should cast Charge, preferably upon the start of combat.

**Revision**: 1217

**Comment by FX-SF** [comment]
They do cast Charge, but very infrequently and only under certain conditions.

**Comment by Cold-Martijn** [comment]
No problem, I converted them to new SAI and added charge to spells. They will now use it when not in melee range at the start of combat. The possible repeat time I've set to about 10 seconds if i remember correctly.
