### ISSUE TITLE
[NPC][Hellfire Peninsula] Magister Aledis - missing spell, unpolished AI

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#604]
**Description**: During the quest [Arelion's Secret](https://tbc.wowhead.com/quest=10286/arelions-secret) {Quest ID: 10286}, you are tasked with subduing [Magister Aledis](https://tbc.wowhead.com/npc=20159/magister-aledis#abilities) {NPC ID: 20159}. Magister Aledis utilizes 3 spells. Two of these spells are [Pyroblast ](https://tbc.wowhead.com/spell=33975/pyroblast) {Spell ID: 33975} and [Frost Nova](https://tbc.wowhead.com/spell=11831/frost-nova) {Spell ID: 11831}.

**Current behaviour**: 
1) Magister Aledis does not cast Pyroblast.
2) After casting Frost Nova, Magister Aledis does not move.
3) Magister Aledis runs into melee range frequently.

**Expected behaviour**: 
1) Magister Aledis should cast Pyroblast, often after Frost Nova.
2) After freezing a player with Frost Nova, Magister Aledis should run and create a ranged gap between the frozen character and himself.
3) Magister Aledis should not actively attempt to enter melee combat. He should stay fixed in place, unless he has casted Frost Nova (see point 2 above) or he has no mana, which then he should enter melee combat.

**Revision**: 1217

**Comment by EtheriousNW** [comment]
Fixed and live on beta
