### ISSUE TITLE
[Spell] Fel Flames (Terrorfiend in Hellfire Peninsula)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#606]
**Description**: [Terrorfiend ](https://tbc.wowhead.com/npc=16951/terrorfiend) {NPC ID: 16951} casts [Fel Flames](https://tbc.wowhead.com/spell=37488/fel-flames) {Spell ID: 37488}, a spell that takes 2 seconds to cast, and then channels for 3 seconds.

**Current Behavior**: The spell can be "missed" by the player, canceling the channeled part of the spell

**Expected Behavior**: Regardless if the spell should or should not be "missed" by the player, the channeled part of the spell should always occur.

**Revision**: 1217

https://user-images.githubusercontent.com/105084838/169535884-1567107e-8ffc-4ce9-95b2-323cb6764f6c.mp4

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
