### ISSUE TITLE
[Quest][Hellfire Peninsula] Administering the Salve - 2 Minor Issues

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#607]
**Description**: During the quest [Administering the Salve](https://tbc.wowhead.com/quest=9447/administering-the-salve) {Quest ID: 9447}, you are required to use [Healing Salve](https://tbc.wowhead.com/item=23394/healing-salve) {Item ID: 23394} on 10x [Debilitated Mag'har Grunts](https://tbc.wowhead.com/npc=16847/debilitated-maghar-grunt#drops) {NPC ID: 16847}, "healing" them.

**Current behaviour**: 
1) Using Healing Salve creates a cast bar titled: _Quest - Healing Salve_
2) A "Healed" Debilitated Mag'har Grunt does not move. After some time it will de-spawn.

**Expected behaviour**: 
1) Using Healing Salve is instant; there is no cast time.
2) A "Healed" Debilitated Mag'har Grunt will get up and move around a bit. After some time it will de-spawn.

**Revision**: 1217

[Video of Classic Quest](https://www.youtube.com/watch?v=XjpEc9_9VS0&ab_channel=WoWQuests)

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
