### ISSUE TITLE
[NPC][Hellfire Peninsula] Shattered Hand Guard/Acolyte - Don't Run in Fear

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#608]
**Description**: [Shattered Hand Guard](https://tbc.wowhead.com/npc=19414/shattered-hand-guard) {NPC ID: 19414} and [Shattered Hand Acolyte](https://tbc.wowhead.com/npc=19415/shattered-hand-acolyte) {NPC ID: 19415} exist in Hellfire Peninsula, notably for the quest [How to Serve Goblins](https://tbc.wowhead.com/quest=10238/how-to-serve-goblins) {Quest ID: 10238}. 

**Current behaviour**: These two mobs do not run in fear.

**Expected behaviour**: These two mobs should run in fear, around 30% hp.

**Revision**: 1217

[Video Evidence of Mobs Fleeing](https://www.youtube.com/watch?v=MhaVk7dKmxw&ab_channel=GameGuidesChannel)

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
