### ISSUE TITLE
[NPC][Spell][Hellfire Peninsula] Gan'arg Sapper - Incorrect AI

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#609]
**Description**: [Gan'arg Sappers](https://tbc.wowhead.com/npc=18827/ganarg-sapper) {NPC ID: 18827} are demons located in a cave under Thrallmar. They have [Set Charge](https://tbc.wowhead.com/spell=33895/set-charge) {Spell ID: 33895} as an ability/spell in their kit.

**Current behaviour**: Upon entering combat, Sappers casts Set Charge. Set Charge summon Object (183410). This object eventually creates an explosion animation, but no damage occurs.

**Expected behaviour**: Sapper should not use Set Charge as part of his combat spell/ability kit. It should, if anything, be used outside of combat, as a Role-Playing spell animation.

**Revision**: 1217
[Video of Classic Casual playthrough](https://www.youtube.com/watch?v=5I13FsA2GIw&ab_channel=GameGuidesChannel)
[Video of Beta Server - Useless Set Charge](https://user-images.githubusercontent.com/105084838/169560615-afd84ed4-f714-4cd4-a708-5378184318f7.mp4)

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
