### ISSUE TITLE
Everyone left an rdf because it was a 4 man, requeued back into the same rdf as 4 people from a new queue

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Wotlk-Beta#61]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Everyone left our halls of lightning after finishing it as 4 man. I requeued rdf and the same 4 people got sent back to halls of lightning still missing 1 person, and others were not even in rdf queue. 
**Current behaviour**:
I queued and all previous players got sent back to the same dungeon we just left, even when not in queue.
**Expected behaviour**: 
I queue and find a new group of people who also queued and randomly get placed into a different dungeon.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in revision 1039.
