### ISSUE TITLE
[NPC][Spell] Maiden of Pain

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#610]
**Description**: [Maiden of Pain](https://tbc.wowhead.com/npc=19408/maiden-of-pain) {NPC ID: 19408} is a succubus that can buff allies with [Whipped Frenzy](https://tbc.wowhead.com/spell=34086/whipped-frenzy#used-by-npc) {Spell ID: 34086}. They can be found in Thrallmar Mine, northwest of Thrallmar in Hellfire Peninsula.

**Current behaviour**: 
1) Maiden of Pain only buffs Whipped Frenzy if in combat. 
2) Maidens do not patrol in Thrallmar Mine

**Expected behaviour**: 
1) Maiden of Pain occasionally buffs Whipped Frenzy on nearby mobs, probably every minute, even outside of combat.
2) Maidens should patrol up and down the cave.

**Revision**: 1217

[Evidence of mobs with Whipped Frenzy buff outside of combat](https://youtu.be/LP4bhhMtbtI?t=108)

![image](https://user-images.githubusercontent.com/105084838/169564893-4299de75-63e9-437d-8d62-3ac6f529b6a8.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
