### ISSUE TITLE
[NPC] Avruu - No Spells

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#611]
**Description**: [Avruu](https://tbc.wowhead.com/npc=17084/avruu) {NPC ID: 17084} is a unique birdman NPC located south of Falcon Watch in Hellfire Peninsula. He is known for casting [Judgement of Darkness](https://tbc.wowhead.com/spell=34112/judgement-of-darkness#used-by-npc) {Spell ID: 34112} and [Dark Mending ](https://tbc.wowhead.com/spell=16588/dark-mending) {Spell ID: 16588}

**Current behaviour**: Avruu casts no spells.

**Expected behaviour**: Avruu should utilize Judgement of Darkness and Dark Mending spell.

**Revision**: 1217

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
