### ISSUE TITLE
[Quest][Hellfire Peninsula] The Cleansing Must Be Stopped - (not Stormforge quality at all) (completable)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#612]
**Description**: 
1) During the quest [The Cleansing Must Be Stopped](https://tbc.wowhead.com/quest=9370/the-cleansing-must-be-stopped) {Quest ID: 9730}, you are tasked with using quest item [Signaling Gem](https://tbc.wowhead.com/item=23358/signaling-gem) {Item ID: 23358} to spawn 1x [Draenei Anchorite](https://tbc.wowhead.com/npc=16994/draenei-anchorite#abilities) {NPC ID: 16994} and 2x [Draenei Vindicator](https://tbc.wowhead.com/npc=16996/draenei-vindicator) {NPC ID: 16996}. 
2) Draenei Anchorite is known for casting [Holy Fire](https://tbc.wowhead.com/spell=17140/holy-fire) {Spell ID: 17140}.
3) Draenei Vindicators are known for casting [Divine Shield](https://tbc.wowhead.com/spell=13874/divine-shield) {Spell ID: 13874}, [Hammer of Justice](https://tbc.wowhead.com/spell=13005/hammer-of-justice) {Spell ID: 13005}, [Seal of Command](https://tbc.wowhead.com/spell=33127/seal-of-command) {Spell ID: 33127}, and [Seal of Command](https://tbc.wowhead.com/spell=20424/seal-of-command) {Spell ID: 20424}

**Current behaviour**:
1) Draenei Anchorite never casts Holy Fire
2) Draenei Vindicator never casts any spells.
3) Upon using Signaling Gem, three Draenei immedietaly spawn, incorrectly.
4) You can pull each of the three spawned Draenei individually without pulling the other two.
5) You can use Signaling Gem multiple times and the mobs never de-spawn (see #591 for example)

**Expected behaviour**: 
1) Draenei Anchorite should cast Holy Fire (and possibly a healing spell)
2) Draenei Vindicator should cast Hammer of Justice, Divine Shield, and Seal of Command(s)
3) Upon using Signaling Gem, three Draenei spawn a large distance away, taking time to walk a particular path to a particular location.
4) Pulling any of these three draenei will trigger the other two to enter combat as well.
5) Mobs should de-spawn after a set amount of time so multiple copies do not flood the server.

**Revision**: 1217

[Video 1: Shows all Vindicator spells and Holy fire from Anchorite very clearly, as well as pathing.](https://youtu.be/LRzsTmB5ZHE?t=93)

**Comment by Evolvee** [comment]
fixed in next rev

**Comment by FX-SF** [comment]
holy shit you guys are quick
