### ISSUE TITLE
[NPC][Howling Fjord] Daggercap Hammerhead

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#616]
**Description**: 
Its a [Shark](https://www.wowhead.com/npc=23785/daggercap-hammerhead) located in Howling Fjord

**Current behaviour**:
There is no shark below the deck (ship during the quest [The New Plague](https://www.wowhead.com/quest=11167/the-new-plague) )

**Expected behaviour**: 
There should be 1 shark below the deck (81.0 35.6) according to this [Video](https://youtu.be/NzbuYKH9YHI?t=68) and this comment posted at wowhead 
![image](https://user-images.githubusercontent.com/4455568/169617956-d4fa6a4c-e55b-4334-b7c1-9ce6eddfafa8.png)

**Revision**: 
1217

**Comment by Tereneckla** [comment]
Fixed
