### ISSUE TITLE
[NPC] Thornfang Ravager/Venomspitter - (shows hidden spell aura)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#617]
**Description**: Thornfang Ravager and Thornfang Venomspitter are two mobs found during the quest Keeping Thornfang Hill Clear! They have buff on them named Thorns
[Quest ID: 10159, Keeping Thronfang Hill Clear!](https://www.wowhead.com/quest=10159/keep-thornfang-hill-clear)
[NPC ID: 19349, Thornfang Ravager]( https://tbc.wowhead.com/npc=19349/thornfang-ravager)
[NPC ID: 19350, Thornfang Venomspitter](https://tbc.wowhead.com/npc=19350/thornfang-venomspitter)
[Spell ID: 22696, Thorns](https://tbc.wowhead.com/spell=22696/thorns)

**Current behaviour**: Thorns buff exists, and it is visable (See Picture 1). Mage can spellsteal and shaman can purge.

**Expected behaviour**: Thorns buff exists, but it should not be visable (See Video 1) Mage cannot spellsteal and shaman cannot purge.

**Revision**: 1217

Picture 1:
![image](https://user-images.githubusercontent.com/105084838/169619412-f72469a9-2133-45a0-88fd-23993dccdf64.png)

additional note: using idTip addon, I determined Thorn spell ID is 22696. On Wowhead, Spell ID 22696 is not casted by Thornfangs. 

Video 1:
This is earliest video I could find on Google using _"Keeping Thornfang Hill Clear!"_ as the search word. Only 1 video appeared, Cata era: [Keeping Thornfang Hill Clear!](https://youtu.be/hhW8UolhrRA?t=2015). You can see in this video the warlock's minion receiving 39 or 40 damage often. This is the spell Thorns. It is an invisible buff, but they still have it.

**Comment by Wolffenstein** [comment]
Fixed in rev 1241.
