### ISSUE TITLE
Group member was queued for RDF, got instance he was locked to, can't teleport or walk in

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Wotlk-Beta#62]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Group member was queued for RDF, got instance he was locked to, can't teleport or walk into the dungeon
**Current behaviour**:
as above
**Expected behaviour**: 
Either not be able to RDF queue for the dungeon hes locked for or be able to teleport into dungeon
**Revision**:

**Comment by Wolffenstein** [comment]
Should be fixed after revision 1039.
