### ISSUE TITLE
[Spell][Item] Devastate / Glyph of Sunder Armor - No Longer Effecting Devastate

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#620]
**Description**: 
Glyph of sunder armor should function with devastate and apply an additional sunder armor to another target in front of the warrior.  In addition, when used with Glyph of Devastate it should apply two stacks to an additional target in front of the warrior.

https://www.mmo-champion.com/threads/619134-Glyph-of-Sunder-Armor-Devestate - Original Discussion
http://forum.warmane.com/showthread.php?t=358529 - Warmane secondary source.

**Current behaviour**:
Currently only applies sunder armor to the main target.   Glyph of devastate currently increases the number of sunder armors on the main target but does not add any to the secondary target.

https://streamable.com/rpcvoe

**Expected behaviour**: 
A single stack of sunder armor should be applied to a secondary target when using devastate with glyph of sunder armor and should apply two stacks of sunder armor to a secondary target if used with glyph of devastate and glyph of sunder armor.

**Revision**: 
1217

**Comment by NatsumeLily** [comment]
Currently "Glyph of Sunder Armor" is not working. It should work with Devastate too. 
Currently "Glyph of Devastate" is working. 

They should not stack like that. If you have them both learned, the correctly interaction is

2 Sunders on the primary target and
1 Sunder on another target.

**Comment by Ceago** [comment]
> 

Thanks for the clarification.  That sounds correct to me and is corroborated by the mmo-champion thread.

**Comment by Wolffenstein** [comment]
So what works and what doesn't? im confused

**Comment by NatsumeLily** [comment]
Glyph of Sunder Armor

It should work with the sunder armor effect Devastate does.

**Comment by Wolffenstein** [comment]
Fixed in rev 1282.
