### ISSUE TITLE
[NPC][Dungeon] The Nexus - Crystalline Tender

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#623]
**Description**: 
Crystalline Tender's currently begin casting Tranquility almost immediate after they begin melee attacking the player.  Per https://youtu.be/pySQvQey1f8?t=651 they should begin casting tranquility at approx. 50% health.  Seems pretty consistent on each pull.

**Current behaviour**:
NPC begins casting it's Tranquility almost directly following the pull.
See - https://streamable.com/r5n3bv

**Expected behaviour**: 
NPC should cast tranquility closer to approximately 50% health.

**Revision**: 
1217

**Comment by Wolffenstein** [comment]
Fixed in rev 1238.
