### ISSUE TITLE
[Quest] Stranglethorn Fever

### ISSUE THREAD

**Issue by Smokey7777** [Stormforge-gg/Bugtracker-Wotlk-Beta#626]
**Description**: 
To complete the quest Stranglethorn Fever (https://wotlkdb.com/?quest=348) you must turn in the miniquest Stranglethorn Fever (https://wotlkdb.com/?quest=349). Upon turning in, several waves of gorillas will spawn, culminating in Mokk who drops the quest item for the aforementioned quest.
**Current behaviour**:
You can turn in the miniquest but nothing spawns.
**Expected behaviour**: 
Wowhead comment from patch 1.12: "Once you click the "complete quest" button in the quest entry box, the troll will begin spawning gorillas that will run up the hill at you. The first wave is 3 enraged gorillas (level 42), the second wave is 4 enraged gorillas and a named gorilla (level 43). The third, and final wave, is 5 enraged gorillas and Mokk himself (level 44)."
My comment: I am unsure if it was nerfed in wotlk to spawn less, but it should definitely spawn something.
**Revision**: 
1217

**Comment by Evolvee** [comment]
fixed in next rev
