### ISSUE TITLE
[Quest] The Bloodsail Buccaneers 

### ISSUE THREAD

**Issue by Smokey7777** [Stormforge-gg/Bugtracker-Wotlk-Beta#627]
**Description**: 
Multiple quests share the same name, but in this one, where you need to kill ten and get the charts and orders (https://wotlkdb.com/?quest=604), the charts do not spawn. The way the quest is supposed to work is (wowhead comment): "The CHARTS spawn at either the 3 tent camp on some crates near the eastmost tent, in the boat, or at the one tent camp to the northeast. The ORDERS spawn on a stool in the north section of the 3 tent camp, in the tent of the 1 tent camp, or in the boat."
**Current behaviour**:
The orders spawn repeatedly on the boat spawn. The charts do not spawn at all.
**Expected behaviour**: 
Both spawning, preferably in multiple areas. 
**Revision**: 
1217

**Comment by Evolvee** [comment]
fixed in next rev

**Comment by zetryz** [comment]
1

**Comment by Evolvee** [comment]
Did you check all the possible locations? Its 4 for each of the chart

**Comment by Godmatik** [comment]
I believe it's a long respawn issue, GMs have been manually spawning them these past couple of days
