### ISSUE TITLE
[NPC]Scalder (doesn't close ranged gap)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#628]
**Description**: [Scalder ](https://www.wowhead.com/npc=25226/scalder) {NPC ID: 25226} is a water elemental. Located in Borean Tundra, she is needed to complete the quest [Learning to Communicate](https://www.wowhead.com/quest=11571/learning-to-communicate) {Quest ID:11571}. She can cast [Scalding Blast](https://www.wowhead.com/spell=50257/scalding-blast) {Spell: 50257}

**Current behaviour**: Often, Scaldar will not close the ranged gap between her and her target, even with 0 mana. This usually occur after she casts Scalding Blast.

**Expected behaviour**: Scaldar should be closing the ranged gap between her and her target, even after Scalding Blast.

**Revision**: 1217

Video of Stormforge Server. Shows 2 Scalding Blasts and no closing of melee gap.
https://user-images.githubusercontent.com/105084838/169665188-a516ae9a-8a6c-4a83-8e52-f11116566e64.mp4

Videos of the Past:
[Shows movement of Scalder (2015)](https://youtu.be/NP0tFn95w3k?t=34)
[Shows movement of Scalder (2017)](https://www.youtube.com/watch?v=8jO852bDaEg&ab_channel=Finom)

**Comment by FX-SF** [comment]
This honestly may be a normal feature, since it takes a full 15 seconds for him to cast this spell, and most will have the mobs dead by then.

**Comment by Wolffenstein** [comment]
Fixed in rev 1240.
