### ISSUE TITLE
Able to "Join as Party" rdf queue when the group is already full and we get teleported into a new id of the same instance

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Wotlk-Beta#63]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Able to "Join as Party" rdf queue when the group is already full and we get teleported into a new id of the same instance
**Current behaviour**:
as above
**Expected behaviour**: 
The Join as Party button should not be an option when we are a 5 man group
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in revision 1039.
