### ISSUE TITLE
[OBJECT] The Black Shield

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#630]
Black Shield object with starts quest "The Black Shield" is placed incorrectly inside of the structure, most of it is hidden as well as the quest exclamation point as a result.

https://classic.wowhead.com/object=20992/black-shield

![Black Shield](https://user-images.githubusercontent.com/37913400/169666478-f210452b-be46-408b-9b14-6677f2ef7454.png)

**Comment by EtheriousNW** [comment]
improved somehwat, can fix properly when editor gets support for it.
