### ISSUE TITLE
[Mage][Talent][Spell] Fingers of Frost stacks get consumed too fast (with no delay)

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#634]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  There should be a delay befor FoF stack is consumed so you still should be able to do shatter combo with just one stack of FoF. The spell that is already in flight when you get the proc shouldn't get affected by FoF buff nor consume it.

**Current behaviour**: FoF stacks get consumed too fast so you can't do Frostbolt>DF/shatter combo with just one FoF stack what's not correct. It's pretty big problem for mages because doing Frostbolt>DF/shatter combo with just 1 FoF stack is a common WotLK frost mage trick.

**Expected behaviour**: There should be a DELAY befor FoF stack is consumed.

Proof that FoF stacks should NOT get instantly consumed on cast - https://youtu.be/8ET2Ct9_Ma8?t=1m6s ; https://www.youtube.com/watch?v=4X-GB9GB7Ic. In these videos you can see mage doing Frostbolt > DF with just one FoF stack. Watch in slow motion.

**Revision**: 1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1237.
