### ISSUE TITLE
[NPC][Howling Fjord] North Fleet Soldier

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#639]
**Expected behaviour**: 
[North Fleet Soldier](https://www.wowhead.com/npc=23793/north-fleet-soldier) should run away in fear at low health.
Don't know what about others like [Marksman](https://www.wowhead.com/npc=23946/north-fleet-marksman), [Medic](https://www.wowhead.com/npc=23794/north-fleet-medic) [Sailor](https://www.wowhead.com/npc=23866/north-fleet-sailor)
I remember it was hard to do escort quest because they were running everywhere.

**Revision**: 
1225

**Comment by Cold-Martijn** [comment]
unassigned because im going to focus on another part of Howling Fjord first, srry :) might come back to this later.

**Comment by Tereneckla** [comment]
none of them fled in my tests
