### ISSUE TITLE
[Item] Copper Racer (no action, no de-spawn)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#640]
**Description**: Jepetto Joybuzz and Clockwork Assistant in Dalaran sells [Heavy Copper Racer](https://www.wowhead.com/?item=44601), [Zippy Copper Racer](https://www.wowhead.com/item=44599/zippy-copper-racer#comments), and [Thrusty Copper Racer](https://www.wowhead.com/item=44482/trusty-copper-racer#comments).

**Current behaviour**: All Copper racers spawn and do nothing. They never de-spawn.

**Expected behaviour**: Hard to say. I could not find video evidence. I did find comments:
1) A toy racer will appear and race forwards 20 yards.  Then it stops and disappears.

4) If there isn't 20 yards ahead of the player, either one or two is meant to occur::
 A) A message saying "No path available" occurs.  
 B) the racer will spawn, sit/do nothing for a few seconds, then de-spawn.

2) From a post in 4.1.0 - When you place this item and have [ Lil' XT](https://www.wowhead.com/item=54847/lil-xt) out, Lil' XT will shoot a 'rocket' at the zippy racer and destroy it.

**Revision**: 1225

Jepetto Joybuzz           (NPC ID: 29478)
Clockwork Assistant (NPC ID 29716)
Heavy Copper Racer (Item ID: 44601)
Zippy Copper Racer (Item ID: 44599)
Thrusty Copper Racer (Item ID: 44482)
Lil' XT (Item ID: 54847)
![WoWScrnShot_052122_140949](https://user-images.githubusercontent.com/105084838/169670745-b66b99b0-781a-4710-bcac-ad860110d121.jpg)

**Comment by Emtec** [comment]
Fixed in 1243
