### ISSUE TITLE
[Core] Darkmoon Faire

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#645]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Darkmoon Faire doesn't appear to exist on the calendar. Idk if it's just not implemented at all (will be a problem since pre raid bis trinkets for melee dps is a darkmoon card, no?) or if it's just not showing on the calendar, but yeah, something is off.

**Comment by Wolffenstein** [comment]
Fixed in rev 1323.
