### ISSUE TITLE
[Item] Grindgear Toy Gorilla (no movement/jump animations/long de-spawn)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#646]
**Description**: [Grindgear Toy Gorilla](https://www.wowhead.com/item=44481/grindgear-toy-gorilla#comments) is a consumable item you can buy from a toy store in Dalaran. It spawns the NPC [Grindgear Toy Gorilla](https://www.wowhead.com/npc=32345/grindgear-toy-gorilla).

**Current behaviour**: Upon using Item , NPC spawns and does nothing. It does not move, nor does it do a 'Jungle Jumping Action'. It de-spawns after 1 minute.

**Expected behaviour**: Upon using Item, NPC should spawn and begin to move around the area. After 15 full seconds, NPC will do a leaping 'Jungle Jumping Action' to wherever the player, seemingly 'as long as you can still /target it. Nigh impossible to outrange'. After 20 seconds, the NPC will de-spawn

**Revision**: 1225

**ID's:**
[Item IDL 44481](https://www.wowhead.com/item=44481/grindgear-toy-gorilla#comments)
[Spell ID: 60832](https://www.wowhead.com/spell=60832/grindgear-toy-gorilla)
[NPC ID: 32345](https://www.wowhead.com/npc=32345/grindgear-toy-gorilla)

**Video Evidence**:
[Video from 2017, still relevant, good quality](https://youtu.be/Jb-8kX_FV2E?t=35)

**Comment by Emtec** [comment]
Fixed in 1127
