### ISSUE TITLE
Leaving group after completing halls of lightning, group members were teleported to graveyard outside instead of where we accepted the queue

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Wotlk-Beta#65]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Leaving group after completing halls of lightning, group members were teleported to graveyard outside instead of where we accepted the queue, we did die in the dungeon and get res'd inside
**Current behaviour**:
as above
**Expected behaviour**: 
Get put back where we accepted the queue
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in revision 1039.
