### ISSUE TITLE
[NPC] Uda the Beast (no reaction to /kiss)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#652]
**Description**: [Uda the Beast](https://www.wowhead.com/npc=31557/uda-the-beast#comments) is the Innkeeper at Sunreaver's Sanctuary.

**Current behaviour**: Uda does not react to the /kiss emote

**Expected behaviour**: If you do /kiss emote at Uda she will laugh and flex.

**Revision**:  1225

Uda the Beast [NPC ID: 31557](https://www.wowhead.com/npc=31557/uda-the-beast#comments)

![image](https://user-images.githubusercontent.com/105084838/169687818-7bc5aa76-7ab1-4e96-9cbb-cd4b26069374.png)

Response to Kiss 2011 Image:
![image](https://user-images.githubusercontent.com/105084838/169687858-94b150a3-cf00-48b5-8e9b-428d70020e04.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
