### ISSUE TITLE
([Spell][DK] Army of the Dead)

### ISSUE THREAD

**Issue by HiKO0711** [Stormforge-gg/Bugtracker-Wotlk-Beta#655]
On Frost Specialization sometimes nothing happens after using the Spell-
It only sometimes happens and i cant find a reason for it so far.

**Comment by Cold-Martijn** [comment]
on wotlk talents are quite flexible :)
can you screenshot your talent tree? perhaos it has nothing to do with it, but it might help.

**Comment by Cold-Martijn** [comment]
It was closed as completed HiKO :) usually that means its fixed.
