### ISSUE TITLE
[Quest][NPC](Grizzly Hills) Filling the Cages/Budd

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#656]
**Description**: 
You can't have [Budd](https://www.wowhead.com/npc=26422/budd) (NPC ID : 26422) as pet if you are mounted during [Filling the Caged](https://www.wowhead.com/quest=11984/filling-the-cages) you have to wait his respawn, seems like a minor issue, but actually since the item has 15 charges for 20 mobs to kill, it make the quest pretty hard to complete

**Current behaviour**:
https://www.youtube.com/watch?v=7LsRF8Y6AJY
**Expected behaviour**: 
https://www.youtube.com/watch?v=o4qNh6xqNis
**Revision**: 
1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
