### ISSUE TITLE
[Quest][Item](Grizzly Hills) Seared Scourge/Mack's Dark Grog 

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#657]
**Description**: 
[Mack's Dark Grog](https://wotlkdb.com/?item=35908) you get is supposed to put an AoE on the ground that burn [Famished Scourge Troll (NPC ID 26570)](https://www.wowhead.com/npc=26570/famished-scourge-troll), they are supposed to burn when walking on it then die, it's not a minor issue since the item has 15 charges and you need to kill 20 mobs with it

**Current behaviour**:
Trolls are walking randomly, the item insta kill them and the fire on the ground don't burn them
https://youtu.be/jup-l-CRBz8

**Expected behaviour**: 
Trolls are running randomly, the item burn troll touched by it or walking in the fire and die after few seconds
https://youtu.be/ecT30eRpico

**Revision**: 
1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
