### ISSUE TITLE
[Spell] Fishing (2 versions in spellbook)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#661]
**Description**: 

- You can obtain Fishing Spell. 

**Current behaviour**: 

- Upon learning Max Fishing from PTR Paladin, your spellbook displays 2 versions of Fishing Spell: 
   1)  [Spell ID: 51294](https://www.wowhead.com/spell=51294/fishing)
   2) Spell ID: 62734
- Spell ID: 62734 does not exist on Wowhead. (possibly a PTR buff)

**Expected behaviour**: 

- There should only be [Spell ID: 51294](https://www.wowhead.com/spell=51294/fishing)

**Revision**: 

- 1225

Video of Spell ID: 62734 being casted without a fishing pole.

https://user-images.githubusercontent.com/105084838/169718515-63dda052-d3a0-4031-80f9-cff3a9a8f6b0.mp4

**Comment by Wolffenstein** [comment]
ptr only bug
