### ISSUE TITLE
[NPC] Innkeeper Coryth Stoktron

### ISSUE THREAD

**Issue by Smokey7777** [Stormforge-gg/Bugtracker-Wotlk-Beta#662]
**Description**: 
https://wotlkdb.com/?npc=18907 
**Current behaviour**:
Currently facing the wrong direction spamming the /ask emote on loop
**Expected behaviour**: 
Standing there like a normal NPC.
**Revision**: 
1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
