### ISSUE TITLE
[NPC] Naka

### ISSUE THREAD

**Issue by Smokey7777** [Stormforge-gg/Bugtracker-Wotlk-Beta#663]
**Description**: 
https://wotlkdb.com/?npc=18993
**Current behaviour**:
Currently facing the wrong direction spamming the /ask emote on loop (same exact issue as previous ticket for the innkeeper).
**Expected behaviour**: 
Standing there like a normal NPC.
**Revision**: 
1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
