### ISSUE TITLE
[Item] Windle's Lighter (doesnt light lamp/missing sound effect)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#665]
**Description**: [Windle's Lighter](https://www.wowhead.com/item=44435) {Item ID: 44435} is an item you can buy from [Windle Sparkshine](https://www.wowhead.com/npc=29261/windle-sparkshine). The lighter casts the spell [Light Lamp](https://www.wowhead.com/spell=60535/light-lamp)

**Current behaviour**: The Lighter will only light up the Wall Scones. It will not light the Floating Lamps (Out of Range).
The Lighter does not utilize [Holy Impact Uber Chest sound effect](https://www.wowhead.com/sound=10014/holy-impactdd-uber-chest) on the Wall Scones

**Expected behaviour**: The Lighter will light up both the Wall Scones and the Floating Lamps.
The Lighter should utilize [Holy Impact Uber Chest sound effect](https://www.wowhead.com/sound=10014/holy-impactdd-uber-chest)  on the Wall Scones

**Revision**: 1225

Additional Evidence:

- [WotLK-era Video showing Floating Lamps being lit. ](https://www.youtube.com/watch?v=zFZZZDRyxAg)

- Beta exhibits correct behavior with Wall Scones. (Picture from wowhead) 

![image](https://user-images.githubusercontent.com/105084838/169720065-86229ae0-2c07-4e55-87a0-ef8cde7e8617.png)

- Beta does NOT exhibit correct behavior with Floating Lamps (Picture from wowhead)

![image](https://user-images.githubusercontent.com/105084838/169720052-9e1077b8-d005-41b0-8c44-9897b5505c25.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
