### ISSUE TITLE
[NPC] Ninsianna (wont /dance or chat)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#666]
**Description**:  [Ninsianna](https://www.wowhead.com/npc=29529/ninsianna#comments) {NPC ID: 29529} is a Night Elf in Dalaran. She is known for dancing with players and giving advice.

**Current behaviour**: 
If you perform the /dance emote while targeting Ninsianna, she will do nothing.

**Expected behaviour**: 
If you perform the /dance emote while targeting Ninsianna, she should say the following dialog: 
 
        - "Not bad, though some additional schooling wouldn't hurt! Here, watch my hips... like so!"
Several seconds after her dialog, she will perform the /dance emote herself.

**Revision**: 1225

Evidence: [Wowhead comments](https://www.wowhead.com/npc=29529/ninsianna#comments)

Picture from Wowhead of dance:
![image](https://user-images.githubusercontent.com/105084838/169721707-0fce3ce4-2697-4c48-9005-a6d3be36054b.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
