### ISSUE TITLE
[NPC] Zidormi (doesn't hover)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#668]
**Description**: [Zidormi](https://www.wowhead.com/npc=31848/zidormi#screenshots:id=165422) {NPC ID: 31848} is an NPC located in the Violet Citidel of Dalaran. She is a Bronze Dragon in disguise.

**Current behaviour**: Zidormi stands on the ground.

**Expected behaviour**: Zidormi should hover just above the ground.

**Revision**: 1225

![image](https://user-images.githubusercontent.com/105084838/169727033-642618ea-e7e3-4b17-aa28-61789f4fe294.png)

[Wowhead Pictures. 7-9 different pictures](https://www.wowhead.com/npc=31848/zidormi#screenshots). Some examples:
![image](https://user-images.githubusercontent.com/105084838/169726747-83b9a883-250f-45be-b1d6-0c356b1eabfb.png)
![image](https://user-images.githubusercontent.com/105084838/169726767-56dafb44-ad7f-49f8-868a-2297a8928758.png)
![image](https://user-images.githubusercontent.com/105084838/169726774-070410cb-bac5-4147-b874-50c4999d2769.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
