### ISSUE TITLE
[NPC] Image of Archmage Modera (wrong dialog /w horde player)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#669]
**Description**: [Archmage Modera](https://www.wowhead.com/npc=26673/image-of-archmage-modera) {NPC ID: 26673} is an Kirin-Tor NPC in Dragonblight. As a Horde character, you can right click to interact with her.

**Current behaviour**: 
![image](https://user-images.githubusercontent.com/105084838/169731970-0d8f6aca-a0e3-45a1-9eb0-18e7235ff68f.png)

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/105084838/169731238-39f92c30-e6fd-45ec-8a06-cdd92e166aa4.png)

**Revision**: 1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
