### ISSUE TITLE
[NPC] Underbelly Croc (doesn't lick chop emote)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#670]
**Description**: [Underbelly Croc](https://www.wowhead.com/npc=32441/underbelly-croc#comments) {NPC ID: 32441} is an encaged alligator in The Underbelly of Dalaran. He moves back and forth.

**Current behaviour**: Underbelly Croc never emotes.

**Expected behaviour**: Upon moving close to the Underbelly Croc, it will perform the emote: 
       `"Underbelly Croc stares at you hungrily as he licks his chops."`

**Revision**: 1225

Evidence:

[Wowhead comments](https://www.wowhead.com/npc=32441/underbelly-croc#comments)
![image](https://user-images.githubusercontent.com/105084838/169740343-896c1b92-a45e-48d2-b48d-c461cf65da98.png)
![image](https://user-images.githubusercontent.com/105084838/169740381-ddbb6283-05af-4f63-8a1b-596afbe4e458.png)
![image](https://user-images.githubusercontent.com/105084838/169740411-5861fb62-a177-410d-938b-01d6b1041efe.png)
![image](https://user-images.githubusercontent.com/105084838/169740503-8f14de3f-6155-4147-a7a0-72d9eefa378d.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
