### ISSUE TITLE
[Quest][Borean Tundra] Bring 'Em Back Alive

### ISSUE THREAD

**Issue by Smokey7777** [Stormforge-gg/Bugtracker-Wotlk-Beta#671]
**Description**: 
The quest involves finding sick kodo and using the quest item on them, which cures them and lets you ride them. 
**Current behaviour**:
While doing the quest, sometimes the kodo becomes sick while you are riding them. NOTE: Only certain spawns of kodo do this. I tested the same spawn twice, and after five seconds it became sick both times. A different spawn tested twice did not get sick once in two minutes. If the kodo gets sick, the only way out is to wait for 2 mins or leave vehicle.
https://imgur.com/a/geOIdgP debuff id either https://wotlkdb.com/?spell=46708 or https://wotlkdb.com/?spell=45771
**Expected behaviour**: 
The kodo shouldn't get sick again. ADDITONALLY: There should be a ten minute timer on the quest, as per wowhead comments: 
"By 560905 on 2010/05/08 (Patch 3.3.3)		
Dont forget about the time limit (10 minutes to return all 8 kodos)."
**Revision**: 
1225

**Comment by Smokey7777** [comment]
Quick addendum: The time minute timer is already in. It just didn't show up for some reason, but the quest failed after ten minutes and picking it back up gives a proper timer.

**Comment by Wolffenstein** [comment]
Fixed in rev 1239.
