### ISSUE TITLE
[Quest=12255][Spell=48619] (Voldrune) Flame Breath from Flamebringer "vehicle" not working properly

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#673]
**Description**: 
During the quest [The Thane of Voldrune](https://www.wowhead.com/quest=12255/the-thane-of-voldrune) you control [Flamebringer](https://www.wowhead.com/npc=27292/flamebringer) to kill [Thane Torvald Eriksson](https://www.wowhead.com/npc=27377/thane-torvald-eriksson), his spell [Flame Breath](https://www.wowhead.com/spell=48619/flame-breath) ID : 48619 do not damage [Thane Torvald Eriksson](https://www.wowhead.com/npc=27377/thane-torvald-eriksson) if you don't aim the ground

**Current behaviour**:
https://www.youtube.com/watch?v=bLQm4cWWVb8
**Expected behaviour**: 
https://youtu.be/mSNhjfkCWo4?t=38
**Revision**: 
1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
