### ISSUE TITLE
[Quest=12296][NPC=27482] Wounded Westfall Infantry

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#675]
**Description**: 
During the quest[ Life or Death](https://www.wowhead.com/quest=12296/life-or-death#) Once you used [Renewing Bandage](https://www.wowhead.com/item=37576/renewing-bandage) (ID=37576) if they meet horde [Wounded Skirmisher](https://www.wowhead.com/npc=27463/wounded-skirmisher) (ID=27463) they attack them, but Wounded Skirmisher don't fight back

Server behavior :
https://www.youtube.com/watch?v=cIJ-nlOgelU

Normal behavior :
https://youtu.be/6tvr3wxqCso?t=54

**Revision**: 
1225

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
