### ISSUE TITLE
[Quest=12070][NPC] Iron Rune Avenger vehicle animation bug

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#677]
During [Rallying the Troops](https://www.wowhead.com/quest=12070/rallying-the-troops) when [Iron Rune Avenger](https://www.wowhead.com/npc=26786/iron-rune-avenger) spawn the vehicle quickly disappear during his animation 

https://youtu.be/ak6HMuzKYg4

**Revision**: 
1225

**Comment by Emtec** [comment]
Fixed in 1251
