### ISSUE TITLE
[Item] Gnomish Flame Turret (no fire damage)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#678]
**Description**: [Gnomish Flame Turret](https://www.wowhead.com/item=23841/gnomish-flame-turret) {Item ID: 23841} is an engineering item. Using this item places a NPC on the ground also named [Gnomish Flame Turret](https://www.wowhead.com/npc=17458/gnomish-flame-turret) {NPC ID: 17458} . This NPC is known for attacking enemies with fire damage, possibly with the spell [Flame Cannon](https://www.wowhead.com/spell=30527/flame-cannon) {Spell ID: 30527}

**Current behaviour**: Upon placing item on the ground, Flame Turret targets any nearby mobs. It does nothing for some time and then de-spawns.

**Expected behaviour**: Upon placing item on the ground, Flame Turret should target any nearby mobs and channel a cone-like fire attack, possibly [Flame Cannon](https://www.wowhead.com/spell=30527/flame-cannon). After some time, it should de-spawn.

**Revision**: 1242

**Video Evidence**:
[2008 video of the turret. shows ability only once](https://youtu.be/qawuMAd0XuE?t=26).

**Comment by Emtec** [comment]
Fixed in 1251
