### ISSUE TITLE
[NPC] Image of Archmage Vargoth

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#679]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Follow up to https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/654

Mostly works now, except maybe the placement of Vargoth and also:

1. He does not react to /sexy
2. He incorrectly flexes when you dance.
 
 
He should laugh when you dance and flex when you /sexy him.

**Comment by Wolffenstein** [comment]
Fixed
