### ISSUE TITLE
[DUNGEON][NPC] Drak'Tharon Keep

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#68]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Dungeon works well for the most part but few NPCs are bugged.

**Current behaviour**:

1) Risen Drakkari Soulmage seems to be missing Blood Siphon ability. Maybe he didn't use it cause I was testing alone. https://www.wowhead.com/npc=26636/risen-drakkari-soulmage
2) Risen Drakkari Bat Rider missing Impale ability. https://www.wowhead.com/npc=26638/risen-drakkari-bat-rider
3) Risen Drakkari Handlers not spawning Drakkari Raptor Mount after they are aggroed and dismount. https://www.wowhead.com/npc=26637/risen-drakkari-handler https://www.wowhead.com/npc=26824/drakkari-raptor-mount
4) Drakkari Guardian and Scourge Brute on the right aren't fighting each other correctly. https://www.wowhead.com/npc=26620/drakkari-guardian https://www.wowhead.com/npc=26623/scourge-brute
5) Drakkari Shamans are oom from fighting scourge. https://www.wowhead.com/npc=26639/drakkari-shaman

**Expected behaviour**: Enemy NPCs should use their abilities and here's how final corridor and stairs area should work - https://youtu.be/Z5mrrnPvbo0?t=773.

**Revision**: 1040

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/162599584-3b6f2a39-dbd1-4d72-8be8-fa379b8775f7.png)
It's a ranged ability and he doesn't use it immediately on aggro, so if his main target is in melee he won't use it.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
