### ISSUE TITLE
[Core] Need before Greed loot system

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#680]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: #588 related. Was only half fixed. Need before Greed loot system rules are still bugged. 

In 3.3.0 the system was given new rules.
![image](https://user-images.githubusercontent.com/15247730/169928625-14dfb244-5dc8-4346-9176-dae74fd07acf.png)

**Need Before Greed rules should be (these are for deciding if you can need the item) -**
1. The class must be able to equip the item.
3.  Pure melee will be unable to roll on spell power items.
4. Classes are limited to their dominant armor type.
5. Players will be able to roll on items with a required level higher than player's current level.

**Confirmed restrictions**
1. Players can't roll need on frozen orbs.

There were some more restrictions added to the wiki page in Cata but don't know if they apply in wotlk.
![image](https://user-images.githubusercontent.com/15247730/169928690-8cee1eca-92b8-4f67-8e9d-940e8cfb42dc.png)

**Revision**: 1242

**Comment by Wolffenstein** [comment]
Fixed in rev 1304.
