### ISSUE TITLE
[Quest][Item](Grizzly Hills) Seared Scourge/Mack's Dark Grog

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#683]
https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/657

[Famished Scourge Troll (NPC ID 26570)](https://www.wowhead.com/npc=26570/famished-scourge-troll) are now running

[Mack's Dark Grog (ID : 35908)](https://wotlkdb.com/?item=35908) doesn't insta kill them

But

[Famished Scourge Troll (NPC ID 26570)](https://www.wowhead.com/npc=26570/famished-scourge-troll) hit by [Mack's Dark Grog (ID : 35908)](https://wotlkdb.com/?item=35908) don't have the burning FX when hit

[Famished Scourge Troll (NPC ID 26570)](https://www.wowhead.com/npc=26570/famished-scourge-troll) are still not burned by flame AoE [Mack's Dark Grog (ID : 35908)](https://wotlkdb.com/?item=35908) leave on the ground

Revision : 1242

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
