### ISSUE TITLE
[NPC] Segacedi (fish out of water)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#685]
**Description**: [Segacedi](https://www.wowhead.com/npc=32664/segacedi#screenshots) {NPC ID: 32664} is a shark in The Underbelly of Dalaran.

**Current behaviour**: [Segacedi ](https://www.wowhead.com/npc=32664/segacedi#screenshots)can be leashed onto land.

**Expected behaviour**: [Segacedi ](https://www.wowhead.com/npc=32664/segacedi#screenshots)should be limited to only the water.

**Revision**: 1252

https://user-images.githubusercontent.com/105084838/170119729-978f0c71-d1af-4573-966a-4fb6f4cb0027.mp4

**Comment by NatsumeLily** [comment]
This is blizzlike.

**Comment by Vishiswaz** [comment]
It's a funny blizzlike bug with no severe consequences that I can think of. I say keep it in, for flavor.

**Comment by FX-SF** [comment]
![image](https://user-images.githubusercontent.com/105084838/170345949-5024ee72-a5c2-4226-8e2e-836780eb6c45.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1270.
