### ISSUE TITLE
[NPC][Howling Fjord] Iskaal Refugee

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#693]
**Current behaviour**:
[Iskaal Refugee](https://www.wowhead.com/npc=24754/iskaal-refugee#comments)There is once pack of them, they just have random movement
![image](https://user-images.githubusercontent.com/4455568/170142811-5b25e54d-d055-408f-bff7-3e5671ca763c.png)

**Expected behaviour**: 
They should have waypoints.
We can see this on [Video](https://youtu.be/TEHVuigceZc?t=84), on this [Video](https://youtu.be/VsCeR3lmG7o?t=81) aswell
**Revision**: 
1251

**Comment by BAndysc** [comment]
1266
