### ISSUE TITLE
[Warrior][Hunter][Spell] Spell Reflection interaction with hunter's traps

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#694]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Spell Reflection interaction with hunter's traps doesn't work properly. Any trap completely ignores Spell Reflection and goes through it what shouldn't be the case. Spell Reflection should "cancel" most traps and shouldn't apply trap's effect on the hunter (hunter player should still get "Reflected" floating combat text).

**Current behaviour**: Hunter traps ignore Spell Reflection.

**Expected behaviour**: 

Immolation Trap - When warrior walks on top of this trap with Spell Reflection on the trap should trigger, "eat" Spell Reflection buff, NOT apply any effect on the warrior and NOT apply trap's effect on the hunter. Hunter should get "Reflected" floating combat text.

Snake Trap - When warrior walks on top of this trap with Spell Reflection on the trap should trigger and "eat" Spell Reflection buff but it shouldn't apply trap's effect on the hunter. Snakes should spawn normally and attack the warrior. Hunter should get "Reflected" floating combat text.

Freezing Trap/Freezing Arrow - When warrior walks on top of this trap with Spell Reflection on the trap should trigger, "eat" Spell Reflection buff, NOT apply any effect on the warrior and NOT apply trap's effect on the hunter. Hunter should get "Reflected" floating combat text.

Frost Trap - When warrior walks on top of this trap with Spell Reflection on the trap should trigger normally and ignore Spell Reflection.

Explosive Trap - When warrior walks on top of this trap with Spell Reflection on the trap should trigger normally and ignore Spell Reflection.

**Revision**: 1251

**Comment by Wolffenstein** [comment]
Fixed in rev 1258.
