### ISSUE TITLE
[Quest][Zul'Drak] The Storm King's Vengeance

### ISSUE THREAD

**Issue by WeekendWarrior00** [Stormforge-gg/Bugtracker-Wotlk-Beta#699]
**Description**:  You mount on the giant and kill stuff.  Usually you kill the mobs by grabing and throwing them at each other.

**Current behaviour**: When you throw the mob, almost all kills are not counting towards the quest.

**Expected behaviour**:  Besides the elites, you need to kill 100 scourge. When throw the mob to a large group, everyone dies and should count for the quest.

**Revision**:

**Comment by Emtec** [comment]
Fixed in 1254
