### ISSUE TITLE
[Spell][Class] Summon Water Elemental

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#7]
https://ru.tbc.wowhead.com/spell=31687/%D0%BF%D1%80%D0%B8%D0%B7%D1%8B%D0%B2-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BB%D1%8F-%D0%B2%D0%BE%D0%B4%D1%8B

![image](https://user-images.githubusercontent.com/40593874/162324802-7c899afd-e431-46fd-bb40-08fc3603a628.png)

**Description**: 

**Current behaviour**:  when calling a water elemental and giving him the order to attack or using ctrl + 1, nothing happens

**Expected behaviour**: the elemental must go and hit enemies on the head by casting ice arrows

**Revision**:

**Comment by Einia** [comment]
When you click on his spell "Waterbolt" he can cast it normaly right ?

**Comment by Hazas** [comment]
I've done some testing on this and I don't think its a bug. iirc pressing the attack button not doing anything is normal wotlk behavior bc water elem doesnt have a melee attack. Pressing the Waterbolt button works just fine and our ll buddy start casting waterbolt at the enemy until told otherwise.

**Comment by Gn0m** [comment]
Why do you think that this is normal behavior, he has 3 states: follow, stand, attack, if he does not have a melee attack, but only a ranged attack, then he should start casting his ability, which is on auto cast. Now, if the ability was not on auto-cast and I attacked, then it would be logical that he would just stand, because he does not have a melee attack and the magic attack is also disabled.

**Comment by Emtec** [comment]
Fixed in 1105
