### ISSUE TITLE
[DUNGEON][NPC] Eye of Taldaram

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#70]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: This NPC doesn't use his interrupt ability. 

**Current behaviour**: Eyes in the Dark and Dark Counterspell missing (could be cause I was testing alone).

**Expected behaviour**: These NPCs should use these 2 spells.

**Revision**: 1040

**Comment by Wolffenstein** [comment]
He does use it but you have to actually be casting an ability.

**Comment by Nuy** [comment]
I kept casting healing wave/bolt and he didn't use it so idk.
