### ISSUE TITLE
Sholo-Basin Quest  [Reconnaissance Flight] bug/hardstuck

### ISSUE THREAD

**Issue by sillywizzardsi** [Stormforge-gg/Bugtracker-Wotlk-Beta#700]
http://wowhead.com)](https://www.wowhead.com/quest=12671/reconnaissance-flight)

**Description**: 
mid quest when he tries to fly back i get stuck in the air, did it twice, easy to recreate
cant do anything once stuck NEEDS FIXING BEFOER LAUNCH
**Current behaviour**:
getting stuck
**Expected behaviour**: 
flys back

**Comment by Wolffenstein** [comment]
Fixed in rev 1264.
