### ISSUE TITLE
[Quest][Zul'Drak] Dark Horizon

### ISSUE THREAD

**Issue by WeekendWarrior00** [Stormforge-gg/Bugtracker-Wotlk-Beta#701]
**Description**:  Just a regular tour quest. I gargoyle picks you and fly around the map. 
The problem are some inconsistencies with the speed, animations. etc

**Current behaviour**:  The player and the gargoyle turn invisible during the flight, the speed is way faster than usual and the movement is all wrong.

**Expected behaviour**: Regular slow moving flying tour around the map. 

**Revision**:

**Comment by WeekendWarrior00** [comment]
![WoWScrnShot_052422_225436](https://user-images.githubusercontent.com/61029488/170164404-e383d86d-2a93-4fc4-ae26-12a75749e30b.jpg)

Me during the "tour". I even got the "Going Down?" achiev while I was doing it,

**Comment by Wolffenstein** [comment]
Fixed in rev 1264.
