### ISSUE TITLE
[Quest][Zul'Drak] It Rolls Downhill

### ISSUE THREAD

**Issue by WeekendWarrior00** [Stormforge-gg/Bugtracker-Wotlk-Beta#702]
**Description**:  You use the item "Scepter of Suggestion" on Bright Geist so they collect Blight Crystals.  When I charmed one of the Geists it when underground and the mob  Blightguard was nearby. It aggroed the mob and it bugged the quest. The Geist bugged and didn't collect the crystall. I cound't dismiss it and even when the charm timer ended, it didn't go away. Since I had control of a Geist, I couldn't use the item on other mobs.

**Current behaviour**: Some of the Geist are going underground during the Crystall colecting animation.  If a mob is nearby, it can bug the Geist entering combat. It won't collect the crystall and can't be dismissed even after the charm timer ends. 

**Expected behaviour**: You "charm" the Geists and they collect the Crystals. The Blightguards can see your disguise, but they will go to your direction and not for the Geist (usually the collecting animation are far from the mobs).

**Revision**:

**Comment by Emtec** [comment]
Fixed in 1253
