### ISSUE TITLE
[Quest=12330][NPC=27627] Anatoly will Talk/Tatjana

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#703]
**Description**: 
During the quest [Anatoly will Talk](https://www.wowhead.com/quest=12330/anatoly-will-talk), when you use [Tranquilizer Dart](https://www.wowhead.com/item=37665/tranquilizer-dart#reward-from-q) on [Tatjana](https://www.wowhead.com/npc=27627/tatjana) her "friendly" version will drop on the ground, and another "enemy" version will pop on the horse, you can complet the quest but [Tatjana](https://www.wowhead.com/npc=27627/tatjana) can be attacked by the player and she will hit you during the escort

**Current behaviour**:
https://youtu.be/bsLGnuMp018

**Expected behaviour**: 
https://youtu.be/LbuzGiSQQ94?t=23

**Revision**: 
1251

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
