### ISSUE TITLE
[NPC=28083] Serfex the Reaver

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#706]
**Description**: 
[Serfex](https://www.wowhead.com/npc=28083/serfex-the-reaver#screenshots) animation is bug, sometime he stay out instead of waiting under the ground with the ground animation
![image](https://user-images.githubusercontent.com/40879039/170350159-5cd5afca-bae4-4266-ba42-406e778b2131.png)

Sometime he stay under the ground and even if you are in combat, his ground animation is missing when you are out of combat

Something weird is, he don't have NPC ID in my tooltip, and i have an addon to show it
![2022-05-25 21_14_52-World of Warcraft](https://user-images.githubusercontent.com/40879039/170350634-65e09a44-cbf4-474d-8e4d-540d2387f761.png)

**Current behaviour**:
https://youtu.be/qpBkonqQn0g

**Revision**: 
1257

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
