### ISSUE TITLE
[NPC][Howling Fjord] Molly - missing quotes

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#707]
**Description**: 
[Molly](https://www.wowhead.com/npc=24767/molly#comments) has 3 quotes and [Grezzix Spindlesnap](https://www.wowhead.com/npc=24643/grezzix-spindlesnap#comments) has a one quote.
Picture from [Wowpedia](https://wowpedia.fandom.com/wiki/Grezzix_Spindlesnap)
![image](https://user-images.githubusercontent.com/4455568/170352110-cba95c76-55f1-4889-b5b5-b8352057a82d.png)

**Current behaviour**:
They don't say anything
Molly hover in the air

**Expected behaviour**: 
They should say their quotes.
Molly should fly around boat.
**Revision**: 
1257

**Comment by BAndysc** [comment]
I've fixed in rev 1266, forgot to mention it :)
