### ISSUE TITLE
[Quest][Howling Fjord] Street "Cred" bug that gives Going Down? achievement

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#708]
**Description**:
In quest [Street "Cred"](https://www.wowhead.com/quest=11509/street-cred) we can talk to [Lou the Cabin Boy](https://www.wowhead.com/npc=24896/lou-the-cabin-boy) to get boat to pirate's village. When I talk to him I got boat, then after 1sec I had dust animation around like from falling and I got credit [Going Down?](https://www.wowhead.com/achievement=964/going-down). In the picture we can see that I got achievment while being on this boat(chat confirms that).
![image](https://user-images.githubusercontent.com/4455568/170353740-83123fc8-c5ec-48c7-b4a8-01ac3b548a98.png)

**Current behaviour**:
 - It gives achievement. 
 - his boat is too slow.
 - When I leave boat i can't cast spells and mount up for few sec, because I have " Can't do that while moving"

**Expected behaviour**: 
 - It shouldn't give achievement. Maybe the reason is that lou boat, which is inside other boat?
 - His boat should be much faster
 - There should be no " Can't do that while moving" after leaving boat.
 - 
**Revision**: 
1257

**Comment by BAndysc** [comment]
Fixed in rev 1266
