### ISSUE TITLE
[NPC] Jotun

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#71]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: His walking is buggy. 

**Current behaviour**: His waypoints make him sometimes turn around and go a few steps back befor moving forward again and he's "walking" through gaps in the road instead of jumping over them.

**Expected behaviour**: Shouldn't go few steps back and should jump over gaps in the road. https://www.wowhead.com/npc=26290/jotun

**Revision**: 1040

**Comment by FX-SF** [comment]
1) Confirmed: Some visual bugs and pathing issues, but very little game breaking activity.
2) First picture shows him floating across a valley-styled landscape
 Last three pictures show him changing vector directions momentarily.
![WoWScrnShot_050622_191142](https://user-images.githubusercontent.com/105084838/167234098-434ee632-9664-484b-bb6b-d1c7ce843342.jpg)
![WoWScrnShot_050622_191206](https://user-images.githubusercontent.com/105084838/167234104-39869780-9712-42d8-8544-3ff36d08e293.jpg)
![WoWScrnShot_050622_191209](https://user-images.githubusercontent.com/105084838/167234105-e10ace85-c425-432f-8bdb-5d8a142bf029.jpg)
![WoWScrnShot_050622_191211](https://user-images.githubusercontent.com/105084838/167234106-b512b20c-5924-4997-a1ed-dfaeada736b5.jpg)

**Comment by FX-SF** [comment]
https://user-images.githubusercontent.com/105084838/167276390-5861c882-36fb-4131-86f9-247d4c8c8cf3.mp4

**Comment by EtheriousNW** [comment]
Don't have sniffs for this guy 🤔

**Comment by Tereneckla** [comment]
Fixed
