### ISSUE TITLE
[NPC][Howling Fjord] Harry's Bomber

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#712]
**Description**: 
In quest [The Ancient Armor of the Kvaldir]( https://www.wowhead.com/quest=11567/the-ancient-armor-of-the-kvaldir) we fly by plane to our destination but can't take [Harry's bomber](https://www.wowhead.com/npc=28277/harrys-bomber) to fly back              

**Current behaviour**:
This plane is untargetable, so can't talk to take a flight back. It will take a while to go back with ground mount.
![image](https://user-images.githubusercontent.com/4455568/170373861-e779100c-fd77-4dc2-b8de-97e12af3a268.png)

**Expected behaviour**: 
It should be targetable to fly back
![image](https://user-images.githubusercontent.com/4455568/170373721-a3a8ce79-c794-4f63-b3ae-8ab82afe7974.png)

**Revision**: 
1263

**Comment by Wolffenstein** [comment]
Fixed in rev 1265.
