### ISSUE TITLE
[QUEST] Corrosion Prevention

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#714]
Quest item "Ooze Buster" doesn't work on the Corrosive Swamp Ooze, you get 'invalid target' error. Works fine on the other oozes

https://tbc.wowhead.com/quest=11174/corrosion-prevention
https://tbc.wowhead.com/npc=4392/corrosive-swamp-ooze

**Comment by Wolffenstein** [comment]
Fixed in rev 1265.
