### ISSUE TITLE
"Where is the Zeppelin now?" - Dialogues either missing or don't work

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#715]
These are from the Zeppelin masters for horde.
Tested only the Orgrimmar + Grom'gol ones.

Sometimes the option is missing for this gossip, sometime it is there (like from Frezza), but when you click the gossip option, he/she doesn't produce a message with the answer.

Here are some of them, there are Wrath ones also but I'm having a hard time finding all of them:

https://tbc.wowhead.com/npc=12136/snurk-bucksquick
https://tbc.wowhead.com/npc=3150/hin-denburg
https://tbc.wowhead.com/npc=9564/frezza
https://tbc.wowhead.com/npc=12137/squibby-overspeck
https://tbc.wowhead.com/npc=9566/zapetta
https://tbc.wowhead.com/npc=3149/nezraz

**Comment by Wolffenstein** [comment]
Fixed in rev 1293.
