### ISSUE TITLE
[Spell] Track Humanoids for Cat Form

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#719]
Track Humanoids for Cat Form always automatically turns on when you shift into Cat, even if you disable it while in cat form, and then shift out/in again.

Unsure if intended/blizzlike.

https://tbc.wowhead.com/spell=5225/track-humanoids

**Comment by Vishiswaz** [comment]
It certainly would be _nice_ if it would remember whether or not it was disabled manually. Dunno if blizzlike but it'd be a nice minor qol improvement for ferals.

**Comment by NatsumeLily** [comment]
This is sadly blizzlike.
