### ISSUE TITLE
[Instance] [NPC] Arthas RP after Salraam dies

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#724]
After you kill Salraam in wave 10 of the instance, Arthas does his RP text "Meet me at the townhall at once" etc, but instantly teleports himself in front of the townhall.

He should instead run from his previous position toward the town hall (and engage any living zombies along the way)

**Comment by Wolffenstein** [comment]
Fixed in rev 1270.
