### ISSUE TITLE
[Instance] [NPC] Culling of Strat - Infinite Corruptor

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#729]
Issues with this boss:

1. He is facing the wrong direction while doing his RP beam on the guardian of time (see screenshot below)

2. His void strike ability is supposed to ignore 100% of target's armor, but I don't believe it is. Hitting for same amount as his normal attacks.

3. When killed, he does not give "Reins of the Bronze Drake" as he should, should be a 100% drop rate.

https://www.wowhead.com/npc=32273/infinite-corruptor
https://www.wowhead.com/spell=60590/void-strike
https://www.wowhead.com/item=43951/reins-of-the-bronze-drake

![Infinite Corruptor](https://user-images.githubusercontent.com/37913400/170412788-7606db4d-ee39-4a81-8549-632eccd58745.png)

**Comment by Wolffenstein** [comment]
He won't drop it if you already have it

**Comment by Wolffenstein** [comment]
Fixed in rev 1270.

**Comment by Godmatik** [comment]
@Wolffenstein The character I tested it on has no flying mount
