### ISSUE TITLE
[Quest] The last line of defense | [Zone] Icecrown

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#73]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Argent cannons seem to be buggy. Some of the areas which should be reachable are not, due to invisible barriers.

**Current behaviour**: Argent cannons can't reach some of the areas.

**Expected behaviour**:  They should have a wider reach. https://www.wowhead.com/quest=13086/the-last-line-of-defense#videos

**Revision**:

**Comment by therealCrysis** [comment]
This issue has been already reported.

https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/23
