### ISSUE TITLE
[Instance] [NPC] Culling of Strat - Chromie - Skip Arthas Scene dialogue option

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#730]
After you have completed Strat, you can ask Chromie in the next run to skip the Arthas RP with the 2nd dialogue option.

**Currently:**
Doing this will immediately jump ahead to spawning all the zombies, wave 1 of trash, and begin the 25 minute timer (in heroic).

**How it should work:**
I'm fairly certain it should not jump you that far ahead - it should instead take you to the spot where you speak to Arthas and that RP portion begins where he kills a couple of people then Mal'Ganis appears and does his speech.

I'm having difficulty finding a video of this, but I recall this is how it worked back many many years ago. Perhaps someone can verify on retail?

https://www.wowhead.com/npc=26527/chromie#comments

**Comment by Wolffenstein** [comment]
yes it should
