### ISSUE TITLE
[Dungeon] Halls of Stone [NPC] Dark Rune Shaper

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Wotlk-Beta#732]
**Description**: When body-pulled only, the Dark Rune Shapers (npc=27965) in the Halls of Stone get aggro but stay indefinitely still.

**Current behaviour**: The Dark Rune Shapers (npc=27965) in the Halls of Stone get aggro but stay indefinitely still when body pulled. Once one applies a debuff on them or deals damage to them, they move and can follow when being dragged. But until then, they don’t move at all, resulting in issues like in the following pictures:
![image](https://user-images.githubusercontent.com/59399784/170436915-7e543c5b-a2fb-4309-9437-a606cf08c7a5.png)
![image](https://user-images.githubusercontent.com/59399784/170436935-3606e222-0262-4dec-8ff9-6c6506d21b9d.png)

**Expected behaviour**: I can’t find any reliable sources for that given that, in every video I undearth, they usually get more than body pulled (somebody applies a debuff on them or deals damage to them), but my intuition suggests that it is not the correct behavior. But since I don't have hard evidence, it's more a feeling that a fact that is driving this report: feel free to disregard it if you don't agree ^^

**Steps to reproduce the issue**: Enter Halls of Stone, go to the Krystallus’ wing, body pull without hitting the Dark Rune Shapers and run away, break los and observe that they don’t follow you.

**Revision**: 1265

**Comment by Wolffenstein** [comment]
Fixed in rev 1270.
