### ISSUE TITLE
[NPC][Howling Fjord] Vigdis the War Maiden

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#737]
**Current behaviour**:
[Vigdis the War Maiden](https://www.wowhead.com/npc=32386/vigdis-the-war-maiden) has no waypoints, she just has random movement.

**Expected behaviour**: 
This rare patrols the patch of open plains around Nifflevar and Ivald's Ruin

**Revision**: 
1270

**Comment by BAndysc** [comment]
Fixed in 1276

**Comment by eryczek1615** [comment]
She should be mounted while patroling, now she isn't.

**Comment by Cold-Martijn** [comment]
There are currently also multiple spawns active at the same time, it being a rare mob doesn't make sense to have multiple spawns up.

**Comment by BAndysc** [comment]
Mount fixed in rev 1308, @Cold-Martijn  I think you've been testing it on your local server with .npc readd, which doesn't work with pooling, haven't you?
