### ISSUE TITLE
[NPC][Howling Fjord] Enthralled Stone Giant companion

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#738]
**Description**: 
During quest [The Rune of Command](https://www.wowhead.com/quest=11352/the-rune-of-command) we use [Rune of Command](https://www.wowhead.com/item=33796/rune-of-command) on [Stone Giant](https://www.wowhead.com/npc=23725/stone-giant) to take over the control and we have our companion [Enthralled Stone Giant](https://www.wowhead.com/npc=24346/enthralled-stone-giant#comments)

**Current behaviour**:
The problem is that he aggroes to everything hostile and neutral npcs around him and he has big range. Sometimes it is annoying 'cause it gives combat constantly.

**Expected behaviour**: 
He shouldn't attack everything around him. 

**Revision**: 
1275

**Comment by Cold-Martijn** [comment]
https://www.youtube.com/watch?v=eTbWQRLDnXk

not a bug.
