### ISSUE TITLE
[NPC][Howling Fjord] Perobas the Bloodthirster

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#739]
**Current behaviour**:
[Perobas the Bloodthirster](https://www.wowhead.com/npc=32377/perobas-the-bloodthirster#comments) doesn't use his spell [Killing Rage](https://www.wowhead.com/spell=52071/killing-rage). He stands in one place.

**Expected behaviour**: 
He should use this spell. 
He should have some waypoints.

**Revision**: 
1275

**Comment by BAndysc** [comment]
Fixed in 1276
