### ISSUE TITLE
[NPC] Dragonblight Magnataurs

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#74]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Dragonblight elite magnataurs should have some sort of CC immunity depending on the mob. They aren't immune to any CC here.

https://www.wowhead.com/npc=27006/bonesunder#comments
https://www.wowhead.com/npc=27008/bloodfeast#comments
https://www.wowhead.com/npc=27003/dregmar-runebrand#comments
https://www.wowhead.com/npc=27002/gromthar-the-thunderbringer#comments
https://www.wowhead.com/npc=26836/gigantaur#comments

**Current behaviour**: Magnataur elites in Dragonblight don't have any CC immunity making them way too easy to solo.

**Expected behaviour**: Dragonblight elite magnataurs should have some sort of CC immunity depending on the mob.

**Revision**: 1040

**Comment by therealCrysis** [comment]
Confirmed.

**Comment by EtheriousNW** [comment]
Fixed and live on beta
