### ISSUE TITLE
[Global] Guards that attack PvPers + Server Crash (critical)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#741]
So, we encountered several issues.

Issue 1: Sometimes when you attack a player near pvp-aggroing guards, the guards attack the _victim_ instead of the aggressor.

Issue 2: I caused two server crashes tonight while testing this so there's also a server crashing bug involved with this. I got it on video, too.

Issue 3: If you miss, it doesn't cause the guards to come after you. It should. Possibly related to: https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/746

https://youtu.be/zAl58PSxPC0

and again https://youtu.be/YC4lnNyKsQE

Issue 4: (Struggling to get footage of this one) When Player A attacks Player B and the guards attack Player A, if Player B attacks Player A back, guards all the way from China seem to aggro, a very very large radius.

Issue 5: Sometimes when Player B retaliates against player A, the second round of guards that come from China attack player A instead of Player B if anyone. https://youtu.be/lxZTXJ3f1lo

**Comment by NatsumeLily** [comment]
I (the druid) had "At War" on for Gadgetzan for the first two videos. It was turn off for the last video. 
Didn't test it that much since something with this is crashing server.

**Comment by Wolffenstein** [comment]
Fixed in rev 1277.
