### ISSUE TITLE
[Global] Looting gold from pvp corpses doesn't say anything in chat

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#743]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Don't get any chat message about receiving gold when you loot players corpses. 

https://www.youtube.com/watch?v=R_G7-PAM3ys

**Revision**: 1275

**Comment by Vishiswaz** [comment]
Similar to https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/697 and probably needs a similar fix

**Comment by Wolffenstein** [comment]
Fixed in rev 1278.
