### ISSUE TITLE
[Zone][Wintergrasp] Spirit Guides

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#744]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Apparently not all spirit guides are de-spawned outside of wintergrasp battles.

Spirit guides should only be there during wintergrasp battles. Spirit Healers should be there only between battles.

![WoWScrnShot_052622_224915](https://user-images.githubusercontent.com/78314117/170619171-9d6eba49-b1ca-411b-aa92-4f98ca83d6da.jpg)

**Comment by Vishiswaz** [comment]
As an update, it appears the Spirit Guides are now correctly not spawned outside battles.

But the Spirit _Healers_ are still there during battles when they should not be.

**Comment by Emtec** [comment]
Fixed in 1336
