### ISSUE TITLE
[Zone][Wintergrasp] Looting player corpses

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#745]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
1. You can loot players (giving you the gold and forcing them to release) while a Wintergrasp battle isn't active. 
2. When a enemy player releases you can no longer loot their corpse. 

**Revision**: 1275

**Comment by Vishiswaz** [comment]
* only bugged if the dead player isn't released. If the player releases they cannot be looted.

**Comment by Wolffenstein** [comment]
Fixed in rev 1291.
