### ISSUE TITLE
[NPC] Brittle Revenant (underwhelming loot table)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#747]
**Description**: [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) is an NPC {ID: 30160} located in the Frostfield Lake of The Storm Peaks. Brittle Revenant appears to spawn after a certain quest is completed, possibly [A Spark of Hope](https://www.wowhead.com/quest=12956/a-spark-of-hope). 

**Current behaviour**:  With the exception of a quest item named Essence of Ice, [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) has almost no loot table. 

**Expected behaviour**: [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) should have a loot table similar to [this](https://www.wowhead.com/npc=30160/brittle-revenant#comments).

**Revision**: 1275

Loot Table from Wowhead:
![image](https://user-images.githubusercontent.com/105084838/170624584-ab253992-678e-4a1e-9f4a-59d02cc9a34d.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1295.
