### ISSUE TITLE
[Rogue] Feint

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#748]
**Description**: 
Feint Rank 8 does not give an Aura or Buff of "50% reduced damage taken from area of effect attacks."

**Current behaviour**:
Animation plays and Rogue enters combat when tested on a dummy.
No Buff or Aura is shown on player.

**Expected behaviour**: 
Combat skill Feint lowers threat to a target and with Rank 8 it should give a buff as shown here https://wotlkdb.com/?spell=48659.
I did not find how to verify this but seems odd not having any indication of aura or buff on the character.

**Revision**:

**Comment by Wolffenstein** [comment]
Works correctly from what im told

**Comment by zinro** [comment]
I did find a video showing the Feint buff visible https://youtu.be/OQjIy68avck?t=120. First buff that appears is the icon with 6 seconds.
