### ISSUE TITLE
[NPC] Brittle Revenant (shouldn't cast shield bash after patch 3.3)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#749]
**Description**: [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) is an NPC located at Frostfield Lake in The Storm Peaks. [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) is known for performing Shield Bash on a casting opponent.

**Current behaviour**: [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) casts Shield bash on a casting opponent.

**Expected behaviour**: [Brittle Revenant](https://www.wowhead.com/npc=30160/brittle-revenant) should not cast Shield Bash as of patch 3.3

**Revision**: 1275

Evidence:

1) Wowhead Comment:
![image](https://user-images.githubusercontent.com/105084838/170625077-69c6fd4b-c63b-49ba-9b80-979c612e2090.png)

**Comment by Godmatik** [comment]
Shouldn't the NPC mechanics mimic 3.0 - and this be intended?

Only thing that should be 3.3.5 is player spells/talents?

**Comment by FX-SF** [comment]
If NPC mechanics are to mimic 3.0, yes this is working as intended. Is Stormforge meant to mimic 3.0 NPC mechanics?
If yes, then this ticket should be closed.

**Comment by Wolffenstein** [comment]
Fixed in rev 1295.
