### ISSUE TITLE
[NPC][Naxxramas] Stoneskin Gargoyle

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#751]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Waypoints look like trash for some reason. It doesn't look like it's flying through the air, it looks like it's perpetually falling. https://youtu.be/YBty7ZFNLPI

**Comment by Wolffenstein** [comment]
Fixed in rev 1291.
