### ISSUE TITLE
[NPC][Naxxramas] Noth the Plaguebringer

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#753]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This might be a global bug and not specific to Noth, but it appears that if you pull with a spell that misses, Noth goes to another player instead of the one that pulled. https://youtu.be/D5YQ-jUmNco

**Comment by Wolffenstein** [comment]
Fixed in rev 1292.
