### ISSUE TITLE
[Spell][Hunter] Feign Death resist chance

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#754]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Feign death resist chance seems to be missing. Tested on Naxx trash (level 81) as a level 1. 
I think it should use the same table for used for TBC/Netherwing. 

**Revision**: 1275

**Comment by Wolffenstein** [comment]
Fixed in rev 1291.

**Comment by Nuy** [comment]
The difference is that in WotLK it probably should have 0% chance to resist when you're hit capped.
