### ISSUE TITLE
{Quest][The Storm Peaks] Thrusting Hodir's Spear (too much emote)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#755]
**Description**: [Thrusting Hodir's Spear](https://www.wowhead.com/quest=13003/how-to-slay-your-dragon#comments) is a repeatable quest {ID: 13003} where you 'hitch a ride on a dragon'. During this time, you enter a vehicle-type scenario and are able to use [Thrust Spear](https://www.wowhead.com/spell=56690) {ID 56690} and [Mighty Spear Thrust](https://www.wowhead.com/spell=60586/vengeful-spear-thrust) {ID:60586}. This encounter has 2 phases.

**Current behaviour**: In phase 1, using [Thrust Spear](https://www.wowhead.com/spell=56690) and [Mighty Spear Thrust](https://www.wowhead.com/spell=60586/vengeful-spear-thrust) throughout the encounter spams an annoying emote: `FATAL STRIKE MISSED! KEEP PRYING!`

**Expected behaviour**: In phase 1, using [Thrust Spear](https://www.wowhead.com/spell=56690) and [Mighty Spear Thrust](https://www.wowhead.com/spell=60586/vengeful-spear-thrust) should not trigger the emote. 

**Revision**: 1275

The emote is strictly for [Fatal Strike](https://www.wowhead.com/spell=60587/fatal-strike), a spell used in phase 2 and the phase is working correctly.

[WotLK era video of correct emoting](https://youtu.be/M1vH7BjqtjQ?t=205)

What is looks like on SF atm:
![image](https://user-images.githubusercontent.com/105084838/170642577-ceff075b-d323-4fb2-9e9f-30adfdd2795c.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1280.
