### ISSUE TITLE
[Quest] [Dalaran>Sholazar] Where in the World is Hemet Nesingwary?

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Stormforge-gg/Bugtracker-Wotlk-Beta#762]
**Description**: 
Take the copter to sholazar and meet with Hemit 
**Current behaviour**:
You fly over correctly then it just drops you almost to your death.

**Expected behaviour**: 
Fly over when you are dropped you should parachute down.

**Revision**: 
1275

https://youtu.be/2YXu_vzrChE?t=55

Also Monte is in wrong orientation he is laying down in mid-air when he should be more hung from the parachute lines

**Comment by Wolffenstein** [comment]
Fixed in rev 1291.
