### ISSUE TITLE
[NPC][Howling Fjord] Keeper Witherleaf

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#765]
**Current behaviour**:
[Keeper Witherleaf](https://www.wowhead.com/npc=24638/keeper-witherleaf#comments) doesn't run away in fear.

**Expected behaviour**: 
He should run far away in fear at low health.

**Revision**: 
1288

**Comment by Cold-Martijn** [comment]
works for me
