### ISSUE TITLE
[Item] Hodir's Horn (spammable soundbite)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#768]
**Description**: [Hodir's Horn](https://www.wowhead.com/item=42164/hodirs-horn#comments) is a quest item {Item ID 42164}. 
Upon use, the item casts the [Lay to Rest](https://www.wowhead.com/spell=55983/lay-to-rest#used-by-item) spell {Spell ID 44983}.
This horn is accompanied by [HornOfAwakening(1)](https://www.wowhead.com/sound=7054/hornofawakening-1), a sound {Sound ID: 7054}

**Current behaviour**: You can spam [HornOfAwakening(1)](https://www.wowhead.com/sound=7054/hornofawakening-1). The sound can only be heard by the caster.

**Expected behaviour**: You should not be able to spam [HornOfAwakening(1)](https://www.wowhead.com/sound=7054/hornofawakening-1)

**Revision**: 1288

https://user-images.githubusercontent.com/105084838/170792809-6c5ec97f-f433-40f9-8d89-3085942ffa93.mp4

**Comment by Wolffenstein** [comment]
clientside
