### ISSUE TITLE
[NPC][Howling Fjord] Ahota Whitefrost, Mage-Lieutenant Malister - no whisper

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#769]
**Current behaviour**:
[Ahota Whitefrost](https://www.wowhead.com/npc=24127/ahota-whitefrost) after return [Of keys and cages](https://www.wowhead.com/quest=11265/of-keys-and-cages#comments) doesn't whisper to us.
![image](https://user-images.githubusercontent.com/4455568/170792884-34b6823b-552c-4472-a802-f9062616ab25.png)

**Expected behaviour**: 
 - After retrun the quest Ahota should whisper to us **"<race>, a moment of your time?"** 'cause he has a new quest to us, there where we are going to. [Video](https://youtu.be/61bAuaC7VJ0?t=237)
 - I don't know what about alliance but [Mage-Lieutenant Malister](https://www.wowhead.com/npc=23888/mage-lieutenant-malister) shoudl whisper **"<name>, I would have words with you"** [Video](https://youtu.be/bKKICZK_7Yk?t=223)
 
![image](https://user-images.githubusercontent.com/4455568/170793294-6f21a7c4-f4c7-4a1d-9d57-fe9407092487.png)

**Revision**: 
1288

**Comment by Cold-Martijn** [comment]
rev 1349
