### ISSUE TITLE
[NPC] High Shaman Bloodpaw

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#77]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: He should be immune to stun and disarm but isn't here.

**Current behaviour**: Isn't immune to stun and disarm. 

**Expected behaviour**: He should be immune to stun and disarm. https://www.wowhead.com/npc=27762/high-shaman-bloodpaw#comments

**Revision**: 1040

**Comment by Nuy** [comment]
![opera_j1ZssCvNAK](https://user-images.githubusercontent.com/4800827/167871365-d59677e6-0241-4de1-8ea4-fed627748f90.png)
![opera_X9mngahk1k](https://user-images.githubusercontent.com/4800827/167871390-7e8d994f-4f3d-48bb-84bb-074ef1f4920d.png)
![opera_1DWYhaBkLU](https://user-images.githubusercontent.com/4800827/167871411-6b2910fe-263c-4366-ae57-a60a3be5ffda.png)
![opera_QJvceaHEiG](https://user-images.githubusercontent.com/4800827/167871459-74b82316-a16d-400d-b253-dcf6a648049e.png)

**Comment by therealCrysis** [comment]
confirmed

**Comment by Wolffenstein** [comment]
Fixed in rev 1242.
