### ISSUE TITLE
[Rogue] Feint #748

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#773]
**Description**: 
Update for a closed issue for more information.

**Revision**: 
I did find a video showing the Feint buff visible here https://www.youtube.com/watch?v=OQjIy68avck&t=120s First buff that appears is the icon with 6 seconds.

I reported this for people who want to track the duration for PvE or PvP even if the spell is working otherwise.

**Comment by FX-SF** [comment]
#748 original ticket

**Comment by Wolffenstein** [comment]
Fixed in rev 1299.
