### ISSUE TITLE
[Core][Quest][The Storm Peaks][The Reckoning] position makes dialog confusing

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#775]
**Description**: [The Reckoning](https://www.wowhead.com/quest=13047/the-reckoning) is a quest {ID: 13047}.
During the quest, a major RP event that occurs. 
Dialog is said between [Thorim ](https://www.wowhead.com/npc=30399/thorim) and [Loken](https://www.wowhead.com/npc=30396/loken).

**Current behaviour**: **_Depending on your position_**, it is difficult to see both NPC's dialog, creating confusion in the plot.

1. [Video 1]( https://user-images.githubusercontent.com/105084838/170799727-928315ee-8d86-41ba-9076-a72c3891fe39.mp4) : Missing dialog where [Loken ](https://www.wowhead.com/npc=30396/loken) taunts [Thorim ](https://www.wowhead.com/npc=30399/thorim) about Syf, a love interest of [Thorim](https://www.wowhead.com/npc=30399/thorim).
4. [Video 2](https://user-images.githubusercontent.com/105084838/170799691-edd74b03-620a-48cb-9088-64997553fa47.mp4): Missing dialog and confusion of what's going on

**Expected behaviour**: There appears to be an increased distance in which a player can visually see the dialog of both NPCs, avoiding confusion in the plot.

1. [Video 3](https://youtu.be/W9CpULF_4JM?t=120): Shows [Loken's ](https://www.wowhead.com/npc=30396/loken) taunt to [Thorim ](https://www.wowhead.com/npc=30399/thorim) about Syf. Notice the player's distance from [Loken ](https://www.wowhead.com/npc=30396/loken) throughout the video, especially at [2:18](https://youtu.be/W9CpULF_4JM?t=138)
2. [Video 4](https://youtu.be/rk7LIMa-kyc?t=118) Not as great, but another example

**Revision**: 1288

![image](https://user-images.githubusercontent.com/105084838/170800358-d236b50f-4249-437a-bd70-a484c40acd55.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
