### ISSUE TITLE
[The Iron Colossus][The Storm Peaks] NPC resets upon submerged worm

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#776]
**Description**: 

1. [Iron Colossus](https://www.wowhead.com/npc=30300/iron-colossus) is an elite NPC {ID 30300} located in the Snowdrift Plains of The Storm Peaks. 
2. He is required to kill for [The Iron Colossus](https://www.wowhead.com/quest=13007/the-iron-colossus#) quest {ID: 13007}. 
3. During the quest, you enter vehicle-style combat with the elite, using [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar) {NPC ID: 30301}. 
4. [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar) can cast the [Submerge](https://www.wowhead.com/spell=56504/submerge) spell {ID: 56504}, a spell meant to dodge [Iron Colossus](https://www.wowhead.com/npc=30300/iron-colossus)' [Ground Slam](https://www.wowhead.com/spell=61673/ground-slam) spell {ID: 61673}

 **Current behaviour**: 

1. Casting [Submerge ](https://www.wowhead.com/spell=56504/submerge)resets combat with [The Iron Colossus](https://www.wowhead.com/npc=30300/iron-colossus). 
2. A submerged [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar) is not damaged by [Ground Slam](https://www.wowhead.com/spell=61673/ground-slam) (possibly due to non-combat)

https://user-images.githubusercontent.com/105084838/170805364-ec7f57d3-dce9-4a22-bb9f-daecfdb2fd41.mp4

**Expected behaviour**: 

1. [Iron Colossus](https://www.wowhead.com/npc=30300/iron-colossus) stays in combat with [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar), even if it is submerged.

2. A submerged [Tamed Jormungar](https://www.wowhead.com/npc=30301/tamed-jormungar) should take damage by [Ground Slam](https://www.wowhead.com/spell=61673/ground-slam)

**Revision**: 1294

[Video 1 Evidence of Expected Behavior](https://youtu.be/D72JzFo7b9A?t=92)
[Video 2 Evidence of Expected Behavior](https://youtu.be/kDn4Ky5bIwo?t=75)

**Comment by Cold-Martijn** [comment]
rev 1381
