### ISSUE TITLE
[Core] Sale Pending mail

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
An extremely common bug on private servers that always confuses players is the "Sale Pending Mail" bug. When you sell an auction, you get a mail that has a red countdown timer on it counting down from 1 hour. When that hour is up, the Sale Pending mail is supposed to be replaced entirely with the Auction Successful mail, containing the gold.

Stock instead accidentally leavers the Sale Pending mail in the inbox for longer than 1 hour, causing confusion to some players who sell large quantities of the same item, because it looks to them like every other one of their auctions didn't actually have any gold come through.

It would be amazing if we could launch without this bug.

![image](https://user-images.githubusercontent.com/78314117/170806713-c2d61d06-1887-49eb-b55b-5ee7e3f03835.png)

**Comment by Wolffenstein** [comment]
is this actually bugged or are you just guessing?

**Comment by Vishiswaz** [comment]
I'm 100% sure on this. And it appears Martijn is as well since he marked it confirmed bug.

You can confirm it on retail classic if you would like. But this is how the auction house has always worked.

**Comment by Vishiswaz** [comment]
Here is Aithne confirming it's a bug

https://bug.tauriwow.com/index.php?do=details&task_id=28138

**Comment by Wolffenstein** [comment]
im asking if its bugged on FORDRING

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/170833070-be6b7485-01be-4e6d-b42f-bf93863a09df.png)
