### ISSUE TITLE
[Core] Daze with Power Word Shield

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#779]
Currently: You can get dazed by enemies attacking you while you have power word: shield active (or any absorb ability like Divine Aegis).

How it should work: You should be immune to get dazed if that ability is active.

**Comment by Vishiswaz** [comment]
All damage absorb effects should prevent Dazed. Ice Barrier, for example.

**Comment by Wolffenstein** [comment]
Fixed in rev 1299.
