### ISSUE TITLE
[Instance] [Culling of Strat] Arthas RP not fixed.

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#780]
See https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/724

Issue still exists - Arthas instantly teleports in front of town hall after you defeat Salraam, should walk there instead. Tested in Heroic only.

Current Revision: 1294

**Comment by Wolffenstein** [comment]
no he should not

**Comment by Godmatik** [comment]
Look start of this video .... Arthas is running toward the townhall, this was recorded in Wrath. 

Maybe it was changed in a future expansion or something, but this is Blizzlike, no?

https://www.youtube.com/watch?v=dkQ7pvO868Y&ab_channel=MichaelHsiao
