### ISSUE TITLE
[NPCs] Time Watchers misplaced in Tanaris

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#782]
A bunch of "Time Watchers" are flying around in Tanaris at this position - looks they are meant to be inside Caverns of Time instead.

At this spot you can also hear the Caverns of Time ticking clock and other sound effects you should only while inside Caverns of Time.

![WoWScrnShot_052722_225456](https://user-images.githubusercontent.com/37913400/170808891-7554fc8d-fe39-4025-a481-288bb6ef12d3.jpg)

![WoWScrnShot_052722_225506](https://user-images.githubusercontent.com/37913400/170808901-aa35d0b7-1f70-4e2f-827a-97a5068f73e5.jpg)

**Comment by Wolffenstein** [comment]
those sounds are clientside

**Comment by Wolffenstein** [comment]
Fixed in rev 1376.
