### ISSUE TITLE
[Zone][Wintergrasp] Looting Player Corpses (reopen)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#785]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Reopen of https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/745

During a Wintergrasp battle, when Player A dies _and releases_, Player B of the opposing faction cannot loot the corpse. They currently only have the ability to loot the corpse before the player releases.

What should happen:
Player A releases
Player B loots the corpse before Player A is resurrected
Player A gets an error message saying their insignia has been taken and they cannot resurrect the normal way, I don't remember what the exact text is.

**Comment by Vishiswaz** [comment]
In case you want proof this is how it should work: https://youtu.be/efT-5svXJtE?t=14

**Comment by Wolffenstein** [comment]
Fixed in rev 1376.
