### ISSUE TITLE
[QUEST] Tooga's Quest

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#787]
Quest can not be completed - bringing Tooga over to Torta's position does not trigger anything.

https://tbc.wowhead.com/quest=1560/toogas-quest

**Comment by Godmatik** [comment]
https://www.youtube.com/watch?v=oXsogux9vKA&ab_channel=StormblazeGaming&t=9m20s

See above video, only thing missing is the trigger at the end of the quest (and the subsequent RP text)

**Comment by Cold-Martijn** [comment]
rev 1349
