### ISSUE TITLE
[NPC][Wintergrasp] Wintergrasp Tower Cannon (reopen)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#788]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Many of these in the southern towers are still not placed correctly. Reopen of https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/647

Examples of incorrect ones:
![WoWScrnShot_052822_002249](https://user-images.githubusercontent.com/78314117/170809724-dbcdcacf-6af7-42a1-ac51-6bcc7e8cca6d.jpg)
![WoWScrnShot_052822_002254](https://user-images.githubusercontent.com/78314117/170809725-8d0ac3a9-de80-4d4d-94d9-d27294ac0745.jpg)
![WoWScrnShot_052822_002301](https://user-images.githubusercontent.com/78314117/170809726-11a5571e-c7c2-446b-bef7-20cec1828ff2.jpg)

Example of correct one:
![WoWScrnShot_052822_002322](https://user-images.githubusercontent.com/78314117/170809730-d182d03b-45a6-4034-a8e8-0ce9dba116b1.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 1322.
