### ISSUE TITLE
[Zone][Wintergrasp] Vehicle teleport inside keep

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#789]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Vehicle teleporter inside the keep doesn't work for the controlling faction. Should teleport the vehicle outside the wall. 

**Revision**: 1294

**Comment by Vishiswaz** [comment]
(Tested with Horde controlling the keep, using a siege engine)

**Comment by Emtec** [comment]
Fixed in 1337
