### ISSUE TITLE
[Spell] Frost nova (roots) and warrior charge

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#795]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Only tested with frost mages roots so far, but it might happen with all roots. 

When the frost mage roots a warrior mid charge, things get strange. I think you charge back to the starting spot and charge again? 

https://www.youtube.com/watch?v=auXnDsLmIMw

https://www.youtube.com/watch?v=BeTF2HizwTk

https://www.youtube.com/watch?v=ErEcr1kFRy4

**Revision**: 1294

**Comment by Wolffenstein** [comment]
Fixed in rev 1297.
