### ISSUE TITLE
[NPC][Spell][Howling Fjord] Sepulchral Overseer

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#796]
**Current behaviour**:
- [Sepulchral Overseer]( https://www.wowhead.com/npc=23993/sepulchral-overseer#sounds) doesn’t use his spells [Frostbolt]( https://www.wowhead.com/spell=12737/frostbolt) and [Chain of Ice]( https://www.wowhead.com/spell=22744/chains-of-ice). And he has no Sound while dying - its called [LichDeath]( https://www.wowhead.com/sound=5796/lichdeath)

**Expected behaviour**: 
He should use his spells and sound while dying.

**Revision**: 
1294

**Comment by Amun12** [comment]
I reported this a while back, and it was supposed to be fixed. https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/162

**Comment by EtheriousNW** [comment]
Yep, I messed it up. Fixed in the next batch of fixes :c
