### ISSUE TITLE
[NPC][Howling Fjord] Queen Angerboda - quotes

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#798]
**Current behaviour**:
[Queen Angerboda]( https://www.wowhead.com/npc=24023/queen-angerboda) when we pulls her she says **„You will not stop my work here! My husband-king will awaken!”**. But she should say that when she dies. When she aggroes should say **„Give me your souls that I might slay the enemy!”**. She says one of this at pull. Doesn't say anything at death.
![image](https://user-images.githubusercontent.com/4455568/170819306-607d4c25-cdcf-4212-9080-008c9436482c.png)

**Expected behaviour**:
She should say like in the picture below.
![image](https://user-images.githubusercontent.com/4455568/170819271-8cab0b7e-f179-44a4-ac32-9e41ef695877.png)

**Revision**: 
1294

**Comment by Wolffenstein** [comment]
wowwiki is shit and wrong

**Comment by eryczek1615** [comment]
A wise words of wise man, I will follow your lead. :D
