### ISSUE TITLE
RDF - players are not accepting

### ISSUE THREAD

**Issue by matsE94** [Stormforge-gg/Bugtracker-Wotlk-Beta#8]
**Description**: 
There seems to be some kind of error with the RDF. 
The queue pops but the players im grouped with are not accepting the RDF.
Seems like a bug because it happened 10x(++) times in a row.

**Current behaviour**:
RDF queue pops, players outside of party shows as not-accepted and we are requeued. And repeat.

**Expected behaviour**: 
On queue pop players should eventually accept.

**Comment by Wolffenstein** [comment]
Should be fixed now.
