### ISSUE TITLE
[SPELL][PET] Raid buff interaction with guardian pets

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#80]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Raid buffs like Bloodlust or Heroism affect guardian pets like shaman's elementals or DK's Army of the Dead ghouls or Gargoyle what's not correct and can result in insane DPS.

**Current behaviour**: Raid buffs like Bloodlust/Heroism work on guardian pets.

**Expected behaviour**: Raid buffs shouldn't work on guardian pets.

https://wotlk.evowow.com/?spell=2825
https://wotlk.evowow.com/?spell=32182
https://wotlk.evowow.com/?npc=24207
https://wotlk.evowow.com/?npc=31216
https://wotlk.evowow.com/?npc=27829
https://wotlk.evowow.com/?npc=510 (only becomes non-guardian pet with glyph and in such case Hero/BL should work on it)
https://wotlk.evowow.com/?item=50045
https://wotlk.evowow.com/?npc=15438
https://wotlk.evowow.com/?npc=15352

**Revision**: 1040

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.

**Comment by Nuy** [comment]
> Fixed in rev 1041.

Now Hero/BL doesn't work on spirit wolves but it should cause they're not consider guardian pet for some reason. 

https://www.mmo-champion.com/threads/942868-Bloodlust-Heroism-before-or-after-Spirit-Wolfs
