### ISSUE TITLE
[Rogue] [Core] Pick Pocket

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#801]
**Description**: 
Pick pocketing undead mobs in Sholazar Basin often gives the error message “Your target has already had its pockets picked” which either is a bug on undead mobs or the pockets are not respawning. It should take 8-10 minutes for mobs to respawn pockets according to comments https://www.wowhead.com/spell=921/pick-pocket#comments

Here are comments about the Avalanche area which has different undead mobs. https://www.wowhead.com/item=43575/reinforced-junkbox#comments. 

In general Humanoids can be pick pocketed but also Undead like skeletons, ghouls, wights and so on. Mobs that have pockets or have them in death not sure how else to explain, Ghost like mobs for example don't and thus cannot be pick pocketed.

**Current behaviour**:
Some of these examples yield Reinforced Junkbox as they should some give the error message but pretty unsure what is going on.
"Monstrous Wight", "Bonescythe Ravager", "Blighted Corpse", "Frostbitten Corpse". "Snowblind Ghoul" 

These are just some examples could be more in different zones. Zul'Drak has Humanoid & Undead also I believe. 

**Expected behaviour**: 
Pick pocket should yield something like shown here with variance in loot. https://www.wowhead.com/npc=28220/frostbitten-corpse. 
A comment on wowhead "When Pick Pocketed they drop 1-25 Silver, Reinforced Junkbox's, Runic Mana/Healing pots, Food/Drink, and vendor trash. Happy Pickpocketing."

Also the pockets should respawn after some time even if the mob is not killed.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1298.
