### ISSUE TITLE
[Rogue] Sinister Strike

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#803]
**Description**: 
Rogue Combat Skill Sinister Strike damage formula seems incorrect in comparison to other Rogue Skills. 

Here are the chosen Talents in Combat Talent Tree with them being maxed out.
https://wotlkdb.com/?spell=61331
https://wotlkdb.com/?spell=31126
https://wotlkdb.com/?spell=32601

**Current behaviour**:
The percentile weapon damage component does not account Blade Twisting and Surprise Attacks but the added damage math is correct.

243 added is correct but only 115% weapon damage when the percentile should be 135% according to other Rogue Skills.

**Expected behaviour**: 
Here is some math formulas which are known https://wowwiki-archive.fandom.com/wiki/Sinister_Strike_formulas
In-game Combat Skill Backstab does scale correctly with Talents.
Here is baseline max rank Backstab https://wotlkdb.com/?spell=48657

With https://wotlkdb.com/?spell=61331, https://wotlkdb.com/?spell=31126, https://wotlkdb.com/?spell=32601 and Subtlety Talent https://wotlkdb.com/?spell=14072 
The tooltip in-game is 720 added damage + 232% weapon damage.

Subtlety Skill Hemorrhage for reference does seem to scale correctly with affecting talents.

**Revision**:

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/170833547-090599f6-9f74-4449-be97-e0f6517f1063.png)
I don't know how you've tested it but i picked up all of those talents and it seems to be correctly 135% increase
