### ISSUE TITLE
[Core] Sale Pending mail (reopen)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#804]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This is a reopen of a prior ticket (https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/777) because it was closed before I could respond.

An extremely common bug on private servers that always confuses players is the "Sale Pending Mail" bug. When you sell an auction, you get a mail that has a red countdown timer on it counting down from 1 hour. When that hour is up, the Sale Pending mail is supposed to be replaced entirely with the Auction Successful mail, containing the gold.

Stock instead accidentally leavers the Sale Pending mail in the inbox for longer than 1 hour, causing confusion to some players who sell large quantities of the same item, because it looks to them like every other one of their auctions didn't actually have any gold come through.

It would be amazing if we could launch without this bug.

![image](https://user-images.githubusercontent.com/78314117/170806713-c2d61d06-1887-49eb-b55b-5ee7e3f03835.png)

Wolf, you asked me if this was bugged on Fordring. YES. It is. The above screenshot is from Fordring, after the 1 hour timer on the pending mail expires, NOT before it.

**Comment by Wolffenstein** [comment]
Fixed in rev 1299.
