### ISSUE TITLE
[NPC][Dungeon] Gal'darah (Gundrak hm) doesn't cast Puncture nor Stomp

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Wotlk-Beta#81]
**Description**: Gal’darah (npc=29306), the last boss of the dungeon Gundrak, doesn’t use the spells Stomp (spell=55292) and Puncture (spell=55276), at least in heroic mode.

**Current behaviour**: In all the tests I’ve done until now (solo or duo, haven’t got the opportunity to test with a full group yet), Gal’darah (npc=29306) doesn’t ever cast the two following spells: Stomp (spell=55292) and Puncture (spell=55276). 

**Expected behaviour**: In humanoid form, Gal’darah is supposed to cast a 3 main spells, among which Puncture (spell=55276). When he’s in rhino form, he’s supposed to cast 3 other spells, among which Stomp (spell=55292).

References: 

- https://www.wowhead.com/npc=29306/galdarah/heroic-encounter-journal#abilities;mode:normal
- https://www.youtube.com/watch?v=AfLzSYzQbuE (0:17, cast of Puncture // 1:04, cast of Stomp)

**Revision**: 

**_Steps to reproduce the bug_**: Engage Gal’darah, keep him alive forever (I used the GM buffs, didn’t hit him at all, except one every minute to slowly bring him down), ideally with the combatlog activated, observe that both spells never get used by the boss.

**Comment by Nuy** [comment]
I was testing solo too but Puncture should be used even if you're alone I think and should now be fixed.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.

**Comment by Lmdezorn** [comment]
Tested again a few minutes ago: the boss now does cast Stomp in rhino form, but I still haven't seen him cast Puncture on his target when he's in humanoid form. 

If needed, I can upload a vod of how the encounter looks like on my end when I test, feel free to tell me if you think that can help you.

**Comment by Nuy** [comment]
> Tested again a few minutes ago: the boss now does cast Stomp in rhino form, but I still haven't seen him cast Puncture on his target when he's in humanoid form.
> 
> If needed, I can upload a vod of how the encounter looks like on my end when I test, feel free to tell me if you think that can help you.

I reported it befor as not using Puncture in rhino form cause on Wowwiki there's an error that says Puncture is rhino form ability.
