### ISSUE TITLE
[NPC][Icecrown][Into the Wild Green Yonder] no lich king melee

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#810]
**Description**: [Into the Wild Green Yonder](https://www.wowhead.com/quest=13045/into-the-wild-green-yonder) is a quest {ID: 13045} located in Icecrown. During this quest, you encounter a version of [The Lich King](https://www.wowhead.com/npc=30443/the-lich-king#comments) {NPC ID: 30443}

**Current behaviour**: [The Lich King](https://www.wowhead.com/npc=30443/the-lich-king#comments) does not use melee attacks if you get in melee range.

**Expected behaviour**: [The Lich King](https://www.wowhead.com/npc=30443/the-lich-king#comments) should melee attack if you get in melee range.

**Revision**: 1294

![image](https://user-images.githubusercontent.com/105084838/170843852-fa92013b-84cb-40a9-a0ee-ad8fe5780b49.png)
![image](https://user-images.githubusercontent.com/105084838/170843861-0634c29f-b177-4d5a-839e-5e6ab6f167b8.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1303.
