### ISSUE TITLE
[NPC][Naxxramas] Four Horsemen

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#816]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
All 4 Horsemen are currently interruptible. They should not be.

~~You can also spell reflect. I don't believe you should be able to.~~

**Comment by NatsumeLily** [comment]
Lady Blaumeux and Sir Zeliek being interruptible is correct.  
Spell reflect is correct. But only Lady Blaumeux's Shadow Bolt and Sir Zeliek's Holy Bolt.

**Comment by Vishiswaz** [comment]
Apparently that's what the raid was interrupting. So I'll close this.

**Comment by Vishiswaz** [comment]
Aaaand apparently it is indeed a bug. Reopening.

**Comment by Wolffenstein** [comment]
Fixed in rev 1302.
