### ISSUE TITLE
[NPC][Naxxramas] Lady Blowme

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#817]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Lady Blowme (in the 4 horseman fight, shadow bolt caster) will melee people when their shadow bolt is interrupted. She should not. She should just sit there and take it.

**Comment by Godmatik** [comment]
I'm fairly certain that neither of the Horseman casters should be interruptible in the first place and that flag is missing

**Comment by Vishiswaz** [comment]
> I'm fairly certain that neither of the Horseman casters should be interruptible in the first place and that flag is missing

Reopening my ticket for that then. Looks like you're correct about that.

**Comment by FX-SF** [comment]
[Lady Blaumeux](https://www.wowhead.com/npc=16065/lady-blaumeux)

**Comment by Wolffenstein** [comment]
Fixed in rev 1302.
