### ISSUE TITLE
[NPC][Naxxramas] Gluth

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#819]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Because the first person who jumps down from the pipe starts combat for the whole group for Gluth, pets get stuck up in the pipe and won't come down.

They should, otherwise hunters and warlocks and unholy DKs are nerfed for Gluth or they have to all jump at the same time.

![WoWScrnShot_052822_232413](https://user-images.githubusercontent.com/78314117/170850649-16fe0e1d-7e55-4929-91df-0a149cbd1ba0.jpg)

**Comment by Wolffenstein** [comment]
If the pet is set on follow it should teleport after a few seconds of not being able to find the path to the player, works for me.
