### ISSUE TITLE
[NPC][Naxxramas] Heigan the Unclean (Spell Disruption Aura)

### ISSUE THREAD

**Issue by kekkerina** [Stormforge-gg/Bugtracker-Wotlk-Beta#823]
Description:

Heigan the Unclean's (Spell Disruption Aura) in Naxxramas 10man should be a 20yd aura. It is currently 30yds (which is correct in 25m)

source: https://wowpedia.fandom.com/wiki/Heigan_the_Unclean

"Phase one : This is a 20-yard aura around Heigan the Unclean. It will increase cast times by 300%. "

**Comment by Wolffenstein** [comment]
It's increased on purpose to prevent safespotting because blizzard shit the bed 15 years ago
