### ISSUE TITLE
[Raise the Barricades][Icecrown] Barricade Construction Kit

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#829]
**Description**:  [Barricade Construction Kit](https://www.wowhead.com/item=44127/barricade-construction-kit) {Item ID: 44127} is an item used to the quest [Raise the Barricades](https://www.wowhead.com/quest=13332/raise-the-barricades#comments) {Quest ID: 13332}.

**Current behaviour**: You can use the item without being near the correct areas. This causes a cast bar to appear, followed by an "Out of Range" error.

**Expected behaviour**: The cast should never occur unless at a correct location.

**Revision**: 1294

Evidence:

- [Video of expected behavior](https://youtu.be/MAufn-mP6jM?t=22). Shows player using item at wrong area. No cast bar appears. 
- SF Version:

https://user-images.githubusercontent.com/105084838/170859320-34d939f7-a534-4d17-9e39-0d5115ee7689.mp4

**Comment by Evolvee** [comment]
fixed in next rev
