### ISSUE TITLE
[NPC] Magister Keldonus

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#83]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: He should be immune to snares, roots, stuns, silences, slows, sleep etc. but isn't here.

**Current behaviour**: Isn't immune to CC.

**Expected behaviour**:  Should be immune to CC. https://www.wowhead.com/npc=26828/magister-keldonus#comments

**Revision**: 1040

**Comment by EtheriousNW** [comment]
Fixed and live on beta
