### ISSUE TITLE
[Cultist Shard Watcher][Icecrown] missing channeled spell animation

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#830]
**Description**: [Cultist Shard Watcher](https://www.wowhead.com/npc=32349/cultist-shard-watcher#screenshots) is an NPC {ID: 32349} in Icecrown. They are found surrounding 3 crystal "Shards"

**Current behaviour**: While outside of combat, they do not channel any spell.

**Expected behaviour**: While outside of combat, they channel some unknown spell at the "Shards"

**Revision**: 1294

Evidence:
1) [Wowhead](https://www.wowhead.com/npc=32349/cultist-shard-watcher#screenshots)
2) [Google Search](https://www.google.com/search?q=shatter+the+shards+wow&sxsrf=ALiCzsbaZAqfzZlq9khPnmYo21hIRaCNEQ:1653817929683&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjCsuLxt4T4AhXzoI4IHf16DZ8Q_AUoAnoECAEQBA&biw=952&bih=587&dpr=1)

Current Behavior:
![image](https://user-images.githubusercontent.com/105084838/170862140-368255b6-f70e-43fa-a435-95ea00351038.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/105084838/170862155-690bfcf1-a152-465a-8b93-c8d70e912622.png)
![image](https://user-images.githubusercontent.com/105084838/170862178-8e67458e-193c-46fc-959b-37226e4cae9b.png)

**Comment by Evolvee** [comment]
fixed in next rev
