### ISSUE TITLE
[It's All Fun and Games][Icecrown] Deathly Stare does no damage

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#831]
**Description**:

-  [It's All Fun and Games](https://www.wowhead.com/quest=12887/its-all-fun-and-games#comments) is a quest in Icecrown {Quest ID: 12887}.
- This quest requires you to kill [The Ocular](https://www.wowhead.com/npc=29747/the-ocular#abilities) {NPC ID: 9747}.
- The Ocular casts [Deathly Stare](https://www.wowhead.com/spell=55269/deathly-stare#comments) {Spell ID: 55269}.

**Current behaviour**: 

- Deathly Stare does no damage.

**Expected behaviour**:

-  Deathly Stare should do 5% of players Max HP. 

_Possible behaviors mentioned in wowhead comments:_
- It is possible that the rate of fire increases as the fight continues. 
- It is equally possible that this rate of fire was patched out somewhere between 3.0 and 3.3.5. (Hard to tell)

**Revision**: 1294

Evidence: [Wowhead Comments](https://www.wowhead.com/spell=55269/deathly-stare#comments)

![image](https://user-images.githubusercontent.com/105084838/170862851-55aedbf7-f40c-461c-84a6-fcc1e83b7204.png)
![image](https://user-images.githubusercontent.com/105084838/170862908-68da8df9-e604-4221-8633-3a095b58d7fd.png)
--
![image](https://user-images.githubusercontent.com/105084838/170862942-c2011d8e-eea5-477c-af47-0dcf5dd0631b.png)

**Comment by Evolvee** [comment]
it does damage to me, need info on how to reproduce this

![image](https://user-images.githubusercontent.com/1942409/170864359-9fab804b-5fdc-4319-a8e0-28d8eeaf16d2.png)

**Comment by FX-SF** [comment]
I had Rage PTR Buff on. Will close ticket.
