### ISSUE TITLE
[Vault Geist] Missing spell

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#832]
**Description**: [Vault Geist](https://www.wowhead.com/npc=29720/vault-geist#abilities) is an NPC {ID: 29720} in Icecrown. 

**Current behaviour**: Vault Geist does not cast [Rip](https://www.wowhead.com/spell=36590/rip) {Spell ID: 36590}

**Expected behaviour**:  Vault Geist should cast [Rip](https://www.wowhead.com/spell=36590/rip)

**Revision**: 1294

Evidence: [wowhead ability page](https://www.wowhead.com/npc=29720/vault-geist#abilities)
![image](https://user-images.githubusercontent.com/105084838/170863839-dc773013-4062-437b-8638-c8241d26240c.png)

**Comment by Evolvee** [comment]
fixed in next rev
