### ISSUE TITLE
[Lady Nightswood] incorrect dialog, incorrect combat AI.

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#833]
**Description**: [Lady Nightswood](https://www.wowhead.com/npc=29770/lady-nightswood#abilities) is an NPC in Icecrown. {NPC ID: 29770}

**_`Dialog`_**
**Current behaviour**: Lady Nightswood will say "Who intrudes upon my ritual?" at the start of combat and when she is slain.
**Expected behaviour**: Lady Nightswood will say "Who intrudes upon my ritual?" at the start of combat only. She will not sat this when slain.

**_`AI`_**
**Current behavior:** She will not attack until the player interrupts her spell cast animation (i.e. a melee swing)
**Expected behavior:** She will stop a spell cast animation and used spells and abilities upon agro

**Revision**: 1294

**Comment by FX-SF** [comment]
@Evolvee just updated 20 seconds ago

**Comment by Evolvee** [comment]
this will be the same issue for all 3 npcs of the quest

**Comment by Evolvee** [comment]
Yea, same for "Vile" and "The Leaper"

**Comment by Evolvee** [comment]
fixed in next rev
