### ISSUE TITLE
[Talent][Druid] Omen of Clarity doesn't proc from hots.

### ISSUE THREAD

**Issue by Barcaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#836]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Omen of Clarity doesn't seem to proc when you apply rejuvenation from my observations and i think from lifebloom too. Haven't tested it with wild growth, but i assume it doesn't work with any hots.

**Expected behaviour**: It should have a chance to proc on every application of every healing ability.

**Comment by Vishiswaz** [comment]
Yeah, the application of the spell should be eligible to proc Omen, and each tick of the spell should be able to as well.

**Comment by Barcaz** [comment]
> Yeah, the application of the spell should be eligible to proc Omen, and each tick of the spell should be able to as well.

About each tick i don't think it worked like that in retail,but on application should at least. Spammed multiple times rejuv on me and it didn't. And its important to clarify application as its often said like that in wowhead and something like wild growth should have chance on every person they apply the spell as even things like buffing mark of the wild have been giving nearly instant clearcasting.

**Comment by Vishiswaz** [comment]
It is supposed to proc from ticks, yes. If you apply rejuvenation, regrowth, and lifebloom and then sit there and do nothing, it should be able to proc.

**Comment by Vishiswaz** [comment]
Alright so I am wrong about the ticks thing, that's from a set bonus. https://bug.tauriwow.com/index.php?do=details&task_id=27400

**Comment by Barcaz** [comment]
Yeh clearcasting has some super wierd interactions, even in some private servers it procs more with slower spell staff which makes some sense if its ppm, but there is nearly zero information about that from back of the day

**Comment by Vishiswaz** [comment]
So, to be clear:

By default Omen of Clarity should have chance to proc on application of HoTs such as Rejuve and Lifebloom and Wild Growth.

There should also _not be any internal cooldown_.

**Comment by Barcaz** [comment]
In general that is how it is supposed to work,the only thing i'm not 100% sure after i rewatched some old clips is if wild growth have been capped only to cast in retail or its just private servers abomination to proc based on how many people it affected.
