### ISSUE TITLE
[A Short Fuse][Icecrown] doesn't 'teleport' player to fall into pit

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#838]
**Description**: [A Short Fuse](https://www.wowhead.com/quest=13389/a-short-fuse#comments) is a quest {ID: 13389}. 

**Current behaviour**: Upon accepting the quest, a small 'jump' animation occurs. The player is not 'teleported' above the pit.

**Expected behaviour**: Upon accepting the quest, the player is 'teleported above the pit and proceeds to fall.

**Revision**: 

Evidence: 1294
[Video from 2015](https://www.youtube.com/watch?v=rQN5iFIkgsk&ab_channel=GitGudGuides). 
[Video from 2016](https://www.youtube.com/watch?v=0BhcfHN0qSE&ab_channel=WorldOfWarcraftGuidesAndGameplay)
[Video from 2017](https://www.youtube.com/watch?v=NovDvYGyweQ). A bit different than first 2

**Comment by Tereneckla** [comment]
Fixed
