### ISSUE TITLE
[Quest] Crocolisk Mastery: The Ambush [Zone] Sholazar Basin [Spell] Sandfern Disguise

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#84]
**Description**: Sandfern Disguise spell buff not dissapearing upon entering combat.
https://www.wowdb.com/items/38564-sandfern-disguise
https://www.wowdb.com/quests/12569-crocolisk-mastery-the-ambush
https://www.wowhead.com/npc=28317/bushwhacker
**Current behaviour**:
_Sandfern Disguise_ spell buff does not dissapear upon entering combat with Bushwhacker (NPC), it persists untill the spells duration fades. Bushwhacker is able to attack your character all that time, while you cannot move/attack, for in my case 5-6 seconds. After that I entered combat, killed him and quest proceeded normally.
**Expected behaviour**: 
As soon as Bushwhacker (NPC) enganges in combat with the player, *Sandfern Disguise* buff should dissapear and combat should be enabled for the player.
**Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
