### ISSUE TITLE
[Core][Global?] Scroll stacking with Mark of the Wild (buff stacking issue)

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#843]
I tested using a Scroll of Intellect (+3 int) on myself when having rank 3 Mark of the Wild up (+4 all stats).

It wouldn't allow it, saying another stronger buff was already applied. It should allow it to be applied and they should stack.

This might be a global bug that needs looking into.

**Comment by NatsumeLily** [comment]
Proof?

**Comment by Godmatik** [comment]
Will close then, if I see it has trouble stacking with anything besides scrolls, will re-open
