### ISSUE TITLE
[Core] NPCs with Low level quests show exclamation mark

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#844]
Low level (grey) quests will continue to show a quest exclamation mark over the NPC's head and on the mini-map as well.

This should only be visible if you have the "low level quests" tracking turned on (I did not)

![Grey quest](https://user-images.githubusercontent.com/37913400/170890794-4239ff50-92d0-4915-85fa-267e7fe5dd22.png)

**Comment by Godmatik** [comment]
So after I leveled up a bit more, these low level quests with question marks started to go away in Crossroads/Ratchet. 

I think possibly the threshold is set too high.

**Comment by Vishiswaz** [comment]
I remember this being an issue on Crystalsong at first too. Quests should not be viewable (without tracking low level quests) once they would be grey colored in your quest log.
