### ISSUE TITLE
[NPC] [Naxxramas][Respawn time] Rotting Maggot, Diseased Maggot, Eye Stalk

### ISSUE THREAD

**Issue by Tarkamacska** [Stormforge-gg/Bugtracker-Wotlk-Beta#846]
**Description**: 
Rotting Maggot (16075)
Diseased Maggot (16056)
Eye Stalk (16236)

**Current behaviour**:
Theese 3 npc respawning so fast.

**Expected behaviour**: 
 i think , they dont have to. Other trash mobs arent respawn in 30 sec again. 

**Revision**:

**Comment by Godmatik** [comment]
Are those the NPCs in the tunnel between Heigan and Loatheb? 

I'm fairly sure the fast respawn is intended for Wrath, it is a trash gauntlet that you need to go fast. In vanilla - the fast respawn gauntlet used to be between Noth + Heigan, but Blizz changed that in Wrath.

**Comment by Wolffenstein** [comment]
intended
