### ISSUE TITLE
[NPC][Spell][Howling Fjord] Bjomolf, Varg

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Wotlk-Beta#847]
**Current behaviour**:
[Bjomolf](https://www.wowhead.com/npc=24516/bjomolf) doesn't use his spells [Broken Bone](https://www.wowhead.com/spell=50047/broken-bone) and [Gnaw Bone](https://www.wowhead.com/spell=50046/gnaw-bone).
[Varg](https://www.wowhead.com/npc=24517/varg) doesn't use spell [Killing Rage](https://www.wowhead.com/spell=52071/killing-rage).

**Expected behaviour**: 
They should use their spells.

**Revision**: 
1294

**Comment by Wolffenstein** [comment]
this works, in the first case one aura is applied by a a second aura
