### ISSUE TITLE
[An Undead's Best Friend][Icecrown] spell doesn't 'inhibit' combat correctly

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#848]
**Description**: During the quest [An Undead's Best Friend](https://www.wowhead.com/quest=13169/an-undeads-best-friend), you are required to take control of an [Eidolon Watcher](https://www.wowhead.com/npc=31110/eidolon-watcher). This NPC can cast [Feed Hungering Plaguehound](https://www.wowhead.com/spell=58562/feed-hungering-plaguehound). Doing so causes a minor script in the NPC's behavior. 

**Current behaviour**: Using [Feed Hungering Plaguehound](https://www.wowhead.com/spell=58562/feed-hungering-plaguehound) begins a script for the NPC Hungering Plaguehound. During this time, you can agro the Plaguehound
through proximity alert, often resulting in a hilareous scene where the dog attacks you sleeping.  Once the dog has fallen asleep, you can safely go through the dog.

**Expected behaviour**: You should not be able to agro the Plaguehounds through proximity alert once the script begins, neither before or after the dog sleeps. The dog should never attack you as a sleeping unit.

**Revision**: 1294

Evidence:

- [Best video of expected behavior](https://youtu.be/eY-nO3IHrvM?t=46): plaguehound not agro-ing. player just runs through dog after using spell.
- A [video showing no agro](youtube.com/watch?v=zef3eXmFo9M&ab_channel=GitGudGuides) on plaguehounds performing script.
- Video of SF revision 1294 build:

https://user-images.githubusercontent.com/105084838/170892017-17dfa286-4a8a-498b-9962-360f14720f03.mp4

**Comment by Cold-Martijn** [comment]
Oops... my bad...
