### ISSUE TITLE
Tanks are still critable on dungeon mobs with Defensive rating cap!

### ISSUE THREAD

**Issue by Murloc98** [Stormforge-gg/Bugtracker-Wotlk-Beta#849]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Murloc98** [comment]
This was in every Northrend dungeon on heroic

**Comment by FX-SF** [comment]
Could you provide evidence of the tank being critted with defense cap?

**Comment by Cold-Martijn** [comment]
Can you please provide a combat log and screenshot of character stats and current buffs & debuffs?

**Comment by Vishiswaz** [comment]
Got to Heroic Dungeon def cap (535) and aggro'd almost all of Utgarde Keep Heroic, including all but the last boss, got crit 0 times. https://youtu.be/t7rWNYUFD-s

**Comment by Vishiswaz** [comment]
Tested in Naxx at 541 def: No crits.

Removed wep, went down to 528 def: Crits started. 

https://youtu.be/2asryABPDoQ

Seems to be working fine.
