### ISSUE TITLE
[Dungeon] Violet Hold Entrance Event - Mobs Spawn Infinitely

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#85]
**Description**: 
In the Violet Hold - When the friendly NPC's die the Azure Dragonkin spawn infinitely.  There may be a friendly mob stuck in the floor as you can hear the human "attack" noise every now and again but the mobs either cannot get to him or it is just an audio bug.

**Current behaviour**:
Dragons spawn infinitely either due to an NPC stuck under the floor or another issue.

**Expected behaviour**: 
Friendly NPC's should likely respawn after death to curb the dragons or if a lone NPC is stuck under the map it should not do that.

**Revision**: 
1040
![Desktop Screenshot 2022 04 09 - 11 00 06 26](https://user-images.githubusercontent.com/43499757/162580094-0046152e-5b0f-4ede-9204-97f27a7020c1.png)

**Comment by Nuy** [comment]
These guards NPCs should be powerful enough to withstand their attacks and keep killing these azure dragonkin mobs befor next wave comes. Infinite spawning isn't the problem but guards dying/not being there is.

**Comment by Ceago** [comment]
> These guards NPCs should be powerful enough to withstand their attacks and keep killing these azure dragonkin mobs befor next wave comes. Infinite spawning isn't the problem but guards dying/not being there is.

Also a possibility.  The mob spawning may be a bit too fast as they are indeed very squishy.  Currently they are spawning every 15 seconds or so and the last wave had not been dealt with before the next wave arrived.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
