### ISSUE TITLE
[NPC] [Gas Cloud] Arctic Cloud

### ISSUE THREAD

**Issue by Tarkamacska** [Stormforge-gg/Bugtracker-Wotlk-Beta#854]
**Description**: 
Arctic Clouds missing 
**Current behaviour**:
I dont found theese npc s in the world, except 1-2 each :( 

**Expected behaviour**: 
MAP for points : 
https://wowpedia.fandom.com/wiki/Arctic_Cloud
Usually on another wotlk servers: 
https://wotlkdb.com/?npc=24879
I dont found correct information on wowhead, but as i know, clouds always respawns in the same place, and the respawn time for all clouds only 5 min
https://www.wowhead.com/npc=24879/arctic-cloud#comments
**Revision**: 
some more information about gas clouds: https://tbc.wowhead.com/item=23821/zapthrottle-mote-extractor#comments
and here: https://wowwiki-archive.fandom.com/wiki/Gas_cloud

**Comment by Wolffenstein** [comment]
They are pooled together for each zone, there is no guarantee for specific spots
