### ISSUE TITLE
[Spell] Dash (cat form)

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#855]
Currently: 
You can activate dash while out of cat form.

How it should work: 
I believe activating dash should only be possible while in cat form, otherwise you get an error saying it isn't usable.

Tested only with rank 1

https://classic.wowhead.com/spell=1850/dash

**Comment by Vishiswaz** [comment]
Correct, this is a bug.
