### ISSUE TITLE
[The Sum is Greater than the Parts] still buggy (2 tickets before)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#868]
**Description**: This issue has been reported twice before: #205 and #268. I will not go into much detail, except that ability 1 (Punch) seems to miss certain mobs based on position.

**Revision**: 1309

_Previous tickets_: #205 #268

_Video showing 1309 build_. Notice most enemies not being hit with Ability 1 (Punch):

https://user-images.githubusercontent.com/105084838/170940468-a90a07be-a63c-4049-803c-d540d073d4f2.mp4

**Comment by Wolffenstein** [comment]
Fixed in rev 1323.

**Comment by FX-SF** [comment]
works in revision 1330
