### ISSUE TITLE
[Quest] Fuel for the Fire; [Zone] Zul'Drak; [Pet behaviour] Bloated Abomination

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#87]
**Description:** 
Fuel for the Fire - Zul Drak - https://www.wowhead.com/quest=12690/fuel-for-the-fire
Abomination does not disapear after the Controll-Timer runs out.

**Current behaviour:**
When the **Timer (3 Minutes)** runs out after taking controll over a Bloadted Abomination with "_Scepter of Command_".(https://www.wowhead.com/item=39238/scepter-of-command), the abomination does not disapear and keeps following the Player. Even though the pet bar disapears.

Quest itself and killing the objectives is working fine.

**Expected behaviour:** 
https://www.wowhead.com/quest=12690/fuel-for-the-fire - see video
After the Timer runs out, the Abomination should either disapear or run back to its place, where the control was initially taken.

Revision:

**Comment by Evolvee** [comment]
fixed in next rev
