### ISSUE TITLE
[Dungeon] Anub arak adds not despawning after wipe

### ISSUE THREAD

**Issue by Pinnen123** [Stormforge-gg/Bugtracker-Wotlk-Beta#879]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

When I tested out anub'arak in Azjol nerub and tested wiping with adds left after he resurfaces after a transition, the adds didn't despawn. 

![image](https://user-images.githubusercontent.com/106036315/171051654-94db404f-484b-4e2a-ab23-8cdee21dbfde.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1323.
