### ISSUE TITLE
[Raid][NPC] Onyx Blaze Mistress

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#88]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Ability of a [mob](https://www.wowhead.com/npc=30681/onyx-blaze-mistress) in Obsidian Sanctum is not working properly

**Current behaviour**: Conjure Flame Orb is stationary when cast and does not move toward target. The flame orb also does not inflict damage. Although I was buffed with 99% damage reduction, the flame orb was constantly missing which is not normal.

**Expected behaviour**: "Conjures an orb of pure fire that floats through the air toward the target while firing searing beams at enemies that come within 18 yds." [source](https://wowpedia.fandom.com/wiki/Onyx_Blaze_Mistress)

**Revision**: 

--
![b7451ced1f08612df861c87eb258cd0f](https://user-images.githubusercontent.com/17366512/162581202-534d9248-d8ae-4c15-a0f7-3a7241526cb1.png)

**Comment by Wolffenstein** [comment]
The orb is not supposed to move. It uses generic flame orb description but on retail (I tested this) it does not move at all.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
