### ISSUE TITLE
Artisan Riding - sold for too cheap @ Thrallmar

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#889]
Artisan Riding training from Wind Rider Jahubo is being sold at base cost of 4.5k, should be 5k. 

I know the price decreases 5% with every rep level - but my current rep with Thrallmar is currently neutral.

(NOTE - Possibly this NPC is Orgrimmar faction (which I am honored with) rather than Thrallmar faction - that would explain why it is cheaper?)

https://www.wowhead.com/npc=35093/wind-rider-jahubo

![4500g](https://user-images.githubusercontent.com/37913400/171070028-5aed96cd-8408-4dce-8151-1807df528d6e.png)

![Thrallmar](https://user-images.githubusercontent.com/37913400/171070030-b9d58486-fbbf-46a6-972f-ed0927757adf.png)

**Comment by Vishiswaz** [comment]
Orgrimmar faction should be correct.

![image](https://user-images.githubusercontent.com/78314117/171072253-6ad857ef-fa25-46e8-80ac-7c2398761c76.png)

**Comment by Vishiswaz** [comment]
The mob is missing the faction from its tooltip, so at the very least that's a bug. It shouldn't be a guessing game to figure out what faction a mob is with.

**Comment by Godmatik** [comment]
Very interesting, closing
