### ISSUE TITLE
[Quest] Betrayal; [Zone] Zul'Drak; [Pet-Behaiviour]  Cant controll Pet after taking controll over it

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#89]
**Description**: 
Betrayal - Zul Drak - https://www.wowhead.com/quest=12713/betrayal#
Cant attack with Blighblood Troll after taking controll over it.

**Current behaviour**:
After taking controll over the NPC (Blightblood Troll) with "_Scepter of Domination_" (https://www.wowhead.com/item=39664/scepter-of-domination). The NPC keeps following the Player but Player has no controll over the pet. Pet bar appears but using the commands (like command attack or the specific pet abilities) do not work.

**Expected behaviour**: 
https://www.wowhead.com/quest=12713/betrayal - see video
After taking controll over the NPC (Blightblood Troll) , it should start running towards "_Drakuru_" and start attacking him. 

**Revision**:

**Comment by therealCrysis** [comment]
Confirmed in rev 1165

**Comment by Wolffenstein** [comment]
Fixed in rev 1183.
