### ISSUE TITLE
The Black Brewmaiden from Bitter Balebrew Charm Trinket

### ISSUE THREAD

**Issue by Blimsquge** [Stormforge-gg/Bugtracker-Wotlk-Beta#9]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The Black brewmaiden from Bitter Balebrew Charm Trinket doesn't give Brew when you wave

**Current behavior**: The Black Brewmaiden stands neutral until you target her to /wave for a brew, then she tries to attack critters that are nearby and won't give brew. I'm assuming she will attack any neutral enemy nearby.

**Expected behavior**: She is supposed to attack hostile targets that engage in combat with you and is supposed to give brew when waved at.

**Revision**:

**Comment by Emtec** [comment]
Fixed in 1107
