### ISSUE TITLE
[Raid][NPC] Onyx Flight Captain

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#90]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Ability of a [mob](https://www.wowhead.com/npc=30682/onyx-flight-captain) in Obsidian Sanctum not displaying properly.

**Current behaviour**: The debuff from the mob's ability "Hammer Drop" is displaying as a buff and not a debuff. You are not able to click it off like a normal buff but the display is still bugged.

**Expected behaviour**: Should display as a debuff.

**Revision**: 
-- can be seen as the leftmost buff
![3904e339fbf739d1a40d5e12ccfde38c](https://user-images.githubusercontent.com/17366512/162581327-21bd7ba4-3298-4491-9b06-1cf8e1551c5d.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
