### ISSUE TITLE
[Saronite Mine Slave] only speaks orcish

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#901]
**Description**: [Saronite Mine Slave](https://www.wowhead.com/npc=31397/saronite-mine-slave#abilities) is an NPC in Icecrown.

**Current behaviour**: Saronite Mine Slaves speak in orcish only.

**Expected behaviour**: Saronite Mine Slaves should speak English.

**Revision**: 1330

![image](https://user-images.githubusercontent.com/105084838/171108850-8d943958-683a-4cee-8652-21c28f5fe1fb.png)

**Comment by Cold-Martijn** [comment]
> ![image](https://user-images.githubusercontent.com/105084838/171138499-976500d3-07d6-445c-98a9-8ac43b7c732c.png)

He won't speak orcish anymore soon(tm) when the fix is uploaded haha
