### ISSUE TITLE
Dungeon : Utgarde Keep , Boss : Dalronn the Controller

### ISSUE THREAD

**Issue by Manpower99** [Stormforge-gg/Bugtracker-Wotlk-Beta#902]
When Dalronn dies ( havent tested Skarvald yet ) , he should be reanimated as a ghost and continue to cast , but should not be targetable/damageable/tauntable/interruptible in his ghost form.
on PTR in his ghost form he is damageable and targetable.
The Ghost of Dalronn — When Dalronn the Controller is killed, he continues to fight as an untargetable ghost until Skarvald is defeated.
The Ghost of Skarvald — When Skarvald the Constructor is killed, he continues to fight as an untargetable ghost until Dalronn is defeated.

**Comment by FX-SF** [comment]
Similar ticker #413

**Comment by Wolffenstein** [comment]
not a bug
