### ISSUE TITLE
[Profession] Tailoring

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#909]
**Description**: 
Creating https://wowwiki-archive.fandom.com/wiki/Moonshroud or any of the special cloth has the "old" requirements and gives the corresponding buff which is not supposed to be in patch 3.3.3.

The prior location requirements were:
https://wowwiki-archive.fandom.com/wiki/Emerald_Dragonshrine for Moonshroud
https://wowwiki-archive.fandom.com/wiki/Azure_Dragonshrine for Spellweave
https://wowwiki-archive.fandom.com/wiki/Maw_of_Neltharion for Ebonweave

"You are in the wrong zone" is the error text given in-game.
Also the CD is four days.

**Expected behaviour**: 
[Patch 3.3.3] (2010-03-23): Creating Moonshroud no longer has a cooldown or location requirement, but also no longer provides the [Moonshroud Residue] buff on creation.

**Revision**:

**Comment by Vishiswaz** [comment]
These should be kept until 3.3. Allowing people to make as much cloth as they want anywhere they want fucks with the economy and no other popular wotlk server that I'm aware of has this enabled before 3.3.

**Comment by Vishiswaz** [comment]
I'm not sure if that can be fixed server side. That may be a client side thing.

**Comment by Vishiswaz** [comment]
All the wotlk servers I've played did not remove it 3.3.

And whether or not the location can be put in the tooltip/error frame/etc. again, may be a client side issue, not server side.

**Comment by Wolffenstein** [comment]
Added error message in rev 1342. Everything else is as intended.
