### ISSUE TITLE
[NPC] Timothy Jones

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Wotlk-Beta#91]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Timothy Jones currently sells recipies for epic gems, these should not be available until patch 3.2, ToC release. 
He also offers daily quests for Jewelcrafting.
Of course, I'm assuming that the server will follow blizzard patches in this regard.

**Current behaviour**:
Timothy Jones offers recipies for epic gems at 4 Dalaran Jewelcrafter's Tokens each. He also offers quests related to getting this Tokens.

**Expected behaviour**: 
Timothy Jones should not sell epic gem recipies until ToC is released.
EDIT: https://wowpedia.fandom.com/wiki/Patch_3.2.0#Jewelcrafting
I forgot the link.

**Revision**: 
1040

**Comment by Wolffenstein** [comment]
Fixed in rev 1063.
