### ISSUE TITLE
[Restricted Flight Area][Dalaran] Warning: You've entered a no-fly zone and are about to be dismounted!

### ISSUE THREAD

**Issue by NagatoBR** [Stormforge-gg/Bugtracker-Wotlk-Beta#910]
**Current behaviour**: The message "Warning: You've entered a no-fly zone and are about to be dismounted!" does not appear.

**Expected behaviour**: https://youtu.be/NOEdwABWaR4?t=35

**Revision**: 1330

**Comment by Wolffenstein** [comment]
Fixed in rev 1342.
