### ISSUE TITLE
[Shoot 'Em Up][Icecrown] 

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#924]
**Description**: Shoot 'Em Up is a daily quest located in Icecrown. It requires you to hop into a Turret ([Jotunheim Rapid-Fire Harpoon](https://www.wowhead.com/npc=30337/jotunheim-rapid-fire-harpoon)) and shoot [Jotunheim Proto-Drake](https://www.wowhead.com/npc=30330/jotunheim-proto-drake) with spell [Rapid-Fire Harpoon](https://www.wowhead.com/spell=56570/rapid-fire-harpoon). Player can restore energy with the spell [Energy Reserves](https://www.wowhead.com/spell=56585/energy-reserve#comments).

**Current behaviour**:

1. Drakes have regular AI combat and will engage any Player who attacks (i.e., the Harpoons or a fireball spell)
1. A slain Drake appears to be some sort of object when it dies. If it lands on the Turret, Harpoons hit that object. (see pic 1)
2. A Viking hops out of a slain Drake. The Viking can enter combat with the Player and not be able to attack or exit combat. Viking is un-targetable and does not attack. (see pic 2)
3. Energy Reserves can be spammed indefinately. 

**Expected behaviour**:  

1. Drakes should not attempt to enter combat with Player, even when attacked with Harpoons. It should stay out in the open air, away from the ground which the Turret stands on.
2. A slain Drake appearing as an object should not be an issue, since it does not land on the Turret. (See expected behavior 1)
4. Vikings should not be an issue. I am uncertain what expected behavior should be. (See expected behavior 1)
5. Energy Reserve should have a 30s Cooldown (see pic 3)

**Revision**: 1349

[Video 1](https://youtu.be/wJqTaIFQgRM?t=127) shows drake not engaging combat when hit with Harpoon.
[Video 2](https://youtu.be/hLel9QpTuwE?t=217) shows many more examples of drake not engaging.
Pic 1
![image](https://user-images.githubusercontent.com/105084838/171342852-cf5b4565-b607-430a-a521-40d76fc94451.png)
Pic 2
![image](https://user-images.githubusercontent.com/105084838/171343494-95c922ef-eb9b-4922-8183-5680209d38b9.png)
Pic 3
![image](https://user-images.githubusercontent.com/105084838/171352142-9b84ba05-b023-47e4-913c-0b29cc92a538.png)

**Comment by Cold-Martijn** [comment]
rev 1366
