### ISSUE TITLE
[Talent][Warrior] Recklessness

### ISSUE THREAD

**Issue by bonfax4** [Stormforge-gg/Bugtracker-Wotlk-Beta#927]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

Recklessness is being consumed per cast. This makes bladestorm and whirldwing consume 1 stack per wave regardless of number of targets

**Expected behaviour**: 

Recklessness should be consumed per target hit with aoe spells, but the crit should affect the whole wave of damage.

Source:

https://wowpedia.fandom.com/wiki/Recklessness_(original)?oldid=2409689
> Doesn't affect  [[Shockwave]](https://wowpedia.fandom.com/wiki/Shockwave),  [[Concussion Blow]](https://wowpedia.fandom.com/wiki/Concussion_Blow),  [[Heroic Throw]](https://wowpedia.fandom.com/wiki/Heroic_Throw) or [Thunderclap](https://wowpedia.fandom.com/wiki/Thunderclap). Affects  [[Whirlwind]](https://wowpedia.fandom.com/wiki/Whirlwind), but removes 1 charge for each target you hit. While wielding 2 weapons it still will only remove 1 charge per traget. (But 1 remaining charge is enough to have all attacks of a whirlwind against 4 targets while dual-wielding (total of 8 attacks) crit)

and mentioned [here](https://www.mmo-champion.com/threads/780263-fury-and-recklessness?highlight=recklessness)

Retail Video proof : https://www.youtube.com/watch?v=nD2stcm4W8M&t=262s Bladestorm instantly consuming all 3 stacks.
**Revision**:

**Comment by Cold-Martijn** [comment]
rev 1365
