### ISSUE TITLE
[Tirion's Gambit][Icecrown] Tirion not spawned

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#929]
**Description**: For the quest [Tirion's Gambit](https://www.wowhead.com/quest=13403/t), you are required to speak with Tirion at the Cathedrel of Darkness.

**Current behaviour**: Tirion is not at the Cathedral of Darkness. It may be bugged due to me testing it yesterday.

**Expected behaviour**:  Tirion should re-spawn at Cathedral of Darkness.

**Revision**: 1358

**Comment by Cold-Martijn** [comment]
rev 1363
