### ISSUE TITLE
Reputation enchants are on the wrong patch

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#932]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Head enchants at the rep vendors and the shoulder enchants at the Sons of Hodir vendors are currently set to their 3.3 items, which are bind to account. Prior to 3.3, they are supposed to be entirely different items which are BoP. I'll make a list of changes needed.

| Reputation  | Current Item (3.3 version) | Proper Item (3.0, 3.1, 3.2 version) |
| ------------- | ------------- | ------------- |
| Argent Crusade | [Arcanum of the Stalwart Protector](https://wotlkdb.com/?item=44150) | [Arcanum of the Stalwart Protector](https://wotlkdb.com/?item=44878) |
| Knights of the Ebon Blade  | [Arcanum of Torment](https://wotlkdb.com/?item=44149) | [Arcanum of Torment](https://wotlkdb.com/?item=44879) |
| Wyrmrest Accord | [Arcanum of Blissful Mending](https://wotlkdb.com/?item=44152) | [Arcanum of Blissful Mending](https://wotlkdb.com/?item=44876) |
| Kirin Tor | [Arcanum of Burning Mysteries](https://wotlkdb.com/?item=44159) | [Arcanum of Burning Mysteries](https://wotlkdb.com/?item=44877) |
| Sons of Hodir | [Greater Inscription of the Axe](https://wotlkdb.com/?item=44133) | [Greater Inscription of the Axe](https://wotlkdb.com/?item=44871) |
| | [Greater Inscription of the Crag](https://wotlkdb.com/?item=44134) | [Greater Inscription of the Crag](https://wotlkdb.com/?item=44872) |
| | [Greater Inscription of the Pinnacle](https://wotlkdb.com/?item=44136) | [Greater Inscription of the Pinnacle](https://wotlkdb.com/?item=44873) |
| | [Greater Inscription of the Storm](https://wotlkdb.com/?item=44135) | [Greater Inscription of the Storm](https://wotlkdb.com/?item=44874) |

**Comment by Wolffenstein** [comment]
i dont think i want to change this
