### ISSUE TITLE
URGENT - Wintergrasp (and PvP) Vendors

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#933]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Wintergrasp vendors are currently selling the WRONG GEAR for patch 3.0, instead selling many items with way too high of ilvl. This is super critical, people should not be getting ilvl 251 patch 3.3 gear in patch 3.0.

I don't have a complete list of changes that need to be made and I don't have the time today to compile one. If one of the other testers could, that would be amazing. This is, again, super critical and urgent.

This goes for the items sold by Knight Dameron, Marshal Magruder, Stone Guard Mukar, and Champion Ros'slai.

**Comment by Vishiswaz** [comment]
Oh jeez I didn't even think about that. I don't pvp much...

**Comment by Wolffenstein** [comment]
> Going to add to this. The pvp vendors in dalaran sewers are also selling high ilvl pvp gear.

Which vendors and what items?

**Comment by Wolffenstein** [comment]
Fixed in rev 1368.
