### ISSUE TITLE
[Spell][Mage] Arcane Missiles and buffs/debuffs

### ISSUE THREAD

**Issue by bonfax4** [Stormforge-gg/Bugtracker-Wotlk-Beta#934]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Arcane Blast debuff currently is only affecting the 1st tick of arcane missiles, sometimes 2 but it depends on distance but it should buff the full channel. 

**Expected behaviour**: 

You can notice on arcane videos there's no sudden drop in damage from arcane missiles hits, it would be pretty noticeable if the 1st or 2nd tick did 15%/30%/45% extra damage while the followed hits did less. https://youtu.be/_Lr_EDCNv6E?t=189 (He uses a normal non buffed arcane blast buffed missiles here and did about 3k each hit, every other time i've seen him use it he does 3.6k minimum with stacks on the full channel). ~~From what i gathered only Arcane Potency and arcane blast debuff snapshot to the full channel if consumed on cast.~~ Only arcane blast debuff , potency consumed on-hit.

https://www.mmo-champion.com/threads/653025-arcane-missiles-and-shatter?highlight=arcane+missile

> Missile damage is calculated for the current conditions when there's a trinket or AP active (this can be observed from missile damage massively changing from one to the other when a trinket or AP expires). As the shatter crit bonus is checked when the spell is launched, not when it hits, it stands to reason that each missile is checked individually.
> 
> The crit bonus from arcane potency and the arcane blast buff are both exceptions to how buffs are normally checked with AM, and apply to the whole cast.
> 
> I could see this being particularly nasty (if difficult to execute) with an unusual spec that incorporated shatter into a deep arcane build. With Icy Veins, 4t8, and a temporary haste buff, I imagine you could on some occasions get two successive missile barrages in the air before the ice from a frost nova broke. Even if they did break the ice and started to run, it's likely they wouldn't make it far.

https://www.mmo-champion.com/threads/692260-Arcane-Missiles-a-DoT?highlight=arcane+missile

> That might be the case with other channeled spells, but AM checks SP with every missile.
> 
> [11:21:45][You] Arcane Missiles [Grandmaster's Training Dummy] *1(+1041)* Crit <-- With Frostforged Sage (ICC rep ring buff +280 SP)
> [11:21:45][You] ++ Arcane Empowerment [You]
> [11:21:46][You] Arcane Missiles [Grandmaster's Training Dummy] 1(+571) <-- With Frostforged Sage
> [11:21:47][You] -- Frostforged Sage [You]
> [11:21:47][You] Arcane Missiles [Grandmaster's Training Dummy] 1(+571) <-- Was cast before buff ended, but hit target after it ended
> [11:21:48][You] Arcane Missiles [Grandmaster's Training Dummy] 1(+457) <-- No buff
> [11:21:49][You] Arcane Missiles [Grandmaster's Training Dummy] *1(+858)* Crit <-- No buff
> 

>Had no gear on to make sure theres no useless spam between.

Source: [http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_3_live/#ixzz0nHmxouI1](https://web.archive.org/web/20100507223100mp_/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_3_live/#ixzz0nHmxouI1)

**Revision**:

**Comment by bonfax4** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/926#issuecomment-1143722552 interaction with arcane concentration needs to be checked aswell https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/926#issuecomment-1143722552

**Comment by bonfax4** [comment]
Actually correction to arcane potency  "Missiles now trigger Arcane Concentration every missile, but at a reduced rate. And Arcane Potency is said to affect only the first missile, from how I understand the notes. (Which has been like this for a while, I think.)"

**Comment by bonfax4** [comment]
Mentioned in the other post arcane missiles interaction with Arcane concentration aswell, but here's video proof https://www.youtube.com/watch?v=ZlBZaSdftFs. In the whole video i could count 3 times where it proceed on arcane missiles give or take. That should tell you how wrong the proc rate is right now i can proc it 4 times in 3 sets of missiles easily.

**Comment by Wolffenstein** [comment]
Fixed in rev 1372.
