### ISSUE TITLE
[Object] Tattered Chest in Starting zones containing only few coppers

### ISSUE THREAD

**Issue by Dopp0** [Stormforge-gg/Bugtracker-Wotlk-Beta#935]
Description: Looting Tattered Chests in starting zones contains only few coppers.

Current behavior: Tattered Chests contains only few coppers

Expected behavior: Tattered Chests are supposed to contain sometimes green items, potions, food/water and some greys/greens

Revision:

https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/284 - Was fixed/closed, however the issue still remains for tattered chests

**Comment by Vishiswaz** [comment]
The PTR hasn't been updated with the chest fix in place. You can close this.
