### ISSUE TITLE
[Core] Global issue with mobs that have no loot (minor)

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Wotlk-Beta#937]
**Currently:**
If you kill a mob and it drops no loot, there are no visible sparkles + you can not loot the mob.

**How it should work (Blizzlike):**
If you kill a mob that drops no loot, you should still be able to loot it, and a loot window will open up that is empty

**Comment by Wolffenstein** [comment]
As far as I know that was changed in some expansion and should no longer be the case
