### ISSUE TITLE
[Raise Ally][Death Knight] Summoned Ghoul is lower level.

### ISSUE THREAD

**Issue by shammybr** [Stormforge-gg/Bugtracker-Wotlk-Beta#938]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

Death Knight's [Raise Ally] skill summons a level 50 ghoul when used on a level 80 player, when it should spawn a level 80 one. Probably true for lower levels too.

**Current behaviour**:

Using [Raise Ally] on a player of the required range level will ressurrect the player as a ghoul as intended, but the level and stats will be of a level 50 ghoul.

**Expected behaviour**: 

The skill should work exactly as [Raise Dead], but let the targeted player control the ghoul. [Raise Dead] is currently raising a ghoul of the desired level.

**Wowhead link**: 

https://www.wowhead.com/spell=61999/raise-ally#comments

The following comment (from patch 3.0.9): "Turns out, the ghoul raised from an ally has the exact same stats as your ghoul, meaning that it is affected by your strength/stamina, and your talents that increase the effects of your strength/stamina on your normal ghoul"

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1376.
