### ISSUE TITLE
[Gundrak][BOSS: Drakkari Colossus] Aggroing addicional mobs on pull

### ISSUE THREAD

**Issue by WeekendWarrior00** [Stormforge-gg/Bugtracker-Wotlk-Beta#939]
**Description**:  It's the boss that has the mechanical/elemental phases. There are some mobs behind them you clear to continue the dungeon. The bug is that when you pull the boss, all mobs will aggro too. You can aggro them when fighting the boss but only by proximity, but is not the case. This bug happens on both Normal and Heroic modes of the dungeon.

**Current behaviour**: Mobs named "Living Mojo" and "Drakkari Golem" aggro when you pull the boss Drakkari Colossus regarless of your position.

**Expected behaviour**:  You only aggro them if you get too close to them.

**Revision**:

**Comment by WeekendWarrior00** [comment]
![WoWScrnShot_060222_210248](https://user-images.githubusercontent.com/61029488/171760381-9f8738e5-4be0-41e7-b17b-79b08dbab132.jpg)
I was just about to pull the boss

**Comment by WeekendWarrior00** [comment]
![WoWScrnShot_060222_210257](https://user-images.githubusercontent.com/61029488/171760422-544b15d8-6b50-441a-bb3c-389b4e078475.jpg)
I casted only 1 Arcane Blast on the boss and even with the distance, the mobs aggroed.

**Comment by Wolffenstein** [comment]
not a bug

**Comment by Godmatik** [comment]
> **Description**: It's the boss that has the mechanical/elemental phases. There are some mobs behind them you clear to continue the dungeon. The bug is that when you pull the boss, all mobs will aggro too. You can aggro them when fighting the boss but only by proximity, but is not the case. This bug happens on both Normal and Heroic modes of the dungeon.
> 
> **Current behaviour**: Mobs named "Living Mojo" and "Drakkari Golem" aggro when you pull the boss Drakkari Colossus regarless of your position.
> 
> **Expected behaviour**: You only aggro them if you get too close to them.
> 
> **Revision**:

All of the stock wrath servers have this setup wrong, it is intended and blizzlike for those mobs to aggro when you pull the boss
