### ISSUE TITLE
[NPC] Harold Winston

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Wotlk-Beta#94]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:
Harold Winston sells gear and raw gems for gold and emblems. However some of the items that he currently sells are not meant to me obtainable until patch 3.1, 3.2 or even 3.3.

**Current behaviour**:
Harold Winston currently sells raw epic gems for emblems of heroism. This gems should only become available in patch 3.2 with the release of ToC.
He also sells necklaces and rings of ilvls from 200 to 245. (The items of higher ilvl require emblems that aren't available until their corresponding tier, then these items are technically not obtainable, so I guess it's fine)
Harold also sells the Kirin Tor rings for gold.

**Expected behaviour**: 
Harold Winston should not sell raw epic gems until they are supposed to be available.
In theory he should also not sell items of later tiers, but then again, they are technically not obtainable anyways.
He definitely should not sell the 226 and 251 ilvl Kirin Tor rings until later.

**Revision**: 
1040

**Comment by Wolffenstein** [comment]
Fixed in rev 1063.
