### ISSUE TITLE
[Rogue] Hemorrhage

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Wotlk-Beta#95]
**Description**: 
Rogue Subtlety talent skill Hemorrhage does not award 1 combo point as it should.

**Current behaviour**:
Does not award 1 combo point at all.

**Expected behaviour**: 
Awards 1 combo point. https://wotlkdb.com/?spell=48660.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1077.
