### ISSUE TITLE
[NPC} Iron rune mobs [Zone} Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#96]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Multiple Iron Rune mobs at Ivald's ruin are missing their abilities.

**Current behaviour**: Iron Rune Sage, Iron Rune Destroyer and Iron Rune Laborer miss all of their abilities.

**Expected behaviour**:  Iron Rune Sages should have : Fireball and Cone of Cold  https://www.wowhead.com/spell=20823/fireball
                                                                                                                                     https://www.wowhead.com/spell=20828/cone-of-cold
                                        Iron Rune Destroyers should have : Hammer Blow https://www.wowhead.com/spell=48376/hammer-blow
                                        Iron Rune Laborers should have : Puncture Wound https://www.wowhead.com/spell=48374/puncture-wound

**Revision**:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1381
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1380
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1379
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1372
alpha bugtracker reports for easier closing

**Comment by Cold-Martijn** [comment]
fixed.
