### ISSUE TITLE
[NPC][Quest] Eisenfaust - Loken's Lackeys

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Wotlk-Beta#97]
**Description**: 
https://streamable.com/bjhmps

Video attached above showing safe spot from Eisenfaust.  The target is not in LoS but can be hit by AoE spells and could be soloed.

**Current behaviour**:
Eisenfaust does not reset and can be fully killed using AoE spells.  He will still hit with his stomp ability but it is not enough damage to kill the player fast enough.

**Expected behaviour**: 

Should reset or find a way to avoid this safe spot.

**Revision**: 
1040

**Comment by Wolffenstein** [comment]
Fixed in rev 1087.
