### ISSUE TITLE
[DUNGEON][NPC] Azure Spellbinder

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Wotlk-Beta#98]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Missing weapon. 

**Current behaviour**: They're missing their staff weapon. 

**Expected behaviour**: They should have staff.

https://www.wowhead.com/npc=27635/azure-spellbinder#screenshots:id=99570

**Revision**: 1040

**Comment by Wolffenstein** [comment]
It's a small orb, not a staff.

**Comment by Wolffenstein** [comment]
Fixed in rev 1041.
