### ISSUE TITLE
[NPC] Nifflevar NPCs [Zone] Howling Fjord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Wotlk-Beta#99]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Dragonflayer warrior are missing their ability. Valgarde captives are aggresive towards and killing Dragonflayers.

**Current behaviour**:  Dragonflayer warriors miss Whirlwind. 
                                        Valgarde captives are killing surrounding Dragonflayers.

**Expected behaviour**:  Dragonflayer warriors should have Whirlwind. https://www.wowhead.com/npc=23654/dragonflayer-warrior#abilities
                                           Valgarde captives should be passive towards Dragonflayers.

**Revision**:

**Comment by Cold-Martijn** [comment]
Reports from the Alpha test bugtracker for easier closing:
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1377
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1375 - also contains different issues

**Comment by Cold-Martijn** [comment]
fixed
